### ISSUE TITLE
tracing back to PWN distribution

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#1]
I believe it would be nice to have the database files and the lexicographer files from the PWN distributions 3.0 and 3.1 here. The `src` directory is actually produced from these files, right?  People would have more confidence in this repo if they can reproduce the data from PWN sources.

**Comment by jmccrae** [comment]
Hi, I have added a note about this in the [release](https://github.com/globalwordnet/english-wordnet/releases)
