### ISSUE TITLE
(literary) as a tag

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#100]
04839475-n (Interlingual Index: i62386)
(n) bounteousness, bounty 
> generosity evidenced by a willingness to give freely

is a literary term (also agreed by OED: https://en.oxforddictionaries.com/definition/bounty)

Should we mark terms as such? Currently only two terms ('steed' and 'tempest') are marked in this way

**Comment by jmccrae** [comment]
add new relation domain (topic) is `ewn-06376048-n` literature
Update definition by adding '(literary)'

**Comment by arademaker** [comment]
I suspect it will be very difficult to define the limits for marking words as literary or non literary.
