### ISSUE TITLE
irrelevant example?

### ISSUE THREAD

**Issue by aclueless** [globalwordnet/english-wordnet#1000]
In 
https://github.com/globalwordnet/english-wordnet/blob/9d8f710120e8a4949600c9a4481dcd1226ae958f/src/yaml/noun.act.yaml#L47298-L47310

I think the example `four plus three equals seven` on line 47303 became irrelevant because of #994.

**Comment by jmccrae** [comment]
Yes, of course the example should have moved to the new synset along with the entry.
