### ISSUE TITLE
apparel and connected terms but also -ment as a suffix

### ISSUE THREAD

**Issue by busterbeam** [globalwordnet/english-wordnet#1002]
FYI: n00b NLP status, never done linguistics. 

**Affected synsets**
apparel, apparelled and apparelling.  -ment suffix

**Proposed changes**
Accept apparelled and apparelling as "extensions" to apparel.  -ment should be seen as a suffix right?

**Motivation**
Although OED https://www.oed.com/dictionary/apparelling_n?tl=true has very little on it.  I'm surprised the lemmatization (stemming) of apparelled and apparelling is not seen a lemma (?) of apparel. OED on -ment https://www.oed.com/dictionary/ment_suffix?tab=factsheet#37270298.

**Comment by jmccrae** [comment]
Not sure I quite understand the request here. Currently, we have "apparel" as a verb and as such the inflected forms "appareled/apparelled" and "apparelling" are supported. Note that we have "appareled" as an adjective but not "apparelled" as an alternative British spelling. 

We could add the term "apparelling" as a new noun synset. The requirements for this are specified [here](https://github.com/globalwordnet/english-wordnet/blob/main/NEW_SYNSETS.md). I am not sure if this word passes the significance threshold, currently I only see 1 match in CoCA.

I am not sure what is meant by "-ment as a suffix"... if you mean to propose add "apparelment" as a new noun synset this could be possible but again I am not sure it passes the significance criterion as above. We would not add "-ment" as a general suffix... OEWN does not model suffixes and prefixes.

**Comment by busterbeam** [comment]
sorry, with the suffix -ment, I think it was in connection to abandonment.  I can see that wordnet is more of a constructed database from a dictionary subset and not a rule set per-say. either way no worries. trying to get my head around linguistics.
