### ISSUE TITLE
nonprofessional

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#1003]
**Synset**

oewn-01875320-a (Interlingual Index: i10263)

(a) nonprofessional not professional; not engaged in a profession or engaging in as a profession or for gain “the nonprofessional wives of his male colleagues” “nonprofessional actors”

**New definition**

not professional; not engaged in a profession or engaging in nor for gain

**Motivation**

The original description is confusing, as far as I understood, it is wrong.

**Comment by jmccrae** [comment]
Thanks for the report. I would go for an even simpler definition

"not engaged in or related to a profession"

This would also remove the "not professional" definition as (a) we want to avoid multiple definitions as this creates ambiguity (b) defining "un-X/"non-X" words as "not X" is not informative
