### ISSUE TITLE
water skiing

### ISSUE THREAD

**Issue by aclueless** [globalwordnet/english-wordnet#1005]
**Lemmas**
water skiing, water-skiing, waterskiing

**Definition**
_Please see the link to Wikipedia below._

**Relation**
Don't know

**Significance**
https://en.wiktionary.org/wiki/water_skiing

**Comment by jmccrae** [comment]
"waterskiing" has 103 matches in CoCA so this is clearly significant enough.

I would suggest oewn-00524569-n ('sport', 'athletics') as the hypernym

Definition: "sport of riding on skis, while being pulled by a boat"
