### ISSUE TITLE
Examples of two synset of 'individual' are almost the same?

### ISSUE THREAD

**Issue by aclueless** [globalwordnet/english-wordnet#1006]
Look at: https://en-word.net/lemma/individual

One synset has `"please mark the individual pages"`, the other synset has `“mark the individual pages” `. To me, the examples are identical.

I think these examples (or synsets) need an improvement...

**Comment by jmccrae** [comment]
Yes, I agree that the adjective senses of individual are very hard to distinguish. This may make a good candidate for introducing new principles for making sense distinctions

**Comment by jmccrae** [comment]
Looking at the reference dictionaries, it seems that there is no other dictionary that makes this sense. As such, I will implement this as merging `00732690-s` into `00495505-a`
