### ISSUE TITLE
Provide comparisons to Princeton wordnet

### ISSUE THREAD

**Issue by notevenaperson** [globalwordnet/english-wordnet#1011]
Could you provide, for my curiosity, a ""diff"" between The Open English Wordnet and Princeton's? The Open English Wordnet has built upon what was there, but wouldn't it also be easy to provide some concrete numbers? What is the word count difference between the two as of now? 

I've had interest in Wordnet as a dictionary rather than Wordnet itself, so it's certain you'd know other relevant metrics than word count, my uncreative example.

I was also disappointed to not find this information on the website or the github repository. You're looking for ways to communicate the value of the project, and I think featuring (if at least big) numbers would give experts and non-experts a better sense of what the project accomplishes and has accomplished.

**Comment by jmccrae** [comment]
This is a good point, I have added some statistic to the README.
