### ISSUE TITLE
dbfiles

### ISSUE THREAD

**Issue by God-damnit-all** [globalwordnet/english-wordnet#1012]
I couldn't help but notice that english-wordnet lacks the "dbfiles" that are present in http://wordnetcode.princeton.edu/wn3.1.dict.tar.gz

Those dbfiles are used with the [WordNet 3.0 software](https://wordnet.princeton.edu/download/current-version). I managed to use msys2 to compile the CLI tool for Windows, which works great.

I don't know how exactly the dbfiles are derived, but it would be good if there was some sort of conversion script to generate them from the new version of wordnet you've been working on.

Failing that, maybe you know good alternative software?

---

_Also, here's the Windows CLI tool I compiled along with its database, in case you were curious:_ [WordNet CLI for Windows.zip]
+ _Note that you have to set the `WNHOME` environment variable to the directory that contains the `dict` subdirectory_

[WordNet CLI for Windows.zip]: https://github.com/globalwordnet/english-wordnet/files/14593268/WordNet.CLI.for.Windows.zip

**Comment by arademaker** [comment]
> So now I'm wondering what even is the purpose of the dbfiles.

@ImportTaste , this format is originally from Princeton Wordnet. See [here](https://wordnet.princeton.edu/documentation/wndb5wn). Princeton team worked in the [lexicographer files](https://wordnet.princeton.edu/documentation/wninput5wn), which are compiled by the [grind](https://wordnet.princeton.edu/documentation/grind1wn) program to produce the dbfiles.

Nowadays, almost all wordnets use XML, JSON, or RDF as the primary format for data distribution. During the work, different tools were adopted by different projects. The dbfiles are still relevant if one wants to use the [wn](https://wordnet.princeton.edu/documentation/wn1wn) CLI program, also developed by Princeton.

**Comment by jmccrae** [comment]
DB files are provided with every release, e.g.,

https://en-word.net/static/english-wordnet-2023.zip

These files provide backwards compatibility with Princeton releases but do not support all the features of OEWN, so we encourage everyone to migrate to the XML versions of the release, or use the YAML source directly.

As for tools, we make a web interface available at https://en-word.net/ and there is a CLI editing tool that we use internally at https://github.com/jmccrae/ewe
