### ISSUE TITLE
Add `green` to https://en-word.net/id/oewn-90016161-s

### ISSUE THREAD

**Issue by aclueless** [globalwordnet/english-wordnet#1015]
**Affected synsets**
https://en-word.net/id/oewn-90016161-s

**Proposed changes**
Add `green` as a member of the mentioned synset

**Motivation**
See definition number 9 at: https://en.wiktionary.org/wiki/green#Adjective

**Comment by aclueless** [comment]
A related term to consider is `go green`. Currently I can only find this [in Cambridge dictionary](https://dictionary.cambridge.org/dictionary/english/go-green).

**Comment by jmccrae** [comment]
I agree, not having 'green' as a synonym of 'ecofriendly' seems to be a big oversight. I note the [oewn-03081365-a](https://en-word.net/id/oewn-03081365-a) is a very similar sense, but I think we can keep both.

For 'go green', I think the only question is compositionality, but I think it is okay and we have other terms such as 'go Dutch' that are similar.

**Comment by arademaker** [comment]
I would vote against 'go green,' but the limits are always hard to impose.

**Comment by jmccrae** [comment]
'go green' has 233 occurrences so is certainly a term with enough significance, and is more frequent than similar terms ('go red' @ 109 and 'go black' @ 103).

The compositionality question is whether [this synset for 'go'](https://en-word.net/id/oewn-00149403-v) already covers the meaning of the collocation. I would say probably not but it is a borderline case... 

@arademaker is right that 'go Dutch' is a poor justification as this term has not much to do with the Netherlands, where as 'go green' can be paraphrased as 'become ecofriendly'
