### ISSUE TITLE
List of valid relation types?

### ISSUE THREAD

**Issue by pdesaulniers** [globalwordnet/english-wordnet#1023]
Hello! I'm having some trouble figuring out which relation types can be used in Open English WordNet...

The issue template for "Add a relation" currently links to Global WordNet's documentation (gwadoc): https://github.com/globalwordnet/english-wordnet/blob/53330890db0d8dfb6a9b5f79c3a0d33de9bf2ad4/.github/ISSUE_TEMPLATE/add-a-relation.md?plain=1#L16-L17

Meanwhile, Open English WordNet's README links to the [Global WordNet Formats](https://globalwordnet.github.io/schemas/) page, which contains a sightly different list of relation types: 

- Some of them appear to be missing, such as `masculine` and `feminine`
- Some relation types seem to be listed under a different name. For instance, the document refers to `domain_member_topic` which, I assume, is equivalent to `has_domain_topic` in gwadoc.

Then, it seems like Open English WordNet uses a few relation types which are not defined in either documentation, such as `destination`, `event`, `vehicle`...

Also, many of the relations described in gwadoc seem to be missing in Open English WordNet (`masculine`, `feminine`, `young`...)

What are the valid relation types when suggesting new relations in Open English WordNet? Should I refer to gwadoc and the enumerations in `scripts/wordnet.py`?

**Comment by jmccrae** [comment]
Thanks for the comments. I guess it is a bit confusing.

You are right to summarize that `scripts/wordnet.py` gives the relations, that we actually support in this project. That is that we support most of those relations listed in the `gwadoc` repo, but not some like `masculine` or `young` (yet).

There are also a number of "morphosemantic" relation introduced from Princeton WordNet that were introduced in #132 but do not have a great coverage in the resource. These relations are also removed in the exports to the GWA formats so are still quite unstable.

The document at https://globalwordnet.github.io/schemas/ is out-of-date. I will go fix this now.

**Comment by pdesaulniers** [comment]
Thank you for the information :)
