### ISSUE TITLE
Hot weather

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#103]
11487100-n (Interlingual Index: i97847)
(n) hot weather 
> a period of unusually high temperatures

Is a hypernym of 

11545095-n (Interlingual Index: i98170)
(n) conditions, weather condition, atmospheric condition, weather 
> the atmospheric conditions that comprise the state of the atmosphere in terms of temperature and wind and clouds and precipitation; "they were hoping for good weather"; "every day we have weather conditions and yesterday was no exception"; "the conditions were too rainy for playing in the snow"

gloss suggesting time instead of atmospheric conditions

Perhaps we should delete this synset entirely as it is compositional?

**Comment by jmccrae** [comment]
any objections to removing this synset?

**Comment by arademaker** [comment]
In https://www.thestar.com.my/news/world/2020/03/16/can-hot-weather-stop-coronavirus-southeast-asia-surge-raises-doubts

It seems more like a compositional meaning.  A weather that is hot. But in

> During hot weather, think about making daily visits to older relatives and neighbors. (from https://www.nia.nih.gov/health/hot-weather-safety-older-adults)

It looks like a period...

This is hard, we need principles here. I doubt we would have a high agreement about it.

**Comment by dcillessen** [comment]
In my mind "hot weather" is compositional. It is the combination of ewn-01250274-a and ewn-11545095-n.  I'd similarly agree that ewn-11460108-n "cold weather" is compositional. 

OED does not have an entry for "hot weather" or "cold weather" but does feature entries for "hot", "cold", and "weather," which indicates that their conception of the phrase is compositional. The same is true of Webster's.

I found in these dictionaries no reference to a "time period" but weather is something which is always experienced as changing over time, even if slowly.

**Comment by jmccrae** [comment]
Closed by #566
