### ISSUE TITLE
Add Informal tags

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#104]
07726361-n (Interlingual Index: i77515)
(n) spud, potato, murphy, tater, white potato, Irish potato 
> an edible tuber native to South America; a staple food of Ireland

There should be some denotation (e.g., a sense link) to say that some members of the synset are informal

**Comment by arademaker** [comment]
what would be the criteria for define what is formal/informal?

**Comment by jmccrae** [comment]
I think the answer to past me is that we use an `exemplifies` link generally to `ewn-07171981-n` 'slang'

The answer to @arademaker is that this a decision for us to make based on our best lexicographic knowledge

For the specific example here we should add the following links:
exemplifies -> slang to the senses of 'spud', 'tater' and 'murphy'
