### ISSUE TITLE
Support slob format

### ISSUE THREAD

**Issue by balki** [globalwordnet/english-wordnet#1040]
**Is your feature request related to a problem? Please describe.**
[slob](https://github.com/itkach/slob) is a format used by dictionary app [aard2](https://github.com/itkach/aard2-android), which is used by many other ebook reader apps. 

**Describe the solution you'd like**
Please include slob format to release along with the existing xml, rdf options

**Describe alternatives you've considered**
Someone has converted and made available an older version here: https://github.com/itkach/slob/wiki/Word-dictionaries-(Wordnet-and-Freedict)#open-english-wordnet
Would prefer to download latest version from official source instead.

**Comment by jmccrae** [comment]
I could certainly see the value in supporting this. It appears that there is already an export of the 2022 release in Slob, so is the request just to use your converter and release this as part of our release process?
