### ISSUE TITLE
'suffer'

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#1043]
**Synsets**
 oewn-01798679-v (Interlingual Index: i30704)
(v) suffer experience (emotional) pain “Every time her husband gets drunk, she suffers”

oewn-00064841-v (Interlingual Index: i22102)
(v) suffer, [hurt](https://en-word.net/lemma/hurt) be in pain

oewn-02125976-v (Interlingual Index: i32364)
(v) suffer, [hurt](https://en-word.net/lemma/hurt), [ache](https://en-word.net/lemma/ache) feel physical pain “Were you hurting after the accident?”

oewn-00078154-v (Interlingual Index: i22163)
(v) suffer feel unwell or uncomfortable “She is suffering from the hot weather”

**Motivation**
There are four senses of 'suffer', which all basically mean 'to feel pain'. No other reference dictionary makes this distinction. The first sense allows transitive and intransitive usage and the others only allow intransitive usage, but they all seem to have the same frame.

**Comment by arademaker** [comment]
If the frames are the same and the same valency... I would agree to merge.
