### ISSUE TITLE
Consistency of `instance_hypernym` 

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#1044]
We permit `instance_hypernym`s for instances of a class of object, normally referring to named entities of a particular class. Thus it makes sense that such instances should not have further hyponyms and that a synset that is a instance hyponym cannot be a non-instance hyponym as well.

There are a few cases where this is broken at the moment

* "Small Magellanic Cloud" (`09461312-n`) and "Large Magellanic Cloud" (`09359177-n`) are hyponyms  of "Magellanic Cloud" (`09368400-n`)  which is an instance hyponym of "galaxy" (`08287963-n`). They should be holonyms.
* "mare nostrum" (`09369905-n`) is a hyponym of "Mediterranean Sea" (`09372942-n`). They should be synonyms
* "Fury" (`09529469-n`) has three hyponyms ("Alecto", "Megaera", "Tisiphone") but is an instance hyponym of "mythical creature" (`09515254-n`). This should be the other way around ("Alecto" is an instance hyponym of "Fury")
* "God Almighty" (`09559474-n`) is an instance hyponym, but should be a normal hypernym
* "Titan" (`09595603-n`) has a similar problem to "Fury"
* "British West Indies" (`08765327-n`) is an instance hyponym of "West Indies" (`08764887-n`) and should be a holonym
* "Blighty" (`08893374-n`) is a hyponym of "Great Britian" and should be a synonym
* "Guernsey" (`08907571-n`) and "Jersey" (`08907465-n`) are hyponyms of "Channel Island" and should be a holonyms
* "Orion" (`09403029-n`) is hyponym of "gaseous nebula" but it should be a instance hyponym
* "Isle of Wight (`09502368-n`) is a hyponym of "county" but it should be a instance hyponym
* "Age of Enlightenment" (`08489601-n`) should be an instance hyponym of "reform movement"
* "Logrono" (`09048869-n`) is a hyponym of "Spain" but should be a holonym
* "Alabama" (`09075641-n`) is a hyponym of "Southern United States" but should be a holonym

This issue should also extend the validation to check that 
* No synset has both `hypernym` and `instance_hypernym`
* A synset that has an `instance_hypernym` cannot be the `hypernym` or `instance_hypernym` of any other synset

**Comment by ekaf** [comment]
Thanks @jmccrae, your theorems above are very useful for spotting missclassified relations: in general, when an instance_hyponym appears to have further hyponyms, these are actually often part meronyms instead. Please note that your comment above mentions _holonyms_, where you most probably meant _meronyms_ (which is the relation label that OEWN correctly assigns to these cases).
