### ISSUE TITLE
disinterest not defined as lack of interest

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#111]
Only one sense of 'disinterest' does not cover the most frequent usage

06214753-n (Interlingual Index: i69139)
(n) disinterest, neutrality 
> tolerance attributable to a lack of involvement

**Comment by restinplace** [comment]
"Disinterested" does not mean uninterested or lacking interest.
I hate to say this, but the possibility that this could be added to a 
dist is the reason that (imho) crowd-sourced lexicography is not 
good -- a single non-subtle error of this type has a disproportionate 
negative impact on the perception of quality of the work as a whole.

**Comment by jmccrae** [comment]
This refers to the noun 'disinterest' not the adjective 'disinterested'

This sense is contained in other dictionaries:
https://www.lexico.com/definition/disinterest

New synset:
disinterest: lack of interest
hypernym of `ewn-00026390-n` feeling

**Comment by arademaker** [comment]
@restinplace can you ellaborate more? I understand your concerns and I have been also very skeptical about what will happen with this resource. But we need more arguments. Why kind of analysis or methodoloy we are missing?

**Comment by arademaker** [comment]
Taking more about the particular issue:

> "Disinterested" does not mean uninterested or lacking interest.

So what is disinterested? Google gives me two definitions for the adj and two for the noun:

https://www.google.com/search?client=firefox-b-e&q=disinterested
https://www.google.com/search?client=firefox-b-e&q=disinterested#dobs=disinterest

I believe we can follow Google?

**Comment by vcvpaiva** [comment]
well, I think you can use Google if you read the link/page that says:
"Disinterested" and "uninterested" have different meanings, but people are starting to confuse them. An uninterested person is bored, unconcerned, or indifferent; and a disinterested person is impartial, unbiased, or has no stake in the outcome.
So the first one is bad, but the second one is very good (imho of course)

**Comment by dcillessen** [comment]
> This refers to the noun 'disinterest' not the adjective 'disinterested'
> 
> This sense is contained in other dictionaries:
> https://www.lexico.com/definition/disinterest
> 
> New synset:
> disinterest: lack of interest
> hypernym of `ewn-00026390-n` feeling

This definition of "disinterest" appears in OED ([disinterest n, def 3](https://oed.com/view/Entry/54616?rskey=u1lUUL&result=1&isAdvanced=false#eid)) as well as AH ([disinterest n. def 2](https://www.ahdictionary.com/word/search.html?q=disinterest)) and Webster's ([disinterest n. 2](https://www.merriam-webster.com/dictionary/disinterest)). 

I agree with John that we should add the new synset related to `ewn-00026390-n` "feeling"
