### ISSUE TITLE
asymmetry as synonym of disproportion

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#112]
Only sense of asymmetry is mathematical

05072886-n (Interlingual Index: i63615)
(n) dissymmetry, imbalance, asymmetry (mathematics) a lack of symmetry

But could also be a member of:

13921202-n (Interlingual Index: i109977)
(n) disproportion 
> lack of proportion; imbalance among the parts of something

**Comment by arademaker** [comment]
I would vote to have one synset with `asymmetry (mathematics)` and the rest in the other synset.
