### ISSUE TITLE
Issues with 2024 release candidate

### ISSUE THREAD

**Issue by fcbond** [globalwordnet/english-wordnet#1121]
Running validate from the wn module, picked up a couple of issues, see the attached output.

Note to get it to run I had to pretend the DTD was "http://globalwordnet.github.io/schemas/WN-LMF-1.1.dtd".  I don't think that has an effect on the issues.

I think the only show stopper is this:
 ILI is repeated across synsets
     oewn-00035037-s: {'ili': 'i216'}
    oewn-00042912-s: {'ili': 'i216'}
    oewn-00680696-v: {'ili': 'i34688'}
    oewn-00766556-s: {'ili': 'i4234'}
    oewn-00770909-s: {'ili': 'i4234'}
    oewn-00951435-n: {'ili': 'i40396'}
    oewn-00951878-n: {'ili': 'i40396'}
    oewn-02605751-v: {'ili': 'i34688'}

[poi.txt](https://github.com/user-attachments/files/17401439/poi.txt)

**Comment by jmccrae** [comment]
This appears to be cases where PWN3.1 divided some PWN 3.0 senses:

oewn-00035037-s (Interlingual Index: i216)
(s) [activated](https://en-word.net/lemma/activated) (([armed forces](https://en-word.net/id/oewn-08215965-n))) (military) set up and placed on active assignment “a newly activated unit”
oewn-00042912-s (Interlingual Index: i216)
(s) [activated](https://en-word.net/lemma/activated) rendered active; e.g. rendered radioactive or luminescent or photosensitive or conductive

oewn-00766556-s (Interlingual Index: i4234)
(s) [devious](https://en-word.net/lemma/devious), [roundabout](https://en-word.net/lemma/roundabout), [circuitous](https://en-word.net/lemma/circuitous) deviating from a straight course “a scenic but devious route” “a long and circuitous journey by train and boat” “a roundabout route avoided rush-hour traffic”
(s) [roundabout](https://en-word.net/lemma/roundabout), [circuitous](https://en-word.net/lemma/circuitous) marked by obliqueness or indirection in speech or conduct “the explanation was circuitous and puzzling” “a roundabout paragraph” “hear in a roundabout way that her ex-husband was marrying her best friend”

oewn-00951435-n (Interlingual Index: i40396)
(n) [technology](https://en-word.net/lemma/technology) the application of the knowledge and usage of tools (such as machines or utensils) and techniques to control one's environment “the mastery of fire was a huge advance in human technology”
oewn-00951878-n (Interlingual Index: i40396)
(n) [engineering](https://en-word.net/lemma/engineering) the practical application of technical and scientific knowledge to commerce or industry

oewn-00680696-v (Interlingual Index: i34688)
(v) [book](https://en-word.net/lemma/book) engage for a performance “Her agent had booked her for several concerts in Tokyo”
oewn-02605751-v (Interlingual Index: i34688)
(v) [book](https://en-word.net/lemma/book) register in a hotel booker

We should probably just give the ILI for the sense that is closest to the one in the ILI and mark the other as `in`
