### ISSUE TITLE
Dharma represents two concepts

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#113]
09548714-n (Interlingual Index: i86691)
(n) Dharma 
> basic principles of the cosmos; also: an ancient sage in Hindu mythology worshipped as a god by some lower castes

These two are quite distinct IMHO

**Comment by jmccrae** [comment]
Update current synset definition to 

an ancient sage in Hindu mythology worshipped as a god by some lower caste

New synset

Dharma: basic principles of the cosmos according to some Indian religions
hypernym `ewn-05881099-n` (principle)
similar to `ewn-06253100-n` (Tao)

**Comment by arademaker** [comment]
two issues right? split and update the glosses.

**Comment by jmccrae** [comment]
Not a true split, as we maintain the current synset in place due to it being a hyponym of 'Hindu deity'

In a true split we delete the current synset and add two new synsets.
