### ISSUE TITLE
slang expression and slang term

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#114]
07174118-n (Interlingual Index: i74279)
(n) slang expression, slang, slang term 
> informal language consisting of words and expressions that are not considered appropriate for formal occasions; often vituperative or vulgar; "their speech was full of slang expressions"

inconsistency between the synset's elements; "slang" has a meaning of linguistic register, while "slang term" and "slang expression" suggest an individual slangy word or saying

**Comment by jmccrae** [comment]
New synset:

'slang expression', 'slang', 'slang term': a word or expression that outside of standard usage and very informal
hyponym of `ewn-07166088-n`

**Comment by arademaker** [comment]
sorry, I didn't understand what is your suggestion. adding a new synet for `slang expression` and `slang term` is ok. But `slang` will be kept in this synset alone, right?

**Comment by jmccrae** [comment]
you are right. I think 'slang word' would be a good new member
