### ISSUE TITLE
Satire as a genre

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#115]
the single entry for satire is limited to language, which is too narrow

06790003-n (Interlingual Index: i72103)
(n) caustic remark, satire, sarcasm, irony 
> witty language used to convey insults or scorn; "he used sarcasm to upset his opponent"; "irony is wasted on the stupid"; "Satire is a sort of glass, wherein beholders do generally discover everybody's face but their own"--Jonathan Swift

**Comment by jmccrae** [comment]
New synset:

'satire':  a genre of literature and performing arts, in which shortcomings are held up to ridicule, ideally with the intent of shaming others (based on https://en.wikipedia.org/wiki/Satire)
hyponym of `ewn-07106786-n` (literary genre)

**Comment by arademaker** [comment]
In the gloss corpus, I didn't find the need for this new sense. Why not make the gloss more general with:

>  a genre of literature and performing arts, in which shortcomings are held up to ridicule, ideally with the intent of shaming others; witty language used to convey insults or scorn; "he used sarcasm to upset his opponent"; "irony is wasted on the stupid"; "Satire is a sort of glass, wherein beholders do generally discover everybody's face but their own" -- Jonathan Swift

The links for Wikipedia can be a new kind of relations?!

**Comment by arademaker** [comment]
For course, that will require a possible reallocation of this synset in the network.

**Comment by jmccrae** [comment]
I don't want to reallocate if the hyponym is not clearly wrong. The synset that is already there seems to concern 'sarcasm' more than 'satire', but 'sarcasm' is not a genre of literature (unlike 'satire'). As it would have different members, I propose a new synset as a kind of literary genre.
