### ISSUE TITLE
deceitfulness

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#120]
04883756-n (Interlingual Index: i62611)
(n) guile, craftiness, deceitfulness 
> the quality of being crafty

Deceitfulness involves lying or being false which guile and craftiness do not. They should be split

**Comment by jmccrae** [comment]
New synset:

deceitfulness: the quality of being deceitful

**Comment by arademaker** [comment]
relationships between the synset and the other senses of deceitful must be adapted.

**Comment by jmccrae** [comment]
yes, this synset should be marked as derived from both `ewn-01226630-s` and `ewn-01225960-s`
