### ISSUE TITLE
tuners of other musical instruments

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#123]
10752774-n (Interlingual Index: i93803)
(n) piano tuner, tuner 
> someone who tunes pianos

Introduce a "tuner" as a tuner of any musical instrument

**Comment by arademaker** [comment]
This kind of 'situation' is common. We have a single word and a word with a modifier. One can understand that the word without modifier in a proper context will stand for the complete form. How to deal with that consistently?

**Comment by jmccrae** [comment]
The case you are talking about is generally handled by introducing both terms. The issue raised here is that you can also be a "guitar tuner" and so "tuner" should a hypernym of "piano tuner" and "guitar tuner"

**Comment by arademaker** [comment]
Yes. I understood. We should add a synset for tuner hypernym of this synset. What I was trying to say is that this problem may happen many more times. If `A` is a synset with `{word, modifier word}` check if there is a synset `B` that contains `{w}` and `B` hypernym of `A`.

**Comment by jmccrae** [comment]
That is probably a good idea, I imagine there would be a lot

**Comment by jmccrae** [comment]
New definition "someone who tunes a musical instrument"

**Comment by jmccrae** [comment]
This definitely needs a new synset between piano tuner and trained worker
