### ISSUE TITLE
Catapults

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#126]
02985366-n (Interlingual Index: i51633)
(n) catapult, arbalest, arbalist, trebucket, bricole, trebuchet, mangonel, ballista, onager 
> an engine that provided medieval artillery used during sieges; a heavy war engine for hurling large stones and other missiles

the synset consists of arbalest, ballista, mangonel, trebuchet that are the specific kinds of catapult or other kind of weapon

**Comment by restinplace** [comment]
Uh, aren't plenty of words both generic and specific?
Not clear what you are trying to fix.

**Comment by jmccrae** [comment]
This request was sent to me via email. I understand it as a request to add more specific synsets for particular catapult designs, e.g., "trebuchet" as a hyponym of "catapult"

**Comment by jmccrae** [comment]
Proposed new synsets

New hyponyms of catapult:
'trebuchet', 'trebucket': catapult that uses a swinging arm to throw a projectile (see https://en.wikipedia.org/wiki/Trebuchet)
'mangonel', 'bricole', 'traction trebuchet': catapult operated by manpower pulling cords attached to a lever and sling to launch projectiles. (from https://en.wikipedia.org/wiki/Mangonel)
'onager': small catapult used by the Romans (see https://en.wikipedia.org/wiki/Onager_(weapon))

Hyponym of engine `ewn-03292914-n`
'ballista', 'bolt thrower': ancient missile weapon that throws bolts or stones (see https://en.wikipedia.org/wiki/Ballista)

Hyponym of crossbow `ewn-03141020-n`
'arbalest', 'arbalast': a late version of a crossbow with a steel bow (see https://en.wikipedia.org/wiki/Arbalest)

Hyponym of bowman `ewn-09824747-n`
'arbalist': an archer who uses an arbalest
