### ISSUE TITLE
Former name

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#130]
Some synsets are defined as former name of things

14981196-n (Interlingual Index: i115736)
(n) muriatic acid 
> a former name for hydrochloric acid

They should probably be merged into the modern synset and marked as archaic terms

**Comment by jmccrae** [comment]
Add property `exemplifies` `ewn-archaism-n-07087487-01`

**Comment by arademaker** [comment]
this will be a relation between a sense and a synset, right?
