### ISSUE TITLE
hood and 'hood

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#133]
PWN 3.0 contains two senses 

http://wnpt.sl.res.ibm.com/wn/search?term=word_en%3Ahood

08641944-n 'hood | bairro ((slang) a neighborhood)
08225334-n hood ((slang) a neighborhood)

This error was corrected in the PWN 3.1

**Comment by jmccrae** [comment]
It seems that this wasn't fixed in 3.1 as we would have already taken up this change. Otherwise this seems like a simple merge.

**Comment by arademaker** [comment]
Hi @jmccrae , but this repository is based on PWN 3.0, right? Do you mean that 3.1 fixes were applied to 3.0 data? Mapping the synsets from 3.1 to 3.0 and fixing them?

**Comment by arademaker** [comment]
Sorry, maybe I didn't understand previous messages. The XML files are saying that all here is PWN 3.1, https://github.com/globalwordnet/english-wordnet/blob/master/src/wn31-verb.competition.xml#L9. OK.

**Comment by jmccrae** [comment]
Hi Alex, this repo is based on 3.1 not 3.0.

I checked the 3.1 sources and these are two different synsets there too
