### ISSUE TITLE
adj personal 

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#134]
I don't see the diference between (PWN 3.0 ids):

01616157-a personal (particular to a given individual)

01767329-a personal  (concerning or affecting a particular person or his or her private life and personality; "a personal favor"; "for your personal use"; "personal papers"; "I have something personal to tell you"; "a personal God"; "he has his personal bank account and she has hers")

**Comment by restinplace** [comment]
The first (01616157-a) is an abstract instance of many possible individuals:
  "Every user has a personal password."
It is probably a synonym of WN: 
  individual#4, private#3 (concerning one person exclusively) 
  "we all have individual cars"; "each room has a private bath"
The second (01767329-a) refers to a specific individual:
  "His personal favorite password is unprintable."
Together (the 2nd and 3rd instances refer to the individual): 
  "His personal password is personal, but his personal public 
    password is not."

**Comment by jmccrae** [comment]
Another example of issue #35

**Comment by Ciara97olo** [comment]
I agree should be merged, I think that 01767329-a also includes the abstract instance in the definition and examples
