### ISSUE TITLE
rock

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#135]
PWN 3.0:

14696793-n rock, stone  | (material consisting of the aggregate of minerals like those making up the Earth's crust; "that mountain is solid rock"; "stone is abundant in New England and there are many quarries")

09416076-n stone, rock | (a lump or mass of hard consolidated mineral matter; "he threw a rock at me")

could anyone explain the difference to me?

**Comment by arademaker** [comment]
The problem here is the inconsistencies of the hyponyms. See `claystone` that is a hyponym of 14696793-n rock but `xenolith` is hyponym of 09416076-n. 

Note also that `limestone` (http://wnpt.sl.res.ibm.com/wn/synset?id=14936226-n) has the gloss `a sedimentary rock consisting mainly of calcium that was deposited by the remains of marine animals)`  but it is not the hyponym of sedimentary_rock (http://wnpt.sl.res.ibm.com/wn/synset?id=14698000-n) as it should be.

**Comment by restinplace** [comment]
> could anyone explain the difference to me?
First is the substance ("material..."), second is the object ("a lump or ...").
Asking seriously, is there a reason this is not clear from the defs?

**Comment by arademaker** [comment]
What was the decision? What will be changed? @restinplace, my second comment present the problems. Definitions were clear but not consistent with the relations.

**Comment by jmccrae** [comment]
@arademaker I thought you were satisfied with @restinplace's explanation.

One synset refers to rock as a material, and the second a rock as an object. The hypernyms of 'claystone' and 'limestone' (as a material) and 'xenolith' (as a piece of rock) are fine to my understanding

**Comment by alexandretessarollo** [comment]
What about soapstone? 15044327-n Shouldn't it be under rock substance?

**Comment by jmccrae** [comment]
Currently 'soapstone' is a mineral (hence a material) but not a rock. I have no problem with adding this link as well.

Proposal: `ewn-15068894-n` is a hyponym of `ewn-14720954-n`

**Comment by arademaker** [comment]
The definitions of types of rocks are very confusing in PWN 3.0/3.1. Maybe xenolith was not a good example. But we may also be questioning `clastic rock` begin a type of the rock/object versus a sedimentary rock begin a type of rock/material.

To keep our focus on the problems already mentioned. Limestone need not be hyponym of rock (substance) if it is already hyponym of `sedimentary rock`.

**Comment by arademaker** [comment]
Acording to https://en.wikipedia.org/wiki/Soapstone, it is not a mineral but a type of  metamorphic rock.

**Comment by jmccrae** [comment]
I asked a geology PhD: Apparently soapstone is a mineral but maybe also a rock. Essentially, a mineral is composed of a single chemical compound (which soapstone is), but it could be a rock because of how it is made. I wouldn't recommend changing anything here.

In English, it (in my opinion) is incorrect to say "a limestone", you would have to say "a lump of limestone". In contrast it is fine to say "a clastic rock" as well as a "lump of clastic rock", similarly with a "sedimentary rock". Probably both words should have both senses but this is a case of **systematic polysemy** and is a much bigger problem in the wordnet so we should probably postpone these changes.

The link between 'limestone' and 'rock' is superfluous as it is already covered by saying it is a 'sedimentary rock.' This could be removed.

**Comment by arademaker** [comment]
About the second paragraph:

> CaCo3 cement, which may be fine grained (called micrite) or coarse grained (called sparite), holds the fossils (such as coccoliths and foraminifera) together to form a limestone.

From [How is limestone formed?](https://www.bgs.ac.uk/discoveringGeology/geologyOfBritain/limestoneLandscapes/whatIsLimestone/howFormed.html)

Yes, systematic polysemy occurs a lot in the domain-specific texts. That is why such things are relevant to us. But I understand that this is not a priority for a resource designed to general-purpose language comprehension.

**Comment by jmccrae** [comment]
@arademaker What is the issue exactly?

**Comment by jmccrae** [comment]
For general discussion of systematic polysemy please use issue #243

**Comment by arademaker** [comment]
Well, I accepted the fact that this resource is not oriented to be a domain specific expansion. Given that, removing the redundant relation can close this issue. 

But we are working on a branch of PWN to support language processing of texts from technical domain. In our case, a more systematic revision of the rocks and minerals hierarchy is needed to. We are using ontologies and corpus as references.

**Comment by jmccrae** [comment]
@arademaker close this issue?

**Comment by arademaker** [comment]
@alexandretessarollo and I have a paper about our systematic review of all terms related to lithology. So yes, you can close this issue for now and latter we can see how to sync our own PWN branch (https://github.com/own-pt/own-en) with this repo.
