### ISSUE TITLE
typo in 00176880-r "repeatedly"

### ISSUE THREAD

**Issue by vcvpaiva** [globalwordnet/english-wordnet#136]
00176880-r repeatedly 
(several time; "it must be washed repeatedly")

Surely this should be several times!

Yes, I have read the [contributing guidelines](https://github.com/globalwordnet/english-wordnet/blob/master/CONTRIBUTING.md) but would rather not deal with the whole forking/pulling/committing cycle, if this is allowed. (I'd rather not mess things up through my incompetence with github processes. But if this is not allowed, no worries. just close the issue.)

**Comment by jmccrae** [comment]
Thanks for this.

I have updated the contribution guidelines to cover contributing by making issues... thanks for the reminder :)

**Comment by vcvpaiva** [comment]
Thanks! 
one more thing: if you want to classify the kinds of issues, as in the contributing guidelines, I think you need a class "other" or "misc", because the kinds you have so far are not enough. For instance, there are many synsets that are too English. they might be ok in a monolingual thesaurus, but will not work if we want to have parallel corpora from a multilingual one. A gloss that is an idiom is an example of what I mean, e.g. 01369346-v wear_out, bust, break, fall_apart, wear 
(go to pieces; "The lawn mower finally broke"; "The gears wore out"; "The old chair finally fell apart completely")

**Comment by jmccrae** [comment]
Hi, thanks. I would rather avoid a `misc` category as the tags should indicate the action that needs to be taken to fix the problem, which `misc` does not do. In the case you give it may be `definition` as the definition needs to be updated to better capture a clear sense (that would work cross-linguistically) or something like `synset split` to make two clearer concepts out of the one existing concept.
