### ISSUE TITLE
northern

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#137]
I can't see the difference, especially because the `or` which makes `situated in` valid for both cases.

- http://wnpt.sl.res.ibm.com/wn/synset?id=01604226-a (situated in or coming from regions of the north ...)
- http://wnpt.sl.res.ibm.com/wn/synset?id=01601297-a (situated in or oriented toward the north; ...)

**Comment by jmccrae** [comment]
This also seems to affect southern, eastern (but not western).

To provide a cross linguistic motivation, Irish distinguishes between 'lying north', 'from the north'.

* 'thuaidh': lying north or going to the north
* 'tuaisceatach': from the north or in the north

So perhaps, there is a justification for this split, but the definitions could be updated?

**Comment by arademaker** [comment]
> So perhaps, there is a justification for this split, but the definitions could be updated?

it makes sense for me.

**Comment by arademaker** [comment]
What changes will be made? What was the decision?

**Comment by jmccrae** [comment]
Hi, I closed because the last comment seemed to agree that no changes are necessary, right?

**Comment by arademaker** [comment]
I believe that the glosses should be updated to remove the confusing intersections caused by the OR. We have:

1. 01601297-a northerly, northern (situated in or oriented toward the north; "the northern suburbs"; "going in a northerly direction")

2. 01601069-a northerly, northern (coming from the north; used especially of wind; "the north wind doth blow"; "a northern snowstorm"; "the winds are northerly")

3. 01604226-a northern (situated in or coming from regions of the north; "the northern hemisphere"; "northern autumn colors")

1 and 2 start with `situated in...`. 2 and 3 have `coming from...`. Only 1 has `oriented toward...`

**Comment by jmccrae** [comment]
Okay, good point. I would suggest removing the 'situated in' from the definition 'situated in or oriented toward the north' as this seems more disjoint to me.

**Comment by arademaker** [comment]
IMHO, considering your argument about cross-linguistic motivation, it would make things clear if we make the glosses really disjoint avoiding the OR: 1) `oriented toward...`; 2) `coming from...`; and 3) `situated in...`. But we would have to double-check relations since (2) make the observation "used especially of wind" (maybe unnecessary?)

**Comment by jmccrae** [comment]
I am not keen to make such a fine sense distinction and introduce a new synset as (IMHO) this is not a sense distinction that is made in general in English, e.g., "Brazilian" means both situated in and coming from Brazil. The sense of orientated is synonymous with "northerly" and there is not normally an equivalent for most origins, i.e., there is no "Brazilianly" meaning orientated towards Brazil.

Perhaps we can push this until we have a better idea of when to make sense distinctions (see #243)?

**Comment by arademaker** [comment]
Ok, but I am not suggesting the creation of new synsets, just the rewritten of the definitions.

**Comment by dcillessen** [comment]
Is the idea to essentially remove "or" from these definitions, and to have each of refer to orientation, origin, and situation individually? 

Perhaps the new definitions would look something like: 

01601297-a northerly, northern (oriented toward the north; "going in a northerly direction")

01601069-a northerly, northern (coming from the north; used especially of wind; "the north wind doth blow"; "a northern snowstorm"; "the winds are northerly")

01604226-a northern (situated in the regions of the north; "the northern hemisphere"; "northern autumn colors"; "the northern suburbs")

To me this makes sense. the original definition for 01601297-a describes a sense of "northerly" which is also essentially covered by 01604226-a.

**Comment by jmccrae** [comment]
Closed by #573
