### ISSUE TITLE
missing a word in the gloss

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#138]
http://wnpt.sl.res.ibm.com/wn/synset?id=02685703-a

(of or denoted by an integer)

should be 

(made of or denoted by an integer)

?

**Comment by jmccrae** [comment]
This definition is exactly the same as the one used by the OED:

https://en.oxforddictionaries.com/definition/integral

My intuition is that it sounds okay as is, but maybe a bit old-fashioned. As this is simply the pertainym of integer, shouldn't we use the more standard definition for pertainyms:

"of or pertaining to integers"

**Comment by jmccrae** [comment]
@arademaker close this issue?

**Comment by arademaker** [comment]
I prefer definitions more explicit but fine
