### ISSUE TITLE
Quality guidelines for new synsets

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#141]
Discussion of minimal quality guidelines for new synsets.

Comments from @fcbond 
* should we ask for subcategorization patterns for verbs?
* should we ask for lexicographer filenames?
* I would prefer not to have the quotes in the examples
* definitions should use ';' to separate sentences and for nothing else :-)
* do we want new synsets/lemmas to have all relevant links
* > domain, derivation, antonym, synonym?  

Comments from @arademaker 
If we are opening for broad collaboration, we will need to be specific. Will we accept new synsets? What about new relations? I agree with Francis that we need to ask for relatively complete entries. But how to consistently check it? Will we allow new lexicographer files or subcategorization patterns? I agree with the quotes and the `;` too.

We may need to reimplement the grind tool for data validation.

**Comment by jmccrae** [comment]
I have written these guidelines:

https://github.com/globalwordnet/english-wordnet/blob/issue-141/NEW_SYNSETS.md

PR is #252

**Comment by fcbond** [comment]
I would add:
Section Definition

- all new entries should also have a short example

Section Linked:

- A new verb must have one or more subcategorization patterns.

- New adjectives should have an antonym if appropriate (although I suspect we will not have so many new basic adjectives).

I am not sure whether we should require new lexicographer files, ...

**Comment by arademaker** [comment]
require or allow new lexicographer files? But new files would means change the top level ontology of PWN. Maybe that is a relevant discussion. Do we need changes on that?

**Comment by arademaker** [comment]
> Systematic polysemy: e.g., using a part to refer to a whole ** Example: "congress" meaning the "members of congress"

The example is not part/whole, right?

**Comment by arademaker** [comment]
Should we suggest more relations for nouns? Classified by topic ?

**Comment by jmccrae** [comment]
I addressed @fcbond's comments. Antonyms for adjectives was already in the definition.

@arademaker> "members of congress" are part of "congress", surely? I am not sure what you mean by more relations for nouns, I just added a note that more relations is better.
