### ISSUE TITLE
Validation tool 

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#142]
Introduce a new validation tool (based on existing scripts) and verify that it is equivalent in expressiveness to grind in validating the taxonomy

**Comment by jmccrae** [comment]
This issue has been started:

https://github.com/globalwordnet/english-wordnet/blob/master/scripts/validate.py

However closing this as per original request may take longer, so I will bump this to 2021

**Comment by arademaker** [comment]
Closing or postponing?

**Comment by arademaker** [comment]
We may consider many validations that we implemented in https://github.com/own-pt/mill

**Comment by jmccrae** [comment]
The issue is still open, the change in release marks that we do not aim to completely solve this by the next release (April 2020).

Yes, this may be a good thing to re-use your previous work from OMW-PT.

**Comment by jmccrae** [comment]
Validate.py is now stable. We can close this issue.
