### ISSUE TITLE
License for the resource

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#144]
Should we move from the WordNet license to a more widely accepted license such as CC-BY or [CDLA](https://cdla.io/)?

**Comment by jmccrae** [comment]
Added a pull request to change the resource to CC-BY

**Comment by arademaker** [comment]
We are talking about https://creativecommons.org/licenses/by/4.0/, right?

**Comment by jmccrae** [comment]
Yes, that is the link to the license

**Comment by arademaker** [comment]
I agree with the proposal
