### ISSUE TITLE
Add "complicit"

### ISSUE THREAD

**Issue by dkasak** [globalwordnet/english-wordnet#145]
I sent this omission to the Princeton WordNet mailing list before I knew that version was no longer maintained. Today I saw your fork, so here goes:

(adj) complicit

> Involved with others in an activity that is unlawful or morally wrong.

Derived by back-formation from complicity, which already exists.

<https://en.oxforddictionaries.com/definition/complicit>

**Comment by jmccrae** [comment]
Yes, this should certainly be added.

**Comment by jmccrae** [comment]
similar to `ewn-01518910-a`
