### ISSUE TITLE
Duplicate "mung bean"

### ISSUE THREAD

**Issue by cmbant** [globalwordnet/english-wordnet#149]

**Comment by jmccrae** [comment]
Refers to:

ewn-12599160-n
(n) green soy, green gram, green bean, golden gram, moong, munggo, mung bean, mash bean, mung, monggo seed of the mung bean plant; used for food


ewn-07741018-n (Interlingual Index: in)
(n) green soy, green gram, green bean, golden gram, moong, munggo, mung bean, mash bean, mung, monggo seed of the mung bean plant used for food

**Comment by restinplace** [comment]
This is a poorly worded def; not a duplicate.  The first refers 
to the seed, the second refers to food (like pea#2, pea#1).

**Comment by jmccrae** [comment]
Change the definition of `ewn-12599160-n` to "seed of the mung bean plant"

**Comment by arademaker** [comment]
mung_bean has only one sense in PWN 3.0 (2 below), in PWN 3.1 we have 3 senses being two of them in the `noun.plant` (the plant and the seed of the plant):

1. mung, mung bean, green gram, golden gram, moong, mash bean, munggo, monggo, green soy, green bean -- (seed of the mung bean plant; used for food)

2. mung, mung bean, mung bean plant, Vigna radiata, Phaseolus aureus -- (erect bushy annual widely cultivated in warm regions of India and Indonesia and United States for forage and especially its edible seeds; chief source of bean sprouts used in Chinese cookery; sometimes placed in genus Phaseolus)

3. mung bean, mung, green bean, green gram, golden gram, moong, mash bean, munggo, monggo, green soy -- (seed of the mung bean plant used for food)

I doubt the change was consistently made to all other seeds and plants used or not for food! ;-)

**Comment by jmccrae** [comment]
It seems that other similar words, e.g., 'pea', 'lentil', 'soybean', 'chickpea' do make this distinction. All of these were in PWN3.0. I think for this lemma, the senses were added to conform to these words.
