### ISSUE TITLE
down (02061678-a)

### ISSUE THREAD

**Issue by malangali** [globalwordnet/english-wordnet#15]
02061678-a 'being put out by a strikeout'

2 issues:

1. Link to baseball domain

2. Definition is wrong. As a verb, a strikeout is common but not necessary, eg https://twitter.com/BeaverSoftball/status/967807448298876929.
But if there are "two down in the bottom of the ninth" (the example sentence), there is no implication of how the players were downed out.
https://twitter.com/search?q=%22two%20down%20in%20the%20bottom%20of%20the%20ninth%22&src=typd

**Comment by jmccrae** [comment]
New definition: 'being put out in a game of baseball'
Add link domain_topic to `ewn-00472688-n`
