### ISSUE TITLE
Bug: Invalid synset offsets

### ISSUE THREAD

**Issue by ekaf** [globalwordnet/english-wordnet#152]
The synset offsets mentioned in the Princeton-compatible db files
do not correspond to those mentioned in the XML files.
For each part of speach, the first few offsets are identical,
after which the rest of the offsets become increasingly divergent.

For example, with adjectives, the discrepancy starts with
offset 00003937 in data.adj being off-by-one from ewn-00003938-a
in wn-adj.all.xml, after which the differences between offsets
become increasingly larger.

data.adj:
00003937 00 a 01 dying 0 003 ! 00003356 a 0101 & 00004169 a 0000 & 00004294 a 0000 |
in or associated with the process of passing from life or ceasing to be;
"a dying man"; "his dying wish"; "a dying fire"; "a dying civilization"  

wn-adj.all.xml:
Sense id="ewn-dying-a-00003938-01" n="0" synset="ewn-00003938-a" dc:identifier="dying%3:00:00::"

The same occurs also with the nouns, verbs and adverbs,
indicating that the two db formats might have been compiled
from different revisions of the lexical files.

**Comment by jmccrae** [comment]
We have no intention of syncing the identifiers used in the XML with those in the WNDB export. Instead identifiers are frozen to those that are in PWN 3.1 and for new synsets we will use a new scheme not based on byte offsets. 

For mapping between previous versions, please use the Collaborative Interlingual Index (CILI)
