### ISSUE TITLE
Overloaded sense keys

### ISSUE THREAD

**Issue by ekaf** [globalwordnet/english-wordnet#153]
In the XML dbs, 76 sense keys are members of two different synsets.
For example,with "abbreviated%5:00:00:short:00":

wn-adj.all.xml:
Sense id="ewn-abbreviated-s-01439307-01" n="0" synset="ewn-01439307-s" dc:identifier="abbreviated%5:00:00:short:00"
Sense id="ewn-abbreviated-s-01445488-01" n="1" synset="ewn-01445488-s" dc:identifier="abbreviated%5:00:00:short:00"

english-wordnet-2019.xml:
Sense id="ewn-abbreviated-s-01439307-01" synset="ewn-01439307-s" dc:identifier="abbreviated%5:00:00:short:00"
Sense id="ewn-abbreviated-s-01445488-01" synset="ewn-01445488-s" dc:identifier="abbreviated%5:00:00:short:00"

**Comment by arademaker** [comment]
@ekaf mentioned 76 sense keys. But @jmccrae closed the issue solving just one case, is it right?

**Comment by jmccrae** [comment]
Most changes were made in this previous commit:
https://github.com/globalwordnet/english-wordnet/commit/30c8304235fc8ecc67cf047831d84d39da49fc0d

I just verified the result today

**Comment by ekaf** [comment]
76 was the number of overloaded sense keys cited in english-wordnet-2019.xml, which are now obsolete, since they no longer correspond to the new index.sense file.

The new index.sense is improved, but still has a problem, because it just fails to mention the overloaded lex_ids which actually occur in the data files. For example, index.sense only knows one sense of "multiply" in the lexical file 30 (verb.change):

multiply%2:30:00:: 00248618 2 0

But data.verb has two senses of multiply#0 from verb.change in different synsets but with the same overloaded lex_id:

00248306 30 v 02 multiply 0 manifold 1 009 (...)
00248618 30 v 02 manifold 0 multiply 0 002 (...)

I counted 28 such cases, so things are going in the right direction, but the issue remains.

In WN 3.1, there is only one sense of "multiply" in the lexical file verb.change, so my guess is that the bug will be found there, but who knows, when the lexical files are not released?

**Comment by jmccrae** [comment]
Yes, this seems to spring from the newly introduced synset members, which do not have a `lex_id`. I have updated the released `sense.index` but we should probably find a more permanent fix in the next version (see issue #157)
