### ISSUE TITLE
Index.sense offsets off by a few bytes

### ISSUE THREAD

**Issue by ekaf** [globalwordnet/english-wordnet#155]
In the index.sense file of the Princeton-compatible release, 23136 synset offsets differ from those in the data.* files. Most of these are verbs, plus a few nouns, adjectives and adverbs. For example:

index.sense:
aah%2:32:00:: 00867581 1 0

data.verb:
00867579 32 v 02 ooh 0 aah 0 001 @ 00914199 v 0000 01 + 02 00 | express admiration and pleasure by uttering `ooh' or `aah'; "They oohed and aahed when they unwrapped the presents"

The XMl ids are still different, and I understand that these are offsets in a "frozen WordNet 3.1" version:

wn-verb.communication.xml:
Sense id="ewn-aah-v-00867440-02" n="0" synset="ewn-00867440-v" dc:identifier="aah%2:32:00::"

But the 23136 diverging offsets in index.sense do not seem to correspond to any released data file.

**Comment by jmccrae** [comment]
Okay, it seems that the conversion script is less consistent than I had believed. I have uploaded a new `sense.index` generated directly from the release. This will not affect future releases as the sense.index will be generated along with the other data files.
