### ISSUE TITLE
Open the source?

### ISSUE THREAD

**Issue by ekaf** [globalwordnet/english-wordnet#156]
Some years ago, the Debian community argued that calling a WordNet-package "Open Source" implied to release the lexical files, since these are the primary and preferred format for making changes.

Otherwise it is very difficult for other developers to see exactly what is going on.

**Comment by jmccrae** [comment]
I don't understand this... the project uses the XML lexicographer files under the `src` folder. They seem quite clearly open source to me.

**Comment by ekaf** [comment]
OK, I was not aware that the files in the "src" directory are lexicographic source files, because I thought that this version still relied on Princeton-style lexical files. Sorry for this misunderstanding.

Now it will be much easier to resolve some issues, knowing that the src directory is the primary place to look.
