### ISSUE TITLE
Upper-case in the sense keys?

### ISSUE THREAD

**Issue by ekaf** [globalwordnet/english-wordnet#158]
According to the Princeton WordNet documentation, sense keys are in lower case, so that an upper-case and lower-case version of the same word-sense pair share the same sense key.

On the contrary, the new index.sense file contains upper-case words, which may be an improvement over the Princeton format, but breaks compatibility with applications that expect the standard format.

**Comment by jmccrae** [comment]
Fixed

**Comment by ekaf** [comment]
Almost there! The fix is good, but according to the Princeton "senseidx" manual, "lex_id is a two digit decimal integer", while the lex_ids in the new index.sense file include 578 hex numbers, which need conversion to decimal, like f. ex. "0a" in "active%3:00:0a::".

**Comment by jmccrae** [comment]
Thanks for this, yes indeed I made a small mistake here.

**Comment by ekaf** [comment]
This mistake is very easy to make, because in the data files, the lex_id is a "One digit hexadecimal integer" (quoting the wndb manual). Admittedly, this is a little confusing, and could be more streamlined.
