### ISSUE TITLE
Add "mentee"

### ISSUE THREAD

**Issue by dkasak** [globalwordnet/english-wordnet#159]
(n) mentee

> a person who is helped by a mentor (= a person who gives a younger or less experienced person help and advice over a period of time, especially at work or school)

https://dictionary.cambridge.org/us/dictionary/english/mentee

**Comment by jmccrae** [comment]
Member: mentee, mentoreee
Definition: one who is being mentored
Hypernym: ewn-00007846-n 'someone' (see #187)
Example: "A student mentor may support up to seven mentees"

**Comment by arademaker** [comment]
Why making it hyponym of “someone” and not something more specific like “student”? What are the arguments?

**Comment by jmccrae** [comment]
The two current definitions of "student" are

`ewn-10577282-n` (Interlingual Index: i92752)
(n) scholarly person, scholar, student, bookman 
> a learned person (especially in the humanities); someone who by long study has gained mastery in one or more disciplines

`ewn-10685137-n` (Interlingual Index: i93383)
(n) pupil, student, educatee 
> a learner who is enrolled in an educational institution

Neither of these seem like appropriate hypernyms.

**Comment by arademaker** [comment]
First, these needs revision. Why do we need the parenthetical restriction on the first synset?

Moreover, sorry, but you didn’t answer my question. You have just shown me two synsets and repeated that both are not suitable for being hyper of mentee. 

Maybe http://wn.mybluemix.net/synset?id=10059162-n?

**Comment by arademaker** [comment]
I think there are many things to improve in this part of the graph of PWN. We may need to redefine some concepts to remove the restriction of the formal enrollment with a school or university so we can have a learner as the most general concept related to someone that is in the process of learn. 

See http://wn.mybluemix.net/search?search_field=all&term=learner

**Comment by arademaker** [comment]
So we can make mentee a learner that have a mentor

**Comment by jmccrae** [comment]
I am not sure what you mean by 'parenthetical restrictions'

I don't see 'enrollee' as a relevant hypernym either. 

I am not keen on 'learner' as a hypernym either as it seems to be a different aspect. We currently don't say that 'mentor' is a 'teacher', so I am not sure of the validity of mentorees as learners.

Please note that the hypernym will become more specific later due to issue #187.

**Comment by jmccrae** [comment]
@arademaker> I closed this issue as the current hypernym is not _wrong_, and I don't know what a better solution would be. I am welcome to introduce new issues, however I want to go ahead with the synset as it is for the 2020 release.

**Comment by arademaker** [comment]
For the `parenthetical restriction`, I mean the `(especially in the humanities)` in the first definition above.

**Comment by jmccrae** [comment]
Can you create this as a new issue?

**Comment by dkasak** [comment]
What happened with this synset in the 2020 release, specifically the WNDB release? I can't seem to find neither "mentee" nor "mentoree" by grepping the files.

**Comment by jmccrae** [comment]
Not sure, it is there for me
```
jmccrae@nacreous [12:02:59] [~/Downloads] 
-> % unzip english-wordnet-2020.zip 
Archive:  english-wordnet-2020.zip
  inflating: adj.exc                 
  inflating: adv.exc                 
  inflating: data.adj                
  inflating: data.adv                
  inflating: data.noun               
  inflating: data.verb               
  inflating: index.adj               
  inflating: index.adv               
  inflating: index.noun              
  inflating: index.sense             
  inflating: index.verb              
  inflating: lexnames                
  inflating: noun.exc                
  inflating: verb.exc                
  inflating: verb.Framestext         
  inflating: sentidx.vrb             
  inflating: sents.vrb               
jmccrae@nacreous [12:03:17] [~/Downloads] 
-> % grep mentee data.noun 
15452915 18 n 02 mentee 1 mentoree 1 001 @ 00007972 n 0000 | one who is being mentored; "A student mentor may support up to seven mentees" 
```

**Comment by dkasak** [comment]
Eh, you're right, it must have been my error. Sorry for the noise.
