### ISSUE TITLE
Offset flaw in WNDB

### ISSUE THREAD

**Issue by 1313ou** [globalwordnet/english-wordnet#162]
I've been trying to convert WordNet 2019 to SQL form to include it in sqlunet (http://sqlunet.sourceforge.net).

The whole conversion process per se brings extra constraints to bear on the database (well-formedness, no duplicate, foreign key reference enforcement, inconsistency detection ...), so it rarely runs on fresh data without raising exceptions. One of the benefit of SQL is that errors will surface immediately.

Doing this I ran into a major integrity error being that data.noun is flawed starting from line 46748 where leading offset does not match real file offset by one. (Eat one of the trailing spaces on the line preceding 'Hot_Springs_National_Park' synset and we're back to normal). This cascades to countless parse errors and ultimately makes the data unusable at least by software that relies on offsets.

Log:

WordNet-2019/dict/data.noun.46748 offset=8628777 line=[08628776 15 n 01 Hot_Springs_National_Park 0 002 @i 08623637 n 0000 #p 09088997 n 0000 | a national park in Arkansas featuring ancient hot springs; bathing is said to have therapeutic effects  ]

WordNet-2019/dict/data.noun.46749 offset=8628971 line=[08628970 15 n 02
Isle_Royale_National_Park 0 Isle_Royal_National_Park 0 002 @i 08623637 n 0000 #p 09129462 n 0000 | a national park on an island in Michigan; includes prehistoric iron mines  ]

etc

lines          82222
offset errors  35474
parse errors   1053
synsets        45665

This affects the WordNet-2019 release as downloaded yesterday with md5 checksum 344dea8bf1dd32f1c862cb31afa3aaf0.

**Comment by jmccrae** [comment]
This is fixed now
