### ISSUE TITLE
two senses of 'property'

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#164]
Can someone help me to distinguish these two senses?

04916342-n property 
(a basic or essential attribute shared by all members of a class; "a study of the physical properties of atomic particles")

05849040-n attribute, dimension, property 
(a construct whereby objects or individuals can be distinguished; "self-confidence is not an endearing property")

**Comment by jmccrae** [comment]
They seem very close to me, but the top level synsets of wordnets contain distinctions like this that are not well separated. Wiktionary makes a similar distinction:

https://en.wiktionary.org/wiki/propertyhttps://en.wiktionary.org/wiki/property

Essentially it seems that you can have a property that distinguishes an individual as opposed to the qualities that define a class

Perhaps this one to ask Christiane about?

**Comment by restinplace** [comment]
The first is concrete, intrinsic, and observable; the second is abstract and assigned or inferred.:   "crystalline minerals are auspicious" shows both concrete (crystalline) and abstract (auspicious) properties. 

This may be clearer  in the "dimension" synsets, which contrast a physical magnitude with an abstract property or attribute.   

However, it is unclear in the "attribute" synsets.   The gloss for attribute#n#2 appears to use "abstraction" where it really means "property#n#2": 
   attribute#n#2  (an abstraction belonging to or characteristic of an entity) 
In my opinion, the gloss as stated does not explicitly contrast with:
  attribute#n#1 (a construct whereby objects or individuals can be distinguished...)
and the sense might reasonably be added to the 04916342-n property synset.

**Comment by arademaker** [comment]
the comments above from @restinplace were ignored?

**Comment by jmccrae** [comment]
Change definition of '04916342-n' to 'a basic or essential **property** shared by all members of a class'
