### ISSUE TITLE
Merge script drops Hawaian character ʻ Unicode 02BB silently and drops entries

### ISSUE THREAD

**Issue by 1313ou** [globalwordnet/english-wordnet#165]
The merge.py script (mis?)handles this Hawaian character ʻ   (not to be confused with single quote character ').

**At the start, the problem is it appears in the XML ID attribute, which is NOT allowed** (see https://www.w3.org/TR/2008/REC-xml-20081126/#NT-NameChar).
Basically this makes an invalid id.

... unless it is dropped silently by the Python library so that 
_id="ewn-Hawaiʻi_Volcanoes_National_Park-n"_ and
_id="ewn-Hawaii_Volcanoes_National_Park-n"_ (which also appears and is meant to be a distinct id)
are one and the same thing.

The end result is that the merged file drops 2 entries (1 LexicalEntry, 1 Sense): they are merged because their IDs, though different, are (wrongly) considered identical.

This is witnessed by:

```
$ grep 'ewn-Hawaiʻi' lexfiles/*.xml merged/english-wordnet-2019.xml
lexfiles/wn-noun.location.xml:    <LexicalEntry id="ewn-Hawaiʻi_Volcanoes_National_Park-n">
lexfiles/wn-noun.location.xml:      <Sense id="ewn-Hawaiʻi_Volcanoes_National_Park-n-ewn-08623419-00" n="0" synset="ewn-08623419-n"/>

```
which shows it appears in wn-noun.location.xml but not in the merged file. The entries are dropped.
`$ grep 'ewn-Hawai.i' lexfiles/*.xml merged/english-wordnet-2019.xml` yields the same result.

To make matters worse, while it is permissible in literals, the character is replaced with the single quote character.

The only instance of this character in the data is in in wn-noun.location.xml for Hawaiʻi
```
$ grep 'ʻ' lexfiles/*.xml
lexfiles/wn-noun.location.xml:    <LexicalEntry id="ewn-Hawaiʻi_Volcanoes_National_Park-n">
lexfiles/wn-noun.location.xml:      <Lemma writtenForm="Hawaiʻi Volcanoes National Park" partOfSpeech="n"/>
lexfiles/wn-noun.location.xml:      <Sense id="ewn-Hawaiʻi_Volcanoes_National_Park-n-ewn-08623419-00" n="0" synset="ewn-08623419-n"/>

```
This may account for the difficulties of gwn tool in the face of incomplete data.

**Comment by 1313ou** [comment]
This is confirmed:
replace 
`ewn-Hawaiʻi`
with
`ewn-Hawai_i`
in wn-noun.location.xml
and the full build chain [lexfiles -> merged xml -> wndb (-> sql)] works flawlessly now that index.sense is generated.

This leaves the question of XML validation...

**Comment by jmccrae** [comment]
So, we don't currently have a plan for supporting non-ASCII input so I have fixed this to be a regular '

**Comment by 1313ou** [comment]
Must be **reopened**. Fix is even worse. Single quote (') is not a valid character in names. It may wreak more havoc with parsers than the Hawaiian character(which used to be admissible, is still accepted by Xerces but is probably mishandled by a number of libraries, including Python's (I have not investigated what is happening in the merging.)

https://www.w3.org/TR/2008/REC-xml-20081126/#NT-NameChar specification that does not allow #x2BB in names

```
[4] | NameStartChar | ::= | ":"  \| [A-Z] \| "_" \| [a-z] \| [#xC0-#xD6] \| [#xD8-#xF6] \| [#xF8-#x2FF] \|  [#x370-#x37D] \| [#x37F-#x1FFF] \| [#x200C-#x200D] \| [#x2070-#x218F] \|  [#x2C00-#x2FEF] \| [#x3001-#xD7FF] \| [#xF900-#xFDCF] \| [#xFDF0-#xFFFD] \|  [#x10000-#xEFFFF]
[4a] | NameChar | ::= | NameStartChar \| "-" \| "." \| [0-9] \| #xB7 \| [#x0300-#x036F] \| [#x203F-#x2040]
[5] | Name | ::= | NameStartChar (NameChar)*
 

```
