### ISSUE TITLE
Hapax

### ISSUE THREAD

**Issue by 1313ou** [globalwordnet/english-wordnet#167]
Some warnings (take them or leave them) about the written form. These occur only once so it's debatable whether they should be allowed.

COLON HAPAX
```
wn-noun.communication.xml; lineNumber: 40510; columnNumber: 85; cvc-pattern-valid: Value 'Capital: Critique of Political Economy' is not facet-valid with respect to pattern '[a-zA-Z0-9 '/\-\.]+' for type 'WrittenFormType'.
wn-noun.communication.xml; lineNumber: 40510; columnNumber: 85; cvc-attribute.3: The value 'Capital: Critique of Political Economy' of attribute 'writtenForm' on element 'Lemma' is not valid with respect to its type, 'WrittenFormType'.

```
COMMA HAPAX
```
wn-noun.person.xml; lineNumber: 89004; columnNumber: 81; cvc-pattern-valid: Value 'Prince William, Duke of Cumberland' is not facet-valid with respect to pattern '[a-zA-Z0-9 '/\-\.]+' for type 'WrittenFormType'.
wn-noun.person.xml; lineNumber: 89004; columnNumber: 81; cvc-attribute.3: The value 'Prince William, Duke of Cumberland' of attribute 'writtenForm' on element 'Lemma' is not valid with respect to its type, 'WrittenFormType'.

```
EXCLAMATION MARK HAPAX
```
wn-noun.communication.xml; lineNumber: 40514; columnNumber: 53; cvc-pattern-valid: Value 'Yahoo!' is not facet-valid with respect to pattern '[a-zA-Z0-9 '/\-\.]+' for type 'WrittenFormType'.
wn-noun.communication.xml; lineNumber: 40514; columnNumber: 53; cvc-attribute.3: The value 'Yahoo!' of attribute 'writtenForm' on element 'Lemma' is not valid with respect to its type, 'WrittenFormType'.

```
This is the output of the XSD validator I wrote, together with a tentative XSD file. These are to be found here (my contribution to the project): 

https://github.com/1313ou/ewn-validation

**Comment by arademaker** [comment]
I didn't find the `wn-X-Y.xml` files in this repository. The files in the `src/` folder are all `wn31-X-Y.xml`. What files are you using?  I didn't find any of the strings above in the files.

**Comment by arademaker** [comment]
What is the difference between this issue and #166?

**Comment by 1313ou** [comment]
the files as pulled from the git repository on github.

**Comment by 1313ou** [comment]
Issue 166 singles out incorrect XML IDs. the part before the ':' should be
a namespace ('Capital' is not a namespace here, 'dc' is) in a NCName.

This issue points at unique occurrences of characters in 'writtenForm' not
IDs. Though xml-valid, they may appear odd, simply because they are nowhere
else to be found. The entries may have to be normalized for the sake of
coherence. This warning may or may not be of use.

That's why I opened distinct issues.

**Comment by arademaker** [comment]
Sorry, my mistake, I was looking for the files in a clone that I had of this repository. 

Hum, not sure how/when the complete title of the book was included in the english-wordnet files. The PWN 31 does not have those values. Maybe @jmccrae has an explanation to it.

data.noun from PWN 3.1 distribution:

> 07297634 10 n 02 Das_Kapital 0 Capital 1 001 @i 06422547 n 0000 | a book written by Karl Marx (1867) describing his economic theories  

noun.communication in the dbfiles: 

>  { Das_Kapital, Capital1, book,@i (a book written by Karl Marx (1867) describing his economic theories) }


Same for the second error:

noun.person in dbfiles:

> { Cumberland, William_Augustus, Duke_of_Cumberland, Butcher_Cumberland, general,@i (English general; son of George II; fought unsuccessfully in the battle of Fontenoy (1721-1765)) }

data.noun from PWN 3.1:

> 10936916 18 n 04 Cumberland 0 William_Augustus 0 Duke_of_Cumberland 0 Butcher_Cumberland 0 001 @i 10143381 n 0000 | English general; son of George II; fought unsuccessfully in the battle of Fontenoy (1721-1765)

**Comment by arademaker** [comment]
For the last case, it is not also in the PWN 3.1:

> 06591303 10 n 01 Yahoo 0 002 @i 06590830 n 0000 ;u 06864792 n 0000 | a widely used search engine for the web that finds information, news, images, products, finance  

I don't see the first two cases as 'word forms' but the last one is questionable since the exclamation mark is part of the name of the company. Moreover, there is nothing in the PWN documentation that prohibits the use of exclamation marks in the lemmas.

**Comment by jmccrae** [comment]
These were added recently. One of the advantages of the XML format is that we don't have to limited in the lemma forms we can use. As such, we have update some of lemmas to include symbols such as !, ',' or :. I don't think this presents any issues for the validity of the XML

**Comment by arademaker** [comment]
I don't see any problem with the symbols. What I am not very comfortable is with the new 'lemmas' :

1. 'Prince William, Duke of Cumberland'
2. 'Capital: Critique of Political Economy' 

They are more than just MWEs. In the first case, I think is more natural to have 'Prince William' and 'Duke of Cumberland'  in the same synset. The second case is more complicated since it is the title of the book. I don't like to have a phrase as a lexical entry, but it is hard to find arguments to not include it.

**Comment by jmccrae** [comment]
Yes, the lemmas were chosen because they matched the title of the
corresponding Wikipedia article. Although in the meantime, it seems that
the book has changed on Wikipedia, back to the German title, ("Das
Kapital"). I don't think it hurts to have these quite long lemmas for a
couple of synsets, before we make a better plan for dealing with the wealth
of proper nouns that could be in WordNet.

**Comment by arademaker** [comment]
I believe we must pay attention to the distinction between a lexical resource and a knowledge base.

**Comment by 1313ou** [comment]
I couldn't agree more with Alexandre. The point is not to copy Wikipedia. I think all proper names should be left out except:
-those that have a close connection to a common name (like God <-> god)
-those that give rise to derivations (like Shakespeare -> shakespearean)
-(other criteria?)
All other '**named entities**' are not lexical resources strictly speaking. Besides, most ML packages like CoreNLP and OpenNLP have their own _Named Entities Recognizers_ that are not trained,  AFAIK, on WordNet data, so it's hardly any use.

**Comment by jmccrae** [comment]
Yes, I also agree... but I would point out that these are concepts that are *already* in the WordNet due to being included by Princeton. My personal opinion is that we should not include named entities either, but instead have links to knowledge bases (such as Wikidata) to manage this
