### ISSUE TITLE
Two senses for New Hampshire? 

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#170]
- 09111366-n New_Hampshire, Granite_State, NH
(a state in New England; one of the original 13 colonies)

- 09111636-n New_Hampshire | Nova hampshire, Nova Hampshire, New Hampshire
(one of the British colonies that formed the United States)

**Comment by odanoburu** [comment]
I guess the first one is the current US state, and the other refers the British colony. it's confusing because the definition of the first refers to the second..

**Comment by jmccrae** [comment]
I would probably agree and move to close this issue, as the same distinction is made by other resources, e.g., Wikipedia

https://en.wikipedia.org/wiki/New_Hampshire
https://en.wikipedia.org/wiki/Province_of_New_Hampshire

**Comment by arademaker** [comment]
I understood the discussion from the beginning, that was not my point. My question is more philosophical! ;-) Does it make sense to maintain the province sense? Keeping old senses or deprecated uses of words can make the maintenance of the resource hard. Similar to the case of one definition of 'young man' = a man who is the lover of a girl or young woman

**Comment by arademaker** [comment]
Considering the gloss corpus, no occurence of New_Hampshire suggest the province sense:

(n) Dartmouth,Dartmouth College | a college in New Hampshire ; 
(n) New England | a region of northeastern United States comprising Maine and New Hampshire and Vermont and Massachusetts and Rhode Island and Connecticut ; 
(n) capital of New Hampshire,Concord | capital of the state of New Hampshire ; located in south central New Hampshire on the Merrimack river ; 
(n) Manchester | largest city in New Hampshire ; located in southeastern New Hampshire on the Merrimack river ; 
(n) Portsmouth | a port town in southeastern New Hampshire on the Atlantic Ocean ; 
(n) Connecticut River,Connecticut | a river in the northeastern United States ; flows south from northern New Hampshire along the border between New Hampshire and Vermont and through Massachusetts and Connecticut where it empties into Long Island Sound ; 
(n) Merrimack River,Merrimack | a river that rises in south central New Hampshire and flows through Concord and Manchester into Massachusetts and empties into the Atlantic Ocean ; 
(n) Granite Stater,New Hampshirite | a native or resident of New Hampshire ;

**Comment by jmccrae** [comment]
Yes, but others have criticized the removal of senses, for which there is no corpus evidence in large Web corpora. This, in comparison, is a fairly well-established sense with a clear meaning, although its inclusion is probably due to the general NE USA bias that there is WordNet.
