### ISSUE TITLE
Validation Schema

### ISSUE THREAD

**Issue by 1313ou** [globalwordnet/english-wordnet#171]
### The bad news 

The dc: attributes are defined as elements not attributes by Dublin Core so that any attempt to validate against this external reference will fail. How to see this ?
The namespace URL [http://purl.org/dc/elements/1.1/](http://purl.org/dc/elements/1.1/) redirects to
[http://dublincore.org/specifications/dublin-core/dcmi-terms/2012-06-14/?v=elements](http://dublincore.org/specifications/dublin-core/dcmi-terms/2012-06-14/?v=elements)

[This page](http://www.dublincore.org/schemas/xmls/) maps the URL to a schema location and contains the following:

**Target namespace:** 	http://purl.org/dc/elements/1.1/ 	
**Schema location:** http://dublincore.org/schemas/xmls/qdc/2008/02/11/dc.xsd

The latter dc.xsd can be downloaded and defines

	  <xs:element name="title" substitutionGroup="any"/>
	  <xs:element name="creator" substitutionGroup="any"/>
	  <xs:element name="subject" substitutionGroup="any"/>
	  <xs:element name="description" substitutionGroup="any"/>
	  <xs:element name="publisher" substitutionGroup="any"/>
	  <xs:element name="contributor" substitutionGroup="any"/>
	  <xs:element name="date" substitutionGroup="any"/>
	  <xs:element name="type" substitutionGroup="any"/>
	  <xs:element name="format" substitutionGroup="any"/>
	  <xs:element name="identifier" substitutionGroup="any"/>
	  <xs:element name="source" substitutionGroup="any"/>
	  <xs:element name="language" substitutionGroup="any"/>
	  <xs:element name="relation" substitutionGroup="any"/>
	  <xs:element name="coverage" substitutionGroup="any"/>
	  <xs:element name="rights" substitutionGroup="any"/>
	
 _All elements are declared as substitutable for the abstract element any, 
  which means that the default type for all elements is dc:SimpleLiteral._

### The good news 

Some documents specify the schema they expect to be validated against, typically using 
xsi:noNamespaceSchemaLocation and/or xsi:schemaLocation attributes.

However, normally this isn't what you want. Usually the document consumer should choose the schema, not the document producer. This is what I did [here](https://github.com/1313ou/ewn-validation) where validation data is split according to namespaces between [dc.xsd](https://github.com/1313ou/ewn-validation/blob/master/dc.xsd) and [WN-LMF-1.1.xsd](https://github.com/1313ou/ewn-validation/blob/master/WN-LMF-1.1.xsdurl).

### Further remarks about the schema

dc: attributes are obviously meta data (I have grouped them into a Meta attribute group) except

- **dc:identifier** (the sensekey): this acts more as a foreign key into another database and is the umbilical cord to the wn31 data, a sort of birth certificate with a mention of the parents. As such it means nothing within the confines of WordNet2019 as pointed out elsewhere : it is NOT a sense (nor synset) pointer. Besides 38 senses in adj alone have no dc:identifier. That's why I call it a **foreign key**. As such it should have its own namespace. I would suggest changing dc:identifier to wn31:sensekey.

- arguably **dc:subject** is another umbilical-cord foreign key into wn31 in which case it should be transformed into _wn31:lexfile_. ... But it is also a reference to the lexical file it belongs to. If we anticipate more lexical files, it should be a _lexfile_ attribute with the current (null) namespace.

- likewise the **ili** attribute is a foreign key. It points to nothing within this database. I would suggest changing it to _ili:id_ with its own namespace.

This leaves the problem of **sensekeys** that would have a meaning within the current database. If they have such a meaning, they are generated, not copied. Incidentally, let me mention that each version of WordNet generates its own sensekeys, the [grinder](https://wordnet.princeton.edu/documentation/grind1wnl) tool does that. It turns out the sensekeys can be generated. I have worked on a XSLT-based transformer tool that does just that in a declarative way (XML-to-XML XSLT transformation description) and is to be found [here](https://github.com/1313ou/ewn-transformation). More on this later. The transformer adds a sensekey attribute. It would make sense to use it in a standalone  generation of index.sense.

Besides being pointers, generated sensekeys have also been considered a measure of stability between successive versions of the WordNet database (if two versions generate the same sensekeys it's highly likely that nothing has changed in the distribution of senses). It can be used as such (and given an important weight) by the [relaxmapper](https://sourceforge.net/projects/relaxmapper/) which is meant to find mappings between hierarchies of data. Again, this makes sense if the sensekeys are generated, not copied.

**Comment by jmccrae** [comment]
I am closing this issue as it refers to the GWA's standard for representing XML schemas. This is supported by the repository here:

https://github.com/globalwordnet/schemas

You are welcome to move the issue there. As the general meeting of the GWA is next week, I will raise these and other concerns and see if we can update the standard.

**Comment by 1313ou** [comment]
Copied to globalwordnet/schemas as [issue 5](https://github.com/globalwordnet/schemas/issues/5)
