### ISSUE TITLE
chance the link for the right collector sense

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#178]
https://en-word.net/lemma/Isabella%20Stewart%20Gardner

change its pointer to 1 instead of 2.

1. collector, aggregator a person who collects things
2. accumulator, collector, gatherer a person who is employed to collect payments (as for rent or taxes)

We don't need instance and hypo. Only instance, right?

**Comment by jmccrae** [comment]
Indeed, it is a mistake to have both relations
