### ISSUE TITLE
Adj position lost

### ISSUE THREAD

**Issue by 1313ou** [globalwordnet/english-wordnet#180]
WN31 adjective position is lost.

This includes 

- a (attributive, eg: the **coming** release)
- ip (immediate postnominal, eg: beaches **galore**) 
- p (predicative, eg: the house is **ablaze**)

Sadly this is encoded in wordnet as a suffix appended to the lemma (that has to be trimmed for 'normal' use). This is why it resurfaces as a '-a', '-p' or '-ip' suffix in the LexicalEntry id.

- src/wn-adj.all.xml:43024:    LexicalEntry id="ewn-ablaze-p-s"
- src/wn-adj.all.xml:62153:    LexicalEntry id="ewn-galore-ip-s"
- src/wn-adj.all.xml:80057:    LexicalEntry id="ewn-coming-a-s"

The full (?) list can be extracted by:

`egrep '<LexicalEntry id="ewn-.*\-(a|ip|p)\-[as]">' src/wn-adj.*.xml`

Now the id should be treated as opaque (although I am sometimes glad it can be meaningfully parsed, especially when troubleshooting) so I see no objection to this suffix.

The problem is adj position extraction from the id is not guaranteed by specifications. Besides, more than one standard lemma termination can map to '-a', '-p' or 'ip'. So how can the information be reliably retrieved ?

Lexical entries are copied here for convenience:

>     <LexicalEntry id="ewn-ablaze-p-s">
>       <Lemma writtenForm="ablaze" partOfSpeech="s"/>
>       <Sense id="ewn-ablaze-p-s-00271362-01" n="3" synset="ewn-00271362-s" dc:identifier="ablaze%5:00:00:light:06"/>
>       <Sense id="ewn-ablaze-p-s-00477298-01" n="1" synset="ewn-00477298-s" dc:identifier="ablaze%5:00:00:lighted:00"/>
>     </LexicalEntry>

>     <LexicalEntry id="ewn-galore-ip-s">
>       <Lemma writtenForm="galore" partOfSpeech="s"/>
>       <Sense id="ewn-galore-ip-s-00014377-02" n="1" synset="ewn-00014377-s" dc:identifier="galore%5:00:00:abundant:00"/>
>       <Sense id="ewn-galore-ip-s-01556519-01" n="0" synset="ewn-01556519-s" dc:identifier="galore%5:00:00:many:00"/>
>     </LexicalEntry>

>     <LexicalEntry id="ewn-coming-a-s">
>       <Lemma writtenForm="coming" partOfSpeech="s"/>
>       <Sense id="ewn-coming-a-s-01736850-02" n="0" synset="ewn-01736850-s" dc:identifier="coming%5:00:01:future:00"/>
>     </LexicalEntry>
>

**Comment by jmccrae** [comment]
This is mostly a schema issue:

https://github.com/globalwordnet/schemas/issues/7

But, we will update the schema soon and then fix the wordnet files here

**Comment by 1313ou** [comment]
Sorry I think it's a bug if the ids are to be meaningful because

- the LexicalEntry and Sense IDs become **unpredictable**
- it leads to wild **double dash**es in ids (the processing is at fault here) : see below
- if we accept the -a -ip -p addition in a Sense, we can't accept it in LexicalEntry because Wordnet **attaches an adjective position to a sense, not to a lexical entry.** The adjective 'proper' is a case in point: 

1.    _proper manners_ ('marked by suitablility', synset 01884565)
2.    _the city proper_ ('limited to the thing specified', synset 01108582)

 Only the latter sense is _immediate postnominal_.

Worse, this handling may lead to **crypto duplicates**. And it does:
`grep 'LexicalEntry id="ewn-proper-' wn-adj.all.xml
`
yields
>     <LexicalEntry id="ewn-proper-a-s">
>     <LexicalEntry id="ewn-proper-s">
>     <LexicalEntry id="ewn-proper-a">
>     <LexicalEntry id="ewn-proper-ip-s">

We have 4  distinct entries where there should be 2.

List of double-dash ids:

>     <LexicalEntry id="ewn-afloat-p--a">
>       <Lemma writtenForm="afloat" partOfSpeech="a"/>
>       <Sense id="ewn-afloat-p--a-00077529-01" n="1" synset="ewn-00077529-a" dc:identifier="afloat%3:00:00::">
> 
>     <LexicalEntry id="ewn-afraid-p--a">
>       <Lemma writtenForm="afraid" partOfSpeech="a"/>
>       <Sense id="ewn-afraid-p--a-00078253-01" n="0" synset="ewn-00078253-a" dc:identifier="afraid%3:00:00::">
> 
>     <LexicalEntry id="ewn-aground-p--a">
>       <Lemma writtenForm="aground" partOfSpeech="a"/>
>       <Sense id="ewn-aground-p--a-00078057-01" n="0" synset="ewn-00078057-a" dc:identifier="aground%3:00:00::">
> 
>     <LexicalEntry id="ewn-alike-p--a">
>       <Lemma writtenForm="alike" partOfSpeech="a"/>
>       <Sense id="ewn-alike-p--a-01413463-01" n="0" synset="ewn-01413463-a" dc:identifier="alike%3:00:00::">
> 
>     <LexicalEntry id="ewn-alive-p--a">
>       <Lemma writtenForm="alive" partOfSpeech="a"/>
>       <Sense id="ewn-alive-p--a-00095301-01" n="0" synset="ewn-00095301-a" dc:identifier="alive%3:00:01::">
> 
>     <LexicalEntry id="ewn-ashamed-p--a">
>       <Lemma writtenForm="ashamed" partOfSpeech="a"/>
>       <Sense id="ewn-ashamed-p--a-00155165-01" n="0" synset="ewn-00155165-a" dc:identifier="ashamed%3:00:00::">
> 
>     <LexicalEntry id="ewn-awake-p--a">
>       <Lemma writtenForm="awake" partOfSpeech="a"/>
>       <Sense id="ewn-awake-p--a-00188104-01" n="0" synset="ewn-00188104-a" dc:identifier="awake%3:00:00::">
> 
>     <LexicalEntry id="ewn-aware-p--a">
>       <Lemma writtenForm="aware" partOfSpeech="a"/>
>       <Sense id="ewn-aware-p--a-00191603-01" n="0" synset="ewn-00191603-a" dc:identifier="aware%3:00:00::">
> 
>     <LexicalEntry id="ewn-black_and_white-p--a">
>       <Lemma writtenForm="black and white" partOfSpeech="a"/>
>       <Sense id="ewn-black_and_white-p--a-00395392-02" n="0" synset="ewn-00395392-a" dc:identifier="black_and_white%3:00:02::"/>
> 
>     <LexicalEntry id="ewn-certain-p--a">
>       <Lemma writtenForm="certain" partOfSpeech="a"/>
>       <Sense id="ewn-certain-p--a-00336319-01" n="2" synset="ewn-00336319-a" dc:identifier="certain%3:00:01::">
>       <Sense id="ewn-certain-p--a-00337729-01" n="1" synset="ewn-00337729-a" dc:identifier="certain%3:00:02::">
> 
>     <LexicalEntry id="ewn-inclined-p--a">
>       <Lemma writtenForm="inclined" partOfSpeech="a"/>
>       <Sense id="ewn-inclined-p--a-01295251-01" n="0" synset="ewn-01295251-a" dc:identifier="inclined%3:00:02::">
> 
>     <LexicalEntry id="ewn-moved-p--a">
>       <Lemma writtenForm="moved" partOfSpeech="a"/>
>       <Sense id="ewn-moved-p--a-01564296-01" n="0" synset="ewn-01564296-a" dc:identifier="moved%3:00:00::">
> 
>     <LexicalEntry id="ewn-obligated-p--a">
>       <Lemma writtenForm="obligated" partOfSpeech="a"/>
>       <Sense id="ewn-obligated-p--a-01620626-01" n="0" synset="ewn-01620626-a" dc:identifier="obligated%3:00:00::">
> 
>     <LexicalEntry id="ewn-out-p--a">
>       <Lemma writtenForm="out" partOfSpeech="a"/>
>       <Sense id="ewn-out-p--a-02068891-01" n="0" synset="ewn-02068891-a" dc:identifier="out%3:00:02::">
> 
>     <LexicalEntry id="ewn-safe-p--a">
>       <Lemma writtenForm="safe" partOfSpeech="a"/>
>       <Sense id="ewn-safe-p--a-02068711-01" n="2" synset="ewn-02068711-a" dc:identifier="safe%3:00:02::">
> 
>     <LexicalEntry id="ewn-unafraid-p--a">
>       <Lemma writtenForm="unafraid" partOfSpeech="a"/>
>       <Sense id="ewn-unafraid-p--a-00082141-01" n="0" synset="ewn-00082141-a" dc:identifier="unafraid%3:00:00::">
> 
>     <LexicalEntry id="ewn-unangry-p--a">
>       <Lemma writtenForm="unangry" partOfSpeech="a"/>
>       <Sense id="ewn-unangry-p--a-00117274-01" n="0" synset="ewn-00117274-a" dc:identifier="unangry%3:00:00::">
> 
>     <LexicalEntry id="ewn-unmoved-p--a">
>       <Lemma writtenForm="unmoved" partOfSpeech="a"/>
>       <Sense id="ewn-unmoved-p--a-01564713-01" n="0" synset="ewn-01564713-a" dc:identifier="unmoved%3:00:00::">
> 
>     <LexicalEntry id="ewn-on_one-ap-s_guard-p-s">
>       <Lemma writtenForm="on one&apos;s guard" partOfSpeech="s"/>
>       <Sense id="ewn-on_one-ap-s_guard-p-s-00163926-02" n="0" synset="ewn-00163926-s" dc:identifier="on_one&apos;s_guard%5:00:00:wary:00"/>
>

**Comment by jmccrae** [comment]
Hi, Sure... I am not closing this issue. But the schema needs to updated first so we can fix this properly

**Comment by arademaker** [comment]
I didn't understand why the issue was closed.

**Comment by jmccrae** [comment]
Issue is not closed, it is referenced from closed issues :)
