### ISSUE TITLE
seismology

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#181]
The definition looks incomplete: 

> the branch of geology that studies earthquakes

but Wikipedia says:

> Seismology ( /saɪzˈmɒlədʒi/; from Ancient Greek σεισμός (seismós) meaning "earthquake" and -λογία (-logía) meaning "study of") is the scientific study of earthquakes and the propagation of elastic waves through the Earth or through other planet-like bodies.

Should we expand the synset gloss?

**Comment by jmccrae** [comment]
I am not sure what you want to add to this, it seems to have a clear genus "the branch of geology" and a differentia "that studies earthquake". While the Wikipedia first sentence is much longer it is does not add much more

**Comment by arademaker** [comment]
the fact is that `geology` is not the study of earthquakes, but the study of elastic waves such as the ones that cause earthquakes... We have edited the Wikipedia page.

**Comment by jmccrae** [comment]
I guess you are saying that the current definition would exclude 'helioseismology' as a hyponym of this concept? Would you propose a new definition?

**Comment by arademaker** [comment]
Yes. We are discussing it in the Wikipedia page. See the history of https://en.wikipedia.org/wiki/Seismology

A possible gloss would be:

> Seismology is the scientific study of the propagation of elastic waves through the Earth or through other planet-like bodies.

See https://www.glossary.oilfield.slb.com/en/Terms/s/seismology.aspx , https://www.aapg.org/about/petroleum-geology/geology-and-petroleum/seismology-and-geophysics, https://www.nature.com/subjects/seismology and https://en.wiktionary.org/wiki/seismology

But the interesting issue here is that etymology is right: `( /saɪzˈmɒlədʒi/; from Ancient Greek σεισμός (seismós) meaning "earthquake" and -λογία (-logía) meaning "study of")`

**Comment by restinplace** [comment]
With all due respect, my understanding is that WN is not a dictionary, but is rather an interlinked set of glossed senses, driven by (but not strictly limited to) corpus usage, and intended to differentiate between senses, rather than to fully define them.

My guess would be that in most contexts, seismology is indeed "the branch of geology that studies earthquakes."   These folks study earthquakes, invent plate tectonics, write building codes, predict volcanic eruptions, and so on. 

There is a second, less common sense that happens to be a more inclusive concept:  "the analysis of natural or man-made vibrations in a planet's interior"    These folks search for oil and mineral deposits, map caves, study nuclear explosion yields, etc. on Earth, and I suppose study stellar interiors further afield. 

Attempting to write an all-in-one definition about elastic waves would, in my opinion, undermine the value of WN for sense disambiguation.  In contrast, adding a sense fixes a perceived problem without disrupting WN's existing structure.

**Comment by arademaker** [comment]
> As WordNet grew and finer distinctions were required, it became obvious that we had not included enough different kinds of semantic relations to characterize all of the differentiae that are needed. Moreover, it was much easier to read a definitional gloss than to try to infer it from the array of pointers associated with each synset. Therefore, explanatory phrases have been added to most synsets... The parenthetical glosses serve to keep the several senses of polysemous words distinct, but redundancy is apparent, parent, for example, between the hypernymic concepts... and the genus words of the defining gloss...If more distinguishing features could be indicated by pointers representing additional semantic relations, the glosses would become even more redundant. (Christiane Fellbaum. WordNet: An Electronic Lexical Database (Kindle Locations 569-570). Kindle Edition.)

From the fragment, we can indeed infer that glosses are 'additional' information. But on the other hand, they are there to facilitate the sense understanding. Anyway, the case of seismology is not so complicated and the gloss doesn't affect the corpus annotation in most cases. But `basin` has the sense:

> a natural depression in the surface of the land often with a lake at the bottom of it "the basin of the Great Salt Lake"

It could almost be used for https://en.wikipedia.org/wiki/Sedimentary_basin but the gloss is more restrictive than necessary. I suspect that your suggestion would be to include yet another synset for `sedimentary_basin`, right? I am still not entirely convinced.

**Comment by restinplace** [comment]
I think your cited item, basin#3, means "endorheic basin" in Wiki-talk.  basin#4 is like Wiki "drainage basin" (or more delightfully, "impluvium").

If your goal is to have a WN-like sense for every Wiki page, then yes, I think adding another numbered sense to "basin" (including the form "endorheic_basin") -- this creates three clearly contrasting geologic basin types -- would be better than rewriting the existing basin#3 sense  Was that your question?

**Comment by jmccrae** [comment]
@arademaker the fix for this is to update the definition to:
> the branch of geology that studies earthquakes **and the propagation of elastic waves through the Earth or through other planet-like bodies**
correct?

**Comment by arademaker** [comment]
good for me the solution for the seismology definition.
