### ISSUE TITLE
missing lemma 'lower'

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#184]
We have 7 senses for upper but only 4 for lower. For the antonyms of upper we only have `low`.

**Comment by jmccrae** [comment]
Not quite sure I understand what you mean here. 'Upper' and 'lower' are not antonyms in many cases and can be quite different in many of their meanings, e.g. 'lower' can be verb but 'upper' can't be. 

I guess you are suggesting there should be antonyms of these synsets:

`ewn-01208990-s` (Interlingual Index: i6594)
> (s) upper higher in place or position "the upper bunk" "in the upper center of the picture" "the upper stories"

`ewn-02348166-s` (Interlingual Index: i12961)
> (s) upper superior in rank or accomplishment "the upper half of the class"

`ewn-02449821-s` (Interlingual Index: i13518)
> (s) upper the topmost one of two

This could be fixed  by adding 'lower' to another synset, e.g.,

`ewn-01210218-s` (Interlingual Index: i6601)
> (s) under, nether located below or beneath something else "nether garments" "the under parts of a machine"

`ewn-02348948-s` (Interlingual Index: i12965)
> (s) low-level at a low level in rank or importance "a low-level job" "low-level discussions"

`ewn-02450085-s` (Interlingual Index: i13520)
> (s) lowermost, bottommost, nethermost farthest down "bottommost shelf"

But, please also note that these are satellite senses, so don't have antonyms according to the 'dumbbell model'

**Comment by arademaker** [comment]
Sorry @jmccrae , my first comment is not clear. I do believe we need an antonym for `upper` but  my point is really that we don't have the lemma `lower` as adjective in the PWN. We have the following adjectives with MWEs that contains `lower`:

00260323-a upper-lower-class
(occupying the upper part of the lower class)

00260973-a lower-middle-class
(occupying the lower part of the middle socioeconomic range in a society)

00259568-a lower-class, low-class
(occupying the lowest socioeconomic position in a society)

02100968-a lower-ranking, subaltern, petty, secondary, junior-grade, lowly
(inferior in rank or status; "the junior faculty"; "a lowly corporal"; "petty officialdom"; "a subordinate functionary")

The fact is that in the glosses we have 346 glosses with the word `lower`. Many can be noun or verbs, I am still checking, but some seem to be adjectives:

1. fish of the lower Mississippi
2. freshwater turtle of Chesapeake Bay tributaries having red markings on the lower shell
3. the overhang at the lower edge of a roof

Moreover, in corpora from the geoscience domain, we also have many occurrences such as:

1. Lower Cretaceous ... (and other possible compounds with chronostratigraphic eras)
2. lower limit of oil generation...
3. lower member or Eagle Sandstone ...
4. lower part of the Mesaverde Formation  ....

So it seems clear that we are missing some senses of lower. Am I right? Possibly, in some of the above cases, the sense of `lower` may have one of the 7 senses of `upper` as an antonym.

**Comment by arademaker** [comment]
Maybe adding lower in the synset

W: (adj) low [Indirect via high] (literal meanings; being at or having a relatively small elevation or upward extension) "low ceilings"; "low clouds"; "low hills"; "the sun is low"; "low furniture"; "a low bow"

would be the first step.

**Comment by jmccrae** [comment]
I don't think that 'low' and 'lower' are synonymous. The main reason I think that 'lower' is not available as a lemma, is that it is seen as an inflection of 'low'. Some of your examples would fall under this, e.g., 'lower member of Eagle Sandstone' 

There is a case for an adjective sense in certain compounds, e.g., "Lower Egypt" when there is a clear alternation with 'upper' (as there is "Upper Egypt"), especially as an antonym of 

`ewn-02449821-s` (Interlingual Index: i13518)
(s) upper 
> the topmost one of two

However for most cases they should be annotated as an appropriate synset of 'low'

**Comment by arademaker** [comment]
Sorry I didn’t understand your suggestion deal with the cases of upper/lower “alternations” 


https://en.m.wiktionary.org/wiki/upper#English

Lower is defined as antonym of upper although it is an inflection of low. But I agree that some cases lower would be annotated with lemma low and one of its sense

**Comment by restinplace** [comment]
I think the problem is the confusing use of the phrase "literal meanings" in the gloss, particularly since the examples given are both literal and kind'a figurative.  I'd follow John, and just clarify that both senses (and hence both inflected forms) apply to this sense of "low", e.g.: 

  (used literally and figuratively to describe a lesser degree of elevation or upward extension, or a relatively more distant or downward temporal or physical location) ... "lower Cretaceous," "lower Mississippi" ....

This assumes that this kind of mixing of forms in examples is legit. 

Btw, my understanding of "Lower Egypt" is that it's called that because it's in the Nile delta; i.e. downstream.  These aren't always contrast relations; e.g. in Thailand, every place outside of (centrally located) Bangkok is "up-country," regardless of geography.

**Comment by jmccrae** [comment]
New synset
Member: lower
Definition: the bottom one of two
Antonym: ewn-02449821-s
Derived from: ewn-01209146-a

**Comment by arademaker** [comment]
Curious to understand what makes @jmccrae change his mind here! ;-)

**Comment by jmccrae** [comment]
Just your clear and helpful comments :smile:
