### ISSUE TITLE
missing noun sense for mapping 'the act of ...'

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#188]
Consider the sentences

1. This paper presents results of an integrated surface to subsurface data supported by regional cleats mapping, characterization, and analysis in relation to Coal Bed Methane (CBM) exploration and development in the basin.

2. The resolution of seismic data is insufficient to permit detailed mapping of the structure of rocks below the pre-Jurassic unconformity. 

Sentence 1 is quite strange (I edited from the [original](http://www.searchanddiscovery.com/abstracts/html/2014/90194ice/abstracts/1935707.html) that looks to me ungrammatical) but even so, characterization has a noun sense but mapping doesn't have a noun sense. We could tag both as verbs but they are functioning as nouns, right?

**Comment by arademaker** [comment]
or ... should we remove many noun senses that could be obtained from the nominalization of verbs?

**Comment by jmccrae** [comment]
Proposed definition: "the process of making maps"

**Comment by arademaker** [comment]
How to make sure that the definition does not constraint other meanings. A mapping could be the act of identifying relationships between concepts. So the question is about your meaning for `maps` or we could have more than one sense of `mappping`, almost one for each verb sense `maps`.
 
Take the example of `heating` that raise another question about how to deal with the derivational relations. These are lexical relations according to the [documentation](https://wordnet.princeton.edu/documentation/wninput5wn) would means that they hold betwen word forms not between the senses, right? But PWN 3.1 seems to be inconsient on that:

We have two senses of heating:

1. (4) heating, warming -- (the process of becoming warmer; a rising temperature)
2. heating system, heating plant, heating, heat -- (utility to warm a building; "the heating system wasn't working"; "they have radiant heating")

and 4 verb senses:

1. (11) heat, heat up -- (make hot or hotter; "the sun heats the oceans"; "heat the water on the stove")
2. heat -- (provide with heat; "heat the house")
3. inflame, stir up, wake, ignite, heat, fire up -- (arouse or excite feelings and passions; "The ostentatious way of living of the rich ignites the hatred of the poor"; "The refugees' fate stirred up compassion around the world"; "Wake old feelings of hatred")
4. heat, hot up, heat up -- (gain heat or get hot; "The room heated up quickly")

but why do we have only 1 link for each noun sense? I would expect that each noun sense is linked to all other verb senses and vice-versa.

```
** Sense 1
heating, warming
       RELATED TO->(verb) heat#4
           => heat, hot up, heat up

** Sense 2
heating system, heating plant, heating, heat
       RELATED TO->(verb) heat#2
           => heat
```

**Comment by jmccrae** [comment]
The examples you have given seem to be covered by a cartographic sense (of literally making maps), this seems to be frequent in other dictionaries, so may be worthy of being a sense in its own right. In general, I think we should not try to create a noun sense for the nominalization of every verb but only when they are significant.

**Comment by jmccrae** [comment]
I think I will close this issue by adding a new synset

Members: mapping
Definition: the process of making maps
Hypernym: ewn-01025762-n
Example: detailed mapping of the structure of rocks
