### ISSUE TITLE
reverse pertainym relations of mellowness

### ISSUE THREAD

**Issue by odanoburu** [globalwordnet/english-wordnet#189]
mellowness (`a feeling of good humor and sympathy through maturity or intoxication or a relaxed state`) has three pertainyms, but the relations are from the noun to the adjectives instead of the contrary.

(not sure how to find the synset ID on the interface at https://en-word.net/lemma/mellowness, sorry.)

label for the issue should be `change relation`

**Comment by 1313ou** [comment]
```
     <Sense id="ewn-mellowness-n-07569690-01" n="0" synset="ewn-07569690-n" dc:identifier="mellowness%1:12:00::">
        <SenseRelation relType="pertainym" target="ewn-mellow-s-01159816-01"/> <!-- mellowed, mellow -->
        <SenseRelation relType="pertainym" target="ewn-mellow-s-02416807-02"/> <!-- laid-back, mellow -->
        <SenseRelation relType="pertainym" target="ewn-mellow-s-00802795-02"/> <!-- high, mellow -->
        </Sense>
```
in wn-noun-feeling.xml (using grep).

This inversion is confined to the 3 cases as the sql version bears witness

```
select count(*) from lexlinks as l
left join linktypes using (linkid)
left join synsets as src on l.synset1id = src.synsetid
left join synsets as dst on l.synset1id = dst.synsetid
where link = 'pertainym' and src.pos = 'n';
```
yields 3.

**Comment by jmccrae** [comment]
The issue is that these are not really pertainyms according to the current usage (as they are in the wrong file). Instead I think I will just remove the links (as nouns are certainly not pertainyms of adjectives), but not add any backlink for the moment (as the existing `derivation` link is sufficient)
