### ISSUE TITLE
Minimum requirements for entry into English WordNet

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#190]
For some entries and variants it is very hard to find corpus evidence, as such the question (initially raised in #148) is whether there should be some minimum for including **new** synsets or lemmas

One candidate could be that there is at least one occurrence in the American National Corpus

http://www.anc.org/data/oanc/ngram/

Any other suggestions?

**Comment by arademaker** [comment]
what about the http://www.webcorp.org.uk/live/ that you mentioned in other issue?

**Comment by jmccrae** [comment]
I am optimistic that we will be able to implement this in 2022 with improvements to the editing framework.

**Comment by jmccrae** [comment]
I think this can be closed. We now require 10 occurrences in the TenTen corpus, but are looking for an open source alternative in #756
