### ISSUE TITLE
birthright 

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#192]
Consider

```
w: birthright
d: a right or privilege that you are entitled to at birth
e: free public education is the birthright of every American child
hypo: heritage

w: birthright 1
d: personal characteristics that are inherited at birth
hypo: heritage
```

The second synset is strange and it is indistinguishable from the first considering its relations with the rest of the graph

**Comment by jmccrae** [comment]
The synset here seems odd to me

`ewn-04928485-n` (Interlingual Index: i62844)
(n) birthright 
> personal characteristics that are inherited at birth

It may be a candidate for deletion, but we should look for some corpus evidence of the word being used with this meaning

**Comment by dcillessen** [comment]
yes,
>  ewn-04928485-n (Interlingual Index: i62844) (n) birthright
is defined in a weird way.  

It doesn't appear in that form in the OED, Webster's or the AH dictionary.  I also can't find any corpus evidence which uses that meaning.  Ultimately I think the synset should be deleted
