### ISSUE TITLE
Reassure

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#193]
The two senses of 'reassure' are both defined as 'cause to feel sure'

`ewn-01021817-v` (Interlingual Index: i26676)
> reassure give or restore confidence in; cause to feel sure or certain; "I reassured him that we were safe"

`ewn-01770259-v` (Interlingual Index: i30569)
> reassure, assure cause to feel sure; give reassurance to; "The airline tried to reassure the customers that the planes were safe"

I suggest merging `ewn-01770259-v` into `ewn-010218178-v`

**Comment by arademaker** [comment]
one is in verb.communication and the other in verb.emotion. one can try to reassure without explicit communication? But actions? If so, we must keep both.

**Comment by jmccrae** [comment]
Seems to be a very fine distinction, that other resources do not make.
