### ISSUE TITLE
Sectarian

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#195]
The two senses of sectarian are indistinguishable

`ewn-02098854-a` (Interlingual Index: i11462)
> sectarian - belonging to or characteristic of a sect

`ewn-02805195-a` (Interlingual Index: i15816)
> sectarian - of or relating to or characteristic of a sect or sects; "sectarian differences"

Propose merging `ewn-02098854-a` into `ewn-02805195-a`

**Comment by arademaker** [comment]
I agree. are they in the same cluster?

**Comment by jmccrae** [comment]
One is a pertainym and one is in a cluster
