### ISSUE TITLE
Tithe

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#201]
`ewn-02257350-v` (Interlingual Index: i32997)
> tithe - pay a tenth of one's income, especially to the church; "Although she left the church officially, she still tithes"

is basically the same as

`ewn-02257563-v` (Interlingual Index: i32998)
> tithe - pay one tenth of; pay tithes on, especially to the church; "He tithed his income to the Church"

They are marked as similar but should probably just be merged

**Comment by arademaker** [comment]
transitive and intransitive senses.

**Comment by jmccrae** [comment]
Yes, but transitivity is not typically a case we distinguish (or at least Princeton didn't consistently do it before). If you think you should create an issue for this.... otherwise I will merge all of these for the next release.

**Comment by arademaker** [comment]
Yes, Princeton didn't consistently do it but they did it. We are fixing problems, right? For verbs, I believe the valences are important.  But, anyway, you are right, you can do the merges. But this attitude makes the project more and more not a collaborative effort but YOUR personal project.

**Comment by jmccrae** [comment]
Okay, let's leave this one as there is disagreement until the next release. 

Ask a quick estimate there are 1,466 verbs senses with both transitive and intransitive frames so this would be a major change to the Princeton WordNet methodology. If the community wishes to change this, then create an issue and we can discuss this. Personally, I would be in favour.

For this specific issue, following the precedent of Princeton, we should merge this synset.

The objective of this project is to continue from PWN, if it was my personal project, I would do many things differently :)
