### ISSUE TITLE
Thai language

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#202]
`ewn-06948926-n` (Interlingual Index: i73034)
> Siamese, Central Thai, Thai - a branch of the Tai languages

The definition describes this as a 'branch' but 'Central Thai' is a single, standardised, national language. This needs a new definitoin

This also affects many other sister synsets, @fcbond has already developed alternative definitions for all these languages

**Comment by arademaker** [comment]
Can @fcbond attach the data here or provide link to it?

**Comment by jmccrae** [comment]
I have it and will attach it soon :)

**Comment by jmccrae** [comment]
Closing as this will be fixed in #261
