### ISSUE TITLE
Canter

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#203]
`ewn-01963199-v` (Interlingual Index: i31524)
> canter - ride at a canter; "The men cantered away"

`ewn-01963341-v` (Interlingual Index: i31525)
> canter - ride at a cantering pace; "He cantered the horse across the meadow"

These seem identical. We should merge `ewn-01963341-v` into `ewn-01963199-v`

**Comment by arademaker** [comment]
one is intransitive the other one is transitive.

**Comment by jmccrae** [comment]
Definition of 'ewn-01963341-v' to '**cause to** ride at a cantering pace'
