### ISSUE TITLE
suffer, hurt

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#209]
`ewn-00064841-v` (Interlingual Index: i22102)
> suffer, hurt - feel pain or be in pain

There is already a synset for feeling pain (`ewn-02125976-v`) so we could simplify this definition to just 'be in pain'

**Comment by arademaker** [comment]
The question here is if we should merge the verb.perception sense with the verb.body sense. These are the lexicographer files of each sense.
