### ISSUE TITLE
slammer

### ISSUE THREAD

**Issue by daikinomura** [globalwordnet/english-wordnet#21]
slammer%1:18:00::  is derived from basball_player. And it's def goes like this

**a person who closes things violently; "she's a dramatic slammer of doors"**

Especially the example sentence doesn't suit for a baseball players. I guess we should put this slammer to other places(for e.x.,  clumsy_person%1:18:01:: or unwelcome_person%1:18:00::).  Or I could have more suitable def for a baseball player.

**Comment by jmccrae** [comment]
Yes, this seems like the wrong hypernym. We should fix this.

**Comment by jmccrae** [comment]
It seems that this is the correct hypernym: 

http://wordnet-rdf.princeton.edu/ili/i89032

**Comment by daikinomura** [comment]
This must be the very place. 

I couldn't have found this one and this is better than clumsy_person or unwelcome_person. 

Maybe, the lexicographer wanted to type "closer1" but he/she typed "closer" and connected it's hypernym relation to baseball players...

**Comment by daikinomura** [comment]
It seems that  I slammed the door impolitely. 

Because link patches need careful comment and other graphical representation to explain the patch's intention,   I am going to make def patches first, and link patches next. I would like to leave this door open for a while.

Please give me your opinion about this topic.

Best regards
