### ISSUE TITLE
ordinary (adj)

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#211]
ewn-00488278-s:
(s) average%5:00:00:common:01, ordinary%5:00:02:common:01 lacking special distinction, rank, or status; commonly encountered "average people" "the ordinary (or common) man in the street"

ewn-01677162-a:
(a) ordinary%3:00:00:: not exceptional in any way especially in quality or ability or size or degree "ordinary everyday objects" "ordinary decency" "an ordinary day" "an ordinary wine"

Could we merge them?

**Comment by jmccrae** [comment]
This is another example of Issue #35 
I completely agree and I think there are a great many cases where satellites are not distinct from a closely related non-satellite, although I think some discussion with Christiane may be necessary here
I will close this issue so we can track it under #35
