### ISSUE TITLE
gloss of ewn-01003512-s

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#212]
ewn-01003512-s (Interlingual Index: i5476)
(s) congratulatory, gratulatory 

> expressive of sympathetic pleasure or joy on account of  someone's success or good fortune "a congratulatory telegram" "the usual congratulatory crowd was conspicuously absent" "a gratulatory address"

Two options to fix the gloss:

s/expressive/express?
s/of/or?

**Comment by jmccrae** [comment]
I don't see an issue with this gloss.

See for example the second sense's example of 'expressive' in MW:
https://www.merriam-webster.com/dictionary/expressive

**Comment by arademaker** [comment]
I am having trouble to parse this gloss. The word 'expressive' is a verb or adjective here?

**Comment by jmccrae** [comment]
'expressive' is an adjective: congratulatory is expressive of pleasure or joy
This sense of 'expressive' is a little archaic, but as you can see from the link earlier still in use.

As a side note, we actually lack this sense of 'expressive'

**Comment by arademaker** [comment]
I am not a native speaker so I will follow your impression but ERG grammar can't parse "foul and novel terms expressive of rage" nor "expressive of sympathetic pleasure or joy on account of someone's success".  Maybe @fcbond can't add something here.

**Comment by jmccrae** [comment]
@arademaker close this issue?

**Comment by arademaker** [comment]
This is so weird to me.. but I finally understood it. The literal translation of “expressive of sympathetic pleasure” for  Portuguese would be “expressivo de prazer simpático...”
