### ISSUE TITLE
never

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#213]
The two senses of 'never' are indistinguishable

`ewn-00021452-r` (Interlingual Index: i18263)
(r) never 
>not at all; certainly not; not in any circumstances "never fear" "bringing up children is never easy" "that will never do" "what is morally wrong can never be politically right"

`ewn-00021214-r` (Interlingual Index: i18262)
(r) ne'er, never 
> not ever; at no time in the past or future "I have never been to China" "I shall never forget this day" "had never seen a circus" "never on Sunday" "I will never marry you!"

Reported by @fcbond

**Comment by arademaker** [comment]
It looks like the first carries a sentimental (some rejection) and the second is more neutral. Does it make sense?
