### ISSUE TITLE
turn (to)

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#214]
`ewn-01955796-v` (Interlingual Index: i31487)
(v) turn 
> channel one's attention, interest, thought, or attention toward or away from something "The pedophile turned to boys for satisfaction" "people turn to mysticism at the turn of a millennium"

Is probably a duplicate of 
` ewn-00550851-v` (Interlingual Index: i24491)
(v) turn to 
> direct one's interest or attention towards; go into "The student turned to the teacher for help" "People turn to mysticism at the turn of a millennium"

It has also been suggested by @fcbond that both should be merged into: 

`ewn-01911251-v` (Interlingual Index: i31251)
(v) turn 
> change orientation or direction, also in the abstract sense "Turn towards me" "The mugger turned and fled before I could see his face" "She turned from herself and learned to listen to others' 

I would prefer to stick with the lemma 'turn to' as the preposition seems essential for the meaning.

**Comment by arademaker** [comment]
This will merge to synsets with different frames.

**Comment by Ciara97olo** [comment]
I think the best way forward would be to merge ewn-01955796-v with ewn-00550851-v as they are the metaphorical, abstract sense of turn. The example "She turned from herself and learned to listen to others' should be deleted from ewn-01911251-v, and the definition should be altered so it does not include the abstract sense.
