### ISSUE TITLE
much

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#215]
The two definitions of much are very similar

`ewn-00059709-r` (Interlingual Index: i18494) 
(r) much, a good deal, a great deal, a lot, very much, lots 
> to a very great degree or extent "I feel a lot better" "we enjoyed ourselves very much" "she was very much interested" "this would help a great deal"

and

`ewn-00059624-r` (Interlingual Index: i18493)
(r) much 
> to a great degree or extent "she's much better now"

These are also both orphans (not connected to any other synset)

Reported by @fcbond

**Comment by jmccrae** [comment]
Another issue is that 'very much' should probably not be a lemma of the synset

**Comment by arademaker** [comment]
Indeed, both are isolated with no relations in PWN 3.0. 

```
% grep 00059171 ~/work/wn/WordNet-3.0/dict/data.adv
00059171 02 r 06 a_lot 0 lots 0 a_good_deal 0 a_great_deal 0 much 4 very_much 1 000 | to a very great degree or extent; "I feel a lot better"; "we enjoyed ourselves very much"; "she was very much interested"; "this would help a great deal"
% grep 00059086  ~/work/wn/WordNet-3.0/dict/data.adv
00059086 02 r 01 much 0 000 | to a great degree or extent; "she's much better now"
```

The problem is the OR in the definitions. It makes very difficult to distinguish the scope of the 7 synsets that contains `much`.

**Comment by dcillessen** [comment]
Perhaps these synsets should be linked to "intensifier" [ewn-06332047-n](https://en-word.net/lemma/intensifier).  Both of them are examples of intensifiers, I'd say.

**Comment by jmccrae** [comment]
Implementing this as follows:

Remove 'much' and 'very much' from `ewn-00059709-r`

Add links `exemplifies` from both synsets to `ewn-06332047-n`

I am going to leave the definitions based on the understanding that these are two degrees of the same basic meaning.
