### ISSUE TITLE
baroque

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#216]
two adj senses ! 

1. (1) baroque, churrigueresque, churrigueresco -- (having elaborate symmetrical ornamentation; "the building...frantically baroque"-William Dean Howells)

2. baroque, Baroque -- (of or relating to or characteristic of the elaborately ornamented style of architecture, art, and music popular in Europe between 1600 and 1750)

Can we merge them?

**Comment by vcvpaiva** [comment]
No. One is the style school, the other is derogatory.
my 2 cents,
Valeria

**Comment by arademaker** [comment]
Yes, it makes sense. In the glosses we don’t have enough context to distinguish them in most of the cases.
