### ISSUE TITLE
know

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#217]
These two synsets seem identical

`ewn-00596016-v` (Interlingual Index: i24736)
(v) cognize, know, cognise 
> be cognizant or aware of a fact or a specific piece of information; possess knowledge or information about "I know that the President lied to the people" "I want to know who is winning the game!" "I know it's time"

` ewn-00597025-v` (Interlingual Index: i24740)
(v) know 
> be aware of the truth of something; have a belief or faith in something; regard as true beyond any doubt "I know that I left the key on the table" "Galileo knew that the earth moves around the sun"

They could likely be merged

**Comment by arademaker** [comment]
in one of these, there is an intransitive frame. But I would consider the merge.
