### ISSUE TITLE
find

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#218]
There seem to be three senses of 'find' as 'make a discovery':

` ewn-00723361-v` (Interlingual Index: i25308)
(v) find, discover 
> make a discovery "She found that he had lied to her" "The story is false, so far as I can discover

` ewn-01641524-v` (Interlingual Index: i29932)
(v) find, discover 
> make a discovery, make a new finding "Roentgen discovered X-rays" "Physicists believe they found a new elementary particle"

`ewn-02158938-v` (Interlingual Index: i32526)
(v) find, notice, observe, discover, detect 
> discover or determine the existence, presence, or fact of "She detected high levels of lead in her drinking water" "We found traces of lead in the paint"

The first one seems to be finding by accident, but could probably be merged into the hypernym

`ewn-00600349-v` (Interlingual Index: i24755)
(v) see, learn, find out, get word, discover, hear, pick up, get a line, get wind 
> get to know or become aware of, usually accidentally "I learned that she has two grown-up children" "I see that you have been promoted"

The second one is the more scientific term.

The third one is a hyponym of 'catch sight of' so the definition could be updated to 
> discover or determine the existence, presence, or fact of **by perception with the eyes**

**Comment by arademaker** [comment]
once more syntactic behavior may justify the senses. I didn't verify.
