### ISSUE TITLE
wish

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#219]
Two very similar synsets for wish

`ewn-01828281-v` (Interlingual Index: i30847)
(v) wish 
> hope for; have a wish "I wish I could go home now"

`ewn-01828678-v` (Interlingual Index: i30849)
(v) like, care, wish 
> prefer or wish to do something "Do you care to try this dish?" "Would you like to come along to the movies?"

As they have the same hypernym they could probably be merged

**Comment by arademaker** [comment]
merging them will make one frame only in the first sense also available in the second sense.
