### ISSUE TITLE
means

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#220]
This synset (as reported by @fcbond) should probably be merged with its hypernym

`ewn-03739038-n` (Interlingual Index: i56097)
(n) means 
> an instrumentality for accomplishing some end

merged with

`ewn-03580409-n` (Interlingual Index: i55130)
(n) instrumentation, instrumentality 
> an artifact (or system of artifacts) that is instrumental in accomplishing some end

The combined definition would be 
> an (artifact that is instrumental in accomplishing some end) for accomplishing some end

The definition is also confusing with

`ewn-00173531-n` (Interlingual Index: i36321)
(n) way, means, agency thing or person that acts to produce a particular effect or achieve an end "a means of control" "an example is the best agency of instruction" "the true way to success"

Whose hypernym is 'implementation', so perhaps the definition could be improved too.

**Comment by arademaker** [comment]
What about the verbal senses:

1. 00955148-v mean, intend 
(mean or intend to express or convey; "You never understand what I mean!"; "what do his words intend?")

2. 00931852-v mean, stand_for, intend, signify 
> (denote or connote; "`maison' means `house' in French"; "An example sentence would show what this word means")

**Comment by jmccrae** [comment]
The verbal senses seem distinct to me
