### ISSUE TITLE
look

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#221]
This synset has some problems:

`ewn-00033592-v` (Interlingual Index: i21933)
(v) look 
> have a certain outward or facial expression "How does she look?" "The child looks unhappy" "She looked pale after the surgery"

It is too similar to

`ewn-02137900-v` (Interlingual Index: i32420)
(v) appear, look, seem 
> give a certain impression or have a certain outward aspect "She seems to be sleeping" "This appears to be a very difficult problem" "This project looks fishy" "They appeared like people who had not eaten or slept for a long time"

Which has the same hypernym and the first synset seems to have the incorrect hyponym

`ewn-00008792-v` (Interlingual Index: i21811)
(v) squint 
> partly close one's eyes, as when hit by direct blinding light "The driver squinted as the sun hit his windshield"

Which should be changed to `ewn-02134989-v`

**Comment by arademaker** [comment]
they differ in one frame only. But the first is about a `facial expression` and the second is purely about the impression. One is in verb.body and the other in verb.perception. So maybe we can just improve the gloss?
