### ISSUE TITLE
likely/unlikely

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#222]
`ewn-01416084-a` (Interlingual Index: i7708)
(a) probable, likely 
> likely but not certain to be or become true or real "a likely result" "he foresaw a probable loss"

`ewn-01416708-a` (Interlingual Index: i7712)
(a) unlikely, improbable 
> not likely to be true or to occur or to have occurred "legislation on the question is highly unlikely" "an improbable event"

For these two, having '(un)likely' as a word seems to contradict the definitions 

@fcbond suggests removing the synset members and linking them as similar to `ewn-01414308-a` and `ewn-01415272-a`

**Comment by vcvpaiva** [comment]
this does not make sense to me: likely and unlikely are antonyms, correct?
and probable and improbable too?
Maybe there is a reasonable explanation on the synsets themselves, but from what is written in this issue, the following makes no sense 

>For these two, having '(un)likely' as a word seems to contradict the definitions

**Comment by jmccrae** [comment]
To clarify I suggest removing 'likely' from `ewn-01416084-a` and removing 'unlikely' from `ewn-01416708-a`
