### ISSUE TITLE
seem

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#224]
Seem has 4 synsets

`ewn-02137900-v` (Interlingual Index: i32420)
(v) appear, look, seem 
> give a certain impression or have a certain outward aspect "She seems to be sleeping" "This appears to be a very difficult problem" "This project looks fishy" "They appeared like people who had not eaten or slept for a long time"

`ewn-02751757-v` (Interlingual Index: i35403)
(v) seem 
> appear to exist "There seems no reason to go ahead with the project now"

`ewn-02139137-v` (Interlingual Index: i32425)
(v) appear, seem 
> seem to be true, probable, or apparent "It seems that he is very gifted" "It appears that the weather in California is very bad"

`ewn-02202748-v` (Interlingual Index: i32747)
(v) seem 
> appear to one's own mind or opinion "I seem to be misunderstood by everyone" "I can't seem to learn these Chinese characters"

I can't find much sense in these distinctions and they all have the same hypernym so perhaps they could all be merged into the first?

**Comment by jmccrae** [comment]
From Christiane Fellbaum:

yes, one could perhaps reduce the number of senses of seem in WN.

I would argue for two:

(1) the "it seems that x" sense, where x is some kind of propositions ("it seems that Trump will not be re-elected")
the syntax is important here!

(2) the "appear to have certain properties/give a certain impression" sense, as in "she seems tired."

There is another sense/use that makes an assertion less strong, as in "I seem to have lost my wallet"
This is basically equivalent to "I have lost my wallet" but has some "softening" value

**Comment by jmccrae** [comment]
Based on this I have the following proposal:

Update the definition of  ewn-02137900-v "give a certain impression of **being something** or hav**ing** a certain ~~outward~~ aspect" 
Update the definition of ewn-02139137-v "**(of a proposition)** seem to be true, probable, or apparent"
And remove ewn-02202748-v ("appear to one's own mind or opinion") and ewn-02751757-v ("appear to exist")?

**Comment by arademaker** [comment]
For verbs, syntax is so essential that I wonder if we should stop changes until these principles are better documented.
