### ISSUE TITLE
offer

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#225]
This sense of 'offer' seems very similar to another one "make available for sale" and not distinguishable from its hypernym

`ewn-02301687-v` (Interlingual Index: i33214)
(v) offer 
> make available or accessible, provide or furnish "The conference center offers a health spa" "The hotel offers private meeting rooms"

Merge into:

`ewn-02332196-v` (Interlingual Index: i33372)
(v) provide, render, furnish, supply 
> give something useful or necessary to "We provided the room with an electrical heater"

**Comment by arademaker** [comment]
I agree.
