### ISSUE TITLE
stride

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#227]
This synset could be deleted

`ewn-01916702-v` (Interlingual Index: i31276)
(v) stride 
> cover or traverse by taking long steps "She strode several miles towards the woods"

Its meaning seems to be covered by 

`ewn-01923704-v` (Interlingual Index: i31313)
(v) stride 
> walk with long steps "He strode confidently across the hall"

**Comment by arademaker** [comment]
one more case of different frames.

**Comment by dcillessen** [comment]
I agree that we can delete ewn-01916702-v.  The difference between it and ewn-01923704-v is their placement in the hyponym hierarchy. As it is now, ewn-01923704-v describes a physical method of moving, while ewn-01916702-v describes a more metaphorical sense of "stride"(ing) across territory as a method of travel.

ewn-01923704-v is related to ewn-01908923-v (walk) 
ewn-01916702-v is related to ewn-01916152-v (traverse, track, cover, cross . . . )

Nonetheless, both of these senses of "stride" are addressed in either definition, so perhaps we could relate one definition to both hypernyms.
