### ISSUE TITLE
grass (verb)

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#229]
`ewn-01211645-v` (Interlingual Index: i27667)
(v) grass over, grass 
> cover with grass
 
`ewn-01605953-v` (Interlingual Index: i29761)
(v) grass 
> cover with grass "The owners decided to grass their property"

I would propose deleting the first one as its hypernym suggests that the subject is also the grass, e.g., "the lawn grassed over the..."

**Comment by arademaker** [comment]
One has frame `somebody ... something` and the other `something .... something`. Is it valid to join them? But one has not example, what makes it suspicious.

**Comment by jmccrae** [comment]
Yeah, I guess I am not sure whether the first one is even a valid term. I guess we need some corpus evidence and then either delete or update definitions

**Comment by dcillessen** [comment]
"grass over" as it appears in ewn-01211645-v can be found in [Collins](https://www.collinsdictionary.com/dictionary/english/grass-over) dictionary, though I didn't see it in AH, or MW.  

[OED](https://oed.com/view/Entry/80889?rskey=vLQCxW&result=3&isAdvanced=false#eid) describes it in "grass" (v) b. "transitive. To cover (land, an area, etc.) with grass or turf; to plant with grass. Frequently with over, down."

I agree that corpus evidence would be helpful here, though as it stands I think we also need to consider where the terms appear in the hierarchy.  

ewn-01211645-v "grass over" falls under ewn-01210571-v "cover" defined as: "form a cover over"
ewn-01605953-v "grass" falls under ewn-01335412-v "cover" defined as "provide with a covering or cause to be covered"

This indicates that "grass over" refers to the idea of "forming" a cover, while "grass" refers to a seemingly already complete cover. 

In practice, however, I think that this distinction is insignificant as hyponyms of both forms of "cover" refer to highly smilar concepts. For example, ewn-01210571-v is a hypernym to ewn-01211328-v "glaciate" defined as "cover with ice or snow or a glacier".  Similarly, ewn-01335412-v is a hypernym to ewn-01211020-v "frost" defined as "cover with frost."  

This being the case, perhaps a higher order merger or deletion is also justified?

**Comment by rwingerter55** [comment]
I looked it up in [Sketch Engine](https://auth.sketchengine.eu/#login) and found one example in the British National Corpus:

> ... of sadness and the old excitement: 'We're very fortunate in that in the near part of the wood garden we've been able **to grass over** and you wouldn't realise the number of big trees that have come down. In some places it may even be an improvement, and of ...

In the English Web Corpus 2015, `grass over` has 344 hits, `to grass over` 9 hits. Two examples:

> ... need dealing with and it needs widening by removing some mature trees with a chainsaw before it will be unshaded enough **to grass over** in the summer. I also walked round some of the boundary ditches and streams, and took some pictures. The best of which is ...

> ... in the past for the growing of asparagus. Since the end of asparagus farming in the 1990s these fields have been left to grass over , however the remnants of the cultivation fields can still be seen today as ridges and furrows. At a T-junction turn left ...

**Comment by jmccrae** [comment]
I think there is evidence for an "intransitive" usage of "grass over" with a definition of something like "become covered in grass".

In which case the appropriate hypernym is the same one as `ewn-01605953-v`:

`ewn-01335412-v` (Interlingual Index: i28352)
(v) cover 
> provide with a covering or cause to be covered "cover her face with a handkerchief" "cover the child with a blanket" "cover the grave with flowers"

This would suggest a merge... however as @arademaker has pointed out we are confusing the transitive and intransitive usage here. Perhaps this should be revisited after we look at #510?
