### ISSUE TITLE
morning_call

### ISSUE THREAD

**Issue by daikinomura** [globalwordnet/english-wordnet#23]
The definition of **morning_call** goes like this: 

**a telephone call that you request be made a specific time in order to wake you up at that time (especially in hotels); "she left a wake-up call for 7 a.m."**

I think this is a very strange sentence that doesn't make sense for me. 
I found this several months ago, but unfortunately I still can't find a way to understand nor fix this.
Or am I missing some phrase or structure?

I really wish I could get the advice from native speakers.

**Comment by jmccrae** [comment]
I would make a couple of changes to:

A telephone call that you request be made *at* a specific time in order to wake you up

**Comment by daikinomura** [comment]
I am sorry for my late reply and making a mistake for the wordform. This should be "wake-up call", not "morning call".

You solved the problem. 
Adding "at" and removing "at that time" greatly improved this sentence.
I would like to make a patch for this and send a pull request later.

P.S.
I noticed that I haven't looked up any other dictionary. Cobuild and Shorter OED doesn't have an entry for "wake-up call" but Wikitionary had one.(https://en.wiktionary.org/wiki/wake-up_call)

"A telephone call to awaken someone at a certain time, especially one requested by the person while staying at a hotel. "

I knew that there are people migrating WordNet defs into Wikitionary.
This was an another surprise and shock for me.
