### ISSUE TITLE
irregularly

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#231]
`ewn-00333384-r` (Interlingual Index: i19485)
(r) irregularly, on an irregular basis 
> in an irregular manner "her letters arrived irregularly"
 
`ewn-00192093-r` (Interlingual Index: i19450)
(r) irregularly 
> in an irregular manner "the stomach mucosa was irregularly blackened"

These are simple duplicates. I think we should remove the second one

**Comment by arademaker** [comment]
merge them to keep both examples.
