### ISSUE TITLE
stub (out)

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#232]
`ewn-01213186-v` (Interlingual Index: i27674)
(v) stub 
> extinguish by crushing "stub out your cigarette now"

`ewn-00479613-v` (Interlingual Index: i24106)
(v) press out, extinguish, stub out, crush out 
> extinguish by crushing "stub out your cigar"

These should be merged into a single synset

**Comment by arademaker** [comment]
It would be nice to be able to visualize the effect of this merging in the graph. One has hyperonym `extinguish, quench...` and the other `end, terminate`. I didn't find where the paths merge.

**Comment by jmccrae** [comment]
I think the 'end, terminate' hypernym is not great, we should just keep the 'extinguish' hypernym
