### ISSUE TITLE
re-create

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#233]
're-create' is just a spelling variant or 'recreate'. So we should either add new lemmas or merge into existing senses of 'recreate'

`ewn-00738804-v` (Interlingual Index: i25383)
(v) re-create 
> form anew in the imagination; recollect and re-form in the mind "His mind re-creates the entire world"
new lemma 

`ewn-01697776-v` (Interlingual Index: i30214)
(v) re-create, copy 
> make a replica of "copy that drawing" "re-create a picture by Rembrandt"
new lemma 

`ewn-01622373-v` (Interlingual Index: i29856)
(v) re-create 
> create anew "Re-create the boom of the West on a small scale"
Merge into `ewn-01741498-v`

We should probably also repeat this for all 're-' words

**Comment by arademaker** [comment]
yes merging with similar senses of recreate.
