### ISSUE TITLE
romantically

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#234]
`ewn-00472504-r` (Interlingual Index: i21405)
(r) romantically 
> in a romantic manner "she fantasized romantically about eloping with her boyfriend"

`ewn-00446613-r` (Interlingual Index: i21207)
(r) romantically 
> in a romantic manner "they were romantically linked"

New definitions
> in an idealistic and unrealistic manner
> in a manner expressive of love or romance

**Comment by arademaker** [comment]
maybe a rewriting of the glosses of `sexually` would also be welcome?

> sexually (with respect to sexuality) "sexually ambiguous"
>  sexually (by sexual means) "reproduce sexually"

**Comment by jmccrae** [comment]
What would you propose? Maybe you can create a different issue for tracking?
