### ISSUE TITLE
oversimplify

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#235]
`ewn-02575150-v` (Interlingual Index: i34536)
(v) oversimplify 
> simplify to an excessive degree "Don't oversimplify the problem"

`ewn-00401647-v` (Interlingual Index: i23733)
(v) oversimplify 
> make too simple "Don't oversimplify the instructions"

These can be merged

**Comment by arademaker** [comment]
The original Princeton web interface shows some differences:

<img width="661" alt="image" src="https://user-images.githubusercontent.com/86403/71522333-0791d700-28a3-11ea-94a5-eb33c24d6dfb.png">

Including a loop in the troponym relation?!

**Comment by arademaker** [comment]
we don't have the adj form `oversimplified`! We should add it.

**Comment by jmccrae** [comment]
There is no loop in the graph here. Troponym is hyponym in the interface so you are just looking at an inverse relation.

WordNet does not typically have every adjective from that is regularly derived from a verb

**Comment by arademaker** [comment]
> WordNet does not typically have every adjective from that is regularly derived from a verb

yes, but we should add once I found that something is missing or removing the ones that we find?

thank you for reminding me about the troponym relation. 

Still, we have some differences. One is in verb.change and the other in the verb.social lexicographer file. The sentence frames also suggest that maybe the synset in `verb.social` should keep only the frame without the complement and the other in `verb.change` should be the one with complement.

```
* Overview of verb oversimplify

The verb oversimplify has 2 senses (no senses from tagged texts)
1. oversimplify -- (simplify to an excessive degree; "Don't oversimplify the problem")
2. oversimplify -- (make too simple; "Don't oversimplify the instructions")

* Synonyms/Hypernyms (Ordered by Estimated Frequency) of verb oversimplify

2 senses of oversimplify                                                

** Sense 1
oversimplify
       => overdo, exaggerate

** Sense 2
oversimplify
       => simplify

* Synonyms (Grouped by Similarity of Meaning) of verb oversimplify

** Sense 1
oversimplify
       => overdo, exaggerate
--------------

** Sense 2
oversimplify
       => simplify
--------------

* Familiarity of verb oversimplify

oversimplify used as a verb is rare (polysemy count = 2)

* Synonyms/Hypernyms (Ordered by Estimated Frequency) of verb oversimplify

2 senses of oversimplify                                                

** Sense 1
oversimplify
       => overdo, exaggerate
           => make, do

** Sense 2
oversimplify
       => simplify
           => change, alter, modify

* Coordinate Terms (sisters) of verb oversimplify

2 senses of oversimplify                                                

** Sense 1
oversimplify
    -> overdo, exaggerate
       => overpraise
       => oversimplify
       => overleap

** Sense 2
oversimplify
    -> simplify
       => reduce
       => oversimplify

* Derived Forms of verb oversimplify

2 senses of oversimplify                                                

** Sense 1
oversimplify
       RELATED TO->(noun) oversimplification#1
           => oversimplification, simplism

** Sense 2
oversimplify
       RELATED TO->(noun) oversimplification#2
           => oversimplification, simplism

* Sample Sentences of verb oversimplify

2 senses of oversimplify                                                

** Sense 1
oversimplify
          *> Somebody ----s
          *> Somebody ----s something

** Sense 2
oversimplify
          *> Somebody ----s something
```
