### ISSUE TITLE
oversimplification

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#236]
`ewn-06752094-n` (Interlingual Index: i71913)
(n) simplism, oversimplification 
> a simplification that goes too far (to the point of misrepresentation)

New definition should clarify that this is a spoken or written statement

> an explication that simplifies too far to the point of misrepresentation

**Comment by arademaker** [comment]
Not sure if I understood the difference between the current and proposed definition. Maybe adding examples?

**Comment by jmccrae** [comment]
Sorry... it should be 
> an **explanation** that simplifies too far to the point of misrepresentation
