### ISSUE TITLE
rural adjective

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#238]
1. (18) rural -- (living in or characteristic of farming or country life; "rural people"; "large rural households"; "unpaved rural roads"; "an economy that is basically rural")

2. (7) rural -- (of or relating to the countryside as opposed to the city; "rural electrification"; "rural free delivery")

Hard to make the difference... maybe the glosses could be edited?

**Comment by arademaker** [comment]
Maybe different from #35, here we have one descriptive and the other relational.

**Comment by jmccrae** [comment]
This isn't related to #35 as neither of these adjectives are satellites.

I think these should be merged, they seem indistinguishable to me.

**Comment by arademaker** [comment]
There are some linguistics tests to distinguish between descriptive and relational adjectives (almost all references from Christiane Fellbaum. WordNet: An Electronic Lexical Database):

> [relational] adjective plays a role similar to that of a modifying noun and functions as a classifier.

> [Relational adjectives] do not refer to a property of the nouns they modify and so do not relate to an attribute.

regarding the position:

> In some cases a noun gives rise to two homonymous adjectives, one a relational adjective, the other descriptive. For example, the adjective in criminal law is not the same as that in criminal behavior, as reflected in the fact that only in the second case can the adjective be used predicatively (His behavior is criminal but not *The law is criminal).

> Typically [relational adjectives] occur only in attributive position, as modifying nouns do.

> Typically they are not gradable

> And typically (but not always) they lack direct antonyms.

In https://www.ucl.ac.uk/internet-grammar/adjectiv/attribut.htm the attributive position is defined:

> Adjectives in the first position - before the noun - are called ATTRIBUTIVE adjectives. Those in the second position - after the noun - are called PREDICATIVE adjectives. Notice that predicative adjectives do not occur immediately after the noun. Instead, they follow a verb. 


The problem is that almost all tests uses **typically**! ;-) The adjective rural is a hard case in the glosses.  Consider the gloss below that defines the descriptive sense, that is the sense that is used to talk about properties of nouns. In the examples, we are suppose to use the sense of this same synset, the descriptive one. But `rural people` is a property of the people? IMO, it is more a modifier of the word people.

(a) rural | living in or characteristic of farming or country life ; rural people ; large rural households ; unpaved rural roads ; an economy that is basically rural

Few more examples: `rural students`  it is more relational; `rural life` is more descriptive (describing properties of life) and `rural matters` looks like both...

So I am not sure if they should be merged. But surely the glosses could be improved... Maybe a pattern for differentiate descriptive/relational would be nice.

**Comment by arademaker** [comment]
In a more radical direction, at some point, we could think of changing the way adjectives are modeled: http://www.sfs.uni-tuebingen.de/GermaNet/adjectives.shtml

**Comment by arademaker** [comment]
After consulting  Christiane Fellbaum, I also agree to merge the two synsets.

**Comment by jmccrae** [comment]
I also don't think either of these senses are a relational sense of the adjective. It is easy to find corpus evidence of either sense being used predicatively and being graded.

I suggest moving `ewn-02801550-a` into `ewn-02057872-a` but keeping the former's definition "of or relating to the countryside as opposed to the city"

**Comment by arademaker** [comment]
It would vote on merging the definitions and examples. So we are not missing anything.

**Comment by jmccrae** [comment]
Actually, that is a good point. We can have multiple definitions, so this would be fine here

**Comment by 1313ou** [comment]
>I suggest moving ewn-02801550-a into ewn-02057872-a

1-You did the opposite: you moved ewn-02057872-a into ewn-02801550-a
[see commit](https://github.com/globalwordnet/english-wordnet/pull/403/commits/de93aaaf5c6b65178e80ee3ba67dbb4495d1e50a)
2-In the process the antonymy relation to **urban** has gone down the drain. So it should be reopened.
3-The similar relation now crosses lexfile boundaries changing how the head is computed.
4-Why didn't '**urban**' undergo the same merging process ?
5-The mystery of multiple definitions is solved.

**Comment by jmccrae** [comment]
Okay, I reverted this commit and will push it to the 2021 release
