### ISSUE TITLE
sit (definition)

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#239]
@fcbond suggests updating the following definition

`ewn-01545905-v` (Interlingual Index: i29448)
(v) sit, sit down 
> be seated

To:

"be in a position in which one's upper body is largely upright and supported by one's backside."

**Comment by arademaker** [comment]
@apease made a good observation.  We have

1. http://wn.mybluemix.net/synset?id=01984902-v (take a seat)
2. http://wn.mybluemix.net/synset?id=01543123-v (be seated)
3. http://wn.mybluemix.net/synset?id=01240029-a (seated | the state)

(1) and (2) are mapped to the concept `SittingDown` (action) in SUMO. The adjective is mapped to the state or situation, the concept `Sitting`.

Francis' definition is very similar to the adjective definition in (3). Do we want that? Actually, can someone give examples for (2)? Adding examples is a good way to make the sense clear (related to #243)

**Comment by jmccrae** [comment]
The distinction between the verbs is that "take a seat" is an action, where as "be seated" describes the state (perhaps the SUMO mapping is incorrect?). This is distinguished in many languages so is useful for inter-lingual mapping, and as the distinction is already in WordNet, I wouldn't want to change it just make the definitions more explicit.
