### ISSUE TITLE
utmost, high and intense

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#240]
The definition of 'utmost' suggests two synsets refer to degree:

`ewn-01214767-s` (Interlingual Index: i6633)
(s) last, utmost 
> highest in extent or degree "to the last measure of human endurance" "whether they were accomplices in the last degree or a lesser one was...to be determined individually"

`ewn-01515272-s` (Interlingual Index: i8298)
(s) utmost, uttermost, extreme 
> of the greatest possible degree or extent or intensity "extreme cold" "extreme caution" "extreme pleasure" "utmost contempt" "to the utmost degree" "in the uttermost distress"

these are both marked as related to the following synsets (respectively):

`ewn-01213526-a` (Interlingual Index: i6627)
(a) high 
> greater than normal in degree or intensity or amount "a high temperature" "a high price" "the high point of his career" "high risks" "has high hopes" "the river is high" "he has a high opinion of himself"

`ewn-01513206-a` (Interlingual Index: i8288)
(a) intense 
> possessing or displaying a distinctive feature to a heightened degree "intense heat" "intense anxiety" "intense desire" "intense emotion" "the skunk's intense acrid odor" "intense pain" "enemy fire was intense"

These definitions need to be clearer I think as in both cases they refer to "degree"

**Proposal**
Change definition of `ewn-01213526-a` to
> greater than normal in quantity or amount

Remove "utmost" from `ewn-01214767-s` (as it is not mentioned in the examples and seems an odd synonym.

Reported by @fcbond

**Comment by arademaker** [comment]
In the glosstag, the utmost occurences were already annotated by Princeton team. The cases of ewn-01213526-a are:

(a) ultimate | furthest or highest in degree or order ; **utmost** or extreme ; the ultimate achievement ; the ultimate question ; man's ultimate destiny ; the ultimate insult ; one's ultimate goal in life ;

(n) extremity | the greatest or **utmost** degree ; the extremity of despair ;

So removing utmost from ewn-01213526-a will force the annotation of these two cases with the other senses of utmost.

**Comment by jmccrae** [comment]
Is that a problem @arademaker?

**Comment by arademaker** [comment]
No. You are right.

**Comment by jmccrae** [comment]
Closed by #240
