### ISSUE TITLE
difficulty

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#241]
There is some similarity between these definitions, but they have distinct places in the synonym hierarchy. 

`ewn-14431490-n` (Interlingual Index: i112724)
(n) difficulty 
> a condition or state of affairs almost beyond one's ability to deal with and requiring great effort to bear or overcome "grappling with financial difficulties"

`ewn-05694760-n` (Interlingual Index: i66800)
(n) difficulty 
> a factor causing trouble in achieving a positive result or tending to produce a negative result "serious difficulties were encountered in obtaining a pure reagent"

Reported by @fcbond

**Comment by arademaker** [comment]
We have four senses in PWN and all of them are hard to distinguish.

**Comment by arademaker** [comment]
1. (18) trouble, difficulty -- (an effort that is inconvenient; "I went to a lot of trouble"; "he won without any trouble"; "had difficulty walking"; "finished the test only with great difficulty")
2. (13) difficulty -- (a factor causing trouble in achieving a positive result or tending to produce a negative result; "serious difficulties were encountered in obtaining a pure reagent")
3. (11) difficulty -- (a condition or state of affairs almost beyond one's ability to deal with and requiring great effort to bear or overcome; "grappling with financial difficulties")
4. (6) difficulty, difficultness -- (the quality of being difficult; "they agreed about the difficulty of the climb")

We have four senses in PWN and all of them are hard to distinguish. Maybe senses 3 and 4 can be merged?

```
** Sense 1
trouble, difficulty
       => effort, elbow grease, exertion, travail, sweat
           => labor, labour, toil
               => work
                   => activity
                       => act, deed, human action, human activity
                           => event
                               => psychological feature
                                   => abstraction, abstract entity
                                       => entity

** Sense 2
difficulty
       => cognitive factor
           => cognition, knowledge, noesis
               => psychological feature
                   => abstraction, abstract entity
                       => entity

** Sense 3
difficulty
       => condition, status
           => state
               => attribute
                   => abstraction, abstract entity
                       => entity

** Sense 4
difficulty, difficultness
       => quality
           => attribute
               => abstraction, abstract entity
                   => entity
```

**Comment by arademaker** [comment]
Consider  the gloss below. How would you annotate it?

> face a difficulty and grapple with it without avoiding it

**Comment by Ciara97olo** [comment]
I agree senses 3 and 4 should be merged. I also think that ewn-05694760-n should be deleted, I don't think there's justification for keeping it and that the hypernym is not correct.
