### ISSUE TITLE
some, every and all.

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#242]
For some two distinctions are made for countable and uncountable:

`ewn-01558420-s` (Interlingual Index: i8531)
(s) some 
> relatively much but unspecified in amount or extent "we talked for some time" "he was still some distance away"

`ewn-01556991-s` (Interlingual Index: i8524)
(s) some 
> relatively many but unspecified in number "they were here for some weeks" "we did not meet again for some years"

Is this actually a sense distinction made in English?

Report by @fcbond

**Comment by jmccrae** [comment]
See #243 for general discussions of sense distinctions.

**Comment by arademaker** [comment]
How do we answer this question:

> Is this actually a sense distinction made in English?

This is issue #243 right?

**Comment by jmccrae** [comment]
Indeed, the general discussion is #243, this issue tracks these particular words
