### ISSUE TITLE
Garbled syntacticbehaviours

### ISSUE THREAD

**Issue by 1313ou** [globalwordnet/english-wordnet#244]
I'm taking the first lexical entry (inoculate) in the first verb file:

GONE
\<SyntacticBehaviour subcategorizationFrame="The banks %s the check" senses="ewn-inoculate-v-00086587-03"/>
<SyntacticBehaviour subcategorizationFrame="They %s the bags on the table" senses="ewn-inoculate-v-00188584-01"/>

REPLACEMENT
\<SyntacticBehaviour subcategorizationFrame="Somebody ----s" senses="ewn-inoculate-v-00086587-03"/>
\<SyntacticBehaviour subcategorizationFrame="Somebody ----s something PP" senses="ewn-inoculate-v-00188584-01"/>

REMAINING
\<SyntacticBehaviour subcategorizationFrame="The coins %s " senses="ewn-inoculate-v-00053234-01 ewn-inoculate-v-00055835-01 ewn-inoculate-v-00188584-01"/>
\<SyntacticBehaviour subcategorizationFrame="They %s the coin " senses="ewn-inoculate-v-00086587-03 ewn-inoculate-v-00834278-01"/>

Obviously the last 2 sound funny (The coins inoculate, They inoculate the coins). They seem to be old inoculated data, immune to changes. I didn't investigate any further.
Besides verb.Framestext coins no 'coin'.

**Comment by 1313ou** [comment]
BTW, this would not happen with factored out syntactic behaviour descriptors.

**Comment by 1313ou** [comment]
There seems to be some confusion between **frames** and **frame sentences**. The \<syntacticbehaviour> tag works as a big bag to contain all this undifferentiated mass.

In wn31, the "_The coins %s_" **sentence** is associated only with senses involving 'jangle', 'jingle', 'opalesce", 'shine', 'twinkle', 'spin'  while the  "_They %s the coins_" **sentence** associates only with senses involving 'flip', 'spin', 'toss'.

So this requires 1) correcting 2) clarification

**Comment by jmccrae** [comment]
It seems there was some issue with the automatic fix here. It should be correct now.

**Comment by 1313ou** [comment]
To be reopened. There are still issues.
Exec grep '%s' * to get the sentence templates (95 of them) with a "The sheets didn&apos;t %s" pervading verb files.

**Comment by 1313ou** [comment]
Reopen, please.
Take _inoculate_ entry in wn-verb.body.
It has 3 senses:

- ewn-inoculate-v-00053234-01
- ewn-inoculate-v-00055835-01
- ewn-inoculate-v-00086587-03

How come syntactic behaviours in that same entry refer to alien sense ewn-inoculate-v-001885**84-01**, that does exist but outside this entry in wn-verb.change ? This violates the principle of modularity and again would not happen if syntactic behaviours were attached to senses, not lex entries (a flawed design to my sense).
