### ISSUE TITLE
sentence template information lost

### ISSUE THREAD

**Issue by 1313ou** [globalwordnet/english-wordnet#245]
Compared to wn31, **sentence template information** for verbs (to be found in sents.vrb+sentidx.vrb) is lost. 

This, together with [adjective position](https://github.com/globalwordnet/english-wordnet/issues/180) (issue conveniently closed as 'enhancement') REMAINS an issue.

**Comment by jmccrae** [comment]
NB. `enhancement` does not mean an issue is closed. Both this issue and #180 are scheduled to be fixed by the April release :)

**Comment by jmccrae** [comment]
I don't think I will finish this one so soon, so it can go for the next release
