### ISSUE TITLE
illusion: 4 senses hard to distinguish without examples 

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#246]
1. (23) illusion, semblance -- (an erroneous mental representation)

2. (6) illusion, fantasy, phantasy, fancy -- (something many people believe that is false; "they have the illusion that I am very wealthy")

3. (1) delusion, illusion, head game -- (the act of deluding; deception by creating illusory ideas)

4. magic trick, conjuring trick, trick, magic, legerdemain, conjuration, thaumaturgy, illusion, deception -- (an illusory feat; considered magical by naive observers)

**Comment by jmccrae** [comment]
Is the request to add suitable examples? I think 1 and 2 are very similar in meaning

**Comment by arademaker** [comment]
Yes, a request for examples of (1), (3) and (4). And yes, they are hard to distinguish during annotation. 1 and 2 are both noun.cognition. 4 and 3 are noun.act.

**Comment by arademaker** [comment]
I would vote on merging 1+2 and 4+3. Does it make sense?

**Comment by vcvpaiva** [comment]
it does not make sense to me. magic tricks are very different from delusions in my books.

**Comment by arademaker** [comment]
Maybe we can agree on 1+2? For 4+3 what about `head game` and `magic trick`? Are they similar enough to you? The problem with the PWN definition of `synonym` is that one simple context where the words/expressions can be interchangeable is not enough to rule out the possibility of the existence of other contexts where they can be interchangeable.

**Comment by dkasak** [comment]
I get the feeling that 1 maybe be talking about sensory illusions (such as optical illusions) while 2 is talking specifically about common but false *beliefs*.
