### ISSUE TITLE
capitalisation rules

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#247]
https://en.wikipedia.org/wiki/Ceylonite

```
(n) Ceylonite, pleonaste 
a dark-colored spinel containing iron
```

Why the term Ceylonite is uppercase and `pleonaste` downcase?

**Comment by jmccrae** [comment]
'Ceylon' is a place, ergo 'Ceylonite' could be capitalised, but the rules of English orthography here are actually ambiguous (see https://english.stackexchange.com/questions/166988/capitalization-of-words-derived-from-proper-nouns)

Wikipedia seems to prefer lower case so we could switch:

https://en.wikipedia.org/wiki/Ceylonite

**Comment by arademaker** [comment]
Yes, I believe we will have to follow Wikipedia most frequent use of the term. In this particular case, it came from Ceylon so it can be justified to be capitalized. But Christiane said:

> I don't know whether there are any rules and I suspect people don't capitalize uniformly, either.  But for practical (NLP) purposes, one can just change all capitalized words to lower case or  treat capitalized and lower-case words the same, so it shouldn't be a major problem.
