### ISSUE TITLE
French and other cases of "X language"

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#248]
ewn-06977643-n

the French language. I would vote to add `French language` in the synset. Many occurrences of the compound in the glosses.  Moreover, the hypernym is `Romance_language` but one could also argue to remove the compound `Romance_language` keeping only the `Romance` word in the hypernym. 

In the glosses, occurrences of `...French language...`,  I am annotating the noun sense for `French` (language) instead of the adjective sense of `French`.

**Comment by jmccrae** [comment]
This is a (arguably) compositional meaning. But there seems to be some inconsistency here. German is the "German language", but the same is not true of Italian, Spanish, etc.

I think if we do this, we do it to all siblings here.

**Comment by jmccrae** [comment]
Gist of the changes:
https://gist.github.com/jmccrae/2d940cc952a9bd17629fcc3304c30cd0
