### ISSUE TITLE
Merge synsets from enWordNet (plWordNet)

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#249]
This issue is to track the merging of enWordNet synsets into this resource.

The list of synsets can be viewed in this document:

https://docs.google.com/spreadsheets/d/1bTTF6mc5SVMVjyXdxhDS27zOQp43vbJCvUvL639F4Oo/edit#gid=0

**Comment by arademaker** [comment]
Who go to the whole list and approve/reject the Polish synsets? It bypasses the GitHub issue revision process.

**Comment by arademaker** [comment]
How to keep the Polish data updated with this resource later? The next synsets will have any id for tracking future resync with Polish data?

**Comment by jmccrae** [comment]
The synsets were checked by myself and @dcillessen. As they are of a high basic quality, it is not necessary to validate every single one... I generally trust Ewa, Maciej... although there were some errors that will be reported back to the plWordNet project (soon).

The IDs map fairly straightforwardly. Essentially we have appended `ewn-92` onto the plWordNet IDs, so

```xml
    <synset id="302385" workstate="Nie przetworzone" split="1" owner=""
        definition="a system of watercourses or drains for carrying off excess water  "
        desc="" abstract="false">
```

is imported as

```xml
    <Synset id="ewn-92302385-n" ili="in" partOfSpeech="n">
      <Definition>a system of watercourses or drains for carrying off excess water</Definition>
```
