### ISSUE TITLE
breakdown

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#253]
https://en-word.net/lemma/breakdown

We don't have a sense for the physical breakdown such as:

1. (n) acantholysis | a **breakdown** of a cell layer in the epidermis ( as in pemphigus )
1. (v) dissociate | to undergo a reversible or temporary **breakdown** of a molecule into simpler molecules or atoms ; acids dissociate to give hydrogen ions ;

**Comment by arademaker** [comment]
MacOS English dictionary have 

2. a failure of a relationship or system: a breakdown in military discipline | some of these women will have experienced marital breakdown | the breakdown of their marriage.

**Comment by jmccrae** [comment]
Might it make sense to add this as a member of the synset. 
`ewn-13479471-n` (Interlingual Index: i107464)
(n) decomposition, chemical decomposition reaction, decomposition reaction 
> (chemistry) separation of a substance into two or more substances that may differ from each other and from the original substance

"Chemical breakdown" and "chemical decomposition" seem like good synonyms.

The MacOS definition is already covered by this synset, right?

`ewn-00554399-n` (Interlingual Index: i38300)
(n) breakdown, dislocation 
> the act of disrupting an established order so it fails to continue "the social dislocations resulting from government policies" "his warning came after the breakdown of talks in London"

**Comment by arademaker** [comment]
I am not sure if cell layers or molecules are substances. The cell (http://wn.mybluemix.net/synset?id=00006484-n: basic structural and functional unit of all organisms)  is in noun.Top but maybe a `cell layer` can be a substance.

But molecule (http://wn.mybluemix.net/synset?id=14682133-n, the simplest structural unit of an element or compound) is in noun.substance.
