### ISSUE TITLE
"William A. Craigie" problem

### ISSUE THREAD

**Issue by daikinomura** [globalwordnet/english-wordnet#28]
This is the synset that include serious problem. I wish I could have your advice.

"English lexicographer who was a joint editor of the Oxford English Dictionary (1872-1966)"

The problem could be summerized in 2 points.

1.) He is a Scottish lexicographer not English.
2.) Birth date and death date are different from what enwiki says.(13 August 1867 – 2 September 1957)  

And I found out that "C.T. Onions" meets these conditions.
1.) "C.T. Onions" is an English.
2.) Birth date and death date roughly matches. (10 September 1873 – 8 January 1965)

I am very troubled in fixing this synset.
I wish I could have a good idea.

http://wordnet-rdf.princeton.edu/lemma/Sir%20William%20Alexander%20Craigie
https://en.wikipedia.org/wiki/William_Craigie
https://en.wikipedia.org/wiki/Charles_Talbut_Onions

**Comment by arademaker** [comment]
Yes, copying here for facilitating my comprehension 

1. PWN says: 

Sir William Alexander Craigie, William A. Craigie, Craigie
English lexicographer who was a joint editor of the Oxford English Dictionary (1872-1966)

2. Wikipedia says:

- Sir William Alexander Craigie (13 August 1867 – 2 September 1957) was a philologist and a lexicographer.
- Charles Talbut Onions (C. T. Onions) (10 September 1873 – 8 January 1965) was an English grammarian and lexicographer and the fourth editor of the Oxford English Dictionary.

This synset is only an instance of http://wnpt.brlcloud.com/wn/synset?id=10256080-n. A leaf in the network easy to fix. I would suggest (1) adjust the gloss of 10914134-n (assuming that Wikipedia is right?) and adding one extra synset to Charles Talbut Onions. 
 
We could try to trace this synset back to the SemCor corpus (http://www.aclweb.org/anthology/W14-0132), but I don't think it is worth the effort.

**Comment by daikinomura** [comment]
Thanks for your reply, Alexandre. 

I have fixed more than 100 synsets so far. However this synset has something that makes me reluctant to touch. Let me explain why I am reluctant to patch this.

1. This synset is OED related. I think WordNet has some respect to OED. For example, 1st paper of Five Papers juxtaposes WordNet with OED(as a representative of alphabetically ordered dictionary), some lexicographer frequently look up OED and he/she checks its meaning(there are some synsets that its meaning couldn't be found other than OED ... e.g.,hour_glass), or OED is an only instance of dictionary%1:10:00:: , and so on... 

So it is hard to believe lexicographers make such a mistake. I suspect some troubles or discussion behind this synset.

2. lexicographer%1:18:00:: is an hyponym of both compiler and linguist. WordNet doesn't use multiple inheritance frequently, and it is a sign (for me) that the lexicographer has some passion for that synset. For example,choreography has three hypernyms: performing_arts, recreation and  show. I feel that there is someone who has strong interest in "dance". In a same manner, I feel there is someone who has strong interest in lexicographer. 

Does lexicographer make a mistake on a lexicographer? I think something had happened ... something that I don't know.

3. Already we have James_Murray as it's sibling. I wonder what is the point for Craigie? Is it the 3rd editor of OED or "Dictionary of American English" or both? I wish I could hear the intention of the lexicographer of WordNet.

4. The eyes of sibling instances makes a Japanese guy nervous to touch them... I am feeling that this synset is too important for me to touch.
   
I would like to wait for a while and post this topic to the mailing list of PWN.

**Comment by jmccrae** [comment]
I have been fixing other birth/death dates in WordNet. In this case I have changed the definition to the name used here and made no other changes
