### ISSUE TITLE
Missing decidable / undecidable  

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#285]
Common words not in PWN

**Comment by jmccrae** [comment]
Could you provide a definition and hypernyms for these synsets?

My feeling is the sense of "able to make a decision" is compositional so would not follow our new guidelines. However the computer science meaning of these words would certainly be of value.

**Comment by arademaker** [comment]
decidable 
> capable of being decided as following or not following from the axioms of a logical system 

undecidable 
> not capable of being decided as following or not following from the axioms of a logical system

**Comment by arademaker** [comment]
both derivated from

 00697589-v make_up_one's_mind, decide, determine (reach, make, or come to a decision about something; "We finally decided after lengthy deliberations")

not sure what do you mean by `hypernyms`. these would be new adjectives, organized as clusters not in an hyper/hypo hierarchy. 

Not sure if it makes sense to add in a alterady available cluster. Maybe `resolvable`?

**Comment by jmccrae** [comment]
PR created as satellites of 'possible' and 'impossible'.
