### ISSUE TITLE
the s/Siege of Syracuse

### ISSUE THREAD

**Issue by 1313ou** [globalwordnet/english-wordnet#286]
The devil resides in the details.

Did you know

- the 'siege of Syracuse' can refer to the Athenian siege or the Roman siege while
- the 'Siege of Syracuse' refers only to the Roman siege ?

```
wn-noun.act.xml:13563:    <LexicalEntry id="ewn-siege_of_Syracuse-n">
wn-noun.act.xml-13564-      <Lemma writtenForm="siege of Syracuse" partOfSpeech="n"/>
wn-noun.act.xml-13565-      <Sense id="ewn-siege_of_Syracuse-n-01298618-02" n="1" synset="ewn-01298618-n" dc:identifier="siege_of_syracuse%1:04:00::"/>
wn-noun.act.xml-13566-      <Sense id="ewn-siege_of_Syracuse-n-01298787-02" n="0" synset="ewn-01298787-n" dc:identifier="siege_of_syracuse%1:04:01::"/>
wn-noun.act.xml-13567-    </LexicalEntry>
--
wn-noun.act.xml:51475:    <LexicalEntry id="ewn-Siege_of_Syracuse-n">
wn-noun.act.xml-51476-      <Lemma writtenForm="Siege of Syracuse" partOfSpeech="n"/>
wn-noun.act.xml-51477-      <Sense id="ewn-Siege_of_Syracuse-n-01298787-00" n="0" synset="ewn-01298787-n"/>
wn-noun.act.xml-51478-    </LexicalEntry>
```

For quick reference;
```
ewn-01298787-n the Roman siege of Syracuse (214-212 BC)
ewn-01298618-n the Athenian siege of Syracuse (415-413 BC)

```

**Comment by jmccrae** [comment]
This is currently how it is represented but it seems odd. Also, the Athenian siege is not significant enough to warrant its own Wikipedia page, so I don't know why it is in WordNet.

I think the best idea would be to have a single lemma (with capitalized 'Siege') as these are instances and hence should be proper nouns.

**Comment by dcillessen** [comment]
The fact that the Athenian siege appears likely stems from an understanding that it was potentially the turning point of the Peloponnesian War.  It also led to the defeat and eventual death of one of the more significant figures in the war, Nicea. He doesn't appear in WN either, though he has his own Wikipedia page. 

This being the case, I'd argue that the siege is significant in the realm of classical studies. 

Perhaps both lemmas should be kept, and referred to as proper nouns with capital "S"es?
