### ISSUE TITLE
Example sentences that use no words in synset

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#30]
Contributed by @daikinomura 

https://drive.google.com/file/d/1ZAfb_7RsdLnhl7uWpi3ODogpEi7r9uxa/view

**Comment by arademaker** [comment]
I don't have native speakers in my group. Still, I would like to  help with that, but we need to devise a guideline for possible actions. 

For instance, taking the case of http://wnpt.brlcloud.com/wn/synset?id=00516539-a, I can see two possible actions. The first one would be to add `partial` as a wordform in the synset 00516539-a. The second one would be to rewrite the example or remove it (since we have two examples in this synset). 

Do all agree with these possibilities? How do we decide the best option for each case? 

Finally, I want to return to the discussion about how to go further with this repo in a manageable way. The XML files are not easy to edit (synsets are not self-contained in the same file region), and the size of each lexicographer file is almost 10x times bigger than the original Wordnet txt files. We have an initial proposal of text format in https://github.com/own-pt/own-en/blob/master/dict/.

**Comment by jmccrae** [comment]
I have created the following document to track all the changes to make to close this issue:

https://docs.google.com/spreadsheets/d/1bmBz81jz2Ov93fetoI0p9apVbb7yGw6-9ozjNLjb1pQ/edit#gid=1800586213

**Comment by arademaker** [comment]
Since @jmccrae closed issue #26, I call the attention here to my comment https://github.com/globalwordnet/english-wordnet/issues/26#issuecomment-439884208 on it. If possible, it would be great to have feedbacks about it.

**Comment by jmccrae** [comment]
Hi Alex, I fixed the permissions on the doc.

As you suggest we need to either:

1/ Add a new wordform
2/ Modify existing example
3/ Remove the example

This should be decided on a case by case basis.
For discussions of changes of format in the repo could you create a new issue?

**Comment by arademaker** [comment]
Just adding more info about the format that I mentioned in my comment https://github.com/globalwordnet/english-wordnet/issues/26#issuecomment-439884208. We had written about this in our paper http://arademaker.github.io/files/gwc-2018-chronostratigraphic.pdf (section 5). A text format could be used to manual editing and a conversion script to generate the XML files for validation and distribution.

**Comment by daikinomura** [comment]
This document is what I have needed.  I really wish these patches to be completed.

Here is my questions and what I noticed.

1.  What does pink colored rows mean? 

2.  There is a related item at the top of FAQ. Does PWN understand these glitches?
https://wordnet.princeton.edu/frequently-asked-questions
Valeria of OpenPT already knew this problem and potentially many people might be in trouble.

3.  I see some tricky examples in noun. I think we can skip "double negative" examples, but I'd like to leave the decision to the guy who patches. Or example sentences of gods of Hindu might be a controversial one.
 
4.  There are some irregular verbs that may have no problem( e.g., "go for broke" and "went for broke" )

As John says, they seems to require case by case judgment. This might be a large patch and I hope this to be successful.

**Comment by jmccrae** [comment]
1. It means that I will return to them
2. I think the FAQ refers to the fact that not every word in a synset occurs in an example. Here we are dealing with the case where no words in the synset occur in the example.
3. Not sure which example you are referring to
4. Yes, I am looking for those.

**Comment by daikinomura** [comment]
###  >3. Not sure which example you are referring to

double_negative is in the row 416, ewn-07219968-n. 

```
wf: double_negative
def: a grammatically substandard but emphatic negative; "I don't never go"
```

The example sentence doesn't include it's wordform "double_negative", but it depicts the meaning.

Hindu gods for example, row 422, ewn-09548621-n.
```
wf: Chandi
def: malevolent aspect of Devi; "the fierce"

```
The example sentence doesn't include it's wordform, but it depicts Chandi's most notable character.
 

### I would like to ask you about this synset.  

```
synset: n07117611
sk: emphasis%1:10:01::
def: special and significant stress by means of position or repetition e.g.

```
Do you think this could be added to the spreadsheet ? This is the hypomym of "rhetorical device" and it's siblings have examples. So I guess the lexicographer wanted to add an example but failed to add for some reason.

**Comment by jmccrae** [comment]
I guess both the examples of "double_negative" and "Chandi" will need to be rewritten something like "A double negative such as "I don't never go"" and "Chandi, the fierce"

I will add the synset to the sheet

**Comment by arademaker** [comment]
This issue was closed because it was solved or because it was rejected?

**Comment by jmccrae** [comment]
This was solved a while back.
