### ISSUE TITLE
boombox?

### ISSUE THREAD

**Issue by vcvpaiva** [globalwordnet/english-wordnet#301]
Is this the right place to ask for synsets that don't exist, yet?
thanks!

**Comment by jmccrae** [comment]
Yes, it is indeed. Any suggestions about a definition and hypernym relation?

**Comment by vcvpaiva** [comment]
from wikipedia:
A boombox (known also as Jambox and ghettoblaster) is a portable music player, generally with a carrying handle.

hypernym? maybe electronic equipment?
I did find electronic equipment
03278248-n
English
(equipment that involves the controlled conduction of electrons (especially in a gas or vacuum or semiconductor))
but no audio_equipment in WN, only in WikiData where it's considered a portable audio player
(Q3347599).

**Comment by dcillessen** [comment]
It looks like "boom box" and "ghetto blaster" are already covered by [ewn-03441092-n](https://en-word.net/lemma/boom%20box).  Perhaps we should add "jam box" to the synset as well.

**Comment by jmccrae** [comment]
Yes, it seems that the main issue is to add the new variants to the existing synset
