### ISSUE TITLE
UI issue

### ISSUE THREAD

**Issue by vcvpaiva** [globalwordnet/english-wordnet#302]
If a lemma is not found, the system should say so. and preferably give some useful information.

**Comment by arademaker** [comment]
Maybe @jmccrae can make it clear in the readme, but this is not an issue for this repository. I believe the interface code is https://github.com/jmccrae/wordnet-angular

**Comment by jmccrae** [comment]
Thanks @arademaker. I have created his as an issue here:

https://github.com/jmccrae/wordnet-angular/issues/6
