### ISSUE TITLE
recital

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#306]
recital (a detailed statement giving facts and figures; "his wife gave a recital of his infidelities")

recital (a detailed account or description of something; "he was forced to listen to a recital of his many shortcomings")

duplicated?

**Comment by jmccrae** [comment]
It seems `ewn-07236416-n` has an odd hypernym ('recitals' aren't really 'chronicles' or 'histories'):

`ewn-06526084-n` (Interlingual Index: i70694)
(n) history, account, story, chronicle 
> a record or narrative description of past events "a history of France" "he gave an inaccurate account of the plot to kill the president" "the story of exposure

It is possible that this synset should be removed and merged into the other.

**Comment by dcillessen** [comment]
The odd hypernym - ewn-06526084-n - is likely to do with "recital" as it pertains to oral tradition.  Though I agree that these senses of "recital" should be merged, I also lightly contend that we should hold on to ewn-16526084-n as a hypernym.

**Comment by rwingerter55** [comment]
Here are both synsets and their hypernyms. IMO `ewn-07236416-n` can be deleted without any loss of information. The hypernyms should not be inherited by `ewn-07249395-n`.

concept | lemmas | definition | 07236416-n | 07249395-n | Note
-- | -- | -- | -- | -- | --
ewn-00033319-n | communication | something that is   communicated by or to or between people or groups | 1 | 1 |  
ewn-06810027-n | indication, indicant | something that serves   to indicate or suggest | 1 |   | ?
ewn-06611268-n | content, message,   subject matter, substance | content communicating   a message; what something is about |   | 1 |  
ewn-06656171-n | evidence | an indication that   makes something evident | 1 |   | ?
ewn-06735202-n | statement | a message that is   stated or declared; a communication (oral or written) setting forth   particulars or facts etc |   | 1 |  
ewn-06659969-n | record | anything (such as a   document or a phonograph record or a photograph) providing permanent evidence   of or information about past events | 1 |   | ?
ewn-07249395-n | recital | a detailed statement   giving facts and figures |   | 1 |  
ewn-06526084-n | chronicle, history,   account, story | a record or narrative   description of past events | 1 |   | ?
ewn-07236416-n | recital | a   detailed account or description of something | 1 |   |
