### ISSUE TITLE
Improve Validation and Add CI

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#310]
The validation scripts are currently incomplete.

The following features should be implemented:

* Symmetry constraints
* Non-closure of transitives
* Loop detection

This should then be checked on every pull by enabling GitHub Actions.

**Comment by jmccrae** [comment]
Fixed now

**Comment by arademaker** [comment]
Can you add link to the PR that closed it?

**Comment by jmccrae** [comment]
https://github.com/globalwordnet/english-wordnet/pull/312
