### ISSUE TITLE
split "voiced" adjective

### ISSUE THREAD

**Issue by dcillessen** [globalwordnet/english-wordnet#331]
In synset [ewn-02293817-a](https://en-word.net/lemma/voiced), "voiced" (adj) is defined as: "produced with vibration of the vocal cords - 'a frequently voiced opinion' 'voiced consonants such as 'b' and 'g' and 'z'".

Each example refers to a different meaning in "voiced".  In the first example, "voiced" is synonymous with "expressed". In the second example, "voiced" refers specifically to vocal cord vibration.  In the verb form of "[voice](https://en-word.net/lemma/voice)", similar meanings are differentiated in two different synsets: ewn-00935365-v and ewn-00954214-v.

Perhaps we could remove the first example from ewn-02293817-a, and add "voiced" to synset ewn-02291757-s "[expressed](https://en-word.net/lemma/expressed)"?

**Comment by arademaker** [comment]
I agree.
