### ISSUE TITLE
duplicated Americanize

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#336]
00409643-v Americanize, Americanise | americanizar
(become American in character; "After a year in Iowa, he has totally Americanized")

00410406-v Americanise, Americanize | americanizar
(make American in character; "The year in the US has completely Americanized him")

**Comment by vcvpaiva** [comment]
this is not a duplicate, one synset is to become American, the other is to turn someone/something into American.

**Comment by jmccrae** [comment]
I agree with @vcvpaiva. Shall we close?
