### ISSUE TITLE
suddenly - 3 senses ? 

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#34]
00171135-r on_the_spur_of_the_moment, suddenly
(on impulse; without premeditation; "he decided to go to Chicago on the spur of the moment"; "he made up his mind suddenly")

00061677-r of_a_sudden, all_of_a_sudden, suddenly 
(happening unexpectedly; "suddenly she felt a sharp pain in her side")

00061528-r short, suddenly, dead, abruptly 
(quickly and without warning; "he stopped suddenly")

**Comment by jmccrae** [comment]
Other dictionaries do not have more than one sense of 'suddenly' and EWN does not have more than one sense of 'sudden'. I support this merge

https://en.wiktionary.org/wiki/suddenly
https://www.lexico.com/definition/suddenly
https://en-word.net/lemma/sudden

**Comment by arademaker** [comment]
We need a list of 'gold' sources of references. What dictionaries we trust? But yes, I agree to merge these 3 synsets.

**Comment by jmccrae** [comment]
Good idea. Please discuss at #341
