### ISSUE TITLE
gloss of student

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#340]
ewn-10577282-n (Interlingual Index: i92752)
(n) scholarly person, scholar, student, bookman

> a learned person (especially in the humanities); someone who by long study has gained mastery in one or more disciplines

Do we need the restriction `especially in the humanities`?

**Comment by dcillessen** [comment]
I agree that we don't need to keep 
>(especially in the humanities)

in this definition. 

I'd like to also make the case that 1: "student" should be removed from this synset, and that 2: [ewn-09778642-n](https://en-word.net/lemma/schoolman) "schoolman, academician" should be merged with ewn-10577282-n. 

1: "student" seems to be more related more to a striving towards mastery than to an achievement of mastery, as in ewn-10685137-n (pupil, student, educatee), and in [student, n.1](https://www.oed.com/view/Entry/192056?rskey=qSfA2e&result=1&isAdvanced=false#eid) in the OED. Webster seems to define it more broadly as "scholar, learner, _especially_ one who attends school.  Nonetheless, Webster's definition also emphasizes the act of learning, as opposed to the state of mastery which is described in ewn-10577282-n

2: Currently, ewn-09778642-n is a hyponym of ewn-10577282-n.  ewn-09778642-n is defined as "a scholar who is skilled in academic disputation". This is essentially the same as our proposed definition of ewn-10577282-n, which is something like "a learned person, someone who by long study has gained mastery in one or more disciplines". 

It appears that the terms are different in that ewn-09778642-n is related to scholarship, while ewn-9778642 is related to "academy(s)." By adding ewn-09778642-n to ewn-10577282-n (as it is now), we would create a synset like "scholarly person, scholar, student, bookman, schoolman, academician" and could hold on to those relations from ewn-09778642-n.

What do you all think? also, should this be its own issue?

**Comment by jmccrae** [comment]
I think we can keep this as a single issue.

I agree with the merging 'scholar' with 'academician'. The 'schoolman' definition seems to come directly from Merriam-Webster:

https://www.merriam-webster.com/dictionary/schoolman

So perhaps this is a case of following MW too closely.

It is important that we keep 'scholar' and 'student' as synonyms as there are substitutions that seems synonymous, e.g., 'scholar of the classics'/'student of the classics' are pretty synonymous. But I see that this could be achieved by moving 'student' from this synset to another synset such as `ewn-10271476-n`

**Comment by dcillessen** [comment]
Fair point regarding phrases like 'scholar of the classics' and 'student of the classics.'  I'd agree with moving 'student' to ewn-10271476-n.  OED, WM, and AH all include some sense of 'scholar' as a 'student,' but as seperate definitions from the sense of 'scholar' as an expert in a certain field.   

https://www.oed.com/view/Entry/172481?rskey=MhZxFj&result=1&isAdvanced=false#eid
https://www.merriam-webster.com/dictionary/scholar
https://www.ahdictionary.com/word/search.html?q=scholar


Moving 'student' to ewn-10271467-n then better represents the two distinct definitions of 'scholar'.
