### ISSUE TITLE
List of 'gold' reference dictionaries

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#341]
Sometimes, sense distinctions can only be judged by referring to other dictionaries. We should maintain a list of dictionaries whose quality we trust and can refer to.

See also #243 and #141

**Comment by arademaker** [comment]
1. https://dictionary.cambridge.org/us/
2. https://www.collinsdictionary.com/dictionary/english
3. https://www.merriam-webster.com/
4. https://www.oed.com/ (closed?)

**Comment by dcillessen** [comment]
What about the American Heritage Dictionary of English?  https://www.ahdictionary.com/

**Comment by rwingerter55** [comment]
And wiktionary? https://en.wiktionary.org/

**Comment by rwingerter55** [comment]
In the context of issue #445 I looked up the definitions for "event" in the dictionaries named above. FWIW, here is the number of senses given in each source: 

source | Number   of senses
-- | --
https://www.merriam-webster.com/dictionary/event | 10
https://en.wiktionary.org/wiki/event#Noun | 9
https://www.ahdictionary.com/word/search.html?q=event | 5
https://dictionary.cambridge.org/dictionary/essential-british-english/event | 2
https://dictionary.cambridge.org/us/dictionary/english-german/event | 2
https://www.collinsdictionary.com/dictionary/english/event | 2

**Comment by rwingerter55** [comment]
FWIW, here is the coverage of EWN definitions for concepts containing the noun **show** in EWN compared to some well-known dictionaries (not counting obsolete and archaic senses).  

Source | no? | yes? | Total | Pct
-- | -- | -- | -- | --
Merriam-Webster | 9 | 7 | 16 | 44%
American Heritage | 11 | 5 | 16 | 31%
Wiktionary | 8 | 2 | 10 | 20%
EWN |   | 4 | 4 | 100%
Collins COBUILD | 2 | 2 | 4 | 50%
Cambridge Essential British   English | 2 |   | 2 | 0%
Total | 32 | 20 | 52 | 38%

Details see attachment.
[Definitions of show noun.xlsx](https://github.com/globalwordnet/english-wordnet/files/4712427/Definitions.of.show.noun.xlsx)

**Comment by rwingerter55** [comment]
http://www.ketlab.org.uk/roget.html is an interesting interface to Roget's Thesaurus. Type in any word to see a graphical representation of its concept neighbourhood.

**Comment by rwingerter55** [comment]
[Longman Dictionary of Contemporary English](https://www.ldoceonline.com/dictionary/)
including "Examples from the Corpus"

**Comment by rwingerter55** [comment]
https://www.macmillandictionary.com/
https://www.macmillanthesaurus.com/

**Comment by rwingerter55** [comment]
https://ludwig.guru/ 

> Ludwig is the first sentence search engine that helps you write better English by giving you contextualized examples taken from reliable sources.

Free 15-day trial.

**Comment by rwingerter55** [comment]
vocabulary.com uses Princeton WordNet, but adds example sentences, e.g. 
https://www.vocabulary.com/dictionary/group%20meeting

**Comment by rwingerter55** [comment]
Online OXFORD Collocation Dictionary, e.g. 
http://www.freecollocation.com/search1?word=meeting
