### ISSUE TITLE
duplicated synsets for Aram Khachaturian

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#342]
> (Russian composer (born in Armenia) whose works are romantic and reflect his interest in folk music (1903-1978))

Aram_Khachaturian • Khachaturian • Aram_Ilich_Khachaturian 

> (Armenian composer who incorporated oriental folk music (1903-1978))

Kachaturian • Aram_Kachaturian 

this was mentioned in #5

**Comment by jmccrae** [comment]
Duplicate of #66
