### ISSUE TITLE
Merge "Doubt" with "suspect"

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#36]
Two verb synsets are hypernyms but have very similar definitions

Doubt `ewn-00689424-v`
> lack confidence in or have doubts about;

Suspect, mistrust, distrust `ewn-00689827-v`
> regard as untrustworthy; regard with suspicion; have no faith or confidence in

**Comment by jmccrae** [comment]
I think these are sufficiently distinguished, but the examples need to be updated

**Comment by arademaker** [comment]
both examples from 00689424-v should be moved to 00689827-v. But I can't see how to distinguish them...
