### ISSUE TITLE
Merge "pop out" and "pop up"

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#40]
Highly similar definitions:

burst out, pop out `ewn-00427109-v`
> appear suddenly

crop up, pop, pop up `ewn-02161949-v`
> appear suddenly or unexpectedly

**Comment by arademaker** [comment]
one has a transitive frame the other has an intransitive frame.

**Comment by jmccrae** [comment]
Frames should also be fixed... I don't think any of these terms (or the defining word 'appear') are used transitively with this sense.

**Comment by jmccrae** [comment]
Pushing to 2021 as there is no agreement

**Comment by dcillessen** [comment]
I agree that the synsets should be merged.  In terms of the definition, I suppose you could say that they point to _slightly_ different methods of "appearing," but they are so similar that it doesn't warrant another synset, in my mind. 

Regarding transitivity, I agree with John that here these senses are not used transitively.
