### ISSUE TITLE
Merge "mulct" and "fine"

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#41]
Highly similar definitions:

mulct `ewn-02312392-v`
> impose a fine on

ticket, fine `ewn-02504365-v`
> issue a ticket or a fine to as a penalty

**Comment by vcvpaiva** [comment]
except that "mulct" is used so little that it doesn't even show up in the Google nGram viewer

https://books.google.com/ngrams/graph?content=mulct%2Cfine%2Cpenalty&year_start=1800&year_end=2000&corpus=15&smoothing=3&share=&direct_url=t1%3B%2Cmulct%3B%2Cc0%3B.t1%3B%2Cfine%3B%2Cc0%3B.t1%3B%2Cpenalty%3B%2Cc0#t1%3B%2Cmulct%3B%2Cc0%3B.t1%3B%2Cfine%3B%2Cc0%3B.t1%3B%2Cpenalty%3B%2Cc0
maybe "mulct" is used in law texts, but it seems to contaminate an otherwise fine synset if you add it to ticket, fine

**Comment by restinplace** [comment]
John E. McIntyre
The Baltimore Sun
The Latin word for a fine, mulcta, leapt into English as mulct (pronounced MULKT), with the same meaning. Transformed into a verb, mulct originally meant “to punish by levying a fine.” But the verb has taken on an unsavory tone, meaning “to extract by fraud,” “to obtain by duress or theft,” usually in reference to money.

Example: Thomas Frank, in “Lie Down for America” (Harper’s, April 2004): “Each of the three cases, like the larger scandals of Enron and WorldCom, involved a quasi-public utility whose leadership had taken long pulls from the bubbling bong of New Economy theory. At each one the bosses, always heralded as geniuses, had invented elaborate plans for freeing themselves from the humdrum of public service and setting out to mulct the world—and in each case these plans collapsed for all the usual, predictable reasons, while workers and customers screamed and mom and pop shareholders discovered they weren't going to retire in Hawaii after all.”

**Comment by jmccrae** [comment]
Frequency of usage is not a reason to distinguish synsets.

Most other dictionaries contain the entry for 'mulct'
https://www.merriam-webster.com/dictionary/mulct
https://en.wiktionary.org/wiki/mulct#Verb
https://www.lexico.com/definition/mulct
https://www.dictionary.com/browse/mulct?s=t

The meaning is to "punish" or "impose (a fine)".

In EWN, we have that the hypernym of 'fine', 'ticket' is 'book' ('record a charge in a police register'), so perhaps this synset is more narrow than the definition appears.

NB. The second sense of 'mulct' mentioned by @restinplace is already covered.

I propose the following changes

Update the definition of `ewn-02504365-v`: 'record a fine as a penalty in a police record'
Add lemma 'fine' to `ewn-02312392-v`

**Comment by arademaker** [comment]
I think the hierarchy of `ticket, fine ewn-02504365-v` is strange. 

ticket, fine < book < record < preserve

It makes more sense to me join both synsets into the mulct synset.

**Comment by jmccrae** [comment]
Pushing to 2021 as I am not sure there is agreement here yet.

**Comment by jmccrae** [comment]
Closed by #591
