### ISSUE TITLE
Hypernym links in adjectives

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#419]
Colloquial WordNet uses a hypernym model of adjectives rather than the satellite model of Princeton WordNet. IMHO this is far more sensible and satellites cause all kinds of problems; see #35 for a longer discussion. **BUT** for this release (2020) we should probably not have 20-odd adjectives that work differently to all the others. This issue will fix these to being `similar` like in Princeton, we can always go back to hypernyms later

Affected synsets

```
ewn-90000541-a
ewn-90000780-a
ewn-90000971-a
ewn-90000981-a
ewn-90001041-a
ewn-90001101-a
ewn-90001641-a
ewn-90001811-a
ewn-90003181-a
ewn-90005911-a
ewn-90008781-a
ewn-90010201-a
ewn-90010341-a
ewn-90010601-a
ewn-90010621-a
ewn-90011351-a
ewn-90013261-a
ewn-90013262-a
ewn-90014551-a
ewn-90016161-a
ewn-90017941-a
ewn-90018291-a
```

**Comment by 1313ou** [comment]
It looks better [now](http://treebolicwordnet.sourceforge.net/images/screenshot-smol.png). You cannot have a model for 99.9% of the data and another for .1%. For alternative models you have GermaNet and pointers by Sara Mendes.
