### ISSUE TITLE
English Prepositions missing.

### ISSUE THREAD

**Issue by LJOld** [globalwordnet/english-wordnet#434]
Roget's Thesaurus has a set of prepositions, in synsets, that could be added. Roget Category labels could be used as hypernyms. There may be good reasons why they are missing. For example their senses may have become conflated with the adverbs. The semantic overlap between prepositions and adverbs might be a can of worms, but in the first instance, Roget's sysets could included as a closed set.

**Comment by jmccrae** [comment]
If you could make this available in some form I can try to convert it into the form we use here

**Comment by LJOld** [comment]
> some form
Please specify your preference or I can just send a "|" delimited file.
Hypernym|RogetsSynSetID|Preposition

**Comment by jmccrae** [comment]
Yes, that would be suitable. Are there definitions available as well for these prepositions?

**Comment by LJOld** [comment]
Hi John

Sorry, I just realised the reason George never included prepositions. There
are no prepositions in in the open source (original) Roget's Thesaurus.
  *POS RT 1911*
pos pmeans poscnt
1 Nouns 57445
2 Verbs 32080
3 Adjectives 26422
4 Adverbs 5483
5 Phrases 3586
6 Interjections 737
I can still produce the prepositions from the 1962 3rd edition of Roget's
International (read, American) Thesaurus, (Ed. COS Mawsom), but because
that is still under American copyright you would have to modify the data to
incorporate it into WN. One way would be to treat it as a guide to the
number of synsets needed, those which are redundant Adverbial synsets in
WordNet, and which are the missing or essential entries.

Cheers,
John

*Roget 1962 synsets*
categnum categnam synset entry
22 Imitation 22:12:1 in imitation of
22 Imitation 22:12:1 after
22 Imitation 22:12:2 in duplicate
22 Imitation 22:12:2 in triplicate
26 Agreement 26:20:1 in agreement
26 Agreement 26:20:1 with
26 Agreement 26:20:1 right with
26 Agreement 26:20:1 in there with
26 Agreement 26:20:1 right along there with
26 Agreement 26:20:2 in line with
26 Agreement 26:20:2 in keeping with
26 Agreement 26:20:3 together
26 Agreement 26:20:3 together on
27 Disagreement 27:10:1 in disagreement with
27 Disagreement 27:10:1 in defiance of
27 Disagreement 27:10:1 in contempt of
27 Disagreement 27:10:1 in opposition to
27 Disagreement 27:10:2 at odds
27 Disagreement 27:10:2 at variance
27 Disagreement 27:10:2 at loggerheads
27 Disagreement 27:10:2 at sixes and sevens
27 Disagreement 27:10:3 out of line with
27 Disagreement 27:10:3 not in keeping with
36 Superiority 36:20:1 exceeding
36 Superiority 36:20:1 beyond
36 Superiority 36:20:1 over
36 Superiority 36:20:1 past
36 Superiority 36:20:1 more than
36 Superiority 36:20:1 in advance of
36 Superiority 36:20:1 over and above
36 Superiority 36:20:1 over the mark
36 Superiority 36:20:1 above the mark
36 Superiority 36:20:1 above par
36 Superiority 36:20:2 at the top of the scale
36 Superiority 36:20:2 at its height
42 Deduction 42:13:1 off
42 Deduction 42:13:1 away
42 Deduction 42:13:1 from
42 Deduction 42:14:1 minus
42 Deduction 42:14:1 less
42 Deduction 42:14:1 short of
42 Deduction 42:14:1 out
42 Deduction 42:14:1 without
42 Deduction 42:14:1 lacking
42 Deduction 42:14:1 leaving out
42 Deduction 42:14:1 excepting
44 Mixture 44:18:1 among
44 Mixture 44:18:1 amongst
44 Mixture 44:18:1 'mongst
44 Mixture 44:18:2 amid
44 Mixture 44:18:2 mid
44 Mixture 44:18:2 'mid
44 Mixture 44:18:2 amidst
44 Mixture 44:18:2 midst
44 Mixture 44:18:2 'midst
44 Mixture 44:18:2 in the midst of
44 Mixture 44:18:2 in the thick of
44 Mixture 44:18:3 with
44 Mixture 44:18:3 together with
80 Speciality 80:20:1 per
80 Speciality 80:20:1 for each
80 Speciality 80:20:2 per annum
80 Speciality 80:20:2 per diem
80 Speciality 80:20:2 per capita
117 Posteriority 117:7:1 after
117 Posteriority 117:7:1 subsequent to
117 Posteriority 117:7:1 later than
117 Posteriority 117:7:1 past
117 Posteriority 117:7:1 beyond
117 Posteriority 117:7:1 behind
121 Future 121:13:1 about to
121 Future 121:13:1 at the point of
121 Future 121:13:1 on the point of
121 Future 121:13:1 on the eve of
121 Future 121:13:1 on the brink of
121 Future 121:13:1 on the verge of
121 Future 121:13:1 near to
121 Future 121:13:1 close upon
121 Future 121:13:1 in the act of
148 Substitution 148:12:1 instead of
148 Substitution 148:12:1 in stead of
148 Substitution 148:12:1 in the stead of
148 Substitution 148:12:1 for
148 Substitution 148:12:1 in place of
148 Substitution 148:12:1 in the place of
148 Substitution 148:12:1 in the room of
148 Substitution 148:12:1 in behalf of
148 Substitution 148:12:1 in lieu of
148 Substitution 148:12:1 in its stead
148 Substitution 148:12:1 in its place
148 Substitution 148:12:2 in one's stead
148 Substitution 148:12:2 in one's behalf
148 Substitution 148:12:2 in one's place
148 Substitution 148:12:2 in one's shoes
148 Substitution 148:12:3 by proxy
148 Substitution 148:12:3 as proxy for
148 Substitution 148:12:3 as a substitute for
148 Substitution 148:12:3 as representing
148 Substitution 148:12:3 as an alternative
148 Substitution 148:12:4 vice
148 Substitution 148:12:5 in loco parentis
157 Impotence 157:20:1 beyond one
157 Impotence 157:20:1 beyond
157 Impotence 157:20:1 past
157 Impotence 157:20:1 beyond the ability
157 Impotence 157:20:1 beyond one's power
157 Impotence 157:20:1 beyond one's capacity
157 Impotence 157:20:1 beyond one's depth
157 Impotence 157:20:1 above one's head
157 Impotence 157:20:1 too much for
183 Location 183:28:1 at
183 Location 183:28:1 in
183 Location 183:28:1 on
183 Location 183:28:1 by
183 Location 183:28:1 near
183 Location 183:28:2 to
183 Location 183:28:2 toward
183 Location 183:28:3 from
183 Location 183:29:1 over
183 Location 183:29:1 here and there on
183 Location 183:29:1 here and there in
183 Location 183:29:1 roundabout
183 Location 183:29:1 through
183 Location 183:29:1 all through
183 Location 183:29:1 throughout
186 Absence 186:18:1 void of
186 Absence 186:18:1 without
198 Distance 198:20:1 to
198 Distance 198:20:1 as far as
198 Distance 198:21:1 beyond
198 Distance 198:21:1 yond
198 Distance 198:21:1 yonder
198 Distance 198:21:1 yonder of
198 Distance 198:21:2 past
198 Distance 198:21:2 over
198 Distance 198:21:2 across
198 Distance 198:21:3 farther
198 Distance 198:21:3 further
198 Distance 198:21:3 farther off
198 Distance 198:21:3 further away
198 Distance 198:22:1 out of reach
198 Distance 198:22:1 beyond reach
198 Distance 198:22:1 out of range
198 Distance 198:22:1 beyond the bounds
198 Distance 198:22:1 out of the way
198 Distance 198:22:1 out of the sphere of
198 Distance 198:22:2 out of sight
198 Distance 198:22:2 à perte de vue
198 Distance 198:22:2 a perte de vue
198 Distance 198:22:3 out of hearing
198 Distance 198:22:3 out of earshot
198 Distance 198:22:3 out of earreach
224 Interiority 224:17:1 in
224 Interiority 224:17:1 into
224 Interiority 224:17:2 within
224 Interiority 224:17:2 at
224 Interiority 224:17:2 inside
224 Interiority 224:17:2 inside of
224 Interiority 224:17:2 in the limits of
227 Covering 227:40:1 on
227 Covering 227:40:1 upon
227 Covering 227:40:1 o'er
227 Covering 227:40:1 over
227 Covering 227:40:1 above
227 Covering 227:40:1 on top of
236 Interposition 236:14:1 between
236 Interposition 236:14:1 atween
236 Interposition 236:14:1 betwixt
236 Interposition 236:14:1 'twixt
236 Interposition 236:14:1 atwixt
236 Interposition 236:14:1 betwixt and between
236 Interposition 236:14:2 among
236 Interposition 236:14:2 amongst
236 Interposition 236:14:2 'mongst
236 Interposition 236:14:3 amid
236 Interposition 236:14:3 amidst
236 Interposition 236:14:3 mid
236 Interposition 236:14:3 'mid
236 Interposition 236:14:3 midst
236 Interposition 236:14:3 'midst
236 Interposition 236:14:4 in the midst of
236 Interposition 236:14:4 in the thick of
241 Side 241:11:1 beside
241 Side 241:11:1 aside
241 Side 241:11:1 alongside
241 Side 241:11:1 abreast
241 Side 241:11:1 on one side
241 Side 241:11:1 on the side
241 Side 241:11:1 by
241 Side 241:11:1 along by
241 Side 241:11:1 by the side of
241 Side 241:11:1 along the side of
241 Side 241:11:1 sidelong
241 Side 241:11:2 fornent
241 Side 241:11:2 fernint
241 Side 241:11:2 fornenst
241 Side 241:11:2 ferninst
241 Side 241:11:3 near by
241 Side 241:11:3 in juxtaposition
241 Side 241:12:1 side by side
241 Side 241:12:1 tête à tête
241 Side 241:12:1 tete a tete
241 Side 241:12:1 tete-a-tete
241 Side 241:12:1 cheek to cheek
241 Side 241:12:1 cheek by cheek
241 Side 241:12:1 cheek by jowl
241 Side 241:12:1 shoulder to shoulder
241 Side 241:12:1 back to back
241 Side 241:12:1 yardarm to yardarm
289 Direction 289:29:1 through
289 Direction 289:29:1 by
289 Direction 289:29:1 by way of
289 Direction 289:29:1 by the way of
289 Direction 289:29:1 via
289 Direction 289:29:2 over
289 Direction 289:29:2 around
289 Direction 289:29:2 roundabout
289 Direction 289:29:2 here and there in
289 Direction 289:29:2 all through
477 Thought 477:23:1 on one's mind
477 Thought 477:23:1 on the brain
477 Thought 477:23:1 on one's chest
477 Thought 477:23:1 in one's craw
477 Thought 477:23:1 in the thoughts
477 Thought 477:23:2 in the heart
477 Thought 477:23:2 in petto
477 Thought 477:23:2 in one's inmost thoughts
547 Unintelligibility 547:22:1 beyond one's comprehension
547 Unintelligibility 547:22:1 beyond
547 Unintelligibility 547:22:1 past
547 Unintelligibility 547:22:1 above
547 Unintelligibility 547:22:2 over one's head
547 Unintelligibility 547:22:2 above one's bend
547 Unintelligibility 547:22:3 beyond one's depth
547 Unintelligibility 547:22:3 too deep for
653 Pursuit 653:12:1 after
653 Pursuit 653:12:1 in pursuit of
653 Pursuit 653:12:1 in pursuance of
653 Pursuit 653:12:1 in search of
653 Pursuit 653:12:1 out for
653 Pursuit 653:12:1 on the lookout for
653 Pursuit 653:12:1 in the market for
653 Pursuit 653:12:1 loaded for bear
653 Pursuit 653:12:1 out for bear
653 Pursuit 653:12:2 on the track
653 Pursuit 653:12:2 on the trail
653 Pursuit 653:12:2 on the scent
656 Means 656:8:1 by means of
656 Means 656:8:1 by the agency of
656 Means 656:8:1 through the instrumentality of
656 Means 656:8:1 by the aid of
656 Means 656:8:1 by use of
656 Means 656:8:1 by way of
656 Means 656:8:1 by dint of
656 Means 656:8:1 by the act of
656 Means 656:8:1 through the medium of
656 Means 656:8:1 by virtue of
656 Means 656:8:1 in virtue of
656 Means 656:8:1 at the hand of
656 Means 656:8:2 with
656 Means 656:8:2 herewith
656 Means 656:8:2 therewith
656 Means 656:8:2 wherewith
656 Means 656:8:2 wherewithal
656 Means 656:8:2 along with
656 Means 656:8:3 whereby
656 Means 656:8:3 thereby
656 Means 656:8:3 hereby
656 Means 656:8:4 through
656 Means 656:8:4 by
656 Means 656:8:4 per
656 Means 656:8:5 on
656 Means 656:8:5 upon
718 Preparation 718:25:1 in preparation for
718 Preparation 718:25:1 against
718 Preparation 718:25:1 for
718 Preparation 718:25:1 in order to
762 Subjection 762:16:1 under
762 Subjection 762:16:1 below
762 Subjection 762:16:1 beneath
762 Subjection 762:16:1 underneath
762 Subjection 762:16:1 subordinate to
762 Subjection 762:16:2 at the feet of
762 Subjection 762:16:3 under the heel of
779 Deputy, Agent 779:16:1 by proxy
779 Deputy, Agent 779:16:1 in behalf of
783 Aid 783:25:1 helped by
783 Aid 783:25:1 with the help of
783 Aid 783:25:1 with the assistance of
783 Aid 783:25:1 by the aid of
783 Aid 783:25:2 by means of
783 Aid 783:26:1 for
783 Aid 783:26:1 on behalf of
783 Aid 783:26:1 in behalf of
783 Aid 783:26:1 in the name of
783 Aid 783:26:1 on account of
783 Aid 783:26:1 on the part of
783 Aid 783:26:1 for the sake of
783 Aid 783:26:1 in the service of
783 Aid 783:26:1 in furtherance of
783 Aid 783:26:1 in favor of
783 Aid 783:27:1 behind
783 Aid 783:27:1 back of
783 Aid 783:27:1 supporting
783 Aid 783:27:1 in support of
806 Possession 806:14:1 with
806 Possession 806:14:1 having
806 Possession 806:14:1 to one's name
832 Securities 832:14:1 at the market price
832 Securities 832:14:1 at the market
832 Securities 832:14:2 at the opening price
832 Securities 832:14:2 at the opening
832 Securities 832:14:3 at a discount
832 Securities 832:14:3 out of favor
832 Securities 832:14:3 below par
832 Securities 832:14:4 above par
832 Securities 832:14:5 at par
832 Securities 832:14:5 at par value
832 Securities 832:14:5 at face value
962 Respect 962:13:1 in deference to
962 Respect 962:13:1 with due respect
962 Respect 962:13:1 with all respect
962 Respect 962:13:1 with all due respect to
962 Respect 962:13:1 with all due respect for
962 Respect 962:13:1 saving
962 Respect 962:13:1 excusing the liberty

**Comment by LJOld** [comment]
There are no glosses  or definitions in Roget's Thesaurus. Words' meanings
are known only from the company they keep.

**Comment by arademaker** [comment]
I remember one or two articles in previous GWC about this topic. I would suggest a literature review of the topic first.

**Comment by LJOld** [comment]
No thanks. I'm retired. Done enough research on the subject including a
doctorate. Just here to help with the data.
The main research question is, to me, "Why hasn't it been done before now?"
and the answer won't be in the literature.

**Comment by dcillessen** [comment]
I did some snooping around in literature as well as other WordNets.  I couldn't find any other wordnets  which featured prepositions from other languages. (I checked French, Italian, Spanish, and German.)

The question that LJOld asks though is an interesting one.  "Why hasn’t it been done before now?" 
I suspect that there are a couple reasons which have to do with how WN is structured as well as with how prepositions have typically been defined. 

Prepositions like "of" are fundamentally abstract. While we could put prepositions in as hyponyms of "simple preposition" or "complex preposition" in WN but this fails to capture their full meaning.  Perhaps we could use the categnum as a layer between this categorization and individual prepositions/prepositional phrases. For example, using "beside" between "simple preposition" and "beside" so the hierarchy is more developed. This, however, could lead to some confusion, so we would need to clearly denote that these new synsets denote a specific meaning, probably by labeling them just as we label the other parts of speech. 

I suppose that the difficulty is that fundamentally just about everything within WN is its own entity, but prepositions do more to serve the connections between entities in the formation of new meanings. For this reason, the Merriam-Webster definition of "of" has multiple entries.  The same issue of contextuality could be applied to adjectives and adverbs, but they are much more specific and definable.  

It also seems to me that many of these potential entries are compositional, especially if we can incorporate key words such as "by," "in," and "at." 

This is just from a cursory bit of research into the subject though. I'd love to hear other perspectives!

**Comment by jmccrae** [comment]
Moving to a more general discussion at #818

**Comment by arademaker** [comment]
I believe prepositions were already discussed in a paper presented in one GWC. If so, I would vote to include them.

**Comment by arademaker** [comment]
I would prefer to keep this issue open to discuss prepositions.
