### ISSUE TITLE
692 sense relation duplicates

### ISSUE THREAD

**Issue by 1313ou** [globalwordnet/english-wordnet#436]
It looks like the generator went into overkill mode (since RC): there are 692 sense relation duplicates. Some are consecutive, others are not. Complete list is attached.

[duplicates2020.txt](https://github.com/globalwordnet/english-wordnet/files/4501387/duplicates2020.txt)

**Comment by ekaf** [comment]
The EWN-2020 release has around 3000 duplicate lexical relations:  

   9 ! (antonyms: [Rel!.lex-3.1E20.NotUnique.txt](https://github.com/globalwordnet/english-wordnet/files/4874588/Rel.lex-3.1E20.NotUnique.txt))
 2416 + (derivations: [Rel+.lex-3.1E20.NotUnique.txt](https://github.com/globalwordnet/english-wordnet/files/4874589/Rel%2B.lex-3.1E20.NotUnique.txt))
  571 ^ (see also: [Rel^.lex-3.1E20.NotUnique.txt](https://github.com/globalwordnet/english-wordnet/files/4874590/Rel.lex-3.1E20.NotUnique.txt))

**Comment by jmccrae** [comment]
Seems to relate to this commit

https://github.com/globalwordnet/english-wordnet/commit/e2f2b705

**Comment by jmccrae** [comment]
This needs to be caught by the commit validator also

**Comment by jmccrae** [comment]
Seems to be fixed now
