### ISSUE TITLE
6 ambiguous sense keys

### ISSUE THREAD

**Issue by ekaf** [globalwordnet/english-wordnet#437]
In the 2020 release, 6 sense keys are ambiguous, i. e. they denote word senses from more than one synset, so they cannot be used as database keys.

For ex., in the XML format:

> Sense id="ewn-pond_cypress-n-80820791-01" synset="ewn-80820791-n" dc:identifier="pond_cypress%1:20:01::" 
> Sense id="ewn-pond_cypress-n-83131879-01" synset="ewn-83131879-n" dc:identifier="pond_cypress%1:20:01::" 

Here are the full details, checked with Prolog (so the synset offsets are prepended with a number between 1 and 4, denoting the pos):

> 6 ambiguous keys: [ (moon%1:17:02::,[109469560,109469752]), (pond_cypress%1:20:01::,[115447780,115449379]), (narrow-minded%3:00:00::,[300288589,302099456]), (full%5:00:01:whole:00,[300517008,300517988]), (rich%3:00:03::,[302032472,303167440]), (peer-to-peer%3:00:01::,[303168750,303168880])]

> moon%1:17:02:: in [109469560,109469752]
109469560 -> the natural satellite of the Earth; "the average distance to the Moon is 384,400 kilometers"; "men first stepped on the moon in 1969"
109469752 -> any object resembling a moon; "he made a moon lamp that he used as a night light"; "the clock had a moon that showed various phases"

> pond_cypress%1:20:01:: in [115447780,115449379]
115447780 -> wood of a deciduous conifer of the genus Taxodium, native to North America
115449379 -> a deciduous conifer of the genus Taxodium, native to North America

> narrow-minded%3:00:00:: in [300288589,302099456]
300288589 -> lacking tolerance or flexibility or breadth of view; "a brilliant but narrow-minded judge"; "narrow opinions"
302099456 -> rigidly adhering to a particular sect or its doctrines

> full%5:00:01:whole:00 in [300517008,300517988]
300517008 -> constituting the full quantity or extent; complete; "an entire town devastated by an earthquake"; "gave full attention"; "a total failure"
300517988 -> not separated into parts or shares; constituting an undivided unit; "an undivided interest in the property"; "a full share"

> rich%3:00:03:: in [302032472,303167440]
302032472 -> suggestive of or characterized by great expense; "a rich display"
303167440 -> causing indignation due to hypocrisy

> peer-to-peer%3:00:01:: in [303168750,303168880]
303168750 -> Of a social network of equal partners able to conduct business without using a middle man
303168880 -> Of a network of two or more computers connected as equal partners and able to share processing, control and access to data and peripherals

**Comment by jmccrae** [comment]
I will update this in the WNDB export of the 2020 release, but the change in the XML will have to wait until the 2021 release. I made a PR that fixes this and adds a validation check so it will never happen again.

**Comment by ekaf** [comment]
The WNDB export is ok now. However, some synset offsets have changed, so  it is really a new subversion:

April 16: 00518174 00 a 02 fractional 0 partial 2 ...
April 21: 00518167 00 a 02 fractional 0 partial 2 ...

In order to reference this synset adequately, it is desirable to be able to distinguish between the two versions (cf. issue #163 ).

Most projects use a minor version number for this purpose. Alternatively, a fuller timestamp could solve the problem, i. e. EWN-2020-0416 vs. EWN-2020-0421.
