### ISSUE TITLE
Antisymmetry breach in domain classification

### ISSUE THREAD

**Issue by ekaf** [globalwordnet/english-wordnet#439]
Hyponymy, meronymy and domain classification are asymmetric (meaning that when A is related to B,  the inverse is necessarily false): if A is a hyponym of B, B cannot be a hyponym of A. Antisymmetry is a weaker property, which forbids the inverse relationship, except in the case where A=B.

Testing the latest WNDB for asymmetry (with Prolog) allows to catch a domain classification loop, which was already present in earlier PWN versions:

Looping cls-t: 103115791-0 (a machine for performing calculations automatically)
           --> 106186735-0 (the branch of engineering science that studies (with the aid of computers) computable processes and structures)
Looping cls-t: 106186735-0 (the branch of engineering science that studies (with the aid of computers) computable processes and structures)
           --> 103115791-0 (a machine for performing calculations automatically)

In WordNet, the "computer science" domain classifies many items like "computer", while the inverse should not hold. Clearly, "computer" and "computer science" are not the same concept (A is not equal to B), so this case breaches both antisymmetry and asymmetry. 

Also, the recent WordNet versions only include the antonym pair "symmetric" vs. "asymmetric", but ignore the word "antisymmetry".

**Comment by ekaf** [comment]
To fix this loop, it is not immediately obvious which of the two symmetric links to remove. But 'computer' is just "a machine",
while the broader term is 'computer_science', since it also "studies processes and structures".

Currently, the topic domain classification for computer has three levels: computer_science > computer > plotter.
The hierarchy is not very well elaborated: for ex., unlike 'plotter', 'printer' (and some other hardware) is placed directly in
the 'computer_science' domain. So there are other problems here than just the loop.

However, for the moment, the top-most classification domain for everything computer-related, is clearly 'computer_science'. So, although other parts of this topic domain construction may be questionable as well, the way to quickly fix the classification loop is to remove the spurious link that makes 'computer_science' a subdomain of 'computer'.

**Comment by jmccrae** [comment]
Thanks @ekaf for the contribution. I have added a validation check so that this won't occur again!
