### ISSUE TITLE
Domains and their topConcepts

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#440]
I think it is great that the English Open WordNet includes domains or  "[semantic fields](http://www.sfs.uni-tuebingen.de/GermaNet/germanet_structure.shtml)" coded as dcterms:subject.

In a SKOS thesaurus the following concepts assigned to "noun.Tops" would be regarded as topConcepts of an existing more specific domain. It can be done both ways, but I would prefer the latter. 

ID | lemmas | definition | subject | more specific subject
-- | -- | -- | -- | --
ewn-00030657-n | act, deed, human action, human   activity | something that people   do or cause to happen@en | noun.Tops | noun.act
ewn-00015568-n | animal, animate being, beast,   brute, creature, fauna | a living organism   characterized by voluntary movement@en | noun.Tops | noun.animal
ewn-00022119-n | artifact, artefact | a man-made object   taken as a whole@en | noun.Tops | noun.artefact
ewn-00024444-n | attribute | an abstraction   belonging to or characteristic of an entity@en | noun.Tops | noun.attribute
ewn-00023451-n | cognition, knowledge, noesis | the psychological   result of perception and learning and reasoning@en | noun.Tops | noun.cognition
ewn-00033319-n | communication | something that is   communicated by or to or between people or groups@en | noun.Tops | noun.communication
ewn-00029677-n | event | something that happens   at a given place and time@en | noun.Tops | noun.event
ewn-00021445-n | food, nutrient | any substance that can   be metabolized by an animal to give energy and build tissue@en | noun.Tops | noun.food
ewn-00031563-n | group, grouping | any number of entities   (members) considered as a unit@en | noun.Tops | noun.group
ewn-00028950-n | infinite, space | the unlimited expanse   in which everything is located@en | noun.Tops | noun.location
ewn-00023953-n | motivation, motive, need | the psychological   feature that arouses an organism to action toward a desired goal; the reason   for the action; that which gives purpose and direction to behavior@en | noun.Tops | noun.motive
ewn-00019308-n | natural object | an object occurring   naturally; not made by man@en | noun.Tops | noun.object
ewn-00007846-n | individual, mortal, person,   somebody, someone, soul | a human being; person,   singular, assertive existential pronoun; pronoun, person, singular;   quantifier: assertive existential@en | noun.Tops | noun.person
ewn-00017402-n | flora, plant life, plant | (botany) a living   organism lacking the power of locomotion@en | noun.Tops | noun.plant
ewn-00029976-n | physical process, process | a sustained phenomenon   or one marked by gradual changes through a series of states@en | noun.Tops | noun.process
ewn-00033914-n | amount, measure, quantity | how much there is or   how many there are of something that you can quantify@en | noun.Tops | noun.quantity
ewn-00007347-n | causal agency, causal agent, cause | any entity that   produces an effect or is responsible for events or results@en | noun.Tops | noun.relation
ewn-00032220-n | relation | an abstraction   belonging to or characteristic of two entities or parts together@en | noun.Tops | noun.relation
ewn-00028005-n | form, shape | the spatial   arrangement of something as distinct from its substance@en | noun.Tops | noun.shape
ewn-00024900-n | state | the way something is   with respect to its main attributes@en | noun.Tops | noun.state
ewn-00021007-n | matter | that which has mass   and occupies space@en | noun.Tops | noun.substance
ewn-00028468-n | time | the continuum of   experience in which events pass from the future through the present to the   past@en | noun.Tops | noun.time

**Comment by jmccrae** [comment]
Just to clarify, the suggestion is to move these synsets from the domain `noun.Tops` to more specific domains?

**Comment by rwingerter55** [comment]
Yes, that's right. Thank you.

**Comment by rwingerter55** [comment]
Here is what the PWN documentation says about "noun.Tops".

- [**noun.Tops**](https://wordnet.princeton.edu/documentation/lexnames5wn):  "unique beginner for nouns".

- **[unique beginner](https://wordnet.princeton.edu/documentation/wngloss7wn)**: "A noun[!] synset with no superordinate". 

This would mean that "noun.Tops" should contain only nouns that have no superordinates (hypernyms). I think this definition is too narrow, actually it is only fulfilled by the concept "entity".

**Comment by jmccrae** [comment]
I think that this would create too much of a change from the schema established by Princeton WordNet and I don't see any advantages for this. As such, I suggest we close this issue with no changes
