### ISSUE TITLE
Add lime metadata 

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#441]
I loaded the data into [VocBench3](http://vocbench.uniroma2.it/), v. 7.0.0. In order to be able to find and display lexical concepts and lexical entries I had to add an instance of lime:Lexicon and connect it (lime:entry) with each lexical entry. I don't know if these lime metadata are obligatory, but VocBench3 seems to expect them.

**Comment by jmccrae** [comment]
Fixed (note these issues do not really affect this repo, the changes are in https://github.com/jmccrae/wordnet-angular)
