### ISSUE TITLE
Two concepts that share the same definition

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#443]
Two concepts that have are related as hypernym/hyponym and have the same definition. 

ID | lemmas | definition | subject
-- | -- | -- | --
ewn-00005787-n | benthos | organisms (plants and animals) that live at or near the bottom of a sea@en | noun.Tops
ewn-92419744-n | marine benthos | organisms (plants and animals) that live specifically at or near the bottom of a sea.@en | noun.Tops

**Comment by dcillessen** [comment]
The added specificity of "marine benthos" seems redundant both in the lemma and the definition.  But, since people seem to use "marine benthos" like in [this](https://biologica.ca/organisms-we-identify/marine-benthos/) article, I'd suggest we merge the synsets while keeping the definition from ewn-00005787-n.

**Comment by arademaker** [comment]
This is not in PWN 3.0 nor in 3.1. So it was introduced in English Wordnet somehow

**Comment by rwingerter55** [comment]
The [Wikipedia article](https://en.wikipedia.org/wiki/Benthos) would be a good source for links to other concepts in EWN, like coral, sea cucumber, sea star.

**Comment by rwingerter55** [comment]
I agree with @dcillessen that the synsets should be merged.

**Comment by Ciara97olo** [comment]
The definition for benthos ewn-00005787-n does not include freshwater lakes, rivers and streams in the definition which it should. Benthos are not specific to the sea. Marine benthos ewn-92419744-n are specific to the sea and should be kept as a separate entry and hyponym of benthos.
