### ISSUE TITLE
event wn:hypernym psychological feature 

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#444]
I don't think ewn-00029677-n is a "pschyological feature". 

ID | lemmas | definition | subject
-- | -- | -- | --
ewn-00023280-n | "psychological feature" | "a feature of the mental life of a living  organism"@en | "noun.Tops"
ewn-00029677-n | "event" | "something that happens at a given place and time"@en | "noun.Tops"

**Comment by jmccrae** [comment]
I would propose this as a better hypernym

`ewn-07298313-n` (Interlingual Index: i74970)
(n) happening, occurrence, occurrent, natural event 
> an event that happens

**Comment by rwingerter55** [comment]
@jmccrae, I think this is a misunderstanding. What we have now is:

![image](https://user-images.githubusercontent.com/62653433/82160133-7643f100-9893-11ea-84d1-9d47eec6d294.png)

**Comment by jmccrae** [comment]
I would propose to change the hypernym of 'event' to 'happening'. Is this not what you were suggesting?

**Comment by rwingerter55** [comment]
I was not sure how to solve it, that's why I didn't make a suggestion. Now I think the best solution would be to have 

`<ewn-00029677-n>` "event" `wn:hypernym` `<ewn-00002137-n>` "abstract entity, abstraction"

IMO your solution would not work. One reason is that `<ewn-07298313-n>` "**happening, natural event, occurrence, occurrent**" is a wn:hyponym* of `<ewn-00029677-n>` "event". The second reason is that not all "events" are "natural events". 

Here is a screenshot of the concept hierarchy in VocBench3:

![image](https://user-images.githubusercontent.com/62653433/82209686-f870fb80-990d-11ea-9367-a546f4f0a73d.png)

**Comment by jmccrae** [comment]
yeah, you're right... :)

The concept of 'natural event' could probably do with a better definition

I guess the solution is just to skip 'psychological feature' and map 'event' directly to 'abstract entity'
