### ISSUE TITLE
Missing hyponyms for "event"

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#445]
The hyponyms for ewn-00029677-n are rather incomplete. 

ID | lemmas | definition | subject
-- | -- | -- | --
ewn-00029677-n | "event" | "something that happens at a given place and   time"@en | "noun.Tops"

Check for example "group meeting" and its hyponyms. 

ID | lemmas | definition | subject
-- | -- | -- | --
ewn-08324519-n | meeting, group meeting | a formally arranged gathering@en | noun.group

Maybe many relevant concepts are missing because they are assigned to dcterms:subject "noun.group", not in dcterms:subject "event", as one might expect. Note that according to the [PWN documentation](https://wordnet.princeton.edu/documentation/lexnames5wn), "noun.event" was meant for "nouns denoting natural events".

**Comment by jmccrae** [comment]
The proposal would be to change the hypernym of `ewn-08324519-n` to `ewn-00029677-n`? 

Would this be instead of or as well as the current hypernym:

`ewn-07991473-n` (Interlingual Index: i79220)
(n) gathering, assemblage 
> a group of persons together in one place

**Comment by rwingerter55** [comment]
The hierarchy "event" > "assemblage, gathering" > "meeting, group meeting" looks fine to me. 

ID | lemmas | definition | subject
-- | -- | -- | --
<https://en-word.net/id/ewn-00029677-n> | event | something that happens at a given place and time@en | noun.Tops
<https://en-word.net/id/ewn-07991473-n> | assemblage, gathering | a group of persons together in one place@en | noun.group
<https://en-word.net/id/ewn-08324519-n> | meeting, group meeting | a formally arranged gathering@en | noun.group

But "meeting, group meeting" was only an example. We need to look for more hypernyms of "event", e.g. 

<ewn-08180691-n> "assembly"| a group of persons who are gathered together for a common purpose. 
IMO <ewn-08180691-n> | "assembly" is also an event (additional sense?) and so is its wn:hypernym "sabbat, witches' Sabbath":

<ewn-08415537-n> | "sabbat, witches' Sabbath" | "a midnight meeting of witches to practice witchcraft and sorcery [...]". 

I think in this area a real improvement requires more than changing two or three relations. 
If you like I can make a proposal.

**Comment by jmccrae** [comment]
Yes, please make a proposal :)

**Comment by rwingerter55** [comment]
I will :-)

**Comment by rwingerter55** [comment]
I haven't found a solution yet. Here is the current state of affairs. 

I felt that the definitions given in EWN where not a sufficient foundation for any changes. So I looked up definitions of event in the dictionaries mentioned in issue #341. 

SenseID | Definition | Example
-- | -- | --
American   Heritage 1 a | Something that takes place, especially a significant occurrence. |  
American   Heritage 1 b | A social gathering or   activity | The fundraising event   was held in the ballroom.
American Heritage   2 | Sports A contest in a sports competition, such as a meet: swimming events. |  
American Heritage   3 | Physics A phenomenon   or occurrence located at a single point in spacetime, regarded as the fundamental observational entity in relativity theory. |  
American Heritage   4 | Archaic A final result; an outcome. |  
Cambridge   essential-british-english 1 | something   that happens, especially something important or   strange | Local people have been   shocked by recent events in the town.
Cambridge   essential-british-english 2 | a race, party,   competition, etc. that has been organized for a particular time | They organize a lot of   social events.
Cambridge us   english-german 1 | something   that happens; an incident or occurrence | That night a terrible   event occurred.
Cambridge us   english-german 2 | an item in a programme   of sports etc | The long jump was to   be the third event of the competition.
Collins   1 | something   that happens, especially when it is unusual or   important. You can use events to describe all the things that are happening   in a particular situation. |  
Collins   2 | a   planned and organized occasion, for example a   social gathering or a sports match. |  
Merriam-Webster  1 a | something   that happens : occurrence |  
Merriam-Webster  1 b | a noteworthy happening |  
Merriam-Webster  1 c | a social occasion or   activity |  
Merriam-Webster  1 d | an adverse or damaging   medical occurrence | a heart attack or other cardiac event
Merriam-Webster  2 | any of the contests in   a program of sports |  
Merriam-Webster  3 a | a postulated outcome,   condition, or eventuality | in the event that I am not there, call the house
Merriam-Webster  3 b | the final outcome or   determination of a legal action |  
Merriam-Webster  3 c | archaic : outcome |  
Merriam-Webster  4 | the   fundamental entity of observed physical reality   represented by a point designated by three coordinates of place and one of   time in the space-time continuum postulated by the theory of relativity |  
Merriam-Webster  5 | a subset of the   possible outcomes of an experiment |  
wiktionary   1 | An occurrence; something that happens | - I went to an event   in San Francisco last week.     - Where will the event be held?
wiktionary   2 | A   prearranged social activity (function, etc.) |  
wiktionary   3 | One of several   contests that combine to make up a competition. |  
wiktionary   4 | An end result; an   outcome (now chiefly in phrases) | In the event, he   turned out to have what I needed anyway.
wiktionary   5 | (physics) A point in   spacetime having three spatial coordinates and one temporal coordinate. |  
wiktionary 6 | (computing) A possible   action that the user can perform that is monitored by an application or the   operating system (event listener). When an event occurs an event handler is   called which performs a specific task. |  
wiktionary   7 | (probability theory) A   set of some of the possible outcomes; a subset of the sample space. | […]
wiktionary   8 | (obsolete) An affair   in hand; business; enterprise. |  
wiktionary   9 | (medicine)   An episode of severe health conditions. |  

Clustering the 30 definitions I identified 11 senses, four of which are covered in EWN:

Domain or sense | instances | EWN
-- | -- | --
general | 7 | 1
organized activity | 5 | 0
sports | 4 | 0
relativity theory | 3 | 1
consequence | 3 | 1
probability theory | 2 | 0
medicine | 2 | 0
affair | 1 | 0
condition | 1 | 1
legal | 1 | 0
computing | 1 | 0
Total | 30 | 4

Next I will check if a concept for "organized activity" needs to be added to EWN and where it would fit in.
