### ISSUE TITLE
"organism" as hyponym of "causal_agent"

### ISSUE THREAD

**Issue by dkasak** [globalwordnet/english-wordnet#446]
Should "organism" be a hyponym of "causal_agent"? To me, the gloss for "causal_agent" suggests it should: 

> any entity that produces an effect or is responsible for events or results.

I encountered this when I realized that "animal" wasn't a causal agent, but "person, individual, someone, ..." is, which seemed odd. In general, the hyponyms of "causal_agent" seem like an odd bunch so I probably wouldn't give it much thought if "person" wasn't a hyponym.

Is there an underlying logic to this that I'm missing?

**Comment by jmccrae** [comment]
The suggestion here would be to make organism the hyponym of causal agent?

Thus, from:

```
person  --->  causal_agent
        \-->  organism
```

To:

```
person ---> organism ---> causal_agent
```

**Comment by dkasak** [comment]
I think that may be a good pragmatic improvement, yes. Some further discussion below.

My primary concern is that the set of synsets from which causal agent can be reached (via the hypernym relation) is very restrictive, given how general the term "causal agent" is. For instance, it seems to me that animals should definitely be (transitively) considered causal agents. The above approach would achieve this.

I refrained from making a practical suggestion since I'm not very familiar with the logic behind the current structure and, additionally, there may be yet more things which should be considered causal agents, so I wanted to hear some opinions first.

Another thing that came to mind: what about mythical or supernatural beings, like centaurs or vampires? Are those also missing here or are they not considered causal agents because they are imaginary?

**Comment by jmccrae** [comment]
The top-level hierarchy is quite inconsistent, there have been some proposals to fix this, e.g. 

https://www.w3.org/2001/sw/BestPractices/WNET/SweeteningWN.pdf

But, I am not sure how (if) we should approach this in this project.

Issue #187 is very closely related.

**Comment by dkasak** [comment]
Thanks for the interesting read. As I suspected, this is a can of worms.

Instead of dealing with the whole thing now, what do you think of the more limited change of making organism a hyponym of causal agent as you illustrated above? While probably not perfect, to me it looks like it makes a lot of sense.

**Comment by arademaker** [comment]
Indeed, there are problems to fix in the top-level hierarchy. But I suspect that first, we need to improve our way to deal with suggestions (too many issues in my inbox) and data visualization to check the data and formulate the hypothesis. We are mostly depending on @jmccrae to change files and almost always depending on a limited view of the data provided by the current web interface. Maybe we need starting to discuss how to improve the infrastructure of the project?

**Comment by rwingerter55** [comment]
@dkasak, note that "entity" is the top concept of EWN. If we take the definition of "causal agent" literally, every single concept in EWN can be a causal agent. 

ewn-00001740-n | entity | that which is perceived or known or inferred to have its own distinct existence (living or nonliving)

**Comment by rwingerter55** [comment]
@arademaker, I like the web interface, but I think you raise an important point. 

I have [VocBench3](http://vocbench.uniroma2.it/) and GraphDB (free version) installed on my notebook. This way I can explore EWN in the UI or with SPARQL. Both tools can also be run on a server for access with a browser ...

**Comment by jmccrae** [comment]
@arademaker, Infrastructure improvements are a top priority. You can already check out the YAML format suggestion on #31. Visualization and editing tools are also under development as well as better guidelines for making changes.

For definitions with 'or', I agree, but this should be a distinct issue.

Adding 'physical' to the definition of 'casual_agent' would be difficult given the non-physical hyponyms it has such as 'cause_of_death' and 'danger'

**Comment by dcillessen** [comment]
I'm with John regarding adding "physical" to the definition of "causal agent." Non-physical entities can be causal agents.

Perhaps it would be useful for us to set an ontological direction, or source, in WN? The organization proposed in the article John shared earlier would provide more structure and clarity than what we have now, I think. (https://www.w3.org/2001/sw/BestPractices/WNET/SweeteningWN.pdf) 

I would argue though that setting a singular ontological direction quashes the emergent characteristics of WN. As an open-source project, we are continually attempting to represent the multitude of underlying ontological-linguistic characteristics of English, which can't be easily pinned down to any particular ontology. Furthermore, we're creating a lexical network so it seems important to consider linguistic characteristics above ontological ones. 

In this particular instance, I think that the proposed change to a more linear hierarchy makes the most sense. 

> person ---> organism ---> causal_agent
