### ISSUE TITLE
"group action" has no hypernym 

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#447]
Well, this is an easy one. 

ID | lemmas | definition | subject
-- | -- | -- | --
<https://en-word.net/id/ewn-01082290-n> | "group action" | "action taken by a group of people"@en | "noun.act"

Should be linked to: 

ID | lemmas | definition | subject
-- | -- | -- | --
<https://en-word.net/id/ewn-00038116-n> | "action" | "something done (usually as opposed to something said)"@en | "noun.act"

**Comment by jmccrae** [comment]
Could you edit this issue to provide more description?

**Comment by rwingerter55** [comment]
Sorry, inadvertently sent.

**Comment by jmccrae** [comment]
thanks for the edit!

**Comment by rwingerter55** [comment]
FWIW, I discovered this and 12 other concepts which have no hypernyms (see following issues) with a simple SPARQL query.

**Comment by 1313ou** [comment]
If you use the yet-to-be-announced **MySql or Sqlite form of EWN**, you  can also use a 'simple' SQL query:

```
SELECT count(*) FROM synsets
LEFT JOIN semlinks ON synsetid = synset1id AND linkid IN (1,3)
WHERE pos = 'n' AND lexdomainid <> 3 AND synset1id IS NULL; 
```
which yields 48 and where _linkid IN (1,3)_ selects hypernym and instance hypernym, and  _lexdomainid <> 3_ rules out top nouns.

If you want the details it goes like this:

```
SELECT synsetid, GROUP_CONCAT(lemma), definition, GROUP_CONCAT(lemma)
FROM synsets
INNER JOIN senses USING (synsetid)
INNER JOIN words USING (wordid)
WHERE synsetid IN
(
SELECT synsetid 
FROM synsets LEFT JOIN semlinks ON synsetid = synset1id AND linkid IN (1,3)
WHERE pos = 'n' AND lexdomainid <> 3 AND synset1id IS NULL
)
GROUP BY synsetid; 

```
Result is here:
[hypernymless-csv.txt](https://github.com/globalwordnet/english-wordnet/files/4637880/hypernymless-csv.txt)

**Comment by 1313ou** [comment]
Peek preview of databases mentioned above (subject to change):

https://github.com/x-englishwordnet/sqlite
https://github.com/x-englishwordnet/mysql

**Comment by rwingerter55** [comment]
@1313ou, thank you very much! I will check it out ...

**Comment by rwingerter55** [comment]
@1313ou, my query excluded concepts that don't have a hyponym either. Dealing with these "orphans" might be my next task.
