### ISSUE TITLE
"limestone" has no hypernym

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#449]
... and should be linked to "stone, rock".

ID | lemmas | definition | subject
-- | -- | -- | --
<https://en-word.net/id/ewn-14960364-n> | "limestone" | "a sedimentary rock consisting mainly of calcium that was deposited by the remains of marine animals"@en | "noun.substance"
<https://en-word.net/id/ewn-09438954-n> | "stone, rock" | "a lump or mass of hard consolidated mineral matter"@en | "noun.object"

**Comment by arademaker** [comment]
We have recently proposed a revision of the terms of rocks in http://arademaker.github.io/bibliography/lrec-MMWN-2020.html.

**Comment by rwingerter55** [comment]
@arademaker, thank you for the link. 

From what I understand, the link should be: 
`ewn-14960364-n wn:hypernym ewn-14720954-n`

Is that correct?

ID | lemmas | definition | subject
-- | -- | -- | --
<https://en-word.net/id/ewn-09438954-n> | "stone, rock" | "a lump or mass of hard consolidated mineral matter"@en | "noun.object"
<https://en-word.net/id/ewn-14720954-n> | "stone, rock" | "material consisting of the aggregate of minerals like those making up the Earth's crust"@en | "noun.substance"
