### ISSUE TITLE
"pike" <ewn-03941726-n> has no hypernym

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#451]
... and should be linked to "spear, lance, shaft". 

Cf. definition of "pike" in Merriam Webster

**pike** noun (4)
: a heavy spear with a very long shaft used by infantry especially in Europe from the Middle Ages to the 18th century

ID | lemmas | definition | subject
-- | -- | -- | --
<https://en-word.net/id/ewn-03941726-n> | "pike" | "medieval weapon consisting of a spearhead attached to a long pole or pikestaff; superseded by the bayonet"@en | "noun.artifact"
<https://en-word.net/id/ewn-04278001-n> | "spear, lance, shaft" | "a long pointed rod used as a tool or weapon"@en | "noun.artifact"

**Comment by jmccrae** [comment]
This is covered by #608 and is already fixed.
