### ISSUE TITLE
"automatic rifle" has no hypernym

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#452]
... and should be linked to "´machine gun" and "rifle". 

ID | lemmas | definition | subject
-- | -- | -- | --
<https://en-word.net/id/ewn-02763860-n> | "automatic, automatic rifle, machine rifle" | "light machine gun"@en | "noun.artifact"
<https://en-word.net/id/ewn-03706725-n> | "machine gun" | "a rapidly firing automatic gun (often mounted)"@en | "noun.artifact"
<https://en-word.net/id/ewn-04097375-n> | "rifle" | "a shoulder firearm with a long barrel and a rifled bore"@en | "noun.artifact"

**Comment by jmccrae** [comment]
PR also adds a new improved definition of this concept
