### ISSUE TITLE
"music genre" has no hypernym

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#453]
... and IMO should be linked to "genre". 

Definition of genre ([Merriam Webster](https://www.merriam-webster.com/dictionary/genre))
1: a category of artistic, musical, or literary composition characterized by a particular style, form, or content

ID | lemmas | definition | subject
-- | -- | -- | --
<https://en-word.net/id/ewn-05853859-n> | "genre" | "a kind of literary or artistic work"@en | "noun.cognition"
<https://en-word.net/id/ewn-07085982-n> | "genre, music genre, musical genre, musical style" | "an expressive style of music"@en | "noun.communication"

**Comment by jmccrae** [comment]
One slight issue is that this would make 'genre' a hypernym of 'genre'. 

I made a PR that also removes 'genre' from the synset... following this principle that reference by hypernym is also possible

**Comment by jmccrae** [comment]
See #237
