### ISSUE TITLE
"Native American" has no hypernym

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#454]
There are two hypernym candidates, but which one to choose? IMO ewn-09757749-n would be appropriate. 

ID | lemmas | definition | subject
-- | -- | -- | --
<https://en-word.net/id/ewn-09757749-n> | "American" | "a native or inhabitant of a North American or Central American or South American country"@en | "noun.person"
<https://en-word.net/id/ewn-09758057-n> | "American" | "a native or inhabitant of the United States"@en | "noun.person"
<https://en-word.net/id/ewn-09664887-n> | "Native American, Amerindian" | "any member of the peoples living in North or South America before the Europeans arrived"@en | "noun.person"

**Comment by jmccrae** [comment]
I would say the first one:

"a native or inhabitant of a North American or Central American or South American country"@en

**Comment by rwingerter55** [comment]
Me too ;-)
