### ISSUE TITLE
"article of commerce" has no hypernym

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#459]
... and should be linked to ewn-00023083-n. 

ID | lemmas | definition | subject
-- | -- | -- | --
<https://en-word.net/id/ewn-00023083-n> | "article" | "one of a class of artifacts"@en | "noun.Tops"
<https://en-word.net/id/ewn-02748096-n> | "article of commerce" | "an article that is offered for sale"@en | "noun.artifact"

BTW, "article of commerce" has one hyponym ("tinware"), while it could have thousands. However, IMO adding more hyponyms doesn't make sense. 

The following table lists some closely related concepts. Which of them should be linked?

c1 | subject | c1Lemmas | definition
-- | -- | -- | --
<https://en-word.net/id/ewn-00023083-n> | "noun.Tops" | "article" | "one of a class of artifacts"@en
<https://en-word.net/id/ewn-02748096-n> | "noun.artifact" | "article of commerce" | "an article that is offered for sale"@en
<https://en-word.net/id/ewn-03080712-n> | "noun.artifact" | "commodity, good, trade good" | "articles of commerce; elaborately crafted"@en
<https://en-word.net/id/ewn-03754377-n> | "noun.artifact" | "product, merchandise, ware" | "commodities offered for sale"@en
<https://en-word.net/id/ewn-04558126-n> | "noun.artifact" | "ware" | "articles of the same kind or material; usually used in combination: `silverware', `software'"@en

**Comment by jmccrae** [comment]
I would even suggest merging this synset with:

`ewn-04558126-n` (Interlingual Index: i60950)
(n) ware 
> articles of the same kind or material; usually used in combination: `silverware', `software'

**Comment by rwingerter55** [comment]
I agree.

**Comment by rwingerter55** [comment]
Note that currently there is no link from ware `ewn-04558126-n` to neither `ewn-03754377-n` nor `ewn-03080712-n`. What do you suggest?

**Comment by jmccrae** [comment]
I think I would suggest adding, `03080712-n` as a hypernym of `04558126-n` and using a similar link to `03754377-n`

**Comment by rwingerter55** [comment]
Let's go step by step. 

The table below contains the concepts we are discussing. It reflects the existing hyponomy relations, with one exception: I added a `wn:hypernym` link from `ewn-02748096-n` to both `ewn-00023083-n` and `ewn-04558126-n`. 

ID | lemmas | definition | subject
-- | -- | -- | --
ewn-00022119-n | artefact | a man-made object taken as a   whole@en | noun.Tops
ewn-00023083-n | . article | one of a class   of artifacts@en | noun.artifact
ewn-02748096-n | . . article of commerce | an article that is   offered for sale@en | noun.artifact
ewn-04558126-n | . ware | articles of the same   kind or material; usually used in combination: `silverware', `software'@en | noun.artifact
ewn-03080712-n | . commodity, good, trade good | articles of commerce;   elaborately crafted@en | noun.artifact
ewn-03754377-n | . . product,   merchandise, ware | commodities   offered for sale@en | noun.artifact

I also considered merging `ewn-02748096-n` and `ewn-03080712-n` (cf. definitions!). Both are "articles of commerce", but commodities are also "elaborately crafted", i.e. more specific in that respect. I think I will check dictionary definitions of  "commodity". 

When I wrote "Note that currently there is no link from ware `ewn-04558126-`n to neither `ewn-03754377-n` nor `ewn-03080712-n`" I was not aware that `ewn-04558126-`n and  `ewn-03080712-n` are on the same hierarchical level, co-hyponyms of "artefact". 

About your suggestions:

1. Merge synsets `ewn-00023083-n` (article) and `ewn-04558126-n` (ware)?
The two concepts are on the same hierarchical level, but judging from the definition "article" is more general. I am not convinced this would be an improvement. 

2. Add `03080712-n` as a hypernym of `04558126-n`? 
Initially I quite liked the idea. But judging from the definitions there is no clear subsumption relation between the two concepts  ("articles of the same kind or material" vs. "articles of commerce, elaborately crafted"). So I am not convinced this would be an improvement. 

3. Add a similar link from `03080712-n` to `03754377-n`"?
Not necessary, the first is a hyponym of the latter.

**Comment by Ciara97olo** [comment]
There is a distinction between ewn-03080712-n and 03754377-n which is not exemplified by the definitions. 
ewn-03080712 usually is defined as a raw material bought and sold in bulk to other companies such as coffee or wood. 
ewn-03754377-n relates to articles that will be bought by an individual consumer.
