### ISSUE TITLE
Merge senses of doubt

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#46]
Highly similar definitions:

doubt `ewn-00689424-v`
> lack confidence in or have doubts about

doubt `ewn-00689196-v`
> consider unlikely or have doubts about

**Comment by jmccrae** [comment]
I propose removing "or have doubts about" from both definitions to clarify the distinction, which is also made by other dictionaries:

https://www.merriam-webster.com/dictionary/doubt

**Comment by arademaker** [comment]
to late to vote ... @jmccrae has already decided by himself. But I agree anyway! ;-)
