### ISSUE TITLE
music <ewn-07034009> has duplicated content (Domains topic / Members topic)

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#466]
The concept `<ewn-07034009-n>` "music" seems to have duplicated content in "Domains (topic)" and "Members (topic)". Please check and correct. 

![image](https://user-images.githubusercontent.com/62653433/82182293-538df880-98e4-11ea-820d-5d7f5b284590.png)

**Comment by jmccrae** [comment]
This is a UI bug. Closing here and opening an issue in the UI project:

https://github.com/jmccrae/wordnet-angular/issues/7

**Comment by jmccrae** [comment]
Fixed and redeployed

**Comment by rwingerter55** [comment]
Great, thank you. That was quick!
