### ISSUE TITLE
The entry for 'hero' is unnecessarily gendered 10325013-n

### ISSUE THREAD

**Issue by fcbond** [globalwordnet/english-wordnet#468]
hero: a man distinguished by exceptional courage and nobility and strength "RAF pilots were the heroes of the Battle of Britain" 10325013-n

change to:
a person distinguished by exceptional courage and nobility and strength

**Comment by udnaan** [comment]
Isn't there a gender specific word for a person with exceptional courage aka `heroine`?

Wouldn't changing `hero` to be a non-gendered word break the symmetry?

**Comment by rwingerter55** [comment]
@udnaan, I checked the definitions of "hero" and "heroine" in various dictionaries (American Heritage, Merriam-Webster, Collins). It seems to be common practice to define "hero" gender neutrally as "a person ..." and "heroine" as "a woman ....", e.g. 

https://www.ahdictionary.com/word/search.html?q=hero
https://www.ahdictionary.com/word/search.html?q=heroine

**Comment by arademaker** [comment]
but we may have many other similar situations here. For `hero` we have 8 senses. The only two with a female counterpart are:

a. `a man distinguished by exceptional courage and nobility and strength` is hyponym of `leader = a person who rules or guides or inspires others` (gender neutral).  
b. `the principal character in a play or movie or novel or poem` hyponym of `character = an actor's portrayal of someone in a play` (gender neutral).

The counterparts are the senses of `heroine`:

1. `a woman possessing heroic qualities or a woman who has performed heroic deeds` hyponym of `woman (an adult female person)`.
2. the main good female character in a work of fiction hyponym of `character`.

So why `hero/a` is a kind of leader and `heroine/1` is only a kind of woman?

**Comment by rwingerter55** [comment]
@arademaker, the proposal is to change the definition of 'hero', not to merge both synsets. What is your worry?

**Comment by udnaan** [comment]
Being similar to other dictionaries wasn't my concern. I was thinking more in terms of having a synset for each gender variation for person + heroic.

However, looking at the hypernyms, hero already is defined as a type of a leader rather than a person, which makes the point moot.

Perhaps it should be moved to be a hyponym of person rather than a leader.

**Comment by jmccrae** [comment]
This project should reflect English usage. A quick Google search for "she's a hero" shows that "hero" is very frequently used in a gender-neutral manner, while "she's a heroine" is much more uncommon.

The question of whether we should have an explicitly male 'hero' is harder. According to the [contribution guidelines](https://github.com/globalwordnet/english-wordnet/blob/master/NEW_SYNSETS.md), we would need 'significance' and 'distinction'. That is we would need a collocate that clearly distinguishes this sense and occurs with some frequency. I can't think of one at the moment...

**Comment by udnaan** [comment]
Fair enough. Thanks for at least considering the idea and clarifying the criterion. Cheers!

**Comment by arademaker** [comment]
> @arademaker, the proposal is to change the definition of 'hero', not to merge both synsets. What is your worry?

losing symmetry.

**Comment by jmccrae** [comment]
Closed by #571
