### ISSUE TITLE
How to link 'hero' and 'heroine'?

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#469]
There is currently no path, neither between the concepts nor between the lemmas. 
Is there an appropriate conceptual or lexical relationship?

**Comment by jmccrae** [comment]
We could use `similar`?

**Comment by rwingerter55** [comment]
As a last resort. 

FWIW, here is a frequency count of relation types used.


p | label | count | pc
-- | -- | -- | --
wn:also | Also@en | 3.879 | 1,2%
wn:antonym | Antonym@en | 7.994 | 2,5%
wn:attribute | Attribute@en | 1.278 | 0,4%
wn:derivation | Derivation@en | 74.781 | 23,3%
wn:domain_region | Domain region@en | 1.512 | 0,5%
wn:hypernym | Hypernym@en | 91.454 | 28,5%
wn:hyponym | Hyponym@en | 91.454 | 28,5%
wn:instance_hypernym | Instance hypernym@en | 8.589 | 2,7%
wn:instance_hyponym | Instance hyponym@en | 8.589 | 2,7%
wn:participle | Participle@en | 73 | 0,0%
wn:pertainym | Pertainym@en | 8.070 | 2,5%
wn:similar | Similar@en | 23.214 | 7,2%
  |   | 320.887 | 100%

Unused relation types:


p | label
-- | --
wn:action | Action@en
wn:agent | Agent@en
wn:beneficiary | Beneficiary@en
wn:cause | Cause@en
wn:creator | Creator@en
wn:domain | Domain@en
wn:domain_category | Domain category@en
wn:domain_member_category | Domain member category@en
wn:domain_member_region | Domain member region@en
wn:domain_member_usage | Domain member usage@en
wn:domain_usage | Domain usage@en
wn:entail | Entail@en
wn:experiencer | Experiencer@en
wn:goal | Goal@en
wn:instrument | Instrument@en
wn:location | Location@en
wn:member | Member@en
wn:member_holonym | Member holonym@en
wn:member_meronym | Member meronym@en
wn:part_holonym | Part holonym@en
wn:part_meronym | Part meronym@en
wn:patient | Patient@en
wn:product | Product@en
wn:result | Result@en
wn:substance_holonym | Substance holonym@en
wn:substance_meronym | Substance meronym@en
wn:theme | Theme@en
wn:verb_group | Verb group@en

**Comment by rwingerter55** [comment]
I think I have seen meronym relations and domain_topic. Perhaps something wrong with my query?

```
SELECT DISTINCT ?p ?label (COUNT(?s) as ?count) WHERE {
    ?p rdfs:subPropertyOf wn:link  .
    OPTIONAL {?p rdfs:label ?label . }
    OPTIONAL { ?s ?p ?o . }
} GROUP BY ?p ?label
ORDER BY ?label

```

**Comment by jmccrae** [comment]
@rwingerter55 I think the subProperty doesn't see transitivity:

wn:meronym_part --rdfs:subPropertyOf--> wn:meronym --rdfs:subPropertyOf--> wn:link

**Comment by rwingerter55** [comment]
The relation types are not nested. 

```
   <rdf:Description rdf:about="http://wordnet-rdf.princeton.edu/ontology#part_meronym">
       <rdfs:label xml:lang="en">Part meronym</rdfs:label>
       <rdf:type rdf:resource="http://www.w3.org/2002/07/owl#TransitiveProperty"/>
       <rdfs:subPropertyOf rdf:resource="http://wordnet-rdf.princeton.edu/ontology#link"/>
   </rdf:Description>
```

**Comment by rwingerter55** [comment]
Back to the original issue. A relation type "male_female" would be useful for humans and animals. It is used for example in the German CISLEX lexicon (LMU München). 

Literature:

    Langer, Stefan, Petra Maier, Jürgen Oesterle (1996). CISLEX - An Electronic Dictionary for German. Its Structure and a Lexicographic Application. Proceedings of COMPLEX '96.

    Langer, Stefan (1996). Selektionsklassen und Hyponymie im Lexikon. Semantische Klassifizierung von Nomina für das elektronische Wörterbuch CISLEX. Dissertation Universität München. CIS-Bericht.

**Comment by rwingerter55** [comment]
> We could use `similar`?

According to [PWN documentation](https://wordnet.princeton.edu/documentation/wninput5wn), `Similar to` is meant to be used with adjectives only.

**Comment by jmccrae** [comment]
Yes, you are right. We use `also` for generic relations between nouns

**Comment by arademaker** [comment]
related to #468
