### ISSUE TITLE
Definition of 'Caucasian' ewn-09660255-n

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#470]
ewn-09660255-n (Interlingual Index: i87277)
(n) White, White person, Caucasian 
definition: a Caucasian

Cf. [Wiktionary](https://en.wiktionary.org/wiki/Caucasian)

1. Of, or relating to the Caucasus region or its people, languages and culture.
2. (anthropology) Of a racial classification; pertaining to people having certain phenotypical features such as straight, wavy or curly hair and very light to brown pigmented skin, and originating from Europe, parts of Northern Africa and Western, Central and South Asia.
Synonyms: Caucasoid, Europid
3. (US, of a person) White, being a white person.

**Comment by jmccrae** [comment]
It is also odd that this entry capitalizes "white"

**Comment by rwingerter55** [comment]
Re: White cf. Wiktionary:

https://en.wiktionary.org/wiki/White

Adjective
White (not comparable)
Alternative letter-case form of white (of or relating to Europeans or Caucasians)

Would that justify 'White person'?

**Comment by jmccrae** [comment]
It seems that it is generally not preferred to capitalize 'white' but that capitalizing it is not wrong:

https://www.diversitystyleguide.com/glossary/white-white/

**Comment by Ciara97olo** [comment]
The other ethnicities in the dictionary are also capitalized, so I think we should keep it capitalized so it is consistent

**Comment by Ciara97olo** [comment]
Other ethnicities and races such as Black, Latino, Asian, etc., are all capitalized. So I think "White" should be left capitalized to keep consistency.
