### ISSUE TITLE
Some relation types not in ontology

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#472]
In https://github.com/globalwordnet/english-wordnet/issues/469#issuecomment-630775660 I listed the relation types used in EWN, but the list was incomplete. Here is the complete list (23 relation types) as retrieved from the data (data relation type, label, count). The column 'ontology relation type' which I added manually maps the relation to the [WordNet RDF Ontology](http://wordnet-rdf.princeton.edu/ontology). The last column contains a confidence score for the mapping. 

The mapping should be checked and empty cells filled. Finally the database should be corrected. 

data relation type | label | count | ontology relation type | confidence
-- | -- | -- | -- | --
wn:hyponym | Hyponym@en | 91.454 | wn:hyponym | 1
wn:hypernym | Hypernym@en | 91.454 | wn:hypernym | 1
wn:similar | Similar@en | 23.212 | wn:similar | 1
wn:holo_member |   | 12.292 | wn:member_holonym | 0,5
wn:mero_member |   | 12.292 | wn:member_meronym | 0,5
wn:holo_part |   | 9.201 | wn:part_holonym | 0,5
wn:mero_part |   | 9.201 | wn:part_meronym | 0,5
wn:instance_hyponym | Instance hyponym@en | 8.589 | wn:instance_hyponym | 1
wn:instance_hypernym | Instance hypernym@en | 8.589 | wn:instance_hypernym | 1
wn:domain_topic |   | 6.716 | wn:domain_category | 0,5
wn:has_domain_topic |   | 6.716 | wn:domain_member_category | 0,5
wn:also | Also@en | 2.729 | wn:also | 1
wn:domain_region | Domain region@en | 1.354 | wn:domain_region | 1
wn:has_domain_region |   | 1.354 | wn:domain_member_region | 0,5
wn:attribute | Attribute@en | 1.278 | wn:attribute | 1
wn:exemplifies |   | 977 | (empty) | 0,5
wn:is_exemplified_by |   | 977 | (empty) | 0,5
wn:mero_substance |   | 830 | wn:substance_meronym | 0,5
wn:holo_substance |   | 830 | wn:member_holonym | 0,5
wn:entails |   | 408 | wn:entail | 0,5
wn:is_entailed_by |   | 408 | (empty) | 0,5
wn:is_caused_by |   | 221 | (empty) | 0,5
wn:causes |   | 221 | wn:cause | 0,5

**Comment by jmccrae** [comment]
The RDF export that is currently available from the site has some issues... I will update this. The actual wordnet ontology is at:

http://globalwordnet.github.io/schemas/wn.rdf

**Comment by rwingerter55** [comment]
Thank you for the enlightenment!

**Comment by 1313ou** [comment]
Same relation statistics broken down into src and dest POS.

https://x-englishwordnet.github.io/mysql/stats/stats-XX.html

**Comment by rwingerter55** [comment]
@1313ou, thank you for the statistics.

I think that parts-of-speech deserve more attention in order to ensure data quality. It should be defined which parts-of-speech can be linked by a given relation type.

**Comment by jmccrae** [comment]
Yes, this should be better documented. Some relations have specific part-of-speech restrictions implemented in `scripts/validate.py` but a more systematic and documented methodology would hep here.

**Comment by arademaker** [comment]
How the `confidence score` was calculated? In http://arademaker.github.io/bibliography/gwc-2016-icv.html, we have already reported some ideas for validating our RDF presentation of PWN and OWN-PT, we have also reported some validation errors in PWN.

**Comment by jmccrae** [comment]
I don't see any actions left on this issue
