### ISSUE TITLE
Define which parts-of-speech can be linked by a given relation type?

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#473]
In https://github.com/globalwordnet/english-wordnet/issues/472#issuecomment-632175090 @1313ou posted statistics for relation types broken down into src and dest POS.

I think that parts-of-speech deserve more attention in order to ensure data quality. Maybe it should be defined which parts-of-speech can be linked by a given relation type.

**Comment by rwingerter55** [comment]
I checked all the cases with a count < 20, but did not find anything wrong. 


rel | c1_POS | c2_POS | count
-- | -- | -- | --
exemplifies | verb | noun | 19
is_exemplified_by | noun | verb | 19
also | noun | noun | 12
domain_region | verb | noun | 9
has_domain_region | noun | verb | 9
also | verb | verb | 7
also | adverb | adverb | 6
also | adjective | noun | 1
domain_region | adverb | noun | 1
domain_topic | adjective | adjective | 1
has_domain_region | noun | adverb | 1
has_domain_topic | adjective | adjective | 1

Here are those with count = 1. 

rel | c1_POS | c2_POS | count | concept   A | concept   B | instances OK
-- | -- | -- | -- | -- | -- | --
also | adjective | noun | 1 | hungover | hangover | yes
domain_region | adverb | noun | 1 | langsyne | Scotland | yes
domain_topic | adjective | adjective | 1 | smol | childish, infantile | ?

**Comment by arademaker** [comment]
What was the conclusion here?

**Comment by jmccrae** [comment]
Not sure. At any rate we do some validation along these lines as part of the standard checks. Anyone is welcome to extend this, see for example:

https://github.com/globalwordnet/english-wordnet/blob/9a2bfafb9b6fced589bfb867703b9edaa3a856ef/scripts/validate.py#L175
