### ISSUE TITLE
wn:attribute used in both directions

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#474]
AFAICS there is no converse relation type defined for `wn:attribute`. The same relation type is used in both directions, from noun to adjective and vice versa. IMO this is a bit unfortunate. 

wn:attribute` is certainly an asymmetrical relation, as it involves two different parts-of-speech. 

> A relation between nominal and adjectival concepts where the concept A is an attribute of   concept B@en

IMO the definition does not make it absolutely clear whether concept A should be the noun and concept B the adjective, or vice versa. 

The first part of the sentence seems to suggest that A is the nominal and B the adjective concept, the second part states that A is the attribute of B. This is confusing.

**Comment by rwingerter55** [comment]
The link to the statistics posted in https://github.com/globalwordnet/english-wordnet/issues/472#issuecomment-632175090 show that both directions have exactly the same frequency. 


linkid | link | pos | pos | COUNT(*)
-- | -- | -- | -- | --
60 | attribute | n | a | 639
60 | attribute | a | n | 639

**Comment by jmccrae** [comment]
It is documented as being a symmetric relationship here:

https://globalwordnet.github.io/gwadoc/#attribute

This constraint is enforced by the scripts in this repo. While I agree that there should be a distinct inverse relation, part-of-speech is sufficient to analyse this.

**Comment by rwingerter55** [comment]
@jmccrae, thank you for the link. I have seen that page before :)
