### ISSUE TITLE
Merge adverbs "langsyne" and "lang syne" 

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#475]
IMO these synsets should be merged. 

ID | lemmas | definition | partOfSpeech
-- | -- | -- | --
<https://en-word.net/id/ewn-00022855-r> | "lang syne, long ago, long since" | "of the distant or comparatively distant past"@en | wn:adverb
<https://en-word.net/id/ewn-00387850-r> | "langsyne" | "at a distant time in the past"@en | wn:adverb

**Comment by arademaker** [comment]
related to #476
