### ISSUE TITLE
SPARQL code to find the smallest common hypernym of a set of concepts?

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#478]
IMO the following insight can be of great practical value when applied to WordNet.  

> For any set of hierarchically related concepts, there is a smallest common superordinate concept (supremum) and a largest common subordinate concept (infimum). 

I use EWN in GraphDB Free and I would like to determine the supremum and infimum with SPARQL. Can anyone help? Maybe somebody has already got a SPARQL script for this?  

The mathematical foundations are described in Wikipedia in [Lattice (order)](https://en.wikipedia.org/wiki/Lattice_(order)), and [Infimum and supremum](https://en.wikipedia.org/wiki/Infimum_and_supremum).

**Comment by rwingerter55** [comment]
I have a first version of the SPARQL script. It selects the common hypernyms of 
```
ewn-03796045-n | "bicycle, bike, cycle, wheel"
ewn-02837983-n | "bike, motorcycle"
```
You might be surprised, that the result includes 


`ewn-03099154-n | "container"`



Download query result: 
[result.txt](https://github.com/globalwordnet/english-wordnet/files/4694482/result.txt)



Download SPARQL query: [Common hypernyms.txt](https://github.com/globalwordnet/english-wordnet/files/4694189/Common.hypernyms.txt)D

**Comment by rwingerter55** [comment]
My apologies first. This thread is not about an issue in WordNet. I am only thinking aloud and sharing my thoughts. 

I am looking for ways to validate hypernym relations in a broader context. 

With the script above we get the hypernyms for a given set of concepts. In the example above, we get a flat table like this:

lc | lemmas | broader | broaderLemmas
-- | -- | -- | --
ewn-02837983-n | bicycle, bike, cycle, wheel | ewn-03580409-n | instrumentality, instrumentation
ewn-02837983-n | bicycle, bike, cycle, wheel | ewn-03105141-n | transport, conveyance
ewn-02837983-n | bicycle, bike, cycle, wheel | ewn-04531608-n | vehicle
etc | etc | etc | etc

The flat table can be converted to a concept matrix ([pivot table](https://en.wikipedia.org/wiki/Pivot_table) in Excel, Google Sheets or Office Libre Calc). The concept matrix ([adjacency matrix](https://en.wikipedia.org/wiki/Adjacency_matrix)) provides a condensed view of the concept relations. The following example shows the hypernyms for five concepts. The concepts are represented as columns and their hypernyms as rows. A descending sort on the last column ("Total") the order reflects the hierarchical level of hypernyms, with the most general hypernyms on top. 

Hyponym | concept | concept | concept | concept | concept | Total
-- | -- | -- | -- | -- | -- | --
Hypernym | bicycle, bike,   cycle, wheel | bike,   motorcycle | moped | minibike,   motorbike | scooter, motor   scooter | Total
transport, conveyance | 1 | 1 | 1 | 1 | 1 | 5
wheeled vehicle | 1 | 1 | 1 | 1 | 1 | 5
vehicle | 1 | 1 | 1 | 1 | 1 | 5
container | 1 | 1 | 1 | 1 | 1 | 5
instrumentality,   instrumentation | 1 | 1 | 1 | 1 | 1 | 5
self-propelled vehicle |   | 1 | 1 | 1 |   | 3
automotive vehicle, motor   vehicle |   | 1 | 1 | 1 |   | 3
bike, motorcycle |   |   | 1 | 1 |   | 2
minibike, motorbike |   |   | 1 |   |   | 1
Total | 5 | 7 | 9 | 8 | 5 | 34

Your ideas and comments are welcome.

**Comment by rwingerter55** [comment]
> A descending sort on the last column ("Total") reflects the hierarchical level of hypernyms

This is not the case here, because four of the concepts with a total of 5 have hypernyms that are not represented here. The `supremum` (smallest common superordinate) of the concept set is "Wheeled vehicle". 

The totals in the last row reflect the hierarchical level within the concept set.

**Comment by jmccrae** [comment]
As this does not seem to make any changes to this repository, can we close this issue?
