### ISSUE TITLE
New synset "pedelec"?

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#481]
I am not sure whether this is an equivalent or hyponym of "electric bike" https://github.com/globalwordnet/english-wordnet/issues/480#issue-627155309. 

**Definition** 

> 
> a bicycle with an electric motor that helps the rider turn the pedals:
> There are currently two types of electric bike available, pedelec and e-bikes.
> Pedelecs are great vehicles for big and small adventures.
> Compare
> e-bike
[Cambridge Dictionary](https://dictionary.cambridge.org/dictionary/english/pedelec)

**Examples:** 

> - Unlike the pedelec, an e-bike is an electric bike that can move forward without the rider pedalling.
> - The project promotes e-bikes and pedelecs for delivery of goods.
> - There is a lot of confusion online about what we mean by a **pedelec bike**.
[Cambridge Dictionary](https://dictionary.cambridge.org/dictionary/english/pedelec)

**Comment by rwingerter55** [comment]
I could not find a dictionary entry for "pedelec" in any other of the dictionaries proposed as "gold standard". 

See also 
https://en.wikipedia.org/wiki/Pedelec

**Comment by dcillessen** [comment]
Simply the frequency at which the word appears online justifies its inclusion, I'd say.

**Comment by rwingerter55** [comment]
@dcillessen, thanks for the support!

**Comment by rwingerter55** [comment]
Lemmas: "pedelec", "pedelec bike".

**Comment by rwingerter55** [comment]
Regarding the hierarchical relations, I would go with the definition in Collin's dictionary quoted in my first message. Here in Europe, different countries have different legal definitions of what is what, which is confusing. Details see Wikipedia.
