### ISSUE TITLE
Merge "fractional" and "partial"

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#49]
Highly similar definitions:

fractional `ewn-00518464-a`
> constituting or comprising a part or fraction of a possible whole or entirety

partial `ewn-00526870-s`
> being or affecting only a part; not total

**Comment by vcvpaiva** [comment]
Very different meanings IMHO

**Comment by jmccrae** [comment]
Perhaps, but 'partial' should be a lemma for `ewn-00518464-a` following its examples, I think this change is okay to make
