### ISSUE TITLE
Validating hierarchical relations - example

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#503]
How can we validate hierarchical relations in a larger context? Here is a description of an example in the Excel file attached. 

1. We start with the lemma `recital-n`.

2. We get the concepts it evokes. (Attachment, Table 1). 

3. We collect all the hypernyms of the concepts in step 2. (Table 2). 

4. We take Table 2 and add one column for each concept from Table 1. (Table 3).

5. We check the actual relations listed in the attachment (Table 4). 

Questions: 

- Do you agree with the hypernym relations? 

- Would you delete or add any relations between the concepts in the matrix?

[Validating hierarchical relations.xlsx](https://github.com/globalwordnet/english-wordnet/files/4719981/Validating.hierarchical.relations.xlsx)

The zip archive contains the same data in ods format. 

[Validating hierarchical relations.zip](https://github.com/globalwordnet/english-wordnet/files/4720031/Validating.hierarchical.relations.zip)

**Comment by jmccrae** [comment]
I guess this is about the methodology of validating relations? Improving the editing methodology is an important goal of the resource.

**Comment by rwingerter55** [comment]
> I guess this is about the methodology of validating relations?
Yes, it is. :-)

**Comment by jmccrae** [comment]
This issue seems to be quite stale. @rwingerter55 would you consider adding a Markdown file describing any procedure for creating links. I would also suggest that we could consider using LLMs such as ChatGPT to help with discovery of new links.

**Comment by jmccrae** [comment]
I am closing this issue as there does not seem to be any specific changes requested.

Please reopen if there are some specific changes or create new issues as necessary
