### ISSUE TITLE
Synonyms for "bicycle rack"

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#505]
We have

ID | lemmas | definition | subject
-- | -- | -- | --
ewn-02839034-n | "bicycle rack" | "a rack for parking bicycles"@en | "noun.artifact"

IMO we should create five new lexical entries and add them to this synset. 

- bike rack (https://en.wiktionary.org/wiki/bike_rack) 

- bicycle parking rack, bike parking rack (https://en.wikipedia.org/wiki/Bicycle_parking_rack)

- bicycle stand, bike stand (https://en.wikipedia.org/wiki/Bicycle_parking_rack)

**Comment by arademaker** [comment]
This is a very compositional concept. Fine to add terms if we choose not to remove synsets. But note that we should have to add 
https://en.m.wikipedia.org/wiki/Bicycle_carrier to keep the resource consistent ?

**Comment by rwingerter55** [comment]
@arademaker I agree. Please create a new issue.

**Comment by arademaker** [comment]
Well, not yet. I believe the guidelines suggest not to add compositional MWE

**Comment by rwingerter55** [comment]
@arademaker, I see. Thank you for the link!

**Comment by jmccrae** [comment]
Yes, I agree with @arademaker that these are compositional, so would not normally be included, however, we could extend the existing synset with these as term variations of `ewn-02839034-n`

Also, I struggle to see the difference between:

`ewn-04045203-n` (Interlingual Index: i57879)
(n) rack 
> framework for holding objects

and 

`ewn-04044916-n` (Interlingual Index: i57878)
(n) rack, stand 
> a support for displaying various articles "the newspapers were arranged on a rack"

Maybe this would be worthy of another issue.

**Comment by rwingerter55** [comment]
@jmccrae, change label to "synset member"?
