### ISSUE TITLE
British English vs. American English?

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#509]
Is this a topic at all? Here is an illustrated example I found on the web. 

> You and I are sitting at a table. In front of us is the plate in the diagram that follows. One of us is from Chicago, the other from London. I say to you "may I have a biscuit?" Your answer is "of course". I then pick up which item(s)?

![image](https://user-images.githubusercontent.com/62653433/84309278-2ab5f780-ab60-11ea-8cdf-05c85680679f.png)

> If I were from Chicago, that plate would contain one biscuit and two cookies. If I were from London, that plate would contain one scone and two biscuits. 

Source: https://www.unifiedcompliance.com/education/how-to-write-definitions/#What-Happens-When-We-Communicate

Cf. definitions in EWN: 

lc | lemmas | definition |    
-- | -- | -- | --
ewn-07709717-n | "biscuit" | "small round bread leavened with baking-powder or soda"@en |  
ewn-07650764-n | "biscuit, cookie, cooky" | "any of various small flat sweet cakes"@en |  
ewn-07706637-n | "scone" | "small biscuit (rich with cream and eggs) cut into diamonds or sticks and baked in an oven or (especially originally) on a griddle"@en

See also: [British English Vs American English: 24 Differences Illustrated](https://www.boredpanda.com/british-american-english-differences-language/)

**Comment by rwingerter55** [comment]
@arademaker, it was a question. Is there a policy? I assume it has been discussed before. 

The distinction can be made using the language tag of the lexical entry (`en` | `en-gb` | `en-us` | ... ). See [ISO Language codes](https://www.andiamo.co.uk/resources/iso-language-codes/). 

Example:


concept | le | entry
-- | -- | --
ewn-04682325-n  | <https://en-word.net/rdf/lemma/color#color-n> | "colour"@en-gb
ewn-04682325-n  | <https://en-word.net/rdf/lemma/colour#colour-n> | "colour"@en-us

**Comment by jmccrae** [comment]
This should be marked with a `domain_region` link to the synset for UK or USA. See for example:

https://en-word.net/id/ewn-00168782-s

This is not always done, however, and is not done for spelling variants such as color/colour

**Comment by rwingerter55** [comment]
@jmccrae, so far the relation type `domain_region` is only used between concepts. Spelling variants like `color` and `colour` pertain to lexical entries, respectively their written representation. Perhaps it would be preferable to have a different method or relation type for them?

There are 1374 relations of type `domain_region`. Here are the top 15 domains used and the number of domain_region links. I will have a closer look how this relation type is used and report the results. 

Rank | pwnid | domain | count | percent
-- | -- | -- | -- | --
1 | ewn-08879115-n | Britain, Great Britain, U.K., UK, United Kingdom of Great   Britain and Northern Ireland, United Kingdom | 519 | 38,3%
2 | ewn-09067337-n | America, United States, U.S., U.S.A., US, USA, United   States of America, the States | 68 | 5,0%
3 | ewn-08949695-n | France, French Republic | 52 | 3,8%
4 | ewn-08941623-n | Japan, Nihon, Nippon | 35 | 2,6%
5 | ewn-08798733-n | Greece, Ellas, Hellenic Republic | 29 | 2,1%
6 | ewn-08910324-n | Scotland | 29 | 2,1%
7 | ewn-08878165-n | Ireland, Emerald Isle, Hibernia | 26 | 1,9%
8 | ewn-08920762-n | India, Bharat, Republic of India | 26 | 1,9%
9 | ewn-08784821-n | Germany, Deutschland, FRG, Federal Republic of Germany | 25 | 1,8%
10 | ewn-08819530-n | Italy, Italia, Italian Republic | 22 | 1,6%
11 | ewn-08891234-n | England | 22 | 1,6%
12 | ewn-08936605-n | Babylon | 22 | 1,6%
13 | ewn-08740839-n | Cathay, China, Communist China, PRC, People's Republic of   China, Red China, mainland China | 21 | 1,6%
14 | ewn-08849996-n | Australia, Commonwealth of Australia | 19 | 1,4%
15 | ewn-08758708-n | Mexico, United Mexican States | 17 | 1,3%

**Comment by arademaker** [comment]
Nothing prevent us to have senses linked via domain_region

**Comment by rwingerter55** [comment]
> Nothing prevent us to have senses linked via domain_region

@arademaker, thank you. You are right, I was not aware of that. 

I found it on this page: https://globalwordnet.github.io/schemas/, more precisely here: https://github.com/globalwordnet/schemas/blob/master/example.xml

The DTD (http://globalwordnet.github.io/schemas/WN-LMF-1.0.dtd) does not have the same level of detail as example.xml.
