### ISSUE TITLE
Merge "black out" and "obliterate"

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#51]
Highly similar definitions:

black out `ewn-02768257-v`
> obliterate or extinguish

obliterate `ewn-00473161-v`
> do away with completely, without leaving a trace

**Comment by jmccrae** [comment]
I think the issue is that "black out" doesn't mean to "obliterate or extinguish", and other dictionaries don't have this meaning. We should look for any evidence of this meaning and if not found, delete the synset.

**Comment by dcillessen** [comment]
After a bit of searching around, I was only able to find this definition repeated in dictionaries which are derived from Princeton WN. eg: https://www.definitions.net/definition/black%20out
