### ISSUE TITLE
cross-lingual synsets

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#511]
over the years we are exploring the mapping of WN on different languages. But definitions like

> (the ultimate agency regarded as predetermining the course of events (often personified as a woman); "we are helpless in the face of destiny") - fate, destiny

pose some challenges. In Portuguese `destino` and `fado` are not personified as a woman, they are masculine gender words. How we should deal with such synsets?

**Comment by jmccrae** [comment]
In general, I don't think there is much to be done here. This wordnet is a wordnet for English and we are limited by the concepts that are lexicalized in English, e.g., in #468 if we don't think there is a specifically male 'hero' in English then we don't have a concept for it even though it clearly exists in other languages. 

This particular case, however, refers to an unnecessary parenthetical, that could be removed as it does not really help to identify the concept, and, moreover, it seems that if 'destiny' is actually personified it should probably have a new synset with a different hypernym. As such, I propose to **remove the parenthetical from this definition**.

As a side, I find it surprising that Portuguese would not see destiny as a woman; this is something that is prevalent in classical European mythology, such as the Moirai in Greek mythology and the Norns in Norse mythology.

**Comment by rwingerter55** [comment]
> I propose to **remove the parenthetical from this definition**.

Your proposal is supported by definitions in AHD, Collins, Merriam-Webster, and [Wiktionary](https://en.wiktionary.org/wiki/fate#Noun): 

> **fate** (countable and uncountable, plural fates)
> 
> 1. The presumed cause, force, principle, or divine will that predetermines events. 
> 
> 2. The effect, consequence, outcome, or inevitable events predetermined by this cause.
> 3. Destiny; often with a connotation of death, ruin, misfortune, etc.
> 
>     Accept your fate.
> 
> 4. **(mythology)** Alternative letter-case form of Fate (one of the goddesses said to control the destiny of human beings).

Looks like EWN joins senses 1 and 4. 

Collins even has a separate entry for [Fates](https://www.collinsdictionary.com/dictionary/english/fates) (plural noun).

**Comment by jmccrae** [comment]
closed by #577
