### ISSUE TITLE
ewn-07428499-n "concentration" has false hyponym

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#513]
`ewn-07428499-n` has two hyponyms, but according to its definition `ewn-07434008-n` cannot be a hyponym of "concentration". Rather it is an antonym of `ewn-07433833-n`.

![image](https://user-images.githubusercontent.com/62653433/85911442-843b4900-b825-11ea-8d33-6e91397d530c.png)

**Comment by jmccrae** [comment]
Agreed. The hypernym should be:

`ewn-07370487-n` (Interlingual Index: i75349)
(n) decrease, lessening, drop-off 
> a change downward "there was a decrease in his temperature as the fever subsided" "there was a sharp drop-off in sales"
