### ISSUE TITLE
Events and groups of people - some cases of systematic polysemy 

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#518]
@jmccrae wrote in #517:

> [... ] I think there is a big issue with systematic polysemy as many of the hyponyms of ewn-07991473-n are words such as 'building', 'floor', 'municipality' used to refer to the people found at that place, which is clarified in the examples, e.g., "the floor complained...". 

I agree that systematic polysemy is a big issue. It also occurs with words for events and people participating in them. `ewn-07991473-n` "assemblage, gathering" has 262 transitive hyponyms, including `ewn-08269132-n` "social affair, social gathering" (50 transitive hyponyms).  

Here are the issues I found analyzing the hyponyms of `ewn-08269132-n` and `ewn-07461861-n`. 

ID | lemmas | definition | subject
-- | -- | -- | --
ewn-07461861-n | affair, function, occasion, social function, social occasion | "a vaguely specified social event"@en | noun.event
ewn-08269132-n | social affair, social gathering | "a gathering for the purpose of promoting  fellowship"@en | noun.group

As the subject shows, the first concept is intended to designate an event, the other a group of people. 

But a closer look at the hyponyms of `ewn-08269132-n` reveals that in many cases the definitions refer to a social event. The following concepts do not have a corresponding concept covering the "event" sense and IMO should be moved to a more appropriate place in the hierarchy. 

ID | Lemmas | Subject | Definition
-- | -- | -- | --
ewn-08271461-n | at home | noun.group | a reception held in your own home
ewn-08272581-n | bachelor party | noun.group | stag party held for a bachelor (usually   on the night before he is married)
ewn-08271116-n | beanfeast | noun.group | an annual dinner party given by an employer for the   employees
ewn-08402221-n | blind date | noun.group | a date with a stranger
ewn-08205897-n | cornhusking, husking   bee | noun.group | a social   gathering for the purpose of husking corn
ewn-08401740-n | date, appointment,   engagement | noun.group | a meeting arranged in advance
ewn-08270736-n | dinner, dinner party | noun.group | a party   of people assembled to have dinner together
ewn-08402333-n | double date | noun.group | a date in which two couples participate
ewn-08270561-n | feast, banquet | noun.group | a ceremonial dinner party for many people
ewn-08272429-n | fete champetre, garden   party, lawn party | noun.group | a party   of people assembled for social interaction out of   doors
ewn-08270976-n | gaudy | noun.group | (Britain) a   celebratory reunion feast or   entertainment held a college
ewn-08273072-n | hen party | noun.group | a party for women only
ewn-07993172-n | love feast | noun.group | a social   gathering intended to create goodwill among the   participants
ewn-08402580-n | lunch meeting,   luncheon meeting | noun.group | a meeting for lunch; usually to conduct business while eating
ewn-08271914-n | open house | noun.group | an informal party of people with hospitality for   all comers
ewn-08402720-n | power breakfast | noun.group | a meeting of influential people to conduct business while eating   breakfast
ewn-07993298-n | quilting bee | noun.group | a gathering to make quilts
ewn-08402448-n | rendezvous, tryst | noun.group | a date; usually with a member of the opposite sex
ewn-08495382-n | reunion | noun.group | a party of former   associates who have come together again
ewn-08434877-n | seance, session,   sitting | noun.group | a meeting of spiritualists
ewn-08272926-n | smoker, stag party | noun.group | a party for men only (or one considered suitable for men only)
ewn-08269132-n | social affair, social   gathering | noun.group | a gathering for the purpose of promoting fellowship
ewn-08402011-n | visit | noun.group | a meeting arranged by the visitor to see someone (such as a doctor or   lawyer) for treatment or advice
ewn-08273656-n | wedding   party, wedding | noun.group | a party of people at a wedding

**Comment by rwingerter55** [comment]
Here are eight additions to the list above. They too are defined as events and should be moved accordingly. 


ID | Lemmas | Subject | Definition
-- | -- | -- | --
ewn-07992356-n | bee | noun.group | a social   gathering to carry out some communal task or to   hold competitions
ewn-08401631-n | conventicle | noun.group | a secret unauthorized meeting for religious worship
ewn-08272030-n | housewarming | noun.group | a party   of people assembled to celebrate moving into a new   home
ewn-08271548-n | levee | noun.group | a formal reception of visitors or guests (as   at a royal court)
ewn-08272294-n | musical soiree, soiree   musicale | noun.group | a soiree assembled for the purpose of listening to music
ewn-08272152-n | soiree | noun.group | a party of people assembled in the evening (usually at a private   house)
ewn-08273488-n | supper | noun.group | a social   gathering where a light evening meal is served
ewn-08271797-n | wedding   reception | noun.group | a reception for wedding guests held   after the wedding

**Comment by jmccrae** [comment]
Moving this to be reviewed for 2022 release.

**Comment by jmccrae** [comment]
Thinking about this I can't see any example of a 'social gathering' that is not also a 'social occasion' and the other way around. As such I would suggest that we merge these two senses together. I would combine all the hyponyms and have both 'event' and 'gathering' as hypernyms of this synset.
