### ISSUE TITLE
ewn-08271662-n "tea" and ewn-07465063-n "tea party"

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#519]
Judging from the definitions this is one and the same concept. IMO `ewn-08271662-n` should be deleted, unless someone comes up with a sentence where 'tea' is used to designate a group of people ;-)

ID | Lemmas | Subject | Definition 
-- | -- | -- | --
ewn-08271662-n | tea | noun.group | a reception or party  at which tea is served
ewn-07465063-n | tea party | noun.event | a party at which tea is served

**Comment by arademaker** [comment]
Interesting, in PWN 3.0 we only have the first sense. So the other one was added in PWN 3.1?
