### ISSUE TITLE
Merge "de-access" and "sell off"

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#52]
Highly similar definitions:

de-access `ewn-02252557-v`
> dispose of by selling

sell off `ewn-02249030-v`
> get rid of by selling, usually at reduced prices

**Comment by restinplace** [comment]
De-access typically refers to assets: "de-access recent acquisitions."
Sell off refers to stock or merchandise: "sell off the slow movers"

**Comment by jmccrae** [comment]
"de-access" seems to have a narrower meaning of selling items in a collection:
https://www.merriam-webster.com/dictionary/deaccession

The definition should be updated to "dispose of an item in a collection by selling it off" and the examples updated

**Comment by arademaker** [comment]
they are in different branches But I agre examples need revision.
