### ISSUE TITLE
RDF Download has no examples

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#520]
@jmccrae, are you aware that the RDF download (*.ttl) does not contain examples?

**Comment by jmccrae** [comment]
Yes, I plan to make a second version of the RDF release soon

**Comment by rwingerter55** [comment]
Thank you!

**Comment by jmccrae** [comment]
Fixed (note these issues do not really affect this repo, the changes are in https://github.com/jmccrae/wordnet-angular)
