### ISSUE TITLE
Identifying polysemous nouns

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#521]
Before we can analyze regular polysemy in EWN we need to identify relevant entries.  For a start I created some statistics about lexical entries of nouns. 

In EWN, each lexical entry is associated with 
- <1, n> concepts (synsets)
- <1, n> subjects (noun.act, noun.artifact etc.)

Here is a small example with three lexical entries mentioned by @jmccrae in #517.  The first column contains the subject, across we have lexical entries and the cells contain the number of concepts.

writtenRep | building | municipality | floor
-- | -- | -- | --
act | 2 |   |  
artifact | 1 |   | 4
attribute |   |   | 1
communication |   |   | 1
group | 1 | 1 | 1
location |   | 1 |  
object |   |   | 3
Total | 4 | 2 | 10

The Excel file attached contains a cross table with all 25 subjects and 16109 polysemous nouns. Maybe it can help to identify subjects that typically occur together. 

[EWN analysis - entry concept subject.xlsx](https://github.com/globalwordnet/english-wordnet/files/4861171/EWN.analysis.-.entry.concept.subject.xlsx)

**Comment by jmccrae** [comment]
Seems like an interesting analysis. Another way to approach it would be to find collocations, that is words that strongly co-occur with a particular sense, and adding them to a future version. I think this would also help a lot in sorting out some of the polysemy

NB. I put this as a 'question' not tied to any milestone as I don't see any actionable changes from this issue.

**Comment by rwingerter55** [comment]
I have added a new table to the Excel file attached. It contains all pairs of subjects and the number (and percentage) of entries they have in common. Here are all combinations that share more than 10% of their entries (average is 2,5 pct overlap). 

subject1 | subject2 | entries1 | entries2 | shared entries | pct shared
-- | -- | -- | -- | -- | --
act | communication | 3.726 | 2.945 | 826 | 14,1%
act | artifact | 3.726 | 3.801 | 779 | 11,5%
act | event | 3.726 | 917 | 480 | 11,5%
act | cognition | 3.726 | 1.695 | 525 | 10,7%
act | state | 3.726 | 1.624 | 505 | 10,4%
animal | food | 1.252 | 1.201 | 234 | 10,5%
artifact | person | 3.801 | 3.674 | 680 | 10,0%
attribute | state | 2.192 | 1.624 | 470 | 14,0%
attribute | cognition | 2.192 | 1.695 | 416 | 12,0%
communication | person | 2.945 | 3.674 | 697 | 11,8%
food | plant | 1.201 | 1.605 | 508 | 22,1%

Of course it is quite normal that an entry appears in two or more subjects (animal and food and plant and food are classic examples). But in some cases we might want to have a closer look to see what kind of entries are shared and what might be missing. 

[EWN analysis - entry concept subject v2.xlsx](https://github.com/globalwordnet/english-wordnet/files/4870822/EWN.analysis.-.entry.concept.subject.v2.xlsx)

**Comment by 1313ou** [comment]
Re collocations, let me mention EWN2020 has already been joined to [SyntagNet](http://syntagnet.org/) (courtesy of SQL).

You'll find the unified database here:
https://sourceforge.net/projects/sqlunet/files/6.0.0/mysql/XX/ (wn + sn modules)
or 
https://sourceforge.net/projects/sqlunet/files/6.0.0/sqlite/XX/

See also the browser for the mobile (based on the latter): 
https://play.google.com/store/apps/details?id=org.sqlunet.browser.sn&hl=en

**Comment by rwingerter55** [comment]
@1313ou, thank you very much for the links. Very interesting!

**Comment by arademaker** [comment]
I am trying to understand the first table presented in this issue. In my online interface of OWN-PT and PWN 3.0:

http://wn.mybluemix.net/search?search_field=word_en&term=building

**Comment by rwingerter55** [comment]
@arademaker, all I can say is that there are 4 concepts in EWN, cf. https://en-word.net/lemma/building. 

I closed the issue because I considered it as solved. I reopened it again.

**Comment by jmccrae** [comment]
I am not sure exactly what changes are being requested here? The four senses of 'building' seem sound to me

**Comment by rwingerter55** [comment]
From my point of view, the issue can be closed.
