### ISSUE TITLE
ewn-08503199-n "wine tasting"

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#524]
This issue is a continuation of #522.

### Current state

"Wine tasting" in EWN is not seen as an activity or an event, but as a group of persons: 

![image](https://user-images.githubusercontent.com/62653433/87557116-ce427c80-c6b7-11ea-9ac9-2cdb35ac155f.png)

### Proposal
IMO EWN should have a separate sense for the **act** of _wine tasting_ as a hyponym of  `ewn-00843562-n` "degustation, relishing, savoring, savouring, tasting". **Definition wanted!**

Cf. the position of `ewn-00843562-n` in the concept hierarchy: 

ID | Lemmas | Subject | Definition
-- | -- | -- | --
ewn-00839759-n | consumption,   ingestion, intake, uptake | noun.act | the process of taking food into the body through the mouth (as by eating)
ewn-00840028-n | eating,   feeding | noun.act | the act of consuming food
ewn-00843562-n | degustation,   relishing, savoring, savouring, tasting | noun.act | taking a small amount into the mouth to test its quality

### Definitions 
Most dictionary definitions I found stress the event aspect: 

Source | Sense | Definition
-- | -- | -- 
https://www.merriam-webster.com/dictionary/wine%20tasting | 1 | an **event**   where people can taste and compare very small samples of wine 
https://www.collinsdictionary.com/dictionary/english/wine-tasting | 1 | an **occasion**   for sampling a number of wines
https://en.wiktionary.org/wiki/winetasting | 1 | (uncountable) The sensory examination and evaluation of   wine. 
https://en.wiktionary.org/wiki/winetasting | 2 | (countable) An **event** for the purpose of tasting and evaluating wine. 

### Example sentences
On OED, which does not have an entry for _wine tasting_, I found these sample sentences, taken from Wikipedia and a Parliament archive. In most of them, wine tasting is an activity. 

no | OED   > Dictionary > Examples of wine tasting
-- | --
1 | In wine tasting,   acidity is perceived by a mouth watering response by the salivary glands.
2 | Their facilities   consist of kitchens, theaters, event space and a wine tasting room, which   hosts an intensive sommelier training course.
3 | The facilities include   industrial kitchens for hands-on cooking and baking classes, specialized wine   tasting classrooms, libraries, theaters, and event spaces.
4 | The film concludes   with a large group conducting a blind wine tasting.
5 | I hope that there was   no under-age drinking on the premises when all the wine tasting took place.
6 | The problem, which is   endemic, is the law relating to wine tasting or sampling, and the amendment   specifically deals with that.
7 | That means that they   cannot have any wine tasting on their on-licence before 12 o'clock midday and   must stop their wine tasting immediately at 2 pm.
8 | She is very   knowledgeable in all matters related to wine and has shown some talents in   wine tasting.
9 | Believing that she   wasn't good enough for him, she accused him of having an affair with a wine   tasting woman.
10 | These flavours are   evaluated using a procedure similar to wine tasting.
11 | Wine tasting is a   highlight of the area and the history of wine in this region is a rich one.
12 | Its programme included   workshops for children and adults as well as wine tasting.
13 | A connoiseur of coffee   and wine, he has a regular wine tasting column for an internet wine magazine.
14 | In wine tasting, wine   is often smelled before being drunk in order to identify some components of   the wine that may be present.
15 | In-store wine tasting   was also legalized, as were certain off-site special events hosted by   wineries.
16 | Events include dinner   parties, evening cocktail parties, weekend brunches, wine tasting   experiences, and childrens tea parties, to raise funds for the organization.
17 | Other activities   include arts and crafts, artichoke souvenirs sales, wine tasting and cooking   demos.
18 | There   are special interest groups for history, literature, music, and for wine   tasting.

**Comment by dcillessen** [comment]
It seems to me that we shouldn't create a new synset specifically for the act of "wine tasting" because it is compositional.  ewn-00843562-n covers this idea nicely already, and adding "wine" or "whisky" just specifies the substance being tasted. 

The event of a "wine tasting" exceeds its component parts, though. In my mind it should be categorized as an event rather than a group. perhaps it would fit as a hypernym of: 
ewn-07461861-n (Interlingual Index: i75849) (n) "affair, occasion, social occasion, function, social function"?

![image](https://user-images.githubusercontent.com/57256998/87706794-5595fb80-c75d-11ea-8c40-f759c782dda9.png)

**Comment by dcillessen** [comment]
ewn-07461861-n has the subject noun.event

**Comment by rwingerter55** [comment]
@dcillessen, your arguments convinced me. I agree with your proposal.

**Comment by johnwbyrd** [comment]
This thread makes me happy.  That is all.
