### ISSUE TITLE
ewn-08269523-n "party" and its hyponyms

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#526]
In issue #522 @jmccrae wrote: 

> [`ewn-07991473-n` "gathering, assemblage"] needs to be made clearer that it **refers only to a group of people, and many of its hyponyms such as 'fair', 'wine-tasting', 'rave-up' and of course 'social gathering' should be moved elsewhere.**

### Current state

`ewn-08269523-n` "party" is an indirect hyponym of `ewn-07991473-n` "gathering, assemblage" and refers to a group of people. 
It has a counterpart `ewn-07462241-n` "party" which is an indirect hyponym of `ewn-07303344-n` "social event". 

ID | Lemmas | Subject | Definition
-- | -- | -- | --
ewn-08269523-n | party | noun.group | a group of people gathered together for pleasure
ewn-07462241-n | party | noun.event | an occasion on which people can assemble for social interaction and   entertainment

### Proposal
All direct and indirect hyponyms of `ewn-08269523-n` "party" (noun.group) should be moved to become (direct or indirect) hyponyms of `ewn-07462241-n`  "party" (noun.event). 

Perhaps with the exception of:

- `ewn-08270062-n` "ball" could be left as is or dropped (merged with `ewn-07463317-n` "ball, formal"). 

- `ewn-08271662-n` "tea" could be left as is or merged with `ewn-07465063-n` "tea party". 

ID | lemmas | definition | 07462241-n     event | 08269523-n     group | proposal
-- | -- | -- | -- | -- | --
ewn-08271461-n | at home | a reception held in your own home |   | 1 | move
ewn-08272581-n | bachelor party | stag party held for a bachelor (usually on the night before   he is married) |   | 1 | move
ewn-08270189-n | ball | the people assembled at a lavish formal dance |   | 1 | drop?
ewn-07463485-n | ball, formal | a lavish dance requiring formal attire | 1 |   |  
ewn-07464052-n | barn dance | a dance party featuring country dancing | 1 |   |  
ewn-07462638-n | bash, brawl, do | an uproarious party | 1 |   |  
ewn-08271116-n | beanfeast | an annual dinner party given by an employer for the   employees |   | 1 | move
ewn-07462721-n | birthday party | a party held on the anniversary of someone's birth | 1 |   |  
ewn-07462832-n | bun-fight, bunfight | (Briticism) a grand formal party on an important occasion | 1 |   |  
ewn-07462994-n | ceilidh | an informal social gathering at which there is Scottish or   Irish folk music and singing and folk dancing and story telling | 1 |   |  
ewn-07463208-n | cocktail party | an afternoon party at which cocktails are served | 1 |   |  
ewn-07463637-n | cotilion, cotillion | a ball at which young ladies are presented to society | 1 |   |  
ewn-07463317-n | dance | a party for social dancing | 1 |   |  
ewn-08270062-n | dance | a party of people assembled for dancing |   | 1 | drop?
ewn-08270736-n | dinner, dinner party | a party of people assembled to have dinner together |   | 1 | move
ewn-07463757-n | fancy-dress ball, masked ball, masquerade ball | a ball at which guests wear costumes and masks | 1 | 1 | move / merge with ewn-08270371-n
ewn-08270561-n | feast, banquet | a ceremonial dinner party for many people |   | 1 | move
ewn-07464462-n | feast, fete, fiesta | an elaborate party (often outdoors) | 1 |   |  
ewn-08272429-n | fete champetre, garden party, lawn party | a party of people assembled for social interaction out of   doors |   | 1 | move
ewn-08270976-n | gaudy | (Britain) a celebratory reunion feast or entertainment held   a college |   | 1 | move
ewn-08273072-n | hen party | a party for women only |   | 1 | move
ewn-07464148-n | hop, record hop | an informal dance where popular music is played | 1 |   |  
ewn-07464829-n | house party | a party lasting over one or more nights at a large house | 1 |   |  
ewn-08272030-n | housewarming | a party of people assembled to celebrate moving into a new   home |   | 1 | move
ewn-07464943-n | jolly | a happy party | 1 |   |  
ewn-08271548-n | levee | a formal reception of visitors or guests (as at a royal   court) |   | 1 | move
ewn-07464655-n | luau | an elaborate Hawaiian feast or party (especially one   accompanied by traditional foods and entertainment) | 1 |   |  
ewn-08270371-n | mask, masquerade, masque, masquerade party | a party of guests wearing costumes and masks |   | 1 | move
ewn-08272294-n | musical soiree, soiree musicale | a soiree assembled for the purpose of listening to music |   | 1 | move
ewn-08271914-n | open house | an informal party of people with hospitality for all comers |   | 1 | move
ewn-07469911-n | potlatch | a ceremonial feast held by some Indians of the northwestern   coast of North America (as in celebrating a marriage or a new accession) in   which the host gives gifts to tribesmen and others to display his superior   wealth (sometimes, formerly, to his own impoverishment) | 1 |   |  
ewn-90003411-n | pre-game | A social gathering before a party or a sports game. | 1 |   |  
ewn-07463916-n | prom, promenade | a formal ball held for a school class toward the end of the   academic year | 1 |   |  
ewn-07464276-n | rave | a dance party that lasts all night and electronically   synthesized music is played | 1 |   |  
ewn-08271252-n | reception | a formal party of people; as after a wedding |   | 1 | move
ewn-08495382-n | reunion | a party of former associates who have come together again |   | 1 | move;   definition:      "a meeting of …"
ewn-08269966-n | shindig, shindy | a large and noisy party of people |   | 1 | move
ewn-08272716-n | shower | a party of friends assembled to present gifts (usually of a   specified kind) to a person |   | 1 | move
ewn-08273150-n | slumber party | an overnight party of girls who dress in nightclothes and   pass the night talking |   | 1 | move
ewn-08272926-n | smoker, stag party | a party for men only (or one considered suitable for men   only) |   | 1 | move
ewn-08273290-n | social, sociable, mixer | a party of people assembled to promote sociability and   communal activity |   | 1 | move
ewn-08272152-n | soiree | a party of people assembled in the evening (usually at a   private house) |   | 1 | move
ewn-08271662-n | tea | a reception or party at which tea is served |   | 1 | merge   with      ewn-07465063-n
ewn-07465063-n | tea party | a party at which tea is served | 1 |   |  
ewn-08273656-n | wedding party, wedding | a party of people at a wedding |   | 1 | move
ewn-08271797-n | wedding reception | a reception for wedding guests held after the wedding |   | 1 | move
ewn-07465149-n | whist drive | a progressive whist party | 1 |   |

**Comment by arademaker** [comment]
This is a systematic error in the assignment of hyponyms to the wrong hypernym. Good job. @rwingerter55 , how did you find these errors? Was it by chance or are you following any specific methodology?

**Comment by rwingerter55** [comment]
> how did you find these errors? Was it by chance or are you following any specific methodology?

In #517 @jmccrae mentioned the problem of systematic polysemy, and I took up the issue in #518 ff. In order to analyze a specific part of the vocabulary I follow more or less the same methodology:

1. Take a set of concepts (1..n) as a starting point (like `ewn-08269523-n` and `ewn-07462241-n`).   
2. Select all their direct and indirect (=transitive) hyponyms with ID, definition, subject. (I use the RDF data in [VocBench3](http://vocbench.uniroma2.it/) and SPARQL as a query language). 
3. The result of step 2 is a table I use for a closer inspection in Excel. 
4. When I am finished I copy and paste the results here. 

I can't imagine doing this without tools like VocBench3 and Excel.

**Comment by arademaker** [comment]
We found similar cases with rocks and their subtypes. Thank you for sharing your strategy. We also did something similar in our Portuguese Wordnet. We use AllegroGraph triplestore and we also have all data in RDF.

**Comment by arademaker** [comment]
I also found that ewn-07463757-n is actually descendent of both party senses. See [query](http://wnpt.sl.res.ibm.com:10035/#/repositories/wn30/query/d/select%20distinct%20?a%20%0A%7B%0A%20%20%3Chttps://w3id.org/own-pt/wn30-en/instances/synset-08252602-n%3E%20wn30:hypernymOf*%20?a%20.%0A%20%20%3Chttps://w3id.org/own-pt/wn30-en/instances/synset-07447641-n%3E%20wn30:hypernymOf*%20?a%20.%0A%7D)

Actually, the confusion with the `party` reflected in the `masked ball` (noun.event) vs `masquerade party` (noun.group). The former is a hyponym of the later...  

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/86403/88061966-97001f80-cb3e-11ea-87b1-d693642b41d4.png">

**Comment by rwingerter55** [comment]
> Actually, the confusion with the party reflected in the masked ball (noun.event) vs masquerade party (noun.group). The former is a hyponym of the later... Above you suggested to move both two one sense of party. But in this case, **we also need to merge them.**

Good catch, thank you! I have edited the table above accordingly. 

> I also found that ewn-07463757-n is actually descendent of both party senses

Yes, that's why it has a "1" in both cells, which I had overlooked.

**Comment by rwingerter55** [comment]
@arademaker wrote:

> Thank you for sharing your strategy.

I forgot to mention that I find Excel's "special filters" and Pivot tables particularly useful.

**Comment by jmccrae** [comment]
Closed this with a pull request that addresses the main issue. If there are other side issues please create new issues.
