### ISSUE TITLE
Definition of ewn-08118903-n "descent, line of descent, ..."

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#527]
IMO the definition of `ewn-08118903-n` is unfortunate and should be replaced; "descendants" are members of the bloodline, but also the opposite of "parentage" and "ancestry". 

ID | lemmas | definition | example
-- | -- | -- | --
ewn-08118903-n | "line, parentage, descent, ancestry, blood line, blood, bloodline, line of descent, lineage, origin, pedigree, stemma, stock" | "the descendants of one individual"@en | "his entire lineage has been warriors"

Cf. 
American Heritage Dictionary:

> 3. Hereditary derivation; lineage: 
> "a person of African descent."

Wiktionary:

> 4. Lineage or hereditary derivation.
> "Our guide was of Welsh descent."

**Comment by jmccrae** [comment]
I am not quite sure I understand the issue here. Do you want to change the members of the synset or just the definition?

**Comment by rwingerter55** [comment]
Just the definition.
