### ISSUE TITLE
Add missing sense for lemma "button"?

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#528]
Currently EWN has these lexical senses of "button":

ID | subject | lemmas | definition
-- | -- | -- | --
ewn-02931992-n | "noun.artifact" | "button" | "a round fastener sewn to shirts and coats etc to fit through buttonholes"@en
ewn-02932225-n | "noun.artifact" | "button" | "any artifact that resembles a button"@en
ewn-04033499-n | "noun.artifact" | "button, push button, push" | "an electrical switch operated by pressing"@en
ewn-04080537-n | "noun.artifact" | "button, release" | "a device that when pressed will release part of a mechanism"@en
ewn-05531071-n | "noun.body" | "clitoris, button, clit" | "a female sexual organ homologous to the penis"@en
ewn-07283118-n | "noun.communication" | "button" | "a round flat badge displaying information and suitable for pinning onto a garment"@en
ewn-11552367-n | "noun.plant" | "button" | "any of various plant parts that resemble buttons"@en

IMO we could add one more meaning, cf. the following senses listed in AHD and Wiktionary:

> 3. Computers
> a. In graphical user interface systems, a well-defined area within the interface that is clicked to select a command.
https://www.ahdictionary.com/word/search.html?q=button

> 3. (graphical user interface) An on-screen control that can be selected as an activator of an attached function.
>     Click the button that looks like a house to return to your browser's home page.
https://en.wiktionary.org/wiki/button#Noun

**Comment by arademaker** [comment]
Yes, I agree. But we can also merge ewn-04080537-n (6) and ewn-04033499-n (2)?

2. (6) push button, push, button -- (an electrical switch operated by pressing; "the elevator was operated by push buttons"; "the push beside the bed operated a buzzer at the desk")
6. release, button -- (a device that when pressed will release part of a mechanism)

```
** Sense 2
push button, push, button
       => switch, electric switch, electrical switch
           => control, controller
               => mechanism
                   => device
                       => instrumentality, instrumentation
                           => artifact, artefact
                               => whole, unit
                                   => object, physical object
                                       => physical entity
                                           => entity

** Sense 6
release, button
       => device
           => instrumentality, instrumentation
               => artifact, artefact
                   => whole, unit
                       => object, physical object
                           => physical entity
                               => entity
```

**Comment by jmccrae** [comment]
@arademaker I am not sure about the merge between these synsets. The first synset clearly only refers to electrical buttons, while the second to emergency release buttons (normally mechanical). In this case, my opinion is that I wouldn't make this distinction, but I don't feel it necessary to merge these synsets that already exist.
