### ISSUE TITLE
Merge "phenomenal" and "fantastic"

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#53]
Highly similar definitions:

phenomenal `ewn-01681586-s`
> exceedingly or unbelievably great

marvelous, grand, marvellous, terrific, tremendous, fantastic, wonderful, rattling, howling, wondrous `ewn-01681111-s`
> extraordinarily good or great; used especially as intensifiers

**Comment by jmccrae** [comment]
These are both satellites of the same synset, they could easily be merged

**Comment by arademaker** [comment]
I vote to merge. But one is adj.all the other is adj.pert. Does it make sense?
