### ISSUE TITLE
New synset "hotline, hot line"

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#530]
We have `ewn-03548192-n` "hot line" and the following definition: 

> a direct telephone line between two officials

Many other dictionaries have another lexical sense, which is missing in EWN:

> 2. A telephone line that gives quick and direct access to a source of information or help: a 24-hour hotline.

https://www.ahdictionary.com/word/search.html?q=hotline

> a special telephone line for people to find out about or talk about something

https://www.ldoceonline.com/dictionary/hotline

> A telephone line that is always staffed and able to give immediate assistance.
> 
>     If you've got any problems with the product, ring our hotline.

https://en.wiktionary.org/wiki/hotline#Noun

See also example sentences at https://www.vocabulary.com/dictionary/hot%20line.

**Comment by arademaker** [comment]
Yes. but where should we add this new synset? The http://wn.mybluemix.net/synset?id=03543012-n is a hyponym of `telephone line`, we can change its scope without affecting the network. Maybe `a direct telephone line between two officials` and `a special telephone line for people to find out about or talk about something` are quite similar and we can generalize the current sense?

The `service` sense would encompass `A telephone line that gives quick and direct access to a source of information or help: a 24-hour hotline.` and `A telephone line that is always staffed and able to give immediate assistance.`?

**Comment by jmccrae** [comment]
I would say as other dictionaries make this distinction, we should probably do so too. However, I would note that there is much less corpus evidence for the current sense, so we could argue that this sense ('an inter-government hotline') has basically been subsumed by the more general sense nowadays.
