### ISSUE TITLE
bug in the PWN data.verb

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#531]
```
02616386 42 v 01 be 6 000 02 + 08 00 + 11 00 | be identical to; be someone or something; "The president of the company is John Smith"; "This is my house"
```

This line is not in the expected format. According to https://wordnet.princeton.edu/documentation/wndb5wn. In the https://en-word.net/lemma/be, we can see this synset without any relation. 

The data.verb from PWN 3.1 has the same error

```
02622439 42 v 01 be 6 000 02 + 08 00 + 11 00 | be identical to; be someone or something; "The president of the company is John Smith"; "This is my house"
```

Not sure how we can recover the relations.

**Comment by arademaker** [comment]
we have many more cases of disconnected synsets. One adv from PWN:

00012531 02 r 02 well 3 easily 5 000 | indicating high probability; in all likelihood; "I might well do it"; "a mistake that could easily have ended in disaster"; "you may well need your umbrella"; "he could equally well be trying to deceive us"

In that case, we can easly add a derivational relation from the adj `easy`.

**Comment by 1313ou** [comment]
What is wrong **with the format** ? This being a singleton synset has nothing to do with the format (either XML or WNDB).

**Comment by arademaker** [comment]
I am not sure if I understood your comment. The point is that the line above is not following the documentation https://wordnet.princeton.edu/documentation/wndb5wn. I am not talking about the WNDB files.

**Comment by 1313ou** [comment]
What's wrong with the line (that wndb5wn forbids) ?
