### ISSUE TITLE
mapping with Princeton WordNet versions ? 

### ISSUE THREAD

**Issue by schwabdidier** [globalwordnet/english-wordnet#537]
There are some mapping between Princeton WordNet versions.

https://github.com/getalp/UFSAC/tree/master/java/src/main/resources/data/wordnet/mapping

Do we have this kind of things with this new version ? Especially mapping to version 3.1 and 3.0. I really would like them in order to update our ressources (sense annotated corpora).

Thank you in advance !

Didier

**Comment by schwabdidier** [comment]
No Answer ?

**Comment by jmccrae** [comment]
Hi,
The preferred way of mapping with other wordnets is through the ILI code (see https://github.com/globalwordnet/ili), there are mappings available to all Princeton WordNet repos on that repository. In addition, as a derivative of Princeton WordNet 3.1, this resource uses the synset offsets of PWN3.1. We also support mapping using Princeton Sense IDs, you can see the sense keys that we have in our files are exactly the same as Princeont and [this file](https://github.com/globalwordnet/english-wordnet/blob/master/src/sensekey-maps.csv) gives all the mappings that have changed between this version and Princeton versions.

I hope this clears things up :)

**Comment by schwabdidier** [comment]
definitely ! Many thanks @jmccrae
