### ISSUE TITLE
The contributing guideline ask to add labels, but you need write access for that

### ISSUE THREAD

**Issue by fcbond** [globalwordnet/english-wordnet#539]
We should note that not everyone can add labels, and maybe make some templates with lables for those without write access?

https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/about-issue-and-pull-request-templates#issue-templates

**Comment by jmccrae** [comment]
I hadn't realised this is an issue, yes, issue templates would be a great idea

**Comment by jmccrae** [comment]
Fixed by https://github.com/globalwordnet/english-wordnet/commit/7c09a2a1b7f7372d82553bf539c21bc5f11f6a53
