### ISSUE TITLE
The sample sentences of honest

### ISSUE THREAD

**Issue by Adnan0703** [globalwordnet/english-wordnet#541]
Two senses of honest has the same phrase as sample. Is it a mistake or does the phrase "**honest reporting**" have two meanings?
https://en-word.net/lemma/honest
ewn-01225031-a
 honest, honorable *not disposed to cheat or defraud; not deceptive or fraudulent "honest lawyers" "honest reporting"*
ewn-01228516-s
 honest *marked by truth "gave honest answers" "honest reporting"*

**Comment by jmccrae** [comment]
I guess this relates to #35 

We should certainly remove the example and consider merging these senses.
