### ISSUE TITLE
I think 'New World' should be synonymous with 'Americas'

### ISSUE THREAD

**Issue by fcbond** [globalwordnet/english-wordnet#547]
This is a part of the western hemisphere, rather than all of it.

So make a new synset for 'New World' and 'Americas', antonym of Afro-Asia.
Remove New World from western hemisphere <pwn3.0-08682389-n>, and make it a part meronym of this, North and South America are then part-meronym of the Americas.

**Comment by jmccrae** [comment]
Surely Australia is in the New World though?
