### ISSUE TITLE
CILI link is 404 in README.md

### ISSUE THREAD

**Issue by simongray** [globalwordnet/english-wordnet#552]
The second paragraph in `README.md`:

> English WordNet is a fork of the [Princeton Wordnet](https://wordnet.princeton.edu/) developed under
an open source methodology. The quality and veracity of the resource may differ from the Princeton 
WordNet and we welcome contributions. Contributions to this wordnet may eventually be incorporated into
future releases of Princeton WordNet. Correspondance to previous versions and wordnets in other language is provided
through the [Collaborative Interlingual Index (CILI)](http://compling.hss.ntu.edu.sg/iliomw/ili). The English WordNet is available as individual files in [GWN-LMF](http://globalwordnet.github.io/schemas/) format.

The CILI link is dead and returns a 404.

Should it be https://github.com/globalwordnet/cili or something else?

**Comment by jmccrae** [comment]
@fcbond do you know what happened to the CILI?

**Comment by simongray** [comment]
I also found this which looks suspiciously like the dead link: https://lr.soh.ntu.edu.sg/omw/ili

**Comment by goodmami** [comment]
> Should it be https://github.com/globalwordnet/cili or something else?

https://github.com/globalwordnet/cili is the GitHub home of the CILI project. The OMW manages and curates additions to CILI and the exported result of that curation is at the GitHub project. The https://lr.soh.ntu.edu.sg/omw/ili page for CILI is the more informative OMW-associated front for the CILI project with instructions for contributing, etc. The GitHub project's README links to this latter URL.

Regarding http://compling.hss.ntu.edu.sg/iliomw/ili, we are retiring the `compling` server at NTU and the https://lr.soh.ntu.edu.sg/omw/ili URL is the *current* home, but this might even be temporary. @fcbond would know what the ultimate plan is for it. Regardless, it would be ideal if we could get a more permanent URL that points to whatever server is hosting the CILI homepage. Or maybe we could just put something at https://globalwordnet.github.io/cili and make that the homepage?

> (it also kinda looks like a randomly generated string, though)

Yes, it's a bit acronym-heavy. LR = "lexical resources" (just a subdomain for that particular server). SoH = "School of Humanities". NTU = "Nanyang Technological University". OMW = "Open Multilingual Wordnet". ILI = "Interlingual Index".
