### ISSUE TITLE
Converter from link is broken

### ISSUE THREAD

**Issue by ryou90** [globalwordnet/english-wordnet#553]
Hi,
great work with the new Wordnet version. I actually try to convert the xml-lmf file to RDF triples, but the converter (https://server1.nlp.insight-centre.org/gwn-converter/) is broken.
Is there any other way to convert this and also other wordnet files, e.g. from this resource https://github.com/bond-lab/omw-data/releases/tag/v1.3 ?

Thx, 
Robert

**Comment by jmccrae** [comment]
The converter can also be downloaded and run locally.

I will close this issue as it is not relevant to this project. (Thanks for creating an issue on the relevant project!)

**Comment by jotree96** [comment]
@jmccrae where can the converter be downloaded? 

Thank you in advance!

**Comment by jotree96** [comment]
@jmccrae where can the converter be downloaded? 

Thank you in advance!

**Comment by jotree96** [comment]
@jmccrae where can the converter be downloaded? 

Thank you in advance!

**Comment by jmccrae** [comment]
https://github.com/jmccrae/gwn-scala-api
