### ISSUE TITLE
Different classification of synsets

### ISSUE THREAD

**Issue by KirilSimov** [globalwordnet/english-wordnet#557]
Dear All,

During mapping Bulgarian BTB-Wordnet and English Wordnet we found the following case:

(n) communist, commie a socialist who advocates communism
Hypernyms (1)
(n) socialist a political advocate of socialism
Hypernyms (1)
(n) politician, politico, pol, political leader a person active in party politics
Hypernyms (1)
(n) leader a person who rules or guides or inspires others
Hypernyms (1)
(n) person, individual, someone, somebody, mortal, soul a human being; person, singular, assertive existential pronoun; pronoun, person, singular; quantifier: assertive existential "there was too much for one person to do"

(n) fascist an adherent of fascism or other authoritarian views
Hypernyms (1)
(n) adult, grownup a fully developed person from maturity onward
Hypernyms (1)
(n) person, individual, someone, somebody, mortal, soul a human being; person, singular, assertive existential pronoun; pronoun, person, singular; quantifier: assertive existential "there was too much for one person to do"

I am not a native English speaker, but to me, it seems quite a different classification of similar concepts.
If this is a correct observation, are you going to change such cases?

I am sorry if this is already clear case.

With best regards,

Kiril

**Comment by jmccrae** [comment]
Thanks for the report. Yes, "communists" are "leaders" and "fascists" are "adults" are both very questionable hypernym relationships.

I would suggest moving "fascist" and "socialist" under "advocate", as this seems to contain most other "advocates of a political philosophy" terms like "republican", "federalist", "Maoist" etc.

`ewn-09794206-n` (Interlingual Index: i88102)
(n) advocate, advocator, proponent, exponent 
> a person who pleads for a cause or propounds an idea

**Comment by KirilSimov** [comment]
Dear John,

Thank you very much for your reply!
We will follow your suggestions. I have the feeling that there are more
such cases in this part of the hierarchy for reclassification. When we
are ready with the Bulgarian classification we could share our observations.

With best regards,

Kiril

**Comment by jmccrae** [comment]
Thanks, Kiril. Yes, please suggest any other issues you come across
