### ISSUE TITLE
Merge "vacuous" and "vacant"

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#56]
Highly similar definitions:

mindless, vacuous `ewn-02581841-s`
> devoid of intelligence or thought

vacant `ewn-01091853-s`
> void of intelligence or thought

**Comment by restinplace** [comment]
Agree.  Fwiw I think the substitution test is stronger -- can one 
replace the other in the example phrase?  
S: (adj) vacant#1 (void of intelligence or thought) "a vacant mind"
S: (adj) mindless#4, vacuous#1 (devoid of intelligence or thought) "a vacuous mind"; "a vacant expression"

**Comment by jmccrae** [comment]
They seem to be substitutable. "vacant" is marked as similar to "empty", whereas "vacuous" is similar to "foolish", as such I would remove `ewn-01091853-s`
