### ISSUE TITLE
Merge "gutless" senses

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#57]
Gutless has to senses with very little difference in meaning, could these be merged?

gutless `ewn-00267851-a`
> lacking courage or vitality

wishy-washy, spineless, gutless, namby-pamby  `ewn-02333585-s`
> weak in willpower, courage or vitality

**Comment by restinplace** [comment]
First def should be "lacking courage".
Second def should be "lacking willpower or resolve".

**Comment by jmccrae** [comment]
I think there is some relation to #35 here

**Comment by arademaker** [comment]
one more case of OR used in definitions that confuse the interpretation.

**Comment by dcillessen** [comment]
Seems to me that we should merge the definitions and relations into one synset. Both synsets currently have useful relations but don't have significantly different definitions. 

"weak in willpower, courage or vitality" is the stronger definition in my mind, and we could still use the examples from ewn-00267851-a: "'he was a yellow gutless worm' 'a spineless craven fellow.'"
