### ISSUE TITLE
'deploy' and 'roll out'

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#580]
The two senses of deploy are very hard to distinguish:

`ewn-01151793-v` (Interlingual Index: i27371)
(v) deploy 
> place troops or weapons in battle formation

`ewn-01382265-v` (Interlingual Index: i28606)
(v) deploy 
> to distribute systematically or strategically

Perhaps we could merge them? Also we could add the synonym of 'roll out' to this synset

(from WN-USERS discussion by @daikinomura)

**Comment by arademaker** [comment]
> ... can be deployed by grenades or cluster bombs

The first sense does not work perfectly here.
