### ISSUE TITLE
Alternate word forms and WNDB exception lists

### ISSUE THREAD

**Issue by goodmami** [globalwordnet/english-wordnet#586]
I was under the impression that the word forms (`<Form>` in WN-LMF, now `form` in YAML) were spellings of irregular plurals, tenses, etc., and that it captured the info in the WNDB exception lists. For the most part this seems to be true, e.g.:

```yaml
matrix:
  n:
    form:
    - matrices
```

...but there are fewer forms than exceptions in the PWN's exception lists:

```console
~$ cat english-wordnet/src/yaml/entries-* | grep -c '^ *form:'
3077
~$ grep -c '<Form ' ewn-2020.xml 
4519
```

And here's from the PWN packaged with the NLTK:

```console
~$ cat ~/nltk_data/corpora/wordnet/*.exc | wc
   5952   12005   99438
```

Each line has an exception and one or more lemmas, so if we subtract the line count (5952) from the word count (12005) we should get the number of exception-lemma pairings: 6053. This number should be comparable to the `<Form ` elements in WN-LMF.

As one example, the word *axis* does not have its plural *axes* listed (also the plural for *ax* and *axe*) in EWN. What is the purpose of listing the forms? Should we add other exception list entries that aren't in EWN?

**Comment by jmccrae** [comment]
Seems like a bug in the original export. I would guess because there were multiple variants listed on the same line:

```
avitaminoses avitaminosis
axes ax axis
axillae axilla
```

**Comment by goodmami** [comment]
Ah ok, good. So the intention is to include all of them. To add the remainder, do we fix and re-run the export script, or do we find a way to add these to the current YAML files?

**Comment by jmccrae** [comment]
I guess there are too many changes from the original export, but it shouldn't be hard to put together a quick script.

**Comment by goodmami** [comment]
My counting of forms in the YAML files was incorrect as it only looked for `form:` and didn't consider the list of items under it, i.e., it returned the number of words with alternate forms (which may be interesting). Counting the number of dashes under `form:` gets a number closer to the number of `<Form` substrings in the XML:

```console
$ cat english-wordnet/src/yaml/entries-* | sed -n '/^ *form:/{:loop n;/^ *-/{p;b loop}}' | wc -l
4523
```

**Comment by jmccrae** [comment]
@goodmami I have closed this issue. Please re-open if you find any further issue here.
