### ISSUE TITLE
"de-ionate" is not a real English word

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#59]
de-ionate `ewn-00521840-v`, "remove ions from" does not seem to be a real scientific term. It has zero hits in Wikipedia and a large Web corpus and searching in Google returns only WordNet and derivative resources.

**Comment by jmccrae** [comment]
I am convinced that this should be "deionize", which already exists. 

However the two synsets `ewn-02369766-v` and `ewn-00521840-v` have different hypernyms, with the hypernym for "de-ionate" being more appropriate to the meaning.

I propose that we thus remove the "deionize" synset (`ewn-00521840-v`) and add "deionize" to the other synset.

**Comment by arademaker** [comment]
ok
