### ISSUE TITLE
"cumulous" lists a minor and possibly unattested sense

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#60]
The only sense of "cumulous" is `ewn-00541427-s` "thrown together in a pile". Web corpus search quickly reveals that the most frequent sense is referring to the shape of clouds and there is no obvious corpus attestation for this sense.

**Comment by jmccrae** [comment]
Still cannot find any attestation of this sense.

The closest is this Merriam-Webster sense, but this is ambiguous
https://www.merriam-webster.com/dictionary/cumulous

Others suggest that it is either not an adjective
https://www.lexico.com/definition/cumulus
https://en.wiktionary.org/wiki/cumulus#English

Or limited to the cloud sense:
https://www.collinsdictionary.com/dictionary/english/cumulous

I suggest preserving ewn-00541427-s and adding a new synset
'cumulous', 'cumulus' of or related to cumulus clouds 
pertains to `ewn-09284866-n`

**Comment by arademaker** [comment]
for me the problem is the examples and the definition. First the definition is more like a definition of a verb 

> thrown together in a pile

No example uses the adj `cumulous`:

> "a desk heaped with books"; "heaped-up ears of corn"; "ungraded papers piled high")

But it has a direct translation to the adj `acumulado` in Portuguese. So the inter-lingual argument can help here.

**Comment by dcillessen** [comment]
It exists in the AH dictionary and the OED as well, but as an adjective. 
https://www.ahdictionary.com/word/search.html?q=cumulous
https://oed.com/view/Entry/45828?redirectedFrom=cumulous#eid

They nonetheless seem related to the cloud sense as well; all the definitions in the OED refer to clouds in their examples.

Ultimately, I agree with John here: 
> I suggest preserving ewn-00541427-s and adding a new synset
'cumulous', 'cumulus' of or related to cumulus clouds
pertains to ewn-09284866-n
