### ISSUE TITLE
Version confusion

### ISSUE THREAD

**Issue by ekaf** [globalwordnet/english-wordnet#603]
The datafiles in the WNDB release of EWN 2020 include the following line:
 
> 14 WordNet 3.1 Copyright 2011 by Princeton University.  All rights reserved. 

This poses a compatibility issue with other projects, because  f. ex. the NLTK wordnet.py module has a get_version function that extracts the version name from the "data.adj" file:

> re.search(r"WordNet (\d+\.\d+) Copyright", line)

On the NLTK side, this regular expression could probably be adapted, in order to accomodate an EWN copyright line.

This issue has been raised in the past (#163), and closed with the "wontfix" tag. However, since the different versions of EWN undeniably differ from WordNet 3.1,  it might be worthwile to reconsider this issue, and allow WNDB users to distinguish between the versions. Having a clue about the actual version name would make it easier for other projects to use WNDB data.

**Comment by jmccrae** [comment]
We should probably ensure that the message in the WNDB format is appropriate. However, there is an issue that the copyright message must be exactly the same length as the existing one, so I will work on how we may do this.

This issue requires a fix in an external project: https://github.com/jmccrae/gwn-scala-api/issues/14

**Comment by ekaf** [comment]
The hard part may not be to keep a length of 1740 bytes, but rather to juggle with the legal content of the copyright message. It seems to me that the current text says that the lines from line 14 must be kept, so only the preceding lines may probably be changed.

**Comment by ekaf** [comment]
Closed through #604
