### ISSUE TITLE
Missing hypernym relations 

### ISSUE THREAD

**Issue by KirilSimov** [globalwordnet/english-wordnet#608]
Dear All,

For the following synsets the hypernym relation is missing:
ewn-01082290-n	group action
ewn-01316379-n	recombinant
ewn-02748096-n	article of commerce
ewn-02763860-n	automatic, machine rifle, automatic rifle
ewn-02941705-n	calcimine
ewn-03045617-n	chopper, cleaver, meat cleaver
ewn-03062970-n	coat of paint
ewn-03493686-n	hand shovel
ewn-03941726-n	pike
ewn-04022873-n	pruning knife
ewn-04421611-n	terrycloth, terry cloth, terry
ewn-06364189-n	Devanagari script, Nagari, Nagari script, Devanagari
ewn-07053516-n	allegro
ewn-07053695-n	allegretto
ewn-07053894-n	andante
ewn-07060601-n	largo
ewn-07061862-n	adagio
ewn-07085982-n	genre, musical genre, music genre, musical style
ewn-07759878-n	cranberry
ewn-08490184-n	IWW, Industrial Workers of the World, I.W.W.
ewn-08517454-n	space, outer space
ewn-09664887-n	Amerindian, Native American
ewn-11550459-n	microflora
ewn-11749947-n	clematis
ewn-12732577-n	sweet lime, Citrus limetta, sweet lemon
ewn-13288557-n	grant-in-aid
ewn-14636495-n	hexanedioic acid, adipic acid
ewn-14640359-n	octanedioic acid, suberic acid
ewn-14640470-n	succinic acid
ewn-14653098-n	argon, Ar, atomic number 18
ewn-14657384-n	C, carbon, atomic number 6
ewn-14664099-n	helium, He, atomic number 2
ewn-14666595-n	iron, atomic number 26, Fe
ewn-14667094-n	atomic number 36, Kr, krypton
ewn-14670330-n	atomic number 10, Ne, neon
ewn-14672085-n	atomic number 76, Os, osmium
ewn-14676283-n	atomic number 86, Rn, radon
ewn-14677421-n	ruthenium, atomic number 44, Ru
ewn-14685453-n	Xe, xenon, atomic number 54
ewn-14700917-n	gesso
ewn-14763913-n	saccharic acid
ewn-14764040-n	sebacic acid, decanedioic acid
ewn-14768768-n	ammonium chloride, sal ammoniac
ewn-14836403-n	chrysoprase
ewn-14960364-n	limestone
ewn-15004520-n	peridot
ewn-15028884-n	chymosin, rennin
ewn-15043456-n	starch

With best regards,

Kiril

**Comment by ekaf** [comment]
The list above by @KirilSimov is accurate for the EWN-2020 release. 

Additionally, in the current "master" branch, the following two noun synsets  also lack a hypernym:
ewn-11487233-n scorcher
ewn-11487308-n sultriness

On the other hand, the following 18 have been fixed, and now have a hypernym or an instance_hypernym:
ewn-01082290-n group action
ewn-02763860-n automatic, machine rifle, automatic rifle
ewn-02941705-n calcimine
ewn-03045617-n chopper, cleaver, meat cleaver
ewn-03062970-n coat of paint
ewn-03493686-n hand shovel
ewn-03941726-n pike
ewn-04022873-n pruning knife
ewn-04421611-n terrycloth, terry cloth, terry
ewn-07085982-n genre, musical genre, music genre, musical style
ewn-07759878-n cranberry
ewn-09664887-n Amerindian, Native American
ewn-11749947-n clematis
ewn-13288557-n grant-in-aid
ewn-14657384-n C, carbon, atomic number 6
ewn-14666595-n iron, atomic number 26, Fe
ewn-14960364-n limestone
ewn-15028884-n chymosin, rennin

**Comment by jmccrae** [comment]
I added a warning to the validation script for synsets without hypernyms. Currently I have the following gist to track the missing hypernyms and what their hypernyms would be:

https://gist.github.com/jmccrae/94dafba3487d621be3824d3a49401f9d

**Comment by jmccrae** [comment]
Thanks to @KirilSimov I updated the list of hypernyms. There is also at least one error in PWN 3.1, as "sweet lime" should be a holonym of "Genus citrus" rather than a hyponym. Also, I am not sure about the hypernym of "recombinant".

**Comment by jmccrae** [comment]
I also note I removed the case of transitive links (hypernyms to hypernyms of hypernyms) as we try to avoid these.
