### ISSUE TITLE
"convert" meaning in a sporting sense

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#61]
There are three senses for "convert" meaning to score a shot in a sporting game

convert `ewn-01087135-v`
> complete successfully; "score a penalty shot or free throw"

convert `ewn-01087277-v`
> core an extra point or points after touchdown by kicking the ball through the uprights or advancing the ball into the end zone; "Smith converted and his team won"

convert `ewn-01086999-v`
> score (a spare)

Perhaps these could be merged into a single more general sense?

**Comment by arademaker** [comment]
@jmccrae since it appears you are going to start deep changes in PWN, what is your intension with these issues? How do you plan to solve them? I mean, what is the expected input to answer your question?

**Comment by jmccrae** [comment]
A discussion of this issue and a resolution that can be implemented in the XML data here. The change logs we make here acts as a guide for Princeton, when they come to implement these changes in their version.

**Comment by restinplace** [comment]
I'm with arademaker on this.  Is there any document that lays 
out systemic issues in PWN, along with approaches to addressing 
them, and ensuring that "solutions" have been evaluated by 
qualified (sigh ... by which I mean over-educated and/or 
excessively well-read, preferably with some understanding of 
lexicography) native speakers?

**Comment by arademaker** [comment]
The second synset has an intransitive frame.

**Comment by dcillessen** [comment]
We could tack "convert" on to ewn-01114241-v "score, hit, tally, rack up" considering the use of all these terms across a multitude of sports.  I don't think we would lose much by getting rid of the redundancy and centralizing the relations associated with ewn-01087135-v, ewn-01087277-v, and ewn-01086999-v.

**Comment by Ciara97olo** [comment]
I agree with @dcillessen, each of them are already linked as hypernym with ewn-01114241-v and are terms used in relation to various sports.

**Comment by jmccrae** [comment]
I wonder if we are losing an important shade of meaning here as 'converting' has to come from a specific situation in a game.
For example Oxford's definition
> Score from (a penalty kick, pass, or other opportunity) in a sport or game.
suggests that convert is a hyponym of 'score', perhaps merging these senses together may be a better solution?
