### ISSUE TITLE
"changed" in a geographical meaning

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#62]
There is a sense of "changed" `ewn-01535138-s` "changed in constitution or structure or composition by metamorphism; "metamorphic rocks". Corpus evidence seems to show no sign of this being used in a geological and the usage of this sense seems to be clearly educational, e.g.,

https://www.lcps.org/cms/lib/VA01000195/Centricity/Domain/11412/PDF%20-%20Metamorphic%20Rocks%201a.pdf

**Comment by arademaker** [comment]
not clear what are you suggesting here.

**Comment by dcillessen** [comment]
The [Wikipedia page on "metamorphism"](https://en.wikipedia.org/wiki/Metamorphism) seems to be describing this kind of change. 

Nonetheless, I think we can delete ewn-01535138-s.  It is essentially the same as ewn-00353817-s, but used in an unnecessarily specific context.
