### ISSUE TITLE
"highly sensitive" is not a valid term

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#63]
The synset "highly sensitive" `ewn-02111676-s` "readily affected by various agents" seems to just be the hypernym sense "sensitive" with an intensifier not a phrase with a distinct meaning

**Comment by arademaker** [comment]
hyponym sense you mean, right? I agree. suggestion is to remove this synset, right?

**Comment by jmccrae** [comment]
yes, indeed
