### ISSUE TITLE
soccer players and other sports

### ISSUE THREAD

**Issue by KirilSimov** [globalwordnet/english-wordnet#647]
Dear All,

Here are some problems with the definitions of the players in different disciplines:
================
(n) goalkeeper, goalie, goaltender, netkeeper, netminder the soccer or hockey player assigned to protect the goal
Hypernyms (2)
(n) soccer player an athlete who plays soccer
MORE ▶
(n) hockey player, ice-hockey player an athlete who plays hockey
MORE ▶
================
Here the problem is the multiple inheritance if it is strict - goalkeeper in the two sports have different characteristics
If it is not strict then it is ok.

Bur for:

(n) forward the person who plays the position of forward in certain games, such as basketball, soccer, or hockey
Hypernyms (1)
(n) basketball player, basketeer, cager an athlete who plays basketball
MORE ▶

The definition mentions  basketball, soccer, or hockey, but it is only a hyponym of basketball player.

With best regards,

Kiril

**Comment by jmccrae** [comment]
Yeah, the definition of hypernym includes "if X is a hypernym of Y, then all Y are X." See https://globalwordnet.github.io/gwadoc/#hypernym

I guess that the hypernym of 'goalkeeper' should then be changed to 'athlete' and 'player'

**Comment by KirilSimov** [comment]
Dear John,

This is also my understanding. In our wordnet (for Bulgarian) we included several
sinsets for goalkeeper under 'athlete'.

With best regards,

Kiril
