### ISSUE TITLE
Change sense ID schema

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#662]
The IDs we use on sense's XML will be changed to resemble the PWN sense IDs.

For example
```xml
<Sense id="ewn-street_credibility-n-04791753-01" n="0" synset="ewn-04791753-n" dc:identifier="street_credibility%1:07:00::"/>
```

Will become

```xml
<Sense n="0" synset="ewn-04791753-n" id="street_credibility__1:07:00::"/>
```

NB `%` is not a valid XML identifier character so will be replaced by `__`
NB The loss of the sense ordering will be fixed by #660 so this can only be implemented after this issue

**Comment by jmccrae** [comment]
Following on from #749 it seems that colons are challenging. The alternative suggestion is to replace the colons in PWN sense IDs with periods and use `__` to replace the `%` in IDs. Following on from the previous example, we would have:

```xml
<Sense n="0" synset="ewn-04791753-n" id="street_credibility__1.07.00.."/>
```

Are there any objections?

**Comment by ekaf** [comment]
From my point of view, periods seem fine.

**Comment by jmccrae** [comment]
Okay, I think we go ahead with this schema using `.` in place of `:`
