### ISSUE TITLE
"Kingdom of The Netherlands" is distinct from the "Netherlands"

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#68]
Referring to `ewn-08968866-n` (The Netherlands, Nederland, Kingdom of The Netherlands, Netherlands, Holland) 
> a constitutional monarchy in western Europe on the North Sea; half the country lies below sea level

However, the Kingdom of the Netherlands consists of four parts: the Netherlands, Aruba, Curaçao and Sint Maarten. (see https://en.wikipedia.org/wiki/Kingdom_of_the_Netherlands)

**Comment by arademaker** [comment]
Maybe we can have a wiki page describing the idea of the labels. You added `synset member` and `new synset` but this can also be solved by editing the gloss, right?

**Comment by jmccrae** [comment]
I think in this case we need to introduce a new synset to distinguish between the European part of the Netherlands and the four parts together,

You can see (and improve) the definition of labels by clicking on the cog icon above
