### ISSUE TITLE
Hypernyms contradiction

### ISSUE THREAD

**Issue by ZaraKancheva** [globalwordnet/english-wordnet#682]
There is a contradiction in the hypernyms of ewn-10237713-n "Ivy Leaguer" a student or graduate at an Ivy League school. 
It has two hypernyms - ewn-10685137-n "student, pupil, educatee" a learner who is enrolled in an educational institution and ewn-09805779-n "alumnus, alumna, alum, graduate, grad" a person who has received a degree from a school (high school or college or university). The first one is a person who is still studying and the second - a person who has graduated. 
Probably "Ivy Leaguer" could be divided in two synsets.

**Comment by jmccrae** [comment]
I guess splitting the synset is the only way to handle this as there is no convenient co-hyponym

**Comment by ekaf** [comment]
The gloss is an instance of #109 (Glosses containing 'or'), which @arademaker recommends to examine globally. This is an inclusive 'or' meaning the set union of both hypernym sets.
