### ISSUE TITLE
Observations about "buffet"

### ISSUE THREAD

**Issue by radev2711** [globalwordnet/english-wordnet#683]
The synsets for the lemma "buffet" are divided into one as a piece of furniture ewn-02915411-n buffet, counter, sideboard a piece of furniture that stands at the side of a dining room; has shelves and drawers and one as establishment ewn-04254864-n  snack bar, snack counter, buffet usually inexpensive bar which seems to have problem with its hypernym ewn-02792510-n bar a counter where you can obtain food or drink leading back to the the furniture. Maybe the hypernym needs to be the ewn-02800154-n  barroom, bar, saloon, ginmill, taproom a room or establishment where alcoholic drinks are served over a counter.

**Comment by jmccrae** [comment]
There is a case of synecdoche here, a 'bar' is used in 02800154-n to refer to the whole establishment but in ewn-02792510-n it remains as a reference to just the bar itself. These are valid sense distinctions but also unlikely to be cognitively highly distinct and so there is an argument that we should have a merged sense of 'bar'. At any rate, considering non-alcoholic 'snack bars' to be furniture and alcohol-serving 'bars' to be rooms is inconsistent.

I am not sure if there is an obvious resolution to this, but it is something we should also consider this in issue #243 on making sense distinctions.

**Comment by jmccrae** [comment]
After reviewing this and with no further comments, I will close this issue without any changes.
