### ISSUE TITLE
Wrong definition and hypernym

### ISSUE THREAD

**Issue by ZaraKancheva** [globalwordnet/english-wordnet#684]
The definition and hypernym (ewn-00017402-n plant, flora, plant life (botany) a living organism lacking the power of locomotion) of ewn-11551166-n endemic a plant that is native to a certain limited area "it is an endemic found only this island" is wrong - both plants and animals can be endemic.

**Comment by jmccrae** [comment]
Seems reasonable. The fix is:

Update definition of `11551166-n` to "a plant **or animal** that is native to a certain limited area".
Change hypernym of `11551166-n` to `00004475-n`

Supported by other dictionaries, e.g., 
https://www.lexico.com/definition/endemic
