### ISSUE TITLE
Merge "Operation Desert Storm" and "Gulf War"

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#69]
These seen to refer to the same war 

Operation Desert Storm `ewn-01292124-n`
> the United States and its allies defeated Iraq in a ground war that lasted 100 hours (1991)

Gulf War `ewn-01309581-n`
> a war fought between Iraq and a coalition led by the United States that freed Kuwait from Iraqi invaders; 1990-1991

**Comment by arademaker** [comment]
Hi @jmccrae these are synsets introduced in PWN 3.1, right? I didn't find them in PWN 3.0.

**Comment by jmccrae** [comment]
No, they are present in 3.0 as well. ILI codes are `i42219` and `i42149`

**Comment by arademaker** [comment]
Sorry, I found them. But https://en.wikipedia.org/wiki/Gulf_War says

> The Gulf War (2 August 1990 – 28 February 1991), codenamed Operation Desert Shield (2 August 1990 – 17 January 1991) for operations leading to the buildup of troops and defense of Saudi Arabia and Operation Desert Storm (17 January 1991 – 28 February 1991) in its combat phase, was a war waged by coalition forces from 35 nations led by the United States against Iraq in response to Iraq's invasion and annexation of Kuwait arising from oil pricing and production disputes.

So despite `Operation Desert Storm` being redirected to `Golf War` entry, the paragraph says that the first is `part of` the second. This is modeled in PWN.
