### ISSUE TITLE
Update synsets for "disabled"

### ISSUE THREAD

**Issue by Ciara97olo** [globalwordnet/english-wordnet#703]
1. ewn-07962874-n "disabled, handicapped": people collectively who are crippled or otherwise physically handicapped 
"technology to help the elderly and the disabled"
2. ewn-01022875-s disabled, handicapped: having restricted mental or physical functioning as a consequence of injury or illness

Firstly, the term "handicap" is considered a slur by many people and the entry should be moved from these synsets and identified as a slur.
https://en.wikipedia.org/wiki/List_of_disability-related_terms_with_negative_connotations

The first synset only includes physical disabilities which is incorrect, also the word "crippled" should not be included in the definition. 

The phrasing of the second synset should be updated and bettered. It should specify that restricted mental or physical functions may only apply to certain activities or areas of life. I also do not like the use of the term "consequence" as it has negative connotations, which should be avoided in definitions for these synsets. 
http://nda.ie/disability-overview/definitions/
"Disability means:
(a) the total or partial absence of a person’s bodily or mental functions, including the absence of a part of a person’s body;
(b) the presence in the body of organisms causing, or likely to cause, chronic disease or illness;
(c) the malfunction, malformation or disfigurement of a part of a person’s body;
(d) a condition or malfunction which results in a person learning differently from a person without the condition or malfunction; or
(e) a condition, disease or illness which affects a person’s thought processes, perception of reality, emotions or judgement or which results in disturbed behaviour."

**Comment by jmccrae** [comment]
Add relation `exemplifies` 'slur' `oewn-06731387-n`
