### ISSUE TITLE
Is "North Peak" actually "Denali"?

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#71]
I think this mountain may be a duplicate

North Peak `ewn-09396534-n`
> 19,370 feet high
(!) Yes this is all the information we have

McKinley, Mount McKinley, Mt. McKinley, Denali `ewn-09372322-n`
> a mountain in south central Alaska; the highest peak in North America (20,300 feet high)

**Comment by arademaker** [comment]
But we have https://en.wikipedia.org/wiki/Denali and https://en.wikipedia.org/wiki/North_Peak.  An `North Peak` as not in PWN 3.0.

**Comment by jmccrae** [comment]
I excluded the Nevadan mountain as it is ¼ of the size. The Alaskan mountain is sometimes called North Peak and is closer in size but I am not really sure...

**Comment by jmccrae** [comment]
Also the synset is part of the Alaska Range according to Wikipedia, it must refer to this place

https://www.google.com/maps/place/North+Peak/@63.0977868,-151.281818,10z/data=!4m5!3m4!1s0x56cdef4a7e0c8ae5:0xb885900487eac664!8m2!3d63.0977778!4d-151.0016666

It does seem to be distinct from Denali. So I propose a new definition: 'mountain peak in Alaska close to Denali, 19,370 feet high'

**Comment by arademaker** [comment]
We could consider a systematic revision of geonames based on the article 

geoNames Wordnet (gnwn): extracting wordnets from GEoNames, Francis Bond and Arthir Bond, GWC 2019.

**Comment by jmccrae** [comment]
In the long run, we will do something like this. For the moment, I propose freezing the list of geographical place names. The reason to fix this one is that it was ambiguous, a better definition will fix this.
