### ISSUE TITLE
Merge "Ningirsu" and "Ninurta"

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#72]
These refer to the same deity

Ninib, Ninurta `ewn-09544292-n`
> a solar deity; firstborn of Bel and consort was Gula; god of war and the chase and agriculture; sometimes identified with biblical Nimrod

Ningirsu `ewn-09543752-n`
> Babylonian god in older pantheon: god of war and agriculture

**Comment by arademaker** [comment]
This can be very culture specific. Not sure.

**Comment by jmccrae** [comment]
Wikipedia seems happy to consider these the same deity:
https://en.wikipedia.org/wiki/Ninurta
