### ISSUE TITLE
Observation about the lemma  "madame"

### ISSUE THREAD

**Issue by radev2711** [globalwordnet/english-wordnet#725]
I believe there is a contradiction in the synset ewn-10299475-n madame title used for a married Frenchwoman
If the definition says that the concept is a type of title why its hypernym is not ewn-06350786-n title, title of respect, form of address an identifying appellation signifying status or function ?

Maybe the definition or the hypernym of madame need to be changerd.

**Comment by jmccrae** [comment]
I think I would prefer to move the hypernym to `06350786-n` so that it fits with other forms of address like 'Frau' and 'Senora'.
