### ISSUE TITLE
selfish vs self-seeking / self-serving

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#750]
**Synsets**

1. ewn-02105605-a selfish concerned chiefly or only with yourself and your advantage to the exclusion of others "Selfish men were...trying to make capital for themselves out of the sacred cause of civil rights"- Maria Weston Chapman
2. ewn-02106198-s  self-serving, self-seeking interested only in yourself

**Motivation**

As a non-native speaker, I am not sure, but they seems to be quite similar by the definitions.

**Comment by jmccrae** [comment]
This is yet another case of #35 :)

There is also the synset for 'self-centered' that could be also be merged in

`ewn-00102561-a` (Interlingual Index: i538)
(a) egoistic, egoistical, egocentric, self-centered, self-centred 
> limited to or caring only about yourself and your own needs
