### ISSUE TITLE
Remaining illegal colon in ID

### ISSUE THREAD

**Issue by 1313ou** [globalwordnet/english-wordnet#751]
[E] attribute "id" has a bad value: "ewn-capital:_critique_of_political_economy__1_10_01__" does not satisfy the "ID" type [row,col,system-id]: [47060,7,"file:src/xml/wn-noun.communication.xml"]

This colon however is not a field separator in the sense key but part of the lemma. This is the only instance of this happening in a lemma and has already been noted as strange. Unless specific escaping is applied, it makes this sense key unparseable.

**Comment by ekaf** [comment]
This lemma refers to the seminal book by Karl Marx. The part after the colon is the book's subtitle, and should not necessarily be included. Or maybe the synset could include both the short form, and the long form with the colon escaped.
