### ISSUE TITLE
Senorita in English Wordnet

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#755]
**Synset**

ewn-06353552-n (Interlingual Index: i69807)

(n) Senorita `senorita%1:10:00::` a Spanish title or form of address used to or of an unmarried girl or woman; similar to the English `Miss'

**Motivation**

It doesn't make sense to have a synset for a Spanish word in the English Wordnet..  There are other cases (classifiedBy Spanish and German)

**Comment by jmccrae** [comment]
This word is widely used by English speakers with no knowledge of Spanish as supported by corpus evidence and other dictionaries, so I think it is part of the English language too.

**Comment by jmccrae** [comment]
As a side issue, we now support Unicode so we can add the lemma señorita also.

**Comment by arademaker** [comment]
Does this argument support also the other cases that I mentioned? German words? 

For "corpus evidence and other dictionaries", hard to be precise here right? What dictionaries? 

It has:

https://en.m.wiktionary.org/wiki/senorita#English 

https://www.merriam-webster.com/dictionary/senorita

It doesn't have:

https://dictionary.cambridge.org/spellcheck/english/?q=senorita

What corpus? How many occurrences count as sufficient for evidence?

Sorry, I just intend to be more precise for decisions.

**Comment by jmccrae** [comment]
The other examples are "don", "dona", "senora", "Frau", "Fraulein" and "Herr"? I would assume all of these are fine too but I can check.

The guidelines (which are here https://github.com/globalwordnet/english-wordnet/blob/master/NEW_SYNSETS.md) state that it must be at least 100 occurrences in Sketch Engine TenTen's corpus*. There are 3,788 for Senorita, so this is fine.

Similarly it is listed in at least one of our reference dictionaries (listed here https://github.com/globalwordnet/english-wordnet/blob/master/DICTIONARIES.md), so it also passes here. As such, there would be a clear case for including this word if it was a new synset proposal... also the arguments for deleting a synset need to be stronger than for creating a new synset.

* This resource is not free and this IS problematic. I created issues #756
