### ISSUE TITLE
the prefix "ewn" clashes with the Estonian Wordnet (ewn)

### ISSUE THREAD

**Issue by fcbond** [globalwordnet/english-wordnet#759]
The Open English Wordnet has changed its label to 'oewn', but not the string it uses to prefix synsets, sense and so forth.

This means that identifiers may conflict with the Estonian wordnet (which has been using 'ewn' for a long time).   I realize that with the identifier being part of the ids, this is actually a big change.  On the other hand, I think it is going to save a lot of trouble in the long term if we try not to have conflicting labels.  Given that, we need a policy to decide who gets what, I have been going with the first to use the label in an open release with a public upload (the criteria we have for adding to OMW).  Albanian wordnet was conflicting with Arabic wordnet (both 'awn') and  was kind enough to change.

**Comment by jmccrae** [comment]
Seems reasonable to adopt `oewn`. I have made a PR for this change.
