### ISSUE TITLE
inflect form is necessary? 

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#761]
**Affected synsets**

02472293-n human, homo, man, human_being | (any living or extinct member of the family Hominidae characterized by superior intelligence, articulate speech, and erect carriage)

02472987-n man, humanity, human_beings, humankind, human_race, humans, mankind, world | (all of the living human inhabitants of the earth; "all the world loves a lover"; "she always used `humankind' because `mankind' seemed to slight the women")

**Proposed changes**

We have `human_being` (any living member...) and `human_beings` (the plural form used as another sense). Does it make sense?

**Motivation**

It seems to have a inflect form not necessary in the 02472987-n because for the sense 02472293-n taken in the plural, we have the collective sense 02472987-n

**Comment by arademaker** [comment]
armed_service vs armed_services

**Comment by jmccrae** [comment]
There are plenty of English words that appear only in the plural ('scissors', 'trousers' etc.) and all these senses should be marked as `exemplifies 06306016-n` (plural).

In this case these terms lack this link so I think this needs to be fixed, otherwise I am happy to keep these plural forms in.
