### ISSUE TITLE
Is English wordnet a strict superset of wordnet? 

### ISSUE THREAD

**Issue by LifeIsStrange** [globalwordnet/english-wordnet#762]
Hi,
I am new to this.
The goal of having a semantically structured "dictionary" like wordnet is huge. It require a lot of human resources to reach completeness and correctness.
I have no idea how is the guidance of the original Princeton wordnet.
If I'm guessing correctly, the Princeton wordnet is not collaboratively edited and I cannot suggest change like we would on Wikipedia or github?
Hence the reason of this repository?
If so then that is extremely disappointing that most projects use the obscolete Princeton wordnet edition instead of the open source one.
I also don't understand why Google & ci aren't funding this project, it is obviously a fundamental key to progress in natural language understanding. Those are the kind of ineptia that make me lose faith in NLP.

It would be very interesting to make the second best program on word sense disambiguation use this wordnet instead of the Princetonian one
https://paperswithcode.com/sota/word-sense-disambiguation-on-supervised
Since it would discover more hypernyms it could have increased accuracy at this foundational task.

However the Princeton wordnet evolve too and it would be nice to rebase this projects on Princeton changes, periodically.
(if you already do so then please precise it on the Readme)

**Comment by rwingerter55** [comment]
I think this paper will answer your questions: http://john.mccr.ae/papers/mccrae2019english.pdf.

**Comment by LifeIsStrange** [comment]
thanks

**Comment by LifeIsStrange** [comment]
@rwingerter55 BTW https://en-word.net/ is down

**Comment by jmccrae** [comment]
Thanks @rwingerter55 for the quick answer. The online interface is down due to a cyber attack on our network: https://www.irishtimes.com/news/education/attempted-cyberattack-causes-disruption-at-nui-galway-1.4687787
