### ISSUE TITLE
Add reverse links for 'pertainym' and 'also'?

### ISSUE THREAD

**Issue by goodmami** [globalwordnet/english-wordnet#768]
**The source synset**
**The target synset**

There are too many to list here, but I can provide a list.

**The relation**

`pertainym` and `also`

**Motivation**

In https://github.com/globalwordnet/english-wordnet/issues/747#issuecomment-941751543 I brought up that the reverse relations for `pertainym` and `also` were not provided, despite them being their own reverse relation according to https://globalwordnet.github.io/gwadoc/. It appears this is intentional, so I am raising this issue to discuss whether they should be included in future versions.

Here is an example where, unlike `derivation`, `pertainym` is not reciprocated:

```console
$ sed -rn '/id="(oewn-astute__5.00.00.smart.00|oewn-astutely__4.02.00..|oewn-astuteness__1.09.00..)"/,/<\/Sense>/p' english-wordnet-2021.xml 
      <Sense id="oewn-astute__5.00.00.smart.00" synset="oewn-00440649-s">
        <SenseRelation relType="derivation" target="oewn-astuteness__1.09.00.." />
        </Sense>
      <Sense id="oewn-astuteness__1.09.00.." synset="oewn-05629222-n">
        <SenseRelation relType="derivation" target="oewn-astute__5.00.00.smart.00" />
      </Sense>
      <Sense id="oewn-astutely__4.02.00.." synset="oewn-00274018-r">
        <SenseRelation relType="pertainym" target="oewn-astute__5.00.00.smart.00" />
        </Sense>
```

@ekaf responded in https://github.com/globalwordnet/english-wordnet/issues/747#issuecomment-941946044:

> @goodmami Traditionally, according to the *wninput* manual page, *grind* used to limit the number of relations that are their own reverse relation to the following 5, which have eventual missing symmetric pointers added automatically: Antonym, Similar to, Attribute, Verb Group, Derivationally Related.
Many other relations have missing *inverse* pointers added automatically (for ex: hypernyms as inverse of hyponyms), but not *pertainyms* and *also*. So yes, it is probably intentional that these relations are not checked for symmetry, although it would make sense to extend this treatment to all Wordnet relations, since all relations admit an inverse relationship in theory, though not in practice yet.

I was using the reverse/inverse relations described in the [GWADoc](https://globalwordnet.github.io/gwadoc/) pages, which go beyond those applicable to the English wordnet. It also says for `pertainym` that since the wordnet does not say which end of the relation is the base form (e.g., *astute* or *astutely*, or *lunar* and *moon*), the relation is fully reversible. I'm curious whether we should aim to provide the reverse for these.

**Comment by jmccrae** [comment]
The `pertainym` relations is not symmetric as it is a cross-part-of-speech, primarily between adjectives (British, French, etc.) and the corresponding nouns (Britain, France, etc.). We would have to introduce a new relation type and I don't see the value of this.

`also` is symmetric and this is enforced by the validation checks.

**Comment by fcbond** [comment]
G'day,

in terms of people using the lexicon, I think people are as likely to want to go from Britain to British as vice-versa.  Of course, we can always write tools to allow people to do this, but I think it makes sense to reflect this in the data structure.   I don't see the need to add a new relation, the part of speech should tell us which pertains to which.

**Comment by jmccrae** [comment]
Actually the YAML data structure specifically avoids reverse links whether possible (e.g., we only indicate hypernyms not hyponyms) to avoid editor effort. The release formats such as XML could add new relations that are inferred from the YAML, but there is currently no support for this in the XML or the WNDB format. The former is easy to change, the later not so much.

**Comment by arademaker** [comment]
I didn't understand the @fcbond comments. It makes sense to have the inverse relations explicit defined in the lexicon but it is not necessary. So what is the final suggestion?

**Comment by jmccrae** [comment]
I would close this issue. The original request is already implemented for `also` links

For pertainyms, these currently represent a specific syntactic relation as described here:

> Relational adjectives ("pertainyms") point to the nouns they are derived from (criminal-crime). 
There are only few adverbs in WordNet (hardly, mostly, really, etc.) as the majority of English adverbs are straightforwardly derived from adjectives via morphological affixation (surprisingly, strangely, etc.) (from https://wordnet.princeton.edu/)

I would however be in favour of introducing a new relationship between synsets that captures the relationship between pertainyms at a purely semantic level. This relationship could have an inverse as desired by @fcbond
