### ISSUE TITLE
Deriving sensekey from escaped id

### ISSUE THREAD

**Issue by 1313ou** [globalwordnet/english-wordnet#770]
Could we have a note about how to derive the sensekey from the Sense id ? It's now such a hassle !

Plus : the lemma seems to be encoded differently (in the xml files) if it is in the adj head position, as witnessed by accustomed_to / accustomed-sp-to

```
wn-adj.all.xml:      <Sense id="oewn-accustomed_to__3.00.00.." n="0" synset="oewn-00024458-a">
```
```
wn-adj.all.xml:      <Sense id="oewn-wont_to__5.00.00.accustomed-sp-to.00" adjposition="p" n="0" synset="oewn-00024701-s">
wn-adj.all.xml:      <Sense id="oewn-used_to__5.00.00.accustomed-sp-to.00" adjposition="p" n="0" synset="oewn-00024701-s"/>

```

**Comment by jmccrae** [comment]
There is an implementation here for those who wish to do this:

https://github.com/globalwordnet/english-wordnet/blob/master/scripts/wordnet_yaml.py#L14

I am not sure what else you would want?

**Comment by 1313ou** [comment]
Just my luck. I relied on sibling script wordnet.py
https://github.com/globalwordnet/english-wordnet/blob/master/scripts/wordnet.py#L758 
which seems to be doing things slightly differently. 
-sp-, -cl-, -lb-, -rb are cases in point.

**Comment by jmccrae** [comment]
Also if we accept #664 then the XML files will be removed and the remaining YAML files will simply use the sense identifiers in the same format as Princeton.

**Comment by jmccrae** [comment]
As #664 has been accepted, this issue can be closed.
