### ISSUE TITLE
"sleep with" slut shaming

### ISSUE THREAD

**Issue by malangali** [globalwordnet/english-wordnet#772]
**Synset**
oewn-01429048-v sleep with

**Example**
Remove: This student sleeps with everyone in her dorm.
Possible replacement: Genghis Khan slept with so many women that an estimated 1.6 billion people alive today are related to the Mongolian ruler.

**Motivation**
This sentence does not illustrate the concept in any way, but unnecessarily conjures up a negative sexual stereotype. The suggested replacement is an actual sentence from the Google, which clearly illustrates the sexual aspect of the term.

**Comment by 1313ou** [comment]
Controversial example wrt facts. Here is a comment from the same Facebook site (Weird History):

> "Related to" is misleading, as fewer than 20 million are estimated to be "direct descendants" (still a lot but...)

**Comment by jmccrae** [comment]
Yeah, I am not sure about this new example either. With new examples it is also better to add a source also.

**Comment by malangali** [comment]
I agree, the example is weak. How about this:

For many people it’s a tricky subject to broach but something they’re desperate to know: how many others their partner has slept with before them.

From before the paywall at THE IDEAL NUMBER OF SEXUAL PARTNERS TO HAVE BEFORE SETTLING DOWN, STUDY REVEALS, The Independent, 04 May 2017, https://www.independent.co.uk/life-style/love-sex/ideal-number-sexual-partners-settling-down-sex-man-woman-marriage-study-a7717571.html

**Comment by ekaf** [comment]
First, the example doesn't say that the student is a slut. Next, why would the same behaviour not lead to likewise conclusions for a man, even Gengis Khan? Moreover, we can infer that this student does not discriminate against minorities.

**Comment by malangali** [comment]
> The current example doesn't explicitly call the student a slut, so where is the shaming? Also, why would the same behaviour not lead to similar conclusions about a male ruler? Moreover this student appears to not discriminate against minorities.

The current example does not illustrate the concept of sleeping with, in any way, the way  "the car is red" technically contains the word red, but does not give adequate insight into redness. Does she go from room to room in her dorm and cuddle up with her classmates for a good night's snooze? Do they all get together in the common room and pass out en masse? Does she sleep with them the way a mob enemy might sleep with the fishes? No matter how you slice it, it is a good example of a really bad example.

**Comment by jmccrae** [comment]
Before this conversation gets too far off-course, can I just remind you that we can choose examples from the whole of the English language. As such, we have lots of opportunity to avoid choosing examples that may cause offense, even very slightly.

This is also in line with efforts at other lexicographic projects: https://www.theguardian.com/books/2020/nov/07/oxford-university-press-updates-definitions-word-woman

**Comment by EnejdaN** [comment]
A more neutral example could be as follows: 

Most healthcare providers recommend that individuals get tested for STI’s before sleeping with a new partner.

This is not a direct quote as most medical websites do not use the term sleep with, but I think this is good direction to go in as it avoids any negative connotations regarding the act of sleeping with someone.
