### ISSUE TITLE
Synset offset problems in data.verb

### ISSUE THREAD

**Issue by ekaf** [globalwordnet/english-wordnet#776]
**Release format**
WNDB

**Describe the bug**
Synset offset problems in data.verb in the new OEWN 2021 release

**To Reproduce**

> grep 2766066 {data.verb,index.sense,index.verb}

```
index.sense:stress%2:29:01:: 02766066 4 0
index.verb:stress v 4 3 + @ ~ 4 0 01007737 00977858 01791013 02766066  

```
**Expected behavior**

The 02766066 offset should exist in data.verb, but it doesn't

**Additional context**

The test by @mirfan899 (#771), which recently succeeded, now fails:

```
  File "/home/E/Prog/Script/py/Nltk/Branches/Develop/nltk/corpus/reader/wordnet.py", line 1554, in _synset_from_pos_and_line
    sense_index = offsets.index(synset._offset)
ValueError: 2764280 is not in list

```

This is the converse problem: the 2764280 offset is in data.verb, but not in the indexes.

**Comment by ekaf** [comment]
Joining data verb with the verb offsets in index.sense fails with the following statistics:
```
  70 Missing index
  69 Missing data
 139 total

```
Maybe the fact that these numbers are roughly balanced in both files could explain something?

**Comment by jmccrae** [comment]
Fixed (cause of this was I did something stupid)
