### ISSUE TITLE
Roman as a pertain adjective

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#780]
**Synsets**

oewn-02932882-a (Interlingual Index: i16638)
(a) Roman relating to or characteristic of people of Rome “Roman virtues” “his Roman bearing in adversity” “a Roman nose”

oewn-02933399-a (Interlingual Index: i16640)
(a) Roman characteristic of the modern type that most directly represents the type used in ancient Roman inscriptions

oewn-02932638-a (Interlingual Index: i16637)
(a) Roman, Romanic of or relating to or derived from Rome (especially ancient Rome) “Roman architecture” “the old Roman wall”

**Motivation**

Do we need these 3 senses for Roman?

**Comment by jmccrae** [comment]
I think the 1st one should be deprecated. It also unusually pertains to the noun 'Roman', rather than the place 'Rome' like most adjectives of this type.
