### ISSUE TITLE
Delete synset oewn-07251287-n "lodgement, lodgment"

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#790]
**Synset**
oewn-07251287-n "lodgement, lodgment"

Definition: "bringing a charge or accusation against someone"

**Motivation**
The synset should be deleted because this meaning is not widely used. 
There are other meanings of lodgement which seem to be more common. 

Cf. 
https://www.ahdictionary.com/word/search.html?id=L5241200
https://www.collinsdictionary.com/dictionary/english/lodgment
https://dictionary.cambridge.org/de/worterbuch/englisch/lodgement
https://www.merriam-webster.com/dictionary/lodgment

**Comment by jmccrae** [comment]
If we can find no corpus evidence or other dictionaries listing this sense we can delete this synset. I am certainly not aware of this meaning and no other dictionary lists it.
