### ISSUE TITLE
The 2021 release uses the 1.1 DTD but not the lexfile attribute

### ISSUE THREAD

**Issue by fcbond** [globalwordnet/english-wordnet#794]
**Release format**
Delete as required: LMF

**Describe the bug**
Lexicographer files (topics) are stored as `dc:subject="noun.animal"`, however the `WN-LMF-1.1.dtd` defines an attribute `lexfile`, which should be preferred.

**To Reproduce**
Download the release

**Expected behavior**
The attribute on synset used to store the lexicographer file name should be  `lexfile`

**Additional context**
It should be a simple change to `wordnet.py`:
```
"""    <Synset id="%s" ili="%s" members="%s" partOfSpeech="%s" dc:subject="%s"%s> """ %
```
becomes:
```
"""    <Synset id="%s" ili="%s" members="%s" partOfSpeech="%s" lexfile="%s"%s> """ %
```

**Comment by fcbond** [comment]
Without fixing this, the wn python module will not find the lexigorapher files, which I think are used often enough it is worth fixing the release for: @goodmami, @jmccrae  what do you think?

**Comment by goodmami** [comment]
While the oversight is unfortunate, I'm not sure it's worth it to re-release 2021. I think this can wait for 2022. Having the lexicographer file name in `dc:subject` isn't invalid according to the schema, it's just less obvious than if it were to use the dedicated `lexfile` attribute.

As for Wn, you can get it from the metadata:

```pycon
>>> import wn
>>> oewn = wn.Wordnet('oewn:2021')
>>> oewn.synsets('brown bear')[0].metadata()['subject']
'noun.animal'
```
