### ISSUE TITLE
oewn-04845441-n "brass, face, boldness, cheek, nerve"

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#796]
**Synset**
oewn-04845441-n 
Lemmas: brass, face, boldness, cheek, nerve 
Definition: impudent aggressiveness 

**Example**
Example 2 uses the word "effrontery", which is not part of the synset; it could be replaced by "cheek". 
2. “he had the effrontery to question my honesty” --> “he had the cheek to question my honesty”

**Motivation**
Examples should use the words belonging to the synset.

**Comment by arademaker** [comment]
Why not add "effrontery" in the synset?

**Comment by rwingerter55** [comment]
@arademaker, I proposed to change the example for formal reasons. After checking a couple of dictionaries, I don't think there is a strong case for adding "effrontery" as a synonym.
