### ISSUE TITLE
New synset "homework" (schoolwork to do at home)

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#797]
**Lemmas**
Lemma: "homework"

**Definition**
"Work, such as schoolwork or piecework, that is done at home."
https://www.ahdictionary.com/word/search.html?q=homework

"work that teachers give their students to do at home"
https://dictionary.cambridge.org/de/worterbuch/englisch/homework

"Homework is school work that teachers give to pupils to do at home in the evening or at the weekend."
https://www.collinsdictionary.com/dictionary/english/homework

"Work that is done at home, especially school exercises assigned by a teacher."
https://en.wiktionary.org/wiki/homework

**Relation**
Hypernym: oewn-00729939-n
Lemmas: "school assignment, schoolwork"
Definition: "a school task performed by a student to satisfy the teacher"

Different, more specific sense of "homework": 
oewn-00730406-n 
Lemmas: "preparation, homework, prep"
Definition: "preparatory school work done outside school (especially at home)"

**Significance**
Yes :-)

**Comment by jmccrae** [comment]
Are you suggesting that oewn-00730406-n should be a hypernym of the new synset? If so, we generally try to avoid having the same lemma as a hypernym of itself, so I would remove 'homework' from the existing synset and update the definition.

**Comment by rwingerter55** [comment]
Thank you, that's fine.
