### ISSUE TITLE
missing relation

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#80]
(bend one's knee or body, or lower one's head; "He bowed before the King"; "She bowed her head in shame") http://wnpt.brlcloud.com/wn/synset?id=00898691-v is hyponym of gesture (http://wnpt.brlcloud.com/wn/synset?id=00992041-v)

Why kneel (http://wnpt.brlcloud.com/wn/synset?id=01545649-v) is not also hyponym of gesture http://wnpt.brlcloud.com/wn/synset?id=00992041-v?

**Comment by jmccrae** [comment]
@arademaker the proposal is to add `ewn-00994073-v` (gesture) as a hypernym of `ewn-01548431-v` (kneel). Instead of (or as well as) `ewn-01548665-v` (rest)?
