### ISSUE TITLE
Incorrect plural forms for duodenum, hymenium, and substratum

### ISSUE THREAD

**Issue by goodmami** [globalwordnet/english-wordnet#800]
I came across this when testing the predictability of irregular plural forms.

**Affected entries**

(all of these are nouns)

* duodenum
* hymenium
* substratum

**Proposed changes**

Change exceptional (plural) forms to:

* duodena
* hymenia
* substrata

**Motivation**

I made the assumption that for nouns ending in 'm' or 'n' with an exceptional form ending in 'a' that the latter is an irregular plural (e.g., *medium* -> *media*, *phenomenon* -> *phenomena*) and that they follow the pattern such that up until the last 2 letters of the lemma is the same as up until the last letter of the exceptional form (e.g., *medi-*, *phenomen-*). Where that assumption failed is listed below (found using the Wn library):

```pycon
>>> import wn
>>> en = wn.Wordnet('oewn:2021')
>>> a_plural = {w.lemma(): f
...             for w in en.words(pos='n') if w.lemma()[-1] in 'mn'
...             for f in w.forms() if f.endswith('a')}
>>> len(a_plural)
284
>>> for sg, pl in a_plural.items():
...   if sg[:-2] != pl[:-1]:
...     print(sg, pl)
... 
numen numina
cognomen cognomina
substratum substrasta
praenomen praenomina
agnomen agnomina
limen limina
putamen putamina
foramen foramina
lumen lumina
duodenum duona
rumen rumina
hymenium hynia
stamen stamina
```

Most of these represent a pattern *-men* -> *-mina*, but those that do not are:

```
substratum substrasta
duodenum duona
hymenium hynia
```

The plural forms are not correct. Here is the entry for *hymenium*:

https://github.com/globalwordnet/english-wordnet/blob/6f32afa5c30e720b73c74c0214b53d4613e94fe5/src/yaml/entries-h.yaml#L44417-L44424

Not only is the exceptional plural incorrect, but the supposed regular plural is as well (I don't have any strong intuitions about the spelling, but I don't see *hynia* or *hyniums* as plurals in another dictionary, while *hymenia* is listed).

**Comment by goodmami** [comment]
Thanks for the link, that's a neat project. Unfortunately it doesn't have any nouns for English, so it wouldn't help with the current issue. But in general I'd like to see the wordnet encode the set of morphosyntactic properties on exceptional forms.

**Comment by arademaker** [comment]
I hear about this project in a conference few years ago. Sorry I didn't inspect it closer. I just ask there why only verbs...
