### ISSUE TITLE
"sight" (something worth seeing, a tourist attraction)?

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#802]
**Lemmas**
Lemma: "sight" n.

**Definition**
Cf. these dictionary definitions:

Def: "Something worth seeing; a spectacle"
Ex.: "the sights of London."
https://www.ahdictionary.com/word/search.html?q=sight

Def.: "places of interest, especially to visitors"
Ex.: "We spent a week in Rome looking at all the sights."
https://dictionary.cambridge.org/de/worterbuch/englisch/sight

6. plural noun
Def.: "The sights are the places that are interesting to see and that are often visited by tourists."
Ex.: "I am going to show you the sights of our wonderful city."
https://www.collinsdictionary.com/dictionary/english/sight

3. b) the sights [plural] 
Def.: "famous or interesting places that tourists visit"
Ex.: "In the afternoon, you’ll have a chance to relax or see the sights."
https://www.ldoceonline.com/dictionary/sight

2a : (sually used in plural)
Def.: "a thing regarded as worth seeing"
Ex.: "the sights of the city"
https://www.merriam-webster.com/dictionary/sight

Def.: "Something worth seeing; a spectacle, either good or bad"
Ex.: "We went to London and saw all the sights – Buckingham Palace, Tower Bridge, and so on."
https://en.wiktionary.org/wiki/sight#Noun

**Relation**
"sight" in this sense can be considered as a synonym of: `05853820-n` "tourist attraction".
Def.: "a characteristic that attracts tourists"
Ex.:  --

**Significance**
This sense of "sight" does not exist in OEWN, cf. https://en-word.net/lemma/sight.

**Comment by arademaker** [comment]
what about http://wn.mybluemix.net/synset?id=05853820-n or in the OEWN interface: https://en-word.net/lemma/tourist%20attraction?

**Comment by rwingerter55** [comment]
@arademaker, I agree. I had not been aware of it, until I looked for a suitable place in the hierarchy:

> "sight" in this sense can be considered as a synonym of: 05853820-n "tourist attraction".
