### ISSUE TITLE
New synset "recipe" (directions for making or preparing food dishes)

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#803]
**Lemmas**
"recipe", "cooking recipe"?, noun

**Definition**
"directions for making or preparing food dishes"

**Relation**
Hypernym: oewn-06801642-n (Interlingual Index: i72162)
- Lemmas: "formula, recipe" 
- Definition: "directions for making something"
- Topic: noun.communication

**Significance**
This meaning is included in all our reference dictionaries:

https://www.ahdictionary.com/word/search.html?q=recipe
https://www.collinsdictionary.com/dictionary/english/recipe
https://dictionary.cambridge.org/dictionary/english/recipe
https://www.lexico.com/definition/recipe
https://www.macmillandictionary.com/dictionary/british/recipe
https://www.merriam-webster.com/dictionary/recipe
https://en.wiktionary.org/wiki/recipe

**Comment by arademaker** [comment]
Why do we need this synset if we already have recipe in a more general sense? The cooking recipe is a compositional MWE anyway.

**Comment by jmccrae** [comment]
I would probably also agree with @arademaker. This proposal would create "recipe" as a hyponym of "recipe", which we try to avoid. The concept of "cooking recipe" probably doesn't pass the criterion of non-compositionality in our guidelines 
https://github.com/globalwordnet/english-wordnet/blob/master/NEW_SYNSETS.md

**Comment by rwingerter55** [comment]
You are right, "recipe <hyponym> recipe"  would be ugly. 

But what about

"recipe" <hyponym> "recipe, cooking recipe, food recipe"?

**Comment by arademaker** [comment]
The point is that "cooking recipe" and "food recipe" are both compositional in the first place! Except in situations where collocations help organize the hierarchy, we tend to avoid them.

" ... a few are artificial collocations invented for the convenience of categorization.." Christiane Fellbaum. WordNet: An Electronic Lexical Database (Kindle Location 391). Kindle Edition.

**Comment by rwingerter55** [comment]
IMO "cooking recipe" is not an artificial collocation. Compositional, yes. 

Cf. `oewn-08670545-n` "space", it has a couple of compositional hyponyms:
(n) airspace, air space
(n) crawl space, crawlspace
(n) disc space, disk space 
(n) parking space, parking zone

**Comment by rwingerter55** [comment]
The synset proposed does not pass the criterion of non-compositionality.
