### ISSUE TITLE
oewn-02876106-a "millennian, millennial" - duplicated pertainyms (web application)

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#807]
**Release format**
Web application https://en-word.net

**Describe the bug**
Duplicated Pertainyms from oewn-02876106-a "millennian, millennial" 

**To Reproduce**
1. Go to https://en-word.net/lemma/millennial
2. Click on 'Pertainyms (2)'

**Expected behavior**
No redundant content. 

**Additional context**
None.

**Comment by jmccrae** [comment]
Transferred to https://github.com/jmccrae/wordnet-angular/issues/13
