### ISSUE TITLE
duplicate adverbs?

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#81]
00197710-r jointly 
(in collaboration or cooperation; "this paper was written jointly")

00117082-r collectively, together_with, jointly, conjointly 
(in conjunction with; combined; "our salaries put together couldn't pay for the damage"; "we couldn't pay for the damages with all our salaries put together")

**Comment by jmccrae** [comment]
Change labels ("duplicate" is for issues that have already been reported)

**Comment by jmccrae** [comment]
@arademaker close this issue?

**Comment by arademaker** [comment]
after linking by `similar_to`? Yes at least with that action.
