### ISSUE TITLE
"Can" verb is not included

### ISSUE THREAD

**Issue by noe** [globalwordnet/english-wordnet#811]
**Lemmas**
can

**Definition**
To know how to; to be able to.

Another synset would be "to be permitted or enabled to"

**Relation**
See https://en.wiktionary.org/wiki/can#Verb

**Significance**
"can" is a central verb to English, the question is why it's not already included.

**Comment by rwingerter55** [comment]
I guess it is a deliberate decision of the editors not to include modal verbs (like can, may, must, will, shall).

**Comment by LifeIsStrange** [comment]
But why?? Those verbs are important for language understanding !

**Comment by jmccrae** [comment]
Yes, as @rwingerter55 says the main reason for exclusion is that we do not handle closed part-of-speech classes such as auxiliaries and so this would not fit into the scope of the project. Of course, this is an open source project so it is up to the community to decide what we want to do (and also to do the work of implementing this). I will close this issue and replace with a more general discussion at #818
