### ISSUE TITLE
Verb frames in RDF file

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#815]
**Release format**
RDF (Turtle)

**Describe the bug**
According to Christiane Fellbaum, "English Verbs as a Semantic Net", verb frames should be attached to synsets. But in the RDF file they are attached to lexical entries, like in this example:
```

<https://en-word.net/lemma/acquaint#acquaint-v>
    a ontolex:LexicalEntry ;
    ontolex:canonicalForm <https://en-word.net/lemma/acquaint#acquaint-v-lemma> ;
    ontolex:sense <https://en-word.net/lemma/acquaint#acquaint-oewn-00834439-v>, <https://en-word.net/lemma/acquaint#acquaint-oewn-00875857-v>, <https://en-word.net/lemma/acquaint#acquaint-oewn-00902866-v> ;
    synsem:synBehavior [
        rdfs:label "Somebody ----s somebody PP"@en
    ], [
        rdfs:label "Somebody ----s somebody with something"@en
    ], [
        rdfs:label "Somebody ----s to INFINITIVE"@en
    ], [
        rdfs:label "Somebody ----s somebody"@en
    ] ;
    wn:partOfSpeech wn:verb .
```
**To Reproduce**
Open the Turtle file in a text editor and search for "synsem:synBehavior".

**Expected behavior**
Recreate the RDF file in the correct format if possible. 

**Additional context**
none

**Comment by x-englishwordnet** [comment]
Verb frames have always been attached to senses (not synsets) in Princeton WordNet. This means different verbs in the same synset may differ in the way they are used in a sentence, which seems to be a reasonable (syntactic) assumption. A case in point could be 'wait' and 'await', supposing they are members of the same synset(s). Could we have more on Christiane Fellbaum's claim ? (The article was published in 1990 and the PWN team haven't followed this guideline)

**Comment by rwingerter55** [comment]
IMHO word senses would be the best solution. Can it be done?

This is the quote by Christiane Fellbaum I was referring to: 

> WordNet includes for each verb synset one or several sentence frames, which specify the
> subcategorization features of the verbs in the synset by indicating the kinds of sentences
> they can occur in. (Christiane Fellbaum, "English Verbs as a Semantic Net", in: 5papers.pdf, p. 55)

In the web version of OEWN, en-word.net, verb frames are attached to synsets. It does not always look right, cf. `oewn-00902866-v` in https://en-word.net/lemma/acquaint). 

The following quote, taken from Richard Beckwith, George A. Miller, and Randee Tengi: "Design and Implementation of the WordNet Lexical Database and Searching Software", points out that it is also possible to restrict a verb frame to a word:

> 
> Each verb synset contains a list of verb frames illustrating the types of simple
> sentences in which the verbs in the synset can be used. A list of verb frames can be
> restricted to a word form by using the square bracket syntax described above. (5papers.pdf , p. 67).

**Comment by jmccrae** [comment]
As @x-englishwordnet points out, the frames are associated with the senses in the XML and YAML forms of the data, which is consistent with the original Princeton data. The RDF export puts them on the entries following the OntoLex-lemon standard, however there is some loss of information associated with this so the RDF export can certainly be improved
