### ISSUE TITLE
Port english wordnet to Babelnet

### ISSUE THREAD

**Issue by LifeIsStrange** [globalwordnet/english-wordnet#816]
[Babelnet](https://en.wikipedia.org/wiki/BabelNet) is a key dataset that superset wordnet and align it with wikipedia, verbnet, etc
It is powerful, and quite popular, e.g. I was looking into the state of the art neural networks for word sense disambiguation and many output Babelnet word indices instead of wordnet sense indices (despite babelnet leveraging wordnet behing the scene)

I would love to use Babelnet for its expressivity however I would prefer to use the english wordnet vs princeton wordnet because of its higher accuracy/completeness.
As such I would really appreciate if you could build a partnership/contribute to Babelnet in order for them to offer indices that use wordnet-english vs wordnet princeton as an option.

Make it happen plz :)
@jmccrae friendly ping

**Comment by jmccrae** [comment]
I personally know the BabelNet team well and they are aware of this project, and I believe are planning to integrate it. From this side though there is not much we can do, BabelNet is a commercial project that has their own goals. I suggest that you raise this issue with them :)
