### ISSUE TITLE
Provide an API

### ISSUE THREAD

**Issue by LifeIsStrange** [globalwordnet/english-wordnet#817]
Either a native API or an NLTK integration.
https://www.nltk.org/howto/wordnet.html
The NLTK API make it clear and easy on how to use wordnet.
The wordnet english readme isn't clear, you show how to build an XML file containing the whole wordnet but not how to programmatically query it.

This would help making english-wordnet much more used/popular.
@jmccrae friendly ping

Note: I consider this higher priority than [support for Babelnet](https://github.com/globalwordnet/english-wordnet/issues/816)

**Comment by jmccrae** [comment]
Hi, thanks for you interest in the project. We would not really provide an API as there is not really resources to maintain this. However, NLTK integration is in progress (see #771 for discussion). There is also a fairly simple Python script for working with these files provided under the `scripts/` folder.

**Comment by LifeIsStrange** [comment]
@jmccrae
Yes I am now aware of NLTK and WN support
https://github.com/goodmami/wn
That is great, however wordnet English has a major issue to solve for this libraries:

See the last comment in
https://github.com/nltk/nltk/issues/2885

Those are the respective wordnet English issues 
https://github.com/globalwordnet/english-wordnet/issues/773
https://github.com/globalwordnet/english-wordnet/issues/774
Especially the sense ordering issues are worrying from an external user point of view.
