### ISSUE TITLE
spelling inconsistencies

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#82]
There are many cases of spelling inconsistencies among definitions including

* 'focussed' vs. 'focused'
* 'color' vs 'colour' and other American vs. British spellings 

A consistent policy should be applied

**Comment by arademaker** [comment]
I would instead argue that if we have both defined, http://wnpt.brlcloud.com/wn/synset?id=04674968-n, I don't see any problem with definitions and examples using both.

Is there any canonical web interface to browse and search the data from this repository?

**Comment by arademaker** [comment]
I vote to keep the spelling variations.

**Comment by jmccrae** [comment]
Okay, we can keep the spelling variations
