### ISSUE TITLE
No such file or directory: 'src/xml/wn-verb.body.xml'

### ISSUE THREAD

**Issue by aclueless** [globalwordnet/english-wordnet#820]
**Describe the bug**
I run `scripts/merge.py` on `master` branch and get: FileNotFoundError: [Errno 2] No such file or directory: 'src/xml/wn-verb.body.xml'

**To Reproduce**
1. git clone the repo
2. cd to the project root
3. python scripts/merge.py
4. FileNotFoundError: [Errno 2] No such file or directory: 'src/xml/wn-verb.body.xml'

**Expected behavior**
Successfully create the `wn.xml` file

**Comment by jmccrae** [comment]
The instructions on the readme were out-of-date. You now need to first run the script `scripts/from-yaml.py` before `scripts/merge.py`
