### ISSUE TITLE
China 

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#827]
**Synset**

In `oewn-08748383-n` we have one sense of `China`. Problem is that this synset is in the `noun.location` is an instance of `oewn-09339360-n`  (island) but its definition starts with

>  **a government** on the island of Taiwan established in 1949 by Chiang Kai-shek after the conquest of mainland China by the Communists led by Mao Zedong

In most the other countries, the definition says "a republic..." or "a monarchy..."  etc

Do we need both?

1. [08730550-n](http://wn.mybluemix.net/synset?id=08730550-n) Nationalist_China, Republic_of_China, Taiwan, China |  (a government on the island of Taiwan established in 1949 by Chiang Kai-shek after the conquest of mainland China by the Communists led by Mao Zedong)
1. [08723006-n](http://wn.mybluemix.net/synset?id=08723006-n) China, Communist_China, Cathay, People's_Republic_of_China, PRC, Red_China, mainland_China |  (a communist nation that covers a vast territory in eastern Asia; the most populous country in the world)

This is related to [comments](https://github.com/globalwordnet/english-wordnet/pull/708#issuecomment-892715154) about Acre (territory of Brazil in the past) and Acre (a current state of Brazil).

**New definition**

If we want to keep both synsets, maybe the 08730550-n definition need not be changed but its relations.

**Motivation**

Maybe we need an in-depth revision of definitions by synset groups (countries, regions, etc)

**Comment by jmccrae** [comment]
Please see our statement on Neutrality here: https://github.com/globalwordnet/english-wordnet/blob/master/CONTRIBUTING.md#Neutrality

**Comment by arademaker** [comment]
Sorry , I didn’t understand

**Comment by rwingerter55** [comment]
@arademaker, it's a politically sensitive issue, cf. https://en.wikipedia.org/wiki/Two_Chinas.

**Comment by jmccrae** [comment]
Yeah, this could be politically quite sensitive. This may be an opportunity to include other non-recognized states into the resource, such as in the list here:

https://en.wikipedia.org/wiki/List_of_states_with_limited_recognition
