### ISSUE TITLE
Add lemmas to oewn-01329210-v (destroy, put down)

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#831]
**Affected synsets**
oewn-01329210-v 
Lemmas: destroy, put down 
def.: "put (an animal) to death"
ex.:  “The customs agents destroyed the dog that was found to be rabid” “the sick cat had to be put down”

**Proposed changes**
Add lemmas: euthanize, euthanise, euthanatize, euthanatise

**Motivation**
Cf. reference dictionaries:
https://www.ahdictionary.com/word/search.html?q=euthanize
https://dictionary.cambridge.org/dictionary/english/euthanize
https://www.collinsdictionary.com/dictionary/english/euthanize
https://www.dictionary.com/browse/euthanize
https://www.lexico.com/definition/euthanize
https://www.macmillandictionary.com/dictionary/british/euthanize
https://www.merriam-webster.com/dictionary/euthanize
https://en.wiktionary.org/wiki/euthanize

https://dictionary.cambridge.org/dictionary/english/euthanise
https://www.collinsdictionary.com/dictionary/english/euthanise
https://www.dictionary.com/browse/euthanise
https://www.lexico.com/definition/euthanise
https://en.wiktionary.org/wiki/euthanise

https://www.ahdictionary.com/word/search.html?q=euthanatize
https://dictionary.cambridge.org/dictionary/english/euthanatize
https://www.dictionary.com/browse/euthanatize
https://www.merriam-webster.com/dictionary/euthanatize
https://en.wiktionary.org/wiki/euthanatize

https://www.collinsdictionary.com/dictionary/english/euthanatise
https://en.wiktionary.org/wiki/euthanatise

**Comment by jmccrae** [comment]
My only concern would be that the definition mentions animals but 'euthanize' refers also to humans. Do you think we need a new synset that is a hypernym of this one for 'euthanize'?
