### ISSUE TITLE
Examine derogatory terms

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#85]
There should be an examination of highly derogatory terms, e.g. should 

10348226-n (Interlingual Index: i91435)
(n) mongoloid 
> a person suffering from Down syndrome (no longer used technically in this sense, now considered offensive)

Really be a hyponym of

10217144-n (Interlingual Index: i90651)
(n) changeling, half-wit, imbecile, retard, idiot, cretin, moron 
> a person of subnormal intelligence

I think not.

**Comment by arademaker** [comment]
surely not. This must be change right?

**Comment by arademaker** [comment]
This also reflects the idea of a new relation marking a word as an obsolete term.

**Comment by fcbond** [comment]
For obsolete terms we currently mark them as 'archaism' with an exemplify link.

I think we should maybe have two synsets fro mongoloid, as sadly the insulting one exists, and should be linked as derived from or see also to the medical one.
