### ISSUE TITLE
floating word in the gloss 00005472-s

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#855]
**Synset**

In oewn-00005472-s   the gloss is 

> lacking compromising or mitigating elements; exact “the direct opposite”

**New definition**

What is the word 'exact'? Part of the definition? The first example? I would guess it can be added as one lexical entry of this synset and removed from the gloss.

**Motivation**

Make examples and definitions cleaner.

**Comment by mstraughan86** [comment]
From my interpretation of the information presented, it appears to be the second phrase of the definition, separated by the preceding semicolon.

If that is deserving of a separate lexical entry, I am sure I do not know.

**Comment by jmccrae** [comment]
Yes, I also agree that 'exact' should be a member of this synset not a definition by synonyms. This seems relatively distinct from the other senses of 'exact' so I am happy just to add this member.
