### ISSUE TITLE
Addict definition too narrow

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#86]
09788253-n (Interlingual Index: i88073)
(n) addict 
> someone who is physiologically dependent on a substance; abrupt deprivation of the substance produces withdrawal symptoms

synset's definition too narrow - regards only substances; should also include activites like gambling

**Comment by jmccrae** [comment]
new definition: 'someone who is physiologically dependent on a substance or activity'

**Comment by arademaker** [comment]
there is another sense for that. See:

1. addict, nut, freak, junkie, junky -- (someone who is so ardently devoted to something that it resembles an addiction; "a golf addict"; "a car nut"; "a bodybuilding freak"; "a news junkie")

2. addict -- (someone who is physiologically dependent on a substance; abrupt deprivation of the substance produces withdrawal symptoms)

Are you proposing the merge? 

We don't have a sense for annotating 

> (a) hard-core | stubbornly resistant to change or improvement ; hard-core addicts ;

Maybe we also need the sense for the `thing`...

**Comment by jmccrae** [comment]
Not proposing any new senses, just to tag 'gambling addict' and 'golf addict' as distinct senses, with 'gambling addict' being the same sense as 'drug addict'.

On your second point, do you want 'hard-core' to be a noun?

**Comment by arademaker** [comment]
No, I want a sense of addicts (the thing that an addict person is dependent on).. see the example for hard-core: “hard-core addicts”

**Comment by jmccrae** [comment]
Not really sure I get the issue here. The two senses of addict seem sufficient, and this is the same two senses that most other dictionaries have:

https://www.lexico.com/definition/addict
https://en.wiktionary.org/wiki/addict
https://www.merriam-webster.com/dictionary/addict

Could you clarify what you think is wrong with the proposed definitions (as in the PR)?
