### ISSUE TITLE
Leviathan's are not just people and animals

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#88]
10275425-n (Interlingual Index: i90982)
(n) leviathan 
> the largest or most massive thing of its kind; "it was a leviathan among redwoods"; "they were assigned the leviathan of textbooks"

Is a hypernym of 

10129212-n (Interlingual Index: i90079)
(n) monster, lusus naturae, freak, monstrosity 
> a person or animal that is markedly unusual or deformed

Perhaps the definition of the hypernym should be broader

**Comment by jmccrae** [comment]
A better solution maybe to shift the hypernym to `ewn-10148446-n` (someone or something that is abnormally large and powerful)

**Comment by arademaker** [comment]
What about adding leviathan in 10148446-n?

**Comment by jmccrae** [comment]
I feel the meaning is more specific, it is a more extremely large thing than is meant by a 'monster', e.g.,
a 'monster soda' is smaller than a 'leviathan soda'
