### ISSUE TITLE
Add mappings to Wikipedia from Szymanski and Boinski

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#889]
The following paper has manually (through crowd-sourcing) validated 50k links to Wikipedia. I think these can be directly included into the OEWN

http://kask.eti.pg.gda.pl/CompWiki/files/veriffied_mappings.zip

https://www.worldscientific.com/doi/10.1142/S0218194019500141

**Comment by rwingerter55** [comment]
I checked the mappings of all the concepts contained in wn-core and found that 333 of 1.299 mappings (25%) do not have the quality required (see Attachment). Nevertheless, the mappings provide a good starting point. 

As a next step, I am going to enrich the mappings from Szymanski and Boinski with Wordnet IDs and definitions from OEWN 2022 and from DBpedia. This could be the basis for validation.

Linking Wordnet to Wikipedia / DBpedia can be a valuable contribution to LLOD. But it is quite a challenge. It would help to state objectives and key results. We also need some sort of guideline, like

- Which relationship to use (skos mapping relations?)
- How to deal with Wikipedia redirects and links to disambiguation pages

[Mappings first analysis .xlsx](https://github.com/globalwordnet/english-wordnet/files/10445178/Mappings.first.analysis.xlsx)

**Comment by jmccrae** [comment]
I will close this issue as it seems that the source material is not of sufficient quality to include. We could probably get better than 75% linking accuracy with automatic measures so I am not sure that this is useful

Thanks @rwingerter55 for your analysis!
