### ISSUE TITLE
perv

### ISSUE THREAD

**Issue by fcbond** [globalwordnet/english-wordnet#892]
perve, perve (v)
Please suggest one of more lemmas with part of speech for this concept

"stare at someone lustfully"
Give a definition of the concept. If proposing a concept with multiple part-of-speech values give a definition for each part-of-speech

hyponym of oewn-02134989-v
Please suggest at least one relation according to https://github.com/globalwordnet/english-wordnet/blob/master/NEW_SYNSETS.md#Linked

It is a common word, with a negative connotation, so useful for sentiment analysis.
Explain why this synset is important referring to the guidelines here: https://github.com/globalwordnet/english-wordnet/blob/master/NEW_SYNSETS.md

I can't access sketch engine, but 'perving' appears 16 times in COCA, 'perv' is always mistagged as a noun, but appears as a verb many times. https://www.english-corpora.org/coca/

**Comment by jmccrae** [comment]
I am going to implement this by merging the two synsets for 'leer' and 'ogle' and adding 'perv' as a new member of this synset. Is this okay @fcbond ?

**Comment by jmccrae** [comment]
Actually, I guess that 'leer' has some distinction in meaning, so I will just add these as new members of the 'ogle' synset
