### ISSUE TITLE
duplicated synset about terabyte

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#895]
**Synsets**

(n) [TB](https://en-word.net/lemma/TB), terabyte a unit of information equal to 1000 gigabytes or 10^12 (1,000,000,000,000) bytes

(n) [TB](https://en-word.net/lemma/TB), terabyte, [tebibyte](https://en-word.net/lemma/tebibyte), [TiB](https://en-word.net/lemma/TiB) a unit of information equal to 1024 gibibytes or 2^40 (1,099,511,627,776) bytes

**Motivation**

What are the difference between these two? Maybe duplicated?

**Comment by arademaker** [comment]
Yes, one 10^12 and the other 2^40, but does it make sense the two concepts?

**Comment by jmccrae** [comment]
I would say so. They seem to be clearly and scientifically defined as distinct concepts. I know the confusion is often used in marketing, which is why your "10TB HDD" is actually only 9TB

**Comment by arademaker** [comment]
OK, Maybe I was missing some from the definitions.
