### ISSUE TITLE
oxidation pond

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#896]
**Lemmas**

1. oxidation pond
2. lagoons
3. stabilization pond
4. waste stabilization lagoons

**Definition**

large, shallow ponds designed to treat wastewater through the interaction of sunlight, bacteria, and algae.

**Relation**

Hyponym of http://wn.mybluemix.net/synset?id=04563790-n, or maybe the terms can be added to this synset?

**Significance**

The following pages talk about the concept:

1. https://www.britannica.com/technology/wastewater-treatment/Oxidation-pond
2. https://en.wikipedia.org/wiki/Waste_stabilization_pond

In the Princeton WordNet 3.0 examples, we have two references to it:

1. http://wn.mybluemix.net/synset?id=00036609-r  "**oxidation ponds** are extensively used for sewage treatment in the Midwest"
2. http://wn.mybluemix.net/synset?id=03150985-a "the operating conditions of the **oxidation pond**"

On the other hand, we can eventually consider that the meaning of this MWE is compositional... a pond for the oxidation of water. In Portuguese, some dictionaries consider oxygenation and oxidation synonyms.

**Comment by jmccrae** [comment]
Seems reasonable. The only thing I changed in the implementation is that I felt that 'lagoons' was too broad a lemma so I removed it.
