### ISSUE TITLE
`take hold of` and `take hold`

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#897]
**Synsets**

1. http://wn.mybluemix.net/synset?id=01216670-v - (have or hold in one's hands or grip; "Hold this bowl for a moment, please"; "A crazy idea took hold of him") - already have problems. hold an idea vs hold something in our hand?
2. http://wn.mybluemix.net/synset?id=01439190-v - (take hold of so as to seize or restrain or stop the motion of; "Catch the ball!"; "Grab the elevator door!")

**Motivation**

does it make sense to differ the two senses above? Not sure.

**Comment by jmccrae** [comment]
The second definition use the lemma 'take hold of' as part of the definition, as such it is clearly a more specific sense than 'take hold of'. Also its hypernym is quite poorly defined:

`oewn-01215136-v` (Interlingual Index: `i27685`)
(v) [seize](https://en-word.net/lemma/seize), [prehend](https://en-word.net/lemma/prehend), [clutch](https://en-word.net/lemma/clutch) _take hold of; grab_
> “The sales clerk quickly seized the money on the counter” “She clutched her purse” “The mother seized her child by the arm” “Birds of prey often seize small mammals”

I would suggest the following.

* Remove 'take hold of' from `01441809-v`
* Add 'take old of' to `01219234-v`
* Update definition of `01215136-v` to "take into your hands deliberately"
* Add 'take hold' and 'take hold of' to `01215136-v`

**Comment by jmccrae** [comment]
It also seems like this definition refers to the static state of holding something, rather than the action of grabbing something.

`oewn-01219234-v` (Interlingual Index: `i27706`)
(v) [hold](https://en-word.net/lemma/hold), _take hold have or hold in one's hands or grip_
> “Hold this bowl for a moment, please” “A crazy idea took hold of him”

Shouldn't we may remove 'take hold' entirely from this synset?
