### ISSUE TITLE
Download links on 2022 release page point to 2021 Edition

### ISSUE THREAD

**Issue by ekaf** [globalwordnet/english-wordnet#899]
The download links on the Open English WordNet 2022 release page (https://github.com/globalwordnet/english-wordnet/releases/tag/2022-edition) are pointing to the 2021 Edition:

> Download links:
> 
>     GWA XML: https://en-word.net/static/english-wordnet-2021.xml.gz
>     RDF: https://en-word.net/static/english-wordnet-2021.ttl.gz
>     WNDB: https://en-word.net/static/english-wordnet-2021.zip (for legacy applications)
>

**Comment by ekaf** [comment]
Links to the 2022 Edition should also be added to the README.md (https://github.com/globalwordnet/english-wordnet/blob/master/README.md) page.

**Comment by jmccrae** [comment]
Done, thanks for the comment
