### ISSUE TITLE
inevitable accident: remove

### ISSUE THREAD

**Issue by malangali** [globalwordnet/english-wordnet#9]
http://compling.hss.ntu.edu.sg/omw/cgi-bin/wn-gridx.cgi?usrname=&gridmode=grid&synset=07315350-n&lang=eng&lang2=eng

"inevitable accident" is not a legitimate English multiword expression. It is an oxymoron that is (poorly) attempting to define "force majeure" and should be removed entirely.

**Comment by jmccrae** [comment]
Actually it is a valid legal term, see

https://www.merriam-webster.com/legal/inevitable%20accident

@malangali is this okay to close?
