### ISSUE TITLE
Definition of <ewn-02728797-n> "anvil, incus"

### ISSUE THREAD

**Issue by rwingerter55** [globalwordnet/english-wordnet#900]
**Synset**
ewn-02728797-n "anvil, incus"

**New definition**
"a small bone in the middle ear", cf. 
"https://en.wiktionary.org/wiki/incus#Noun"
"https://en.wikipedia.org/wiki/Incus"

**Motivation**
The current definition ("the ossicle between the malleus and the stapes") is difficult to understand. A user should not have to look up "ossicle", "malleus" and "stapes" to understand what it is about.

**Comment by arademaker** [comment]
Are there more bones in the middle ear?

**Comment by rwingerter55** [comment]
Yep, it seems to be full of ossicles (anvils, mallei, stapes. ;-)

**Comment by jmccrae** [comment]
Thanks for the comment. The original post appears to have the wrong synset code. I have implemented it for `05333888-n`

To avoid ambiguity I used the following definition:
> a small bone in the middle ear between the malleus and the stapes
