### ISSUE TITLE
The ILI namespace is incorrect

### ISSUE THREAD

**Issue by simongray** [globalwordnet/english-wordnet#921]
**Release format**
RDF

**Describe the bug**
A wrong namespace is used for the`ili` prefix in the published TTL dataset. This seems a bit more critical than #919.

**To Reproduce**

1. Download the most recent version of the English WordNet: https://en-word.net/static/english-wordnet-2022.ttl.gz
2. Go to line 2 which declares: `@prefix ili: <http://ili.globalwordnet.org/ili/> .`
3. Download the ili.ttl file available at: https://github.com/globalwordnet/cili/blob/master/ili.ttl
4. Compare the prefix declaration used in the English WordNet with the `@base <http://globalwordnet.org/ili/> .` declared in the ILI dataset. They are not the same!

**Expected behavior**
The resources using the `ili:` prefix in the English WordNet data should be the _actual_ ILI resources, not resources in a separate namespace which will be the case when the prefix declaration at the beginning of the Turtle file is wrong.

**Additional context**
Replacing line 2 in the English WordNet TTL file with `@prefix ili: <http://globalwordnet.org/ili/> .` should fix this issue.

**Comment by simongray** [comment]
While the fix is pretty simple, this currently means that the English WordNet RDF isn't actually linked to the ILI like it purports to be! Or, alternatively, that the `ili.ttl` file in the CILI repo declares its own namespace in a wrong way.

I discovered this because (as @jmccrae knows) I am in the process of linking to the CILI via the English WordNet.

**Comment by jmccrae** [comment]
Fixed with 2023 release
