### ISSUE TITLE
missing sense of wheelhouse

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#937]
**Lemmas**

wheelhouse

**Definition**

 (one's wheelhouse) one's area of interest or expertise 

Example:  as the campaign swings to the south, that should be right in his wheelhouse.

**Relation**

domainRegion US

**Significance**

missing sense

**Comment by jmccrae** [comment]
Implemented. 

I did not add a link to note this a US usage for two reasons: firstly, we have no terms marked as being US usage so far (I guess US English is the default of Princeton); secondly, I find that this term is widely used in the UK and Ireland (personal experience).
