### ISSUE TITLE
'write'

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#948]
**Synsets**
`oewn-00995046-v` (Interlingual Index: i26548)
(v) write 
> communicate or express by writing “He wrote about his great love for his wife”

and
`oewn-01009072-v` (Interlingual Index: i26733)
(v) write, [drop a line](https://en-word.net/lemma/drop%20a%20line) 
> communicate (with) in writing “Write to her soon, please!”

**Motivation**
These synsets have the same definition and seem to overlap to a large extent. 

Alternatively, we could make 'contact' the troponym of the second synset and update definitions?

**Comment by arademaker** [comment]
The problem seems to be the verb-frame `Somebody ----s somebody` repeated in the first synset above. If we remove that frame, one synset has an ANIMATE agent as OBJ. The other sense has the thing written as OBJ.

**Comment by jmccrae** [comment]
Yeah, I was changing my mind a bit as wrote the report. 

I think that the second sense should be 'contact in writing', rather than 'communicate'. Then it is clear that this sense has an animate object
