### ISSUE TITLE
'act' 

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#949]
**Synsets**
`oewn-02424173-v` (Interlingual Index: i33830)
(v) act
> be engaged in an activity, often for no particular purpose other than pleasure

and

`oewn-02372362-v` (Interlingual Index: i33603)
(v) act, [move](https://en-word.net/lemma/move)
> perform an action, or work out or perform (an action) “think before you act” “We must move quickly” “The governor should act on the new energy bill” “The nanny acted quickly by grabbing the toddler and covering him with a wet towel”

**Motivation**
I don't think the first sense is very distinct. Other dictionaries don't seem to distinguish 'act' by it being 'for no particular purpose'. I think we can merge this into the general idea of 'acting'

**Comment by arademaker** [comment]
one sense is strict intransitive. The other sense can be intransitive, transitive with/without PP attached.

**Comment by jmccrae** [comment]
The second sense can't actually be transitive, it can be intransitive with an animate or an inanimate subject.

It is clear that the first sense is narrower, i.e., limited to animate subjects and with the differentia in the definition of 'for no particular purpose'. Following the discussions in #243 (on sense distinctions) and #237 (on avoiding hyponyms with the same lemma), I think it is better to merge these senses.
