### ISSUE TITLE
'have' (drink/eat) is missing

### ISSUE THREAD

**Issue by aclueless** [globalwordnet/english-wordnet#955]
https://en-word.net/lemma/have seems missing sense for "have lunch/dinner"

**Comment by jmccrae** [comment]
Would this not be a suitable sense?

`oewn-01159300-v` (Interlingual Index: i27410)
(v) have, [take](https://en-word.net/lemma/take), [take in](https://en-word.net/lemma/take%20in), [consume](https://en-word.net/lemma/consume), [ingest](https://en-word.net/lemma/ingest)
> serve oneself to, or consume regularly “Have another bowl of chicken soup!” “I don't take sugar in my coffee”

**Comment by aclueless** [comment]
Hi, I am not a linguist. I just try to look up WordNet as a person who studies English as a foreign language.

From my viewpoint, I expected that 'have' and 'eat' should be in the same synset because of the sense in "I have dinner". (And similarly, in another synset, we have 'have' and 'drink').

But as you pointed out, 'have' actually means 'consume'. So I was wrong. From now on, I have to understand that 'have' is a kind of "super sense" over 'eat' and 'drink', right?

**Comment by jmccrae** [comment]
Thanks for your report and the interest in the project!

Yes, 'eat' and 'drink' are narrower senses of 'have', which you can see by looking at the hyponyms of this synset.
