### ISSUE TITLE
Why `a.m.` but the other is `A.M.`?

### ISSUE THREAD

**Issue by aclueless** [globalwordnet/english-wordnet#976]
**Affected synsets**

https://en-word.net/lemma/a.m. (Adjective)
https://en-word.net/lemma/A.M. (Adverb)

and similarly:

https://en-word.net/lemma/p.m. (Adjective)
https://en-word.net/lemma/P.M. (Adverb)

**Proposed changes**
I think these items should include alternative forms found in wiktionary.org (links below).

Also, wiktionary.org only has adverbs for these items. This is just a note, I am not an English speaker to say anything about this.

**Motivation**
https://en.wiktionary.org/wiki/a.m.#English
https://en.wiktionary.org/wiki/p.m.#English

**Comment by jmccrae** [comment]
Yes, I don't think these should be adjectives, they can however be nouns (e.g., "in the a.m.")

We should also make sure that we have all variant (A.M., a.m., AM, am) in the synset.

**Comment by jmccrae** [comment]
I also note that the noun senses were identified as missing in #956
