### ISSUE TITLE
Extravagence

### ISSUE THREAD

**Issue by jmccrae** [globalwordnet/english-wordnet#98]
04902002-n (Interlingual Index: i62709)
(n) extravagance, profligacy, prodigality 
> the trait of spending extravagantly

00744939-n (Interlingual Index: i39342)
(n) lavishness, extravagance, high life, highlife, prodigality 
> excessive spending

The synsets are probably not distinct and the definition could be extended to being wasteful in general

**Comment by jmccrae** [comment]
update definition of `ewn-00744939-n` to 'the activity of excessive spending'

**Comment by arademaker** [comment]
but are you merging them? maybe it is the case right?

**Comment by vcvpaiva** [comment]
you have a typo on the issue's name and I don't think the concepts should be merged. one has a negative connotation, the other is less puritanical

**Comment by arademaker** [comment]
wow! Is it the level of granularity that we must keep in the resource? this is far from lexical semantics, don't you think? I may be wrong...

**Comment by dcillessen** [comment]
There are a number of places in WN where the trait of doing something is a seperate synset to the act of doing that thing. Many of those examples end in "-ness," as seen in ewn-92423540-n "fashionableness", as well as in ewn-00744939-n "lavishness" among others. To me the distinctions between these types of synsets, including the ones being discussed here, are significant enough to justify keeping synsets separate.

John's suggestion to change the definition emphasizes the difference between these synsets in terms of the "act of" doing something and the "trait of" (being someone who) does something.
We can see ewn-00744939-n in a sentence like "the ballroom exemplified the _high life_"
and we can see ewn-04902002-n "her _extravagance_ led to her financial ruin"
