### ISSUE TITLE
`Lexico (Oxford)` redirect to https://www.dictionary.com

### ISSUE THREAD

**Issue by aclueless** [globalwordnet/english-wordnet#981]
When I follow [Lexico (Oxford)](https://www.lexico.com/) (in [DICTIONARIES](https://github.com/globalwordnet/english-wordnet/blob/main/DICTIONARIES.md)), it shows me https://www.dictionary.com/ which is the link just above Lexico (Oxford) (in the same DICTIONARIES file).

It's a duplicate or something wrong here?

**Comment by jmccrae** [comment]
It seems that Oxford sold the domain. Now linking to OED
