### ISSUE TITLE
Are 'plus' and 'summation' synonym?

### ISSUE THREAD

**Issue by aclueless** [globalwordnet/english-wordnet#984]
Please for give my ignorance (being a non-English speaker), but I find it's hard to think that 'plus' and 'summation' synomym:

https://en-word.net/id/oewn-00873785-n

[addition](https://en-word.net/lemma/addition), [plus](https://en-word.net/lemma/plus), [summation](https://en-word.net/lemma/summation) the arithmetic operation of summing; calculating the sum of two or more numbers “the summation of four and three gives seven” “four plus three equals seven”

It's weird to say: `four summation three equals seven` instead of `four plus three equals seven`

Are they actually the same?

**Comment by jmccrae** [comment]
The use of 'plus' in the example is as a preposition not a noun. 

I would suggest that we remove this member from the sense.

Also, looking at other dictionaries we might want to add 'plus' as a synonym of 'plus sign'
