### ISSUE TITLE
Add 'phone' to https://en-word.net/id/oewn-02995984-n

### ISSUE THREAD

**Issue by aclueless** [globalwordnet/english-wordnet#985]
I think `phone` should be added to https://en-word.net/id/oewn-02995984-n

**Comment by jmccrae** [comment]
This makes some sense, but 'phone' already is a hypernym of this synset, so it would contradict the work of #237

**Comment by aclueless** [comment]
Two decades ago, we have to say `a mobile phone` for other people to understand correctly that we mean a hand-held device.

But now,  `a phone` is definitely `a mobile phone`. Virtually, all occurrences of `a phone` in documents now and in the future will surely refer to a hand-held device. If someone wants to mention that it is not a phone (which people immediately understand a hand-held device), they have to use different word to describe it, such as 'a desk phone'.

That is why I open this issue. But my view is limited, and I just try to use OEWN as a special dictionary. So, my view may be out of scope. Feel free to close this if it is not really an issue.

I wonder how will OEWN adapt to such changes?

**Comment by jmccrae** [comment]
I am not really convinced that the meaning of "phone" has changed significantly in general usage to justify this change. It is common for people to use hypernyms terms to refer to concepts. I don't think there are people who don't think of a mobile phone as being in the same category as a desk phone.

We normally only have self-hypernyms in a few exceptional circumstances, e.g., '(rock) oil' is 'oil'. This only applies to 33 noun synsets and most of those probably need to be changed.

I will leave this open if there are other opinions from the community.

On the point of OEWN adapting to change: OEWN aims to be a dictionary of contemporary language usage and we try to update with modern usage, we are not frozen like Princeton WordNet.

**Comment by jmccrae** [comment]
Closing this as there does not seem to be strong support for including "phone" here.
