### ISSUE TITLE
two adjetives for climbable

### ISSUE THREAD

**Issue by arademaker** [globalwordnet/english-wordnet#987]
**Synsets**

https://en-word.net/lemma/climbable

**Motivation**

I could not easly distinguish the two senses.

**Comment by jmccrae** [comment]
The second synset is quite odd.

`oewn-01729245-s` (Interlingual Index: i9466)
(s) surmountable, climbable 
> capable of being surmounted

I would suggest we merge this synset into the first sense of 'climbable'.
