### ISSUE TITLE
Download links in the 2023-edition release are incorrect

### ISSUE THREAD

**Issue by goodmami** [globalwordnet/english-wordnet#990]
**Release format**

LMF/RDF/WNDB

**Describe the bug**

The download links in the text of the [release](https://github.com/globalwordnet/english-wordnet/releases/tag/2023-edition) are for the 2022 version:

> Download links:
>
> - GWA XML: https://en-word.net/static/english-wordnet-2022.xml.gz
> - RDF: https://en-word.net/static/english-wordnet-2022.ttl.gz
> - WNDB: https://en-word.net/static/english-wordnet-2022.zip (for legacy applications)

The release assets at the bottom, however, are correct.

**Expected behavior**

These should be corrected as follows:

```md
Download links:
- GWA XML: https://en-word.net/static/english-wordnet-2023.xml.gz
- RDF: https://en-word.net/static/english-wordnet-2023.ttl.gz
- WNDB: https://en-word.net/static/english-wordnet-2023.zip (for legacy applications)

```

**Additional context**

This is _not_ the same issue as #902, even though both `scripts/merge.py` and `scripts/wordnet_yaml.py` specify `2022`:

https://github.com/globalwordnet/english-wordnet/blob/f2528e218eb6034696aff5023d5de54152cb8f9d/scripts/merge.py#L73

https://github.com/globalwordnet/english-wordnet/blob/f2528e218eb6034696aff5023d5de54152cb8f9d/scripts/wordnet_yaml.py#L143

This issue is just about the links in the text of the 2023 release, but the above instances of 2022 might need to be corrected anyway.

**Comment by jmccrae** [comment]
Fixed
