### ISSUE TITLE
Add link oewn-12640957-n =hypernym=> oewn-11690372-n

### ISSUE THREAD

**Issue by aclueless** [globalwordnet/english-wordnet#991]
**Edit**: Add a relation (as in the first comment below) instead of  new synset.

----
Original content:

**Lemmas**
rose

**Definition**
from [wiktionary](https://en.wiktionary.org/wiki/rose#Noun): A flower of the rose plant.

**Relation**
don't know

**Significance**
Seem obvious to me

**Comment by jmccrae** [comment]
OEWN does not list the flowers of plants as separate from their plant, however many flowering plants are listed as a hyponym of the following synset and 'rose' should probably be listed as such

`oewn-11690372-n` (Interlingual Index: i98675)
(n) flower 
> a plant cultivated for its blooms or blossoms

I propose to add the link `oewn-12640957-n =hypernym=> oewn-11690372-n`
